; Generated by NOVA compiler
target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"

declare i32 @printf(ptr, ...)
declare i32 @puts(ptr)
declare noalias ptr @malloc(i64) nounwind allocsize(0)
declare noalias ptr @calloc(i64, i64) nounwind
declare ptr @realloc(ptr, i64) nounwind allocsize(1)
declare void @free(ptr) nounwind
declare ptr @nova_rt_struct_alloc(i64) nounwind
declare i64 @llvm.smax.i64(i64, i64) nounwind readnone
; nova runtime — list ops
declare i64 @nova_rt_list_create() nounwind
declare i64 @nova_rt_list_create_filled(i64, i64) nounwind
declare i64 @nova_rt_list_append(i64, i64) nounwind
declare i64 @nova_rt_list_get(i64, i64) nounwind readonly
declare i64 @nova_rt_list_set(i64, i64, i64) nounwind
declare i64 @nova_rt_list_len(i64) nounwind readonly
declare i64 @nova_rt_list_print(i64) nounwind
declare i64 @nova_rt_iter_has_next(i64, i64) nounwind readonly
declare i64 @nova_rt_iter_get(i64, i64) nounwind readonly
declare i64 @nova_rt_list_iter_has_next(i64, i64) nounwind readonly
declare i64 @nova_rt_list_iter_get(i64, i64) nounwind readonly
; nova runtime — string ops
declare i64 @nova_rt_str_concat(i64, i64) nounwind
declare i64 @nova_rt_int_to_str(i64) nounwind
declare i64 @nova_rt_float_to_str(i64) nounwind
declare i64 @nova_rt_bool_to_str(i64) nounwind
declare i64 @nova_rt_str_len(i64) nounwind readonly
declare i64 @nova_rt_len(i64) nounwind readonly
declare i64 @nova_rt_contains(i64, i64) nounwind readonly
declare i64 @nova_rt_slice(i64, i64, i64) nounwind
declare i64 @nova_rt_upper(i64) nounwind
declare i64 @nova_rt_lower(i64) nounwind
declare i64 @nova_rt_trim(i64) nounwind
declare i64 @nova_rt_repeat(i64, i64) nounwind
declare i64 @nova_rt_split(i64, i64) nounwind
declare i64 @nova_rt_replace(i64, i64, i64) nounwind
declare i64 @nova_rt_starts_with(i64, i64) nounwind readonly
declare i64 @nova_rt_ends_with(i64, i64) nounwind readonly
declare i64 @nova_rt_find(i64, i64) nounwind readonly
declare i64 @nova_rt_join(i64, i64) nounwind
declare i64 @nova_rt_chars(i64) nounwind
; nova runtime — list stdlib
declare i64 @nova_rt_list_reverse(i64) nounwind
declare i64 @nova_rt_list_sort(i64) nounwind
declare i64 @nova_rt_list_map(i64, i64) nounwind
declare i64 @nova_rt_list_filter(i64, i64) nounwind
declare i64 @nova_rt_list_concat(i64, i64) nounwind
declare i64 @nova_rt_list_slice(i64, i64, i64) nounwind
declare i64 @nova_rt_list_to_str(i64) nounwind
declare i64 @nova_rt_len_any(i64) nounwind readonly
; nova runtime — type conversions
declare i64 @nova_rt_parse_int(i64) nounwind
declare i64 @nova_rt_parse_float(i64) nounwind
; nova runtime — character ops
declare i64 @nova_rt_ord(i64) nounwind readonly
declare i64 @nova_rt_chr(i64) nounwind
; nova runtime — process control
declare void @nova_rt_exit(i64) noreturn nounwind
declare i64 @nova_rt_system(i64) nounwind
declare i64 @nova_rt_exec(i64) nounwind
declare i32 @strcmp(ptr, ptr) nounwind readonly
; nova runtime — dict ops (hash map, O(1) avg lookup)
declare i64 @nova_rt_dict_create() nounwind
declare i64 @nova_rt_dict_set(i64, i64, i64) nounwind
declare i64 @nova_rt_dict_get(i64, i64) nounwind readonly
declare i64 @nova_rt_dict_get_concat2(i64, i64, i64) nounwind readonly
declare i64 @nova_rt_dict_set_concat2(i64, i64, i64, i64) nounwind
declare i64 @nova_rt_dict_has(i64, i64) nounwind readonly
declare i64 @nova_rt_dict_del(i64, i64) nounwind
declare i64 @nova_rt_dict_len(i64) nounwind readonly
declare i64 @nova_rt_dict_keys(i64) nounwind
declare i64 @nova_rt_dict_values(i64) nounwind
declare i64 @nova_rt_dict_items(i64) nounwind
; nova runtime — IO ops
declare i64 @nova_rt_read_line() nounwind
declare i64 @nova_rt_read_bytes(i64) nounwind
declare i64 @nova_rt_write_raw(i64) nounwind
declare i64 @nova_rt_read_file(i64) nounwind
declare i64 @nova_rt_write_file(i64, i64) nounwind
declare i64 @nova_rt_append_file(i64, i64) nounwind
declare i64 @nova_rt_file_exists(i64) nounwind readonly
; nova runtime — JSON ops
declare i64 @nova_rt_json_parse(i64) nounwind
declare i64 @nova_rt_json_stringify(i64) nounwind
; nova runtime — HTTP ops
declare i64 @nova_rt_http_get(i64) nounwind
declare i64 @nova_rt_http_post(i64, i64, i64) nounwind
; nova runtime — time ops
declare i64 @nova_rt_time_ms() nounwind
declare i64 @nova_rt_clock_ns() nounwind
declare void @nova_rt_sleep_ms(i64) nounwind
declare void @nova_rt_assert(i64, i64) nounwind
; nova runtime — type dispatch
declare i64 @nova_rt_any_to_str(i64) nounwind
declare i64 @nova_rt_str_concat_safe(i64, i64) nounwind
declare i64 @nova_rt_str_char_at(i64, i64) nounwind
declare i64 @nova_rt_type_of(i64) nounwind
declare i64 @nova_rt_range(i64) nounwind
declare i64 @nova_rt_range_from_to(i64, i64) nounwind
declare void @nova_rt_init() nounwind
declare void @nova_rt_init_args(i64, i64) nounwind
; nova runtime — system ops
declare i64 @nova_rt_args() nounwind
declare i64 @nova_rt_env(i64) nounwind
declare i64 @nova_rt_random_int(i64, i64) nounwind
declare i64 @nova_rt_random_float() nounwind
declare i64 @nova_rt_shell(i64) nounwind
declare i64 @nova_rt_path_join(i64, i64) nounwind
declare i64 @nova_rt_path_parent(i64) nounwind
declare i64 @nova_rt_path_name(i64) nounwind
declare i64 @nova_rt_path_ext(i64) nounwind
declare i64 @nova_rt_mkdir(i64) nounwind
declare i64 @nova_rt_mkdir_p(i64) nounwind
declare i64 @nova_rt_path_exists(i64) nounwind
; nova runtime — regex ops
declare i64 @nova_rt_regex_match(i64, i64) nounwind readonly
declare i64 @nova_rt_regex_find(i64, i64) nounwind
declare i64 @nova_rt_regex_replace(i64, i64, i64) nounwind
declare i64 @nova_rt_regex_split(i64, i64) nounwind
; nova runtime — collection utilities
declare i64 @nova_rt_enumerate(i64) nounwind
declare i64 @nova_rt_zip(i64, i64) nounwind
declare i64 @nova_rt_list_sum(i64) nounwind readonly
declare i64 @nova_rt_list_any(i64) nounwind readonly
declare i64 @nova_rt_list_all(i64) nounwind readonly
declare i64 @nova_rt_list_min(i64) nounwind readonly
declare i64 @nova_rt_list_max(i64) nounwind readonly
; nova runtime — set operations
declare i64 @nova_rt_set_create() nounwind
declare i64 @nova_rt_set_add(i64, i64) nounwind
declare i64 @nova_rt_set_has(i64, i64) nounwind readonly
declare i64 @nova_rt_set_remove(i64, i64) nounwind
declare i64 @nova_rt_set_len(i64) nounwind readonly
declare i64 @nova_rt_set_to_list(i64) nounwind
; nova runtime — datetime operations
declare i64 @nova_rt_datetime_now() nounwind
declare i64 @nova_rt_datetime_format(i64, i64) nounwind
declare i64 @nova_rt_datetime_year(i64) nounwind readonly
declare i64 @nova_rt_datetime_month(i64) nounwind readonly
declare i64 @nova_rt_datetime_day(i64) nounwind readonly
declare i64 @nova_rt_datetime_hour(i64) nounwind readonly
declare i64 @nova_rt_datetime_minute(i64) nounwind readonly
declare i64 @nova_rt_datetime_second(i64) nounwind readonly
; nova runtime — network ops
declare i64 @nova_rt_tcp_connect(i64, i64) nounwind
declare i64 @nova_rt_tcp_listen(i64) nounwind
declare i64 @nova_rt_tcp_accept(i64) nounwind
declare i64 @nova_rt_tcp_send(i64, i64) nounwind
declare i64 @nova_rt_tcp_recv(i64) nounwind
declare void @nova_rt_tcp_close(i64) nounwind
declare i64 @nova_rt_udp_bind(i64) nounwind
declare i64 @nova_rt_udp_send(i64, i64, i64, i64) nounwind
declare i64 @nova_rt_udp_recv(i64) nounwind
; nova runtime — HTTP server
declare i64 @nova_rt_http_listen(i64) nounwind
declare i64 @nova_rt_http_accept(i64) nounwind
declare void @nova_rt_http_respond(i64, i64, i64) nounwind
; nova runtime — byte arrays
declare i64 @nova_rt_bytes_create(i64) nounwind
declare i64 @nova_rt_bytes_get(i64, i64) nounwind
declare void @nova_rt_bytes_set(i64, i64, i64) nounwind
declare i64 @nova_rt_bytes_len(i64) nounwind
declare i64 @nova_rt_bytes_slice(i64, i64, i64) nounwind
declare i64 @nova_rt_bytes_to_str(i64) nounwind
declare i64 @nova_rt_str_to_bytes(i64) nounwind
; nova runtime — channel/spawn ops
declare i64 @nova_rt_channel_create() nounwind
declare i64 @nova_rt_channel_send(i64, i64) nounwind
declare i64 @nova_rt_channel_recv(i64) nounwind
declare i64 @nova_rt_channel_close(i64) nounwind
declare i64 @nova_rt_channel_select(i64, i64) nounwind
declare i64 @nova_rt_channel_recv_timeout(i64, i64) nounwind
declare i64 @nova_rt_spawn(i64, i64) nounwind
declare i64 @nova_rt_monitor(i64) nounwind
declare void @nova_rt_wait_all() nounwind
; nova runtime — math (trig/log via C runtime for non-intrinsic functions)
declare i64 @nova_rt_tan(i64) nounwind
declare i64 @nova_rt_asin(i64) nounwind
declare i64 @nova_rt_acos(i64) nounwind
declare i64 @nova_rt_atan(i64) nounwind
declare i64 @nova_rt_atan2(i64, i64) nounwind
declare i64 @nova_rt_fmod(i64, i64) nounwind
declare i64 @nova_rt_int_pow(i64, i64) nounwind
; nova runtime — memory management
declare void @nova_rt_cleanup() nounwind
declare void @nova_rt_track_raw(ptr) nounwind
declare i64 @nova_rt_alloc_count() nounwind readonly
declare i64 @nova_rt_live_count() nounwind readonly
; nova runtime — reference counting
declare void @nova_rc_inc(i64) nounwind
declare void @nova_rc_dec(i64) nounwind
; nova runtime — distributed computing
declare i64 @nova_rt_serialize(i64) nounwind
declare i64 @nova_rt_deserialize(i64) nounwind
declare i64 @nova_rt_serialize_to_hex(i64) nounwind
declare i64 @nova_rt_node_listen(i64) nounwind
declare i64 @nova_rt_node_accept(i64) nounwind
declare void @nova_rt_node_stop(i64) nounwind
declare i64 @nova_rt_node_connect(i64) nounwind
declare i64 @nova_rt_remote_channel_create(i64) nounwind
declare i64 @nova_rt_remote_send(i64, i64) nounwind
declare i64 @nova_rt_remote_recv(i64) nounwind
declare void @nova_rt_remote_close(i64) nounwind
declare i64 @nova_rt_remote_spawn(i64, i64, i64) nounwind
declare i64 @nova_rt_node_recv_spawn(i64) nounwind
; nova error state — thread-local flag (safe for spawn/concurrent programs)
@__nova_error_flag = thread_local global i64 0
@__nova_error_msg = thread_local global i64 0

@.str.0 = private unnamed_addr constant [27 x i8] c"time_ms should be positive\00"
@.str.1 = private unnamed_addr constant [15 x i8] c"datetime_now: \00"
@.str.2 = private unnamed_addr constant [1 x i8] c"\00"
@.str.3 = private unnamed_addr constant [33 x i8] c"datetime should be a real string\00"
@.str.4 = private unnamed_addr constant [7 x i8] c"year: \00"
@.str.5 = private unnamed_addr constant [8 x i8] c"month: \00"
@.str.6 = private unnamed_addr constant [6 x i8] c"day: \00"
@.str.7 = private unnamed_addr constant [7 x i8] c"hour: \00"
@.str.8 = private unnamed_addr constant [9 x i8] c"minute: \00"
@.str.9 = private unnamed_addr constant [9 x i8] c"second: \00"
@.str.10 = private unnamed_addr constant [23 x i8] c"year should be >= 2026\00"
@.str.11 = private unnamed_addr constant [11 x i8] c"month >= 1\00"
@.str.12 = private unnamed_addr constant [12 x i8] c"month <= 12\00"
@.str.13 = private unnamed_addr constant [9 x i8] c"day >= 1\00"
@.str.14 = private unnamed_addr constant [10 x i8] c"day <= 31\00"
@.str.15 = private unnamed_addr constant [10 x i8] c"hour >= 0\00"
@.str.16 = private unnamed_addr constant [11 x i8] c"hour <= 23\00"
@.str.17 = private unnamed_addr constant [9 x i8] c"%Y/%m/%d\00"
@.str.18 = private unnamed_addr constant [12 x i8] c"formatted: \00"
@.str.19 = private unnamed_addr constant [34 x i8] c"formatted date should be 10 chars\00"
@.str.20 = private unnamed_addr constant [26 x i8] c"all datetime tests passed\00"
@.str.21 = private unnamed_addr constant [6 x i8] c"%lld\0A\00"
@.str.22 = private unnamed_addr constant [4 x i8] c"%f\0A\00"
@.str.23 = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.str.24 = private unnamed_addr constant [5 x i8] c"true\00"
@.str.25 = private unnamed_addr constant [6 x i8] c"false\00"

define i64 @nova_user_main() nounwind {
entry0:
  %r2 = call i64 @nova_rt_time_ms()
  %t0 = icmp sgt i64 %r2, 0
  %r8 = zext i1 %t0 to i64
  %t1 = getelementptr inbounds [27 x i8], ptr @.str.0, i64 0, i64 0
  %r9 = ptrtoint ptr %t1 to i64
  call void @nova_rt_assert(i64 %r8, i64 %r9)
  %r12 = call i64 @nova_rt_datetime_now()
  %t2 = getelementptr inbounds [15 x i8], ptr @.str.1, i64 0, i64 0
  %r16 = ptrtoint ptr %t2 to i64
  call void @nova_rc_inc(i64 %r12)
  %t3 = getelementptr inbounds [1 x i8], ptr @.str.2, i64 0, i64 0
  %r19 = ptrtoint ptr %t3 to i64
  %t4 = call i64 @nova_rt_str_concat(i64 %r16, i64 %r12)
  %t5 = call i64 @nova_rt_str_concat(i64 %t4, i64 %r19)
  call void @nova_rc_dec(i64 %t4)
  call void @nova_rc_dec(i64 %r12)
  %t6 = inttoptr i64 %t5 to ptr
  call i32 @puts(ptr %t6)
  call void @nova_rc_dec(i64 %t5)
  %r23 = call i64 @nova_rt_len(i64 %r12)
  call void @nova_rc_dec(i64 %r12)
  %t7 = icmp sgt i64 %r23, 10
  %r25 = zext i1 %t7 to i64
  %t8 = getelementptr inbounds [33 x i8], ptr @.str.3, i64 0, i64 0
  %r26 = ptrtoint ptr %t8 to i64
  call void @nova_rt_assert(i64 %r25, i64 %r26)
  %r30 = call i64 @nova_rt_datetime_year(i64 %r2)
  %r36 = call i64 @nova_rt_datetime_month(i64 %r2)
  %r42 = call i64 @nova_rt_datetime_day(i64 %r2)
  %r48 = call i64 @nova_rt_datetime_hour(i64 %r2)
  %r54 = call i64 @nova_rt_datetime_minute(i64 %r2)
  %r60 = call i64 @nova_rt_datetime_second(i64 %r2)
  %t9 = getelementptr inbounds [7 x i8], ptr @.str.4, i64 0, i64 0
  %r64 = ptrtoint ptr %t9 to i64
  %r66 = call i64 @nova_rt_int_to_str(i64 %r30)
  %t10 = getelementptr inbounds [1 x i8], ptr @.str.2, i64 0, i64 0
  %r67 = ptrtoint ptr %t10 to i64
  %t11 = call i64 @nova_rt_str_concat(i64 %r64, i64 %r66)
  %t12 = call i64 @nova_rt_str_concat(i64 %t11, i64 %r67)
  call void @nova_rc_dec(i64 %t11)
  call void @nova_rc_dec(i64 %r66)
  %t13 = inttoptr i64 %t12 to ptr
  call i32 @puts(ptr %t13)
  call void @nova_rc_dec(i64 %t12)
  %t14 = getelementptr inbounds [8 x i8], ptr @.str.5, i64 0, i64 0
  %r70 = ptrtoint ptr %t14 to i64
  %r72 = call i64 @nova_rt_int_to_str(i64 %r36)
  %t15 = getelementptr inbounds [1 x i8], ptr @.str.2, i64 0, i64 0
  %r73 = ptrtoint ptr %t15 to i64
  %t16 = call i64 @nova_rt_str_concat(i64 %r70, i64 %r72)
  %t17 = call i64 @nova_rt_str_concat(i64 %t16, i64 %r73)
  call void @nova_rc_dec(i64 %t16)
  call void @nova_rc_dec(i64 %r72)
  %t18 = inttoptr i64 %t17 to ptr
  call i32 @puts(ptr %t18)
  call void @nova_rc_dec(i64 %t17)
  %t19 = getelementptr inbounds [6 x i8], ptr @.str.6, i64 0, i64 0
  %r76 = ptrtoint ptr %t19 to i64
  %r78 = call i64 @nova_rt_int_to_str(i64 %r42)
  %t20 = getelementptr inbounds [1 x i8], ptr @.str.2, i64 0, i64 0
  %r79 = ptrtoint ptr %t20 to i64
  %t21 = call i64 @nova_rt_str_concat(i64 %r76, i64 %r78)
  %t22 = call i64 @nova_rt_str_concat(i64 %t21, i64 %r79)
  call void @nova_rc_dec(i64 %t21)
  call void @nova_rc_dec(i64 %r78)
  %t23 = inttoptr i64 %t22 to ptr
  call i32 @puts(ptr %t23)
  call void @nova_rc_dec(i64 %t22)
  %t24 = getelementptr inbounds [7 x i8], ptr @.str.7, i64 0, i64 0
  %r82 = ptrtoint ptr %t24 to i64
  %r84 = call i64 @nova_rt_int_to_str(i64 %r48)
  %t25 = getelementptr inbounds [1 x i8], ptr @.str.2, i64 0, i64 0
  %r85 = ptrtoint ptr %t25 to i64
  %t26 = call i64 @nova_rt_str_concat(i64 %r82, i64 %r84)
  %t27 = call i64 @nova_rt_str_concat(i64 %t26, i64 %r85)
  call void @nova_rc_dec(i64 %t26)
  call void @nova_rc_dec(i64 %r84)
  %t28 = inttoptr i64 %t27 to ptr
  call i32 @puts(ptr %t28)
  call void @nova_rc_dec(i64 %t27)
  %t29 = getelementptr inbounds [9 x i8], ptr @.str.8, i64 0, i64 0
  %r88 = ptrtoint ptr %t29 to i64
  %r90 = call i64 @nova_rt_int_to_str(i64 %r54)
  %t30 = getelementptr inbounds [1 x i8], ptr @.str.2, i64 0, i64 0
  %r91 = ptrtoint ptr %t30 to i64
  %t31 = call i64 @nova_rt_str_concat(i64 %r88, i64 %r90)
  %t32 = call i64 @nova_rt_str_concat(i64 %t31, i64 %r91)
  call void @nova_rc_dec(i64 %t31)
  call void @nova_rc_dec(i64 %r90)
  %t33 = inttoptr i64 %t32 to ptr
  call i32 @puts(ptr %t33)
  call void @nova_rc_dec(i64 %t32)
  %t34 = getelementptr inbounds [9 x i8], ptr @.str.9, i64 0, i64 0
  %r94 = ptrtoint ptr %t34 to i64
  %r96 = call i64 @nova_rt_int_to_str(i64 %r60)
  %t35 = getelementptr inbounds [1 x i8], ptr @.str.2, i64 0, i64 0
  %r97 = ptrtoint ptr %t35 to i64
  %t36 = call i64 @nova_rt_str_concat(i64 %r94, i64 %r96)
  %t37 = call i64 @nova_rt_str_concat(i64 %t36, i64 %r97)
  call void @nova_rc_dec(i64 %t36)
  call void @nova_rc_dec(i64 %r96)
  %t38 = inttoptr i64 %t37 to ptr
  call i32 @puts(ptr %t38)
  call void @nova_rc_dec(i64 %t37)
  %t39 = icmp sge i64 %r30, 2026
  %r102 = zext i1 %t39 to i64
  %t40 = getelementptr inbounds [23 x i8], ptr @.str.10, i64 0, i64 0
  %r103 = ptrtoint ptr %t40 to i64
  call void @nova_rt_assert(i64 %r102, i64 %r103)
  %t41 = icmp sge i64 %r36, 1
  %r107 = zext i1 %t41 to i64
  %t42 = getelementptr inbounds [11 x i8], ptr @.str.11, i64 0, i64 0
  %r108 = ptrtoint ptr %t42 to i64
  call void @nova_rt_assert(i64 %r107, i64 %r108)
  %t43 = icmp sle i64 %r36, 12
  %r112 = zext i1 %t43 to i64
  %t44 = getelementptr inbounds [12 x i8], ptr @.str.12, i64 0, i64 0
  %r113 = ptrtoint ptr %t44 to i64
  call void @nova_rt_assert(i64 %r112, i64 %r113)
  %t45 = icmp sge i64 %r42, 1
  %r117 = zext i1 %t45 to i64
  %t46 = getelementptr inbounds [9 x i8], ptr @.str.13, i64 0, i64 0
  %r118 = ptrtoint ptr %t46 to i64
  call void @nova_rt_assert(i64 %r117, i64 %r118)
  %t47 = icmp sle i64 %r42, 31
  %r122 = zext i1 %t47 to i64
  %t48 = getelementptr inbounds [10 x i8], ptr @.str.14, i64 0, i64 0
  %r123 = ptrtoint ptr %t48 to i64
  call void @nova_rt_assert(i64 %r122, i64 %r123)
  %t49 = icmp sge i64 %r48, 0
  %r127 = zext i1 %t49 to i64
  %t50 = getelementptr inbounds [10 x i8], ptr @.str.15, i64 0, i64 0
  %r128 = ptrtoint ptr %t50 to i64
  call void @nova_rt_assert(i64 %r127, i64 %r128)
  %t51 = icmp sle i64 %r48, 23
  %r132 = zext i1 %t51 to i64
  %t52 = getelementptr inbounds [11 x i8], ptr @.str.16, i64 0, i64 0
  %r133 = ptrtoint ptr %t52 to i64
  call void @nova_rt_assert(i64 %r132, i64 %r133)
  %t53 = getelementptr inbounds [9 x i8], ptr @.str.17, i64 0, i64 0
  %r137 = ptrtoint ptr %t53 to i64
  %r138 = call i64 @nova_rt_datetime_format(i64 %r2, i64 %r137)
  %t54 = getelementptr inbounds [12 x i8], ptr @.str.18, i64 0, i64 0
  %r142 = ptrtoint ptr %t54 to i64
  call void @nova_rc_inc(i64 %r138)
  %t55 = getelementptr inbounds [1 x i8], ptr @.str.2, i64 0, i64 0
  %r145 = ptrtoint ptr %t55 to i64
  %t56 = call i64 @nova_rt_str_concat(i64 %r142, i64 %r138)
  %t57 = call i64 @nova_rt_str_concat(i64 %t56, i64 %r145)
  call void @nova_rc_dec(i64 %t56)
  call void @nova_rc_dec(i64 %r138)
  %t58 = inttoptr i64 %t57 to ptr
  call i32 @puts(ptr %t58)
  call void @nova_rc_dec(i64 %t57)
  %r149 = call i64 @nova_rt_len(i64 %r138)
  call void @nova_rc_dec(i64 %r138)
  %t59 = icmp eq i64 %r149, 10
  %r151 = zext i1 %t59 to i64
  %t60 = getelementptr inbounds [34 x i8], ptr @.str.19, i64 0, i64 0
  %r152 = ptrtoint ptr %t60 to i64
  call void @nova_rt_assert(i64 %r151, i64 %r152)
  %t61 = getelementptr inbounds [26 x i8], ptr @.str.20, i64 0, i64 0
  %r154 = ptrtoint ptr %t61 to i64
  %t62 = inttoptr i64 %r154 to ptr
  call i32 @puts(ptr %t62)
  ret i64 0
}

define i64 @nova_main() nounwind {
entry0:
  %r0 = call i64 @nova_user_main()
  ret i64 0
}

define i32 @main(i32 %argc, ptr %argv) nounwind {
entry:
  %argc64 = sext i32 %argc to i64
  %argv64 = ptrtoint ptr %argv to i64
  call void @nova_rt_init_args(i64 %argc64, i64 %argv64)
  call i64 @nova_main()
  call i64 @nova_user_main()
  call void @nova_rt_wait_all()
  call void @nova_rt_cleanup()
  ret i32 0
}

!0 = !{!"NOVA TBAA"}
!1 = !{!"list_data_ptr", !0}
!2 = !{!1, !1, i64 0}
!3 = !{!"list_elem", !0}
!4 = !{!3, !3, i64 0}
!5 = !{!"list_size", !0}
!6 = !{!5, !5, i64 0}
!7 = !{!"list_cap", !0}
!8 = !{!7, !7, i64 0}
!90 = !{!"branch_weights", i32 2000, i32 1}
!91 = distinct !{!91, !92, !93}
!92 = !{!"llvm.loop.unroll.enable"}
!93 = !{!"llvm.loop.vectorize.enable", i1 true}
