; Generated by NOVA compiler
target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"

declare i32 @printf(ptr, ...)
declare i32 @puts(ptr)
declare noalias ptr @malloc(i64) nounwind allocsize(0)
declare noalias ptr @calloc(i64, i64) nounwind
declare ptr @realloc(ptr, i64) nounwind allocsize(1)
declare void @free(ptr) nounwind
declare ptr @nova_rt_struct_alloc(i64) nounwind
declare i64 @llvm.smax.i64(i64, i64) nounwind readnone
; nova runtime — list ops
declare i64 @nova_rt_list_create() nounwind
declare i64 @nova_rt_list_create_filled(i64, i64) nounwind
declare i64 @nova_rt_list_append(i64, i64) nounwind
declare i64 @nova_rt_list_get(i64, i64) nounwind readonly
declare i64 @nova_rt_list_set(i64, i64, i64) nounwind
declare i64 @nova_rt_list_len(i64) nounwind readonly
declare i64 @nova_rt_list_print(i64) nounwind
declare i64 @nova_rt_iter_has_next(i64, i64) nounwind readonly
declare i64 @nova_rt_iter_get(i64, i64) nounwind readonly
declare i64 @nova_rt_list_iter_has_next(i64, i64) nounwind readonly
declare i64 @nova_rt_list_iter_get(i64, i64) nounwind readonly
; nova runtime — string ops
declare i64 @nova_rt_str_concat(i64, i64) nounwind
declare i64 @nova_rt_int_to_str(i64) nounwind
declare i64 @nova_rt_float_to_str(i64) nounwind
declare i64 @nova_rt_bool_to_str(i64) nounwind
declare i64 @nova_rt_str_len(i64) nounwind readonly
declare i64 @nova_rt_len(i64) nounwind readonly
declare i64 @nova_rt_contains(i64, i64) nounwind readonly
declare i64 @nova_rt_slice(i64, i64, i64) nounwind
declare i64 @nova_rt_upper(i64) nounwind
declare i64 @nova_rt_lower(i64) nounwind
declare i64 @nova_rt_trim(i64) nounwind
declare i64 @nova_rt_repeat(i64, i64) nounwind
declare i64 @nova_rt_split(i64, i64) nounwind
declare i64 @nova_rt_replace(i64, i64, i64) nounwind
declare i64 @nova_rt_starts_with(i64, i64) nounwind readonly
declare i64 @nova_rt_ends_with(i64, i64) nounwind readonly
declare i64 @nova_rt_find(i64, i64) nounwind readonly
declare i64 @nova_rt_join(i64, i64) nounwind
declare i64 @nova_rt_chars(i64) nounwind
; nova runtime — list stdlib
declare i64 @nova_rt_list_reverse(i64) nounwind
declare i64 @nova_rt_list_sort(i64) nounwind
declare i64 @nova_rt_list_map(i64, i64) nounwind
declare i64 @nova_rt_list_filter(i64, i64) nounwind
declare i64 @nova_rt_list_concat(i64, i64) nounwind
declare i64 @nova_rt_list_slice(i64, i64, i64) nounwind
declare i64 @nova_rt_list_to_str(i64) nounwind
declare i64 @nova_rt_len_any(i64) nounwind readonly
; nova runtime — type conversions
declare i64 @nova_rt_parse_int(i64) nounwind
declare i64 @nova_rt_parse_float(i64) nounwind
; nova runtime — character ops
declare i64 @nova_rt_ord(i64) nounwind readonly
declare i64 @nova_rt_chr(i64) nounwind
; nova runtime — process control
declare void @nova_rt_exit(i64) noreturn nounwind
declare i64 @nova_rt_system(i64) nounwind
declare i64 @nova_rt_exec(i64) nounwind
declare i32 @strcmp(ptr, ptr) nounwind readonly
; nova runtime — dict ops (hash map, O(1) avg lookup)
declare i64 @nova_rt_dict_create() nounwind
declare i64 @nova_rt_dict_set(i64, i64, i64) nounwind
declare i64 @nova_rt_dict_get(i64, i64) nounwind readonly
declare i64 @nova_rt_dict_get_concat2(i64, i64, i64) nounwind readonly
declare i64 @nova_rt_dict_set_concat2(i64, i64, i64, i64) nounwind
declare i64 @nova_rt_dict_has(i64, i64) nounwind readonly
declare i64 @nova_rt_dict_del(i64, i64) nounwind
declare i64 @nova_rt_dict_len(i64) nounwind readonly
declare i64 @nova_rt_dict_keys(i64) nounwind
declare i64 @nova_rt_dict_values(i64) nounwind
declare i64 @nova_rt_dict_items(i64) nounwind
; nova runtime — IO ops
declare i64 @nova_rt_read_line() nounwind
declare i64 @nova_rt_read_bytes(i64) nounwind
declare i64 @nova_rt_write_raw(i64) nounwind
declare i64 @nova_rt_read_file(i64) nounwind
declare i64 @nova_rt_write_file(i64, i64) nounwind
declare i64 @nova_rt_append_file(i64, i64) nounwind
declare i64 @nova_rt_file_exists(i64) nounwind readonly
; nova runtime — JSON ops
declare i64 @nova_rt_json_parse(i64) nounwind
declare i64 @nova_rt_json_stringify(i64) nounwind
; nova runtime — HTTP ops
declare i64 @nova_rt_http_get(i64) nounwind
declare i64 @nova_rt_http_post(i64, i64, i64) nounwind
; nova runtime — time ops
declare i64 @nova_rt_time_ms() nounwind
declare i64 @nova_rt_clock_ns() nounwind
declare void @nova_rt_sleep_ms(i64) nounwind
declare void @nova_rt_assert(i64, i64) nounwind
; nova runtime — type dispatch
declare i64 @nova_rt_any_to_str(i64) nounwind
declare i64 @nova_rt_str_concat_safe(i64, i64) nounwind
declare i64 @nova_rt_str_char_at(i64, i64) nounwind
declare void @nova_rt_init() nounwind
declare void @nova_rt_init_args(i64, i64) nounwind
; nova runtime — system ops
declare i64 @nova_rt_args() nounwind
declare i64 @nova_rt_env(i64) nounwind
declare i64 @nova_rt_random_int(i64, i64) nounwind
declare i64 @nova_rt_random_float() nounwind
declare i64 @nova_rt_shell(i64) nounwind
declare i64 @nova_rt_path_join(i64, i64) nounwind
declare i64 @nova_rt_path_parent(i64) nounwind
declare i64 @nova_rt_path_name(i64) nounwind
declare i64 @nova_rt_path_ext(i64) nounwind
declare i64 @nova_rt_mkdir(i64) nounwind
declare i64 @nova_rt_mkdir_p(i64) nounwind
declare i64 @nova_rt_path_exists(i64) nounwind
; nova runtime — regex ops
declare i64 @nova_rt_regex_match(i64, i64) nounwind readonly
declare i64 @nova_rt_regex_find(i64, i64) nounwind
declare i64 @nova_rt_regex_replace(i64, i64, i64) nounwind
declare i64 @nova_rt_regex_split(i64, i64) nounwind
; nova runtime — network ops
declare i64 @nova_rt_tcp_connect(i64, i64) nounwind
declare i64 @nova_rt_tcp_listen(i64) nounwind
declare i64 @nova_rt_tcp_accept(i64) nounwind
declare i64 @nova_rt_tcp_send(i64, i64) nounwind
declare i64 @nova_rt_tcp_recv(i64) nounwind
declare void @nova_rt_tcp_close(i64) nounwind
declare i64 @nova_rt_udp_bind(i64) nounwind
declare i64 @nova_rt_udp_send(i64, i64, i64, i64) nounwind
declare i64 @nova_rt_udp_recv(i64) nounwind
; nova runtime — HTTP server
declare i64 @nova_rt_http_listen(i64) nounwind
declare i64 @nova_rt_http_accept(i64) nounwind
declare void @nova_rt_http_respond(i64, i64, i64) nounwind
; nova runtime — byte arrays
declare i64 @nova_rt_bytes_create(i64) nounwind
declare i64 @nova_rt_bytes_get(i64, i64) nounwind
declare void @nova_rt_bytes_set(i64, i64, i64) nounwind
declare i64 @nova_rt_bytes_len(i64) nounwind
declare i64 @nova_rt_bytes_slice(i64, i64, i64) nounwind
declare i64 @nova_rt_bytes_to_str(i64) nounwind
declare i64 @nova_rt_str_to_bytes(i64) nounwind
; nova runtime — channel/spawn ops
declare i64 @nova_rt_channel_create() nounwind
declare i64 @nova_rt_channel_send(i64, i64) nounwind
declare i64 @nova_rt_channel_recv(i64) nounwind
declare i64 @nova_rt_channel_close(i64) nounwind
declare i64 @nova_rt_channel_select(i64, i64) nounwind
declare i64 @nova_rt_channel_recv_timeout(i64, i64) nounwind
declare i64 @nova_rt_spawn(i64, i64) nounwind
declare i64 @nova_rt_monitor(i64) nounwind
declare void @nova_rt_wait_all() nounwind
; nova runtime — math (trig/log via C runtime for non-intrinsic functions)
declare i64 @nova_rt_tan(i64) nounwind
declare i64 @nova_rt_asin(i64) nounwind
declare i64 @nova_rt_acos(i64) nounwind
declare i64 @nova_rt_atan(i64) nounwind
declare i64 @nova_rt_atan2(i64, i64) nounwind
declare i64 @nova_rt_fmod(i64, i64) nounwind
declare i64 @nova_rt_int_pow(i64, i64) nounwind
; nova runtime — memory management
declare void @nova_rt_cleanup() nounwind
declare void @nova_rt_track_raw(ptr) nounwind
declare i64 @nova_rt_alloc_count() nounwind readonly
declare i64 @nova_rt_live_count() nounwind readonly
; nova runtime — reference counting
declare void @nova_rc_inc(i64) nounwind
declare void @nova_rc_dec(i64) nounwind
; nova error state — thread-local flag (safe for spawn/concurrent programs)
@__nova_error_flag = thread_local global i64 0
@__nova_error_msg = thread_local global i64 0

@.str.0 = private unnamed_addr constant [17 x i8] c"division by zero\00"
@.str.1 = private unnamed_addr constant [15 x i8] c"Caught error: \00"
@.str.2 = private unnamed_addr constant [1 x i8] c"\00"
@.str.3 = private unnamed_addr constant [9 x i8] c"Result: \00"
@.str.4 = private unnamed_addr constant [22 x i8] c"Should not reach here\00"
@.str.5 = private unnamed_addr constant [14 x i8] c"Good result: \00"
@.str.6 = private unnamed_addr constant [6 x i8] c"hello\00"
@.str.7 = private unnamed_addr constant [6 x i8] c"world\00"
@.str.8 = private unnamed_addr constant [20 x i8] c"index out of bounds\00"
@.str.9 = private unnamed_addr constant [15 x i8] c"Lookup error: \00"
@.str.10 = private unnamed_addr constant [8 x i8] c"default\00"
@.str.11 = private unnamed_addr constant [16 x i8] c"Lookup result: \00"
@.str.12 = private unnamed_addr constant [9 x i8] c"fallback\00"
@.str.13 = private unnamed_addr constant [12 x i8] c"Lookup ok: \00"
@.str.14 = private unnamed_addr constant [24 x i8] c"All error tests passed!\00"
@.str.15 = private unnamed_addr constant [6 x i8] c"%lld\0A\00"
@.str.16 = private unnamed_addr constant [4 x i8] c"%f\0A\00"
@.str.17 = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.str.18 = private unnamed_addr constant [5 x i8] c"true\00"
@.str.19 = private unnamed_addr constant [6 x i8] c"false\00"

define i64 @nova_user_main() nounwind {
entry0:
  %slot.__mb0_ret = alloca i64, align 8
  %slot.__catch_0 = alloca i64, align 8
  %slot.__catch_1 = alloca i64, align 8
  %slot.items = alloca i64, align 8
  %slot.__catch_3 = alloca i64, align 8
  %slot.__catch_4 = alloca i64, align 8
  %slot.__mb1_ret = alloca i64, align 8
  %slot.__mb1_a = alloca i64, align 8
  %slot.__mb1_b = alloca i64, align 8
  %slot.__mb2_ret = alloca i64, align 8
  %slot.__mb2_items = alloca i64, align 8
  %slot.__mb2_idx = alloca i64, align 8
  %slot.__mb2___sc_or_0 = alloca i64, align 8
  %slot.__mb3_ret = alloca i64, align 8
  %slot.__mb3_items = alloca i64, align 8
  %slot.__mb3_idx = alloca i64, align 8
  %slot.__mb3___sc_or_0 = alloca i64, align 8
  store i64 0, ptr %slot.__catch_0, align 8
  store i64 0, ptr %slot.__catch_1, align 8
  store i64 0, ptr %slot.items, align 8
  store i64 0, ptr %slot.__mb2_items, align 8
  store i64 0, ptr %slot.__mb2_ret, align 8
  store i64 0, ptr %slot.__catch_3, align 8
  store i64 0, ptr %slot.__mb3_items, align 8
  store i64 0, ptr %slot.__mb3_ret, align 8
  store i64 0, ptr %slot.__catch_4, align 8
  br label %__mb0_entry0

__mb0_entry0:
  br label %__mb0_ifb_then1

__mb0_ifb_then1:
  %t0 = getelementptr inbounds [17 x i8], ptr @.str.0, i64 0, i64 0
  %r132 = ptrtoint ptr %t0 to i64
  store i64 1, ptr @__nova_error_flag
  store i64 %r132, ptr @__nova_error_msg
  store i64 0, ptr %slot.__mb0_ret, align 8
  br label %__mb0_merge

__mb0_merge:
  %r141 = load i64, ptr %slot.__mb0_ret, align 8
  %t1 = load i64, ptr @__nova_error_flag
  store i64 0, ptr @__nova_error_flag
  %t2 = icmp ne i64 %t1, 0
  br i1 %t2, label %catch_err1, label %catch_ok2

catch_err1:
  %t3 = load i64, ptr @__nova_error_msg
  store i64 0, ptr @__nova_error_msg
  %t4 = getelementptr inbounds [15 x i8], ptr @.str.1, i64 0, i64 0
  %r11 = ptrtoint ptr %t4 to i64
  %t5 = getelementptr inbounds [1 x i8], ptr @.str.2, i64 0, i64 0
  %r14 = ptrtoint ptr %t5 to i64
  %t6 = call i64 @nova_rt_str_concat(i64 %r11, i64 %t3)
  %t7 = call i64 @nova_rt_str_concat(i64 %t6, i64 %r14)
  call void @nova_rc_dec(i64 %t6)
  call void @nova_rc_dec(i64 %t3)
  %t8 = inttoptr i64 %t7 to ptr
  call i32 @puts(ptr %t8)
  call void @nova_rc_dec(i64 %t7)
  store i64 -1, ptr %slot.__catch_0, align 8
  br label %catch_merge3

catch_ok2:
  %t9 = load i64, ptr %slot.__catch_0, align 8
  call void @nova_rc_dec(i64 %t9)
  store i64 %r141, ptr %slot.__catch_0, align 8
  br label %catch_merge3

catch_merge3:
  %r22 = load i64, ptr %slot.__catch_0, align 8
  %t10 = getelementptr inbounds [9 x i8], ptr @.str.3, i64 0, i64 0
  %r26 = ptrtoint ptr %t10 to i64
  %r28 = call i64 @nova_rt_int_to_str(i64 %r22)
  %t11 = getelementptr inbounds [1 x i8], ptr @.str.2, i64 0, i64 0
  %r29 = ptrtoint ptr %t11 to i64
  %t12 = call i64 @nova_rt_str_concat(i64 %r26, i64 %r28)
  %t13 = call i64 @nova_rt_str_concat(i64 %t12, i64 %r29)
  call void @nova_rc_dec(i64 %t12)
  call void @nova_rc_dec(i64 %r28)
  %t14 = inttoptr i64 %t13 to ptr
  call i32 @puts(ptr %t14)
  call void @nova_rc_dec(i64 %t13)
  br label %__mb1_entry0

__mb1_entry0:
  store i64 20, ptr %slot.__mb1_a, align 8
  store i64 4, ptr %slot.__mb1_b, align 8
  br label %__mb1_ifb_else2

__mb1_ifb_else2:
  br label %__mb1_ifb_merge3

__mb1_ifb_merge3:
  %r161 = load i64, ptr %slot.__mb1_a, align 8
  %r162 = load i64, ptr %slot.__mb1_b, align 8
  %r163 = sdiv i64 %r161, %r162
  store i64 %r163, ptr %slot.__mb1_ret, align 8
  br label %__mb1_merge

__mb1_merge:
  %r164 = load i64, ptr %slot.__mb1_ret, align 8
  %t15 = load i64, ptr @__nova_error_flag
  store i64 0, ptr @__nova_error_flag
  %t16 = icmp ne i64 %t15, 0
  br i1 %t16, label %catch_err4, label %catch_ok5

catch_err4:
  %t17 = load i64, ptr @__nova_error_msg
  store i64 0, ptr @__nova_error_msg
  %t18 = getelementptr inbounds [22 x i8], ptr @.str.4, i64 0, i64 0
  %r42 = ptrtoint ptr %t18 to i64
  %t19 = inttoptr i64 %r42 to ptr
  call i32 @puts(ptr %t19)
  store i64 -1, ptr %slot.__catch_1, align 8
  br label %catch_merge6

catch_ok5:
  %t20 = load i64, ptr %slot.__catch_1, align 8
  call void @nova_rc_dec(i64 %t20)
  store i64 %r164, ptr %slot.__catch_1, align 8
  br label %catch_merge6

catch_merge6:
  %r49 = load i64, ptr %slot.__catch_1, align 8
  %t21 = getelementptr inbounds [14 x i8], ptr @.str.5, i64 0, i64 0
  %r53 = ptrtoint ptr %t21 to i64
  %r55 = call i64 @nova_rt_int_to_str(i64 %r49)
  %t22 = getelementptr inbounds [1 x i8], ptr @.str.2, i64 0, i64 0
  %r56 = ptrtoint ptr %t22 to i64
  %t23 = call i64 @nova_rt_str_concat(i64 %r53, i64 %r55)
  %t24 = call i64 @nova_rt_str_concat(i64 %t23, i64 %r56)
  call void @nova_rc_dec(i64 %t23)
  call void @nova_rc_dec(i64 %r55)
  %t25 = inttoptr i64 %t24 to ptr
  call i32 @puts(ptr %t25)
  call void @nova_rc_dec(i64 %t24)
  %t26 = getelementptr inbounds [6 x i8], ptr @.str.6, i64 0, i64 0
  %r60 = ptrtoint ptr %t26 to i64
  %t27 = getelementptr inbounds [6 x i8], ptr @.str.7, i64 0, i64 0
  %r61 = ptrtoint ptr %t27 to i64
  %r62 = call i64 @nova_rt_list_create()
  %t28 = call i64 @nova_rt_list_append(i64 %r62, i64 %r60)
  %t29 = call i64 @nova_rt_list_append(i64 %r62, i64 %r61)
  %t30 = load i64, ptr %slot.items, align 8
  call void @nova_rc_dec(i64 %t30)
  store i64 %r62, ptr %slot.items, align 8
  %r67 = load i64, ptr %slot.items, align 8
  br label %__mb2_entry0

__mb2_entry0:
  %t31 = load i64, ptr %slot.__mb2_items, align 8
  call void @nova_rc_dec(i64 %t31)
  call void @nova_rc_inc(i64 %r67)
  store i64 %r67, ptr %slot.__mb2_items, align 8
  store i64 5, ptr %slot.__mb2_idx, align 8
  store i64 1, ptr %slot.__mb2___sc_or_0, align 8
  %t32 = icmp ne i64 0, 0
  br i1 %t32, label %__mb2_sc_or_merge2, label %__mb2_sc_or_right1

__mb2_sc_or_right1:
  %r181 = load i64, ptr %slot.__mb2_idx, align 8
  %r182 = load i64, ptr %slot.__mb2_items, align 8
  %r183 = call i64 @nova_rt_list_len(i64 %r182)
  %t33 = icmp sge i64 %r181, %r183
  %r184 = zext i1 %t33 to i64
  store i64 %r184, ptr %slot.__mb2___sc_or_0, align 8
  br label %__mb2_sc_or_merge2

__mb2_sc_or_merge2:
  %r186 = load i64, ptr %slot.__mb2___sc_or_0, align 8
  %t34 = trunc i64 %r186 to i1
  br i1 %t34, label %__mb2_ifb_then3, label %__mb2_ifb_else4

__mb2_ifb_then3:
  %t35 = getelementptr inbounds [20 x i8], ptr @.str.8, i64 0, i64 0
  %r189 = ptrtoint ptr %t35 to i64
  store i64 1, ptr @__nova_error_flag
  store i64 %r189, ptr @__nova_error_msg
  %t36 = getelementptr inbounds [1 x i8], ptr @.str.2, i64 0, i64 0
  %r191 = ptrtoint ptr %t36 to i64
  %t37 = load i64, ptr %slot.__mb2_ret, align 8
  call void @nova_rc_dec(i64 %t37)
  store i64 %r191, ptr %slot.__mb2_ret, align 8
  br label %__mb2_merge

__mb2_ifb_else4:
  br label %__mb2_ifb_merge5

__mb2_ifb_merge5:
  %r195 = load i64, ptr %slot.__mb2_items, align 8
  %r196 = load i64, ptr %slot.__mb2_idx, align 8
  %t38 = inttoptr i64 %r195 to ptr
  %t39 = load ptr, ptr %t38, align 8, !tbaa !2
  %t40 = getelementptr i64, ptr %t39, i64 %r196
  %r197 = load i64, ptr %t40, align 8, !tbaa !4
  %t41 = load i64, ptr %slot.__mb2_ret, align 8
  call void @nova_rc_dec(i64 %t41)
  call void @nova_rc_inc(i64 %r197)
  store i64 %r197, ptr %slot.__mb2_ret, align 8
  br label %__mb2_merge

__mb2_merge:
  %r198 = load i64, ptr %slot.__mb2_ret, align 8
  %t42 = load i64, ptr @__nova_error_flag
  store i64 0, ptr @__nova_error_flag
  %t43 = icmp ne i64 %t42, 0
  br i1 %t43, label %catch_err7, label %catch_ok8

catch_err7:
  %t44 = load i64, ptr @__nova_error_msg
  store i64 0, ptr @__nova_error_msg
  %t45 = getelementptr inbounds [15 x i8], ptr @.str.9, i64 0, i64 0
  %r76 = ptrtoint ptr %t45 to i64
  %t46 = getelementptr inbounds [1 x i8], ptr @.str.2, i64 0, i64 0
  %r79 = ptrtoint ptr %t46 to i64
  %t47 = call i64 @nova_rt_str_concat(i64 %r76, i64 %t44)
  %t48 = call i64 @nova_rt_str_concat(i64 %t47, i64 %r79)
  call void @nova_rc_dec(i64 %t47)
  call void @nova_rc_dec(i64 %t44)
  %t49 = inttoptr i64 %t48 to ptr
  call i32 @puts(ptr %t49)
  call void @nova_rc_dec(i64 %t48)
  %t50 = getelementptr inbounds [8 x i8], ptr @.str.10, i64 0, i64 0
  %r82 = ptrtoint ptr %t50 to i64
  %t51 = load i64, ptr %slot.__catch_3, align 8
  call void @nova_rc_dec(i64 %t51)
  store i64 %r82, ptr %slot.__catch_3, align 8
  br label %catch_merge9

catch_ok8:
  %t52 = load i64, ptr %slot.__catch_3, align 8
  call void @nova_rc_dec(i64 %t52)
  store i64 %r198, ptr %slot.__catch_3, align 8
  br label %catch_merge9

catch_merge9:
  %r86 = load i64, ptr %slot.__catch_3, align 8
  %t53 = getelementptr inbounds [16 x i8], ptr @.str.11, i64 0, i64 0
  %r90 = ptrtoint ptr %t53 to i64
  %t54 = getelementptr inbounds [1 x i8], ptr @.str.2, i64 0, i64 0
  %r93 = ptrtoint ptr %t54 to i64
  %t55 = call i64 @nova_rt_str_concat(i64 %r90, i64 %r86)
  %t56 = call i64 @nova_rt_str_concat(i64 %t55, i64 %r93)
  call void @nova_rc_dec(i64 %t55)
  call void @nova_rc_dec(i64 %r86)
  %t57 = inttoptr i64 %t56 to ptr
  call i32 @puts(ptr %t57)
  call void @nova_rc_dec(i64 %t56)
  %r97 = load i64, ptr %slot.items, align 8
  br label %__mb3_entry0

__mb3_entry0:
  %t58 = load i64, ptr %slot.__mb3_items, align 8
  call void @nova_rc_dec(i64 %t58)
  call void @nova_rc_inc(i64 %r97)
  store i64 %r97, ptr %slot.__mb3_items, align 8
  store i64 0, ptr %slot.__mb3_idx, align 8
  store i64 1, ptr %slot.__mb3___sc_or_0, align 8
  %t59 = icmp ne i64 0, 0
  br i1 %t59, label %__mb3_sc_or_merge2, label %__mb3_sc_or_right1

__mb3_sc_or_right1:
  %r215 = load i64, ptr %slot.__mb3_idx, align 8
  %r216 = load i64, ptr %slot.__mb3_items, align 8
  %r217 = call i64 @nova_rt_list_len(i64 %r216)
  %t60 = icmp sge i64 %r215, %r217
  %r218 = zext i1 %t60 to i64
  store i64 %r218, ptr %slot.__mb3___sc_or_0, align 8
  br label %__mb3_sc_or_merge2

__mb3_sc_or_merge2:
  %r220 = load i64, ptr %slot.__mb3___sc_or_0, align 8
  %t61 = trunc i64 %r220 to i1
  br i1 %t61, label %__mb3_ifb_then3, label %__mb3_ifb_else4

__mb3_ifb_then3:
  %t62 = getelementptr inbounds [20 x i8], ptr @.str.8, i64 0, i64 0
  %r223 = ptrtoint ptr %t62 to i64
  store i64 1, ptr @__nova_error_flag
  store i64 %r223, ptr @__nova_error_msg
  %t63 = getelementptr inbounds [1 x i8], ptr @.str.2, i64 0, i64 0
  %r225 = ptrtoint ptr %t63 to i64
  %t64 = load i64, ptr %slot.__mb3_ret, align 8
  call void @nova_rc_dec(i64 %t64)
  store i64 %r225, ptr %slot.__mb3_ret, align 8
  br label %__mb3_merge

__mb3_ifb_else4:
  br label %__mb3_ifb_merge5

__mb3_ifb_merge5:
  %r229 = load i64, ptr %slot.__mb3_items, align 8
  %r230 = load i64, ptr %slot.__mb3_idx, align 8
  %t65 = inttoptr i64 %r229 to ptr
  %t66 = load ptr, ptr %t65, align 8, !tbaa !2
  %t67 = getelementptr i64, ptr %t66, i64 %r230
  %r231 = load i64, ptr %t67, align 8, !tbaa !4
  %t68 = load i64, ptr %slot.__mb3_ret, align 8
  call void @nova_rc_dec(i64 %t68)
  call void @nova_rc_inc(i64 %r231)
  store i64 %r231, ptr %slot.__mb3_ret, align 8
  br label %__mb3_merge

__mb3_merge:
  %r232 = load i64, ptr %slot.__mb3_ret, align 8
  %t69 = load i64, ptr @__nova_error_flag
  store i64 0, ptr @__nova_error_flag
  %t70 = icmp ne i64 %t69, 0
  br i1 %t70, label %catch_err10, label %catch_ok11

catch_err10:
  %t71 = load i64, ptr @__nova_error_msg
  store i64 0, ptr @__nova_error_msg
  %t72 = getelementptr inbounds [9 x i8], ptr @.str.12, i64 0, i64 0
  %r106 = ptrtoint ptr %t72 to i64
  %t73 = load i64, ptr %slot.__catch_4, align 8
  call void @nova_rc_dec(i64 %t73)
  store i64 %r106, ptr %slot.__catch_4, align 8
  br label %catch_merge12

catch_ok11:
  %t74 = load i64, ptr %slot.__catch_4, align 8
  call void @nova_rc_dec(i64 %t74)
  store i64 %r232, ptr %slot.__catch_4, align 8
  br label %catch_merge12

catch_merge12:
  %r110 = load i64, ptr %slot.__catch_4, align 8
  %t75 = getelementptr inbounds [12 x i8], ptr @.str.13, i64 0, i64 0
  %r114 = ptrtoint ptr %t75 to i64
  %t76 = getelementptr inbounds [1 x i8], ptr @.str.2, i64 0, i64 0
  %r117 = ptrtoint ptr %t76 to i64
  %t77 = call i64 @nova_rt_str_concat(i64 %r114, i64 %r110)
  %t78 = call i64 @nova_rt_str_concat(i64 %t77, i64 %r117)
  call void @nova_rc_dec(i64 %t77)
  call void @nova_rc_dec(i64 %r110)
  %t79 = inttoptr i64 %t78 to ptr
  call i32 @puts(ptr %t79)
  call void @nova_rc_dec(i64 %t78)
  %t80 = getelementptr inbounds [24 x i8], ptr @.str.14, i64 0, i64 0
  %r120 = ptrtoint ptr %t80 to i64
  %t81 = inttoptr i64 %r120 to ptr
  call i32 @puts(ptr %t81)
  call void @nova_rc_inc(i64 0)
  %t82 = load i64, ptr %slot.items, align 8
  call void @nova_rc_dec(i64 %t82)
  %t83 = load i64, ptr %slot.__mb2_items, align 8
  call void @nova_rc_dec(i64 %t83)
  %t84 = load i64, ptr %slot.__mb2_ret, align 8
  call void @nova_rc_dec(i64 %t84)
  %t85 = load i64, ptr %slot.__catch_3, align 8
  call void @nova_rc_dec(i64 %t85)
  %t86 = load i64, ptr %slot.__mb3_items, align 8
  call void @nova_rc_dec(i64 %t86)
  %t87 = load i64, ptr %slot.__mb3_ret, align 8
  call void @nova_rc_dec(i64 %t87)
  %t88 = load i64, ptr %slot.__catch_4, align 8
  call void @nova_rc_dec(i64 %t88)
  ret i64 0
}

define i64 @nova_main() nounwind {
entry0:
  %r0 = call i64 @nova_user_main()
  ret i64 0
}

define i32 @main(i32 %argc, ptr %argv) nounwind {
entry:
  %argc64 = sext i32 %argc to i64
  %argv64 = ptrtoint ptr %argv to i64
  call void @nova_rt_init_args(i64 %argc64, i64 %argv64)
  call i64 @nova_main()
  call i64 @nova_user_main()
  call void @nova_rt_wait_all()
  call void @nova_rt_cleanup()
  ret i32 0
}

!0 = !{!"NOVA TBAA"}
!1 = !{!"list_data_ptr", !0}
!2 = !{!1, !1, i64 0}
!3 = !{!"list_elem", !0}
!4 = !{!3, !3, i64 0}
!5 = !{!"list_size", !0}
!6 = !{!5, !5, i64 0}
!7 = !{!"list_cap", !0}
!8 = !{!7, !7, i64 0}
!90 = !{!"branch_weights", i32 2000, i32 1}
!91 = distinct !{!91, !92, !93}
!92 = !{!"llvm.loop.unroll.enable"}
!93 = !{!"llvm.loop.vectorize.enable", i1 true}
