; Generated by NOVA compiler
target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"

declare i32 @printf(ptr, ...)
declare i32 @puts(ptr)
declare noalias ptr @malloc(i64) nounwind allocsize(0)
declare noalias ptr @calloc(i64, i64) nounwind
declare ptr @realloc(ptr, i64) nounwind allocsize(1)
declare void @free(ptr) nounwind
declare ptr @nova_rt_struct_alloc(i64) nounwind
declare i64 @llvm.smax.i64(i64, i64) nounwind readnone
; nova runtime — list ops
declare i64 @nova_rt_list_create() nounwind
declare i64 @nova_rt_list_create_filled(i64, i64) nounwind
declare i64 @nova_rt_list_append(i64, i64) nounwind
declare i64 @nova_rt_list_get(i64, i64) nounwind readonly
declare i64 @nova_rt_list_set(i64, i64, i64) nounwind
declare i64 @nova_rt_list_len(i64) nounwind readonly
declare i64 @nova_rt_list_print(i64) nounwind
declare i64 @nova_rt_iter_has_next(i64, i64) nounwind readonly
declare i64 @nova_rt_iter_get(i64, i64) nounwind readonly
declare i64 @nova_rt_list_iter_has_next(i64, i64) nounwind readonly
declare i64 @nova_rt_list_iter_get(i64, i64) nounwind readonly
; nova runtime — string ops
declare i64 @nova_rt_str_concat(i64, i64) nounwind
declare i64 @nova_rt_int_to_str(i64) nounwind
declare i64 @nova_rt_float_to_str(i64) nounwind
declare i64 @nova_rt_bool_to_str(i64) nounwind
declare i64 @nova_rt_str_len(i64) nounwind readonly
declare i64 @nova_rt_len(i64) nounwind readonly
declare i64 @nova_rt_contains(i64, i64) nounwind readonly
declare i64 @nova_rt_slice(i64, i64, i64) nounwind
declare i64 @nova_rt_upper(i64) nounwind
declare i64 @nova_rt_lower(i64) nounwind
declare i64 @nova_rt_trim(i64) nounwind
declare i64 @nova_rt_repeat(i64, i64) nounwind
declare i64 @nova_rt_split(i64, i64) nounwind
declare i64 @nova_rt_replace(i64, i64, i64) nounwind
declare i64 @nova_rt_starts_with(i64, i64) nounwind readonly
declare i64 @nova_rt_ends_with(i64, i64) nounwind readonly
declare i64 @nova_rt_find(i64, i64) nounwind readonly
declare i64 @nova_rt_join(i64, i64) nounwind
declare i64 @nova_rt_chars(i64) nounwind
; nova runtime — list stdlib
declare i64 @nova_rt_list_reverse(i64) nounwind
declare i64 @nova_rt_list_sort(i64) nounwind
declare i64 @nova_rt_list_map(i64, i64) nounwind
declare i64 @nova_rt_list_filter(i64, i64) nounwind
declare i64 @nova_rt_list_concat(i64, i64) nounwind
declare i64 @nova_rt_list_slice(i64, i64, i64) nounwind
declare i64 @nova_rt_list_to_str(i64) nounwind
declare i64 @nova_rt_len_any(i64) nounwind readonly
; nova runtime — type conversions
declare i64 @nova_rt_parse_int(i64) nounwind
declare i64 @nova_rt_parse_float(i64) nounwind
; nova runtime — character ops
declare i64 @nova_rt_ord(i64) nounwind readonly
declare i64 @nova_rt_chr(i64) nounwind
; nova runtime — process control
declare void @nova_rt_exit(i64) noreturn nounwind
declare i64 @nova_rt_system(i64) nounwind
declare i64 @nova_rt_exec(i64) nounwind
declare i32 @strcmp(ptr, ptr) nounwind readonly
; nova runtime — dict ops (hash map, O(1) avg lookup)
declare i64 @nova_rt_dict_create() nounwind
declare i64 @nova_rt_dict_set(i64, i64, i64) nounwind
declare i64 @nova_rt_dict_get(i64, i64) nounwind readonly
declare i64 @nova_rt_dict_get_concat2(i64, i64, i64) nounwind readonly
declare i64 @nova_rt_dict_set_concat2(i64, i64, i64, i64) nounwind
declare i64 @nova_rt_dict_has(i64, i64) nounwind readonly
declare i64 @nova_rt_dict_del(i64, i64) nounwind
declare i64 @nova_rt_dict_len(i64) nounwind readonly
declare i64 @nova_rt_dict_keys(i64) nounwind
declare i64 @nova_rt_dict_values(i64) nounwind
declare i64 @nova_rt_dict_items(i64) nounwind
; nova runtime — IO ops
declare i64 @nova_rt_read_line() nounwind
declare i64 @nova_rt_read_bytes(i64) nounwind
declare i64 @nova_rt_write_raw(i64) nounwind
declare i64 @nova_rt_read_file(i64) nounwind
declare i64 @nova_rt_write_file(i64, i64) nounwind
declare i64 @nova_rt_append_file(i64, i64) nounwind
declare i64 @nova_rt_file_exists(i64) nounwind readonly
; nova runtime — JSON ops
declare i64 @nova_rt_json_parse(i64) nounwind
declare i64 @nova_rt_json_stringify(i64) nounwind
; nova runtime — HTTP ops
declare i64 @nova_rt_http_get(i64) nounwind
declare i64 @nova_rt_http_post(i64, i64, i64) nounwind
; nova runtime — time ops
declare i64 @nova_rt_time_ms() nounwind
declare i64 @nova_rt_clock_ns() nounwind
declare void @nova_rt_sleep_ms(i64) nounwind
declare void @nova_rt_assert(i64, i64) nounwind
; nova runtime — type dispatch
declare i64 @nova_rt_any_to_str(i64) nounwind
declare i64 @nova_rt_str_concat_safe(i64, i64) nounwind
declare i64 @nova_rt_str_char_at(i64, i64) nounwind
declare void @nova_rt_init() nounwind
declare void @nova_rt_init_args(i64, i64) nounwind
; nova runtime — system ops
declare i64 @nova_rt_args() nounwind
declare i64 @nova_rt_env(i64) nounwind
declare i64 @nova_rt_random_int(i64, i64) nounwind
declare i64 @nova_rt_random_float() nounwind
declare i64 @nova_rt_shell(i64) nounwind
declare i64 @nova_rt_path_join(i64, i64) nounwind
declare i64 @nova_rt_path_parent(i64) nounwind
declare i64 @nova_rt_path_name(i64) nounwind
declare i64 @nova_rt_path_ext(i64) nounwind
declare i64 @nova_rt_mkdir(i64) nounwind
declare i64 @nova_rt_mkdir_p(i64) nounwind
declare i64 @nova_rt_path_exists(i64) nounwind
; nova runtime — regex ops
declare i64 @nova_rt_regex_match(i64, i64) nounwind readonly
declare i64 @nova_rt_regex_find(i64, i64) nounwind
declare i64 @nova_rt_regex_replace(i64, i64, i64) nounwind
declare i64 @nova_rt_regex_split(i64, i64) nounwind
; nova runtime — network ops
declare i64 @nova_rt_tcp_connect(i64, i64) nounwind
declare i64 @nova_rt_tcp_listen(i64) nounwind
declare i64 @nova_rt_tcp_accept(i64) nounwind
declare i64 @nova_rt_tcp_send(i64, i64) nounwind
declare i64 @nova_rt_tcp_recv(i64) nounwind
declare void @nova_rt_tcp_close(i64) nounwind
declare i64 @nova_rt_udp_bind(i64) nounwind
declare i64 @nova_rt_udp_send(i64, i64, i64, i64) nounwind
declare i64 @nova_rt_udp_recv(i64) nounwind
; nova runtime — HTTP server
declare i64 @nova_rt_http_listen(i64) nounwind
declare i64 @nova_rt_http_accept(i64) nounwind
declare void @nova_rt_http_respond(i64, i64, i64) nounwind
; nova runtime — byte arrays
declare i64 @nova_rt_bytes_create(i64) nounwind
declare i64 @nova_rt_bytes_get(i64, i64) nounwind
declare void @nova_rt_bytes_set(i64, i64, i64) nounwind
declare i64 @nova_rt_bytes_len(i64) nounwind
declare i64 @nova_rt_bytes_slice(i64, i64, i64) nounwind
declare i64 @nova_rt_bytes_to_str(i64) nounwind
declare i64 @nova_rt_str_to_bytes(i64) nounwind
; nova runtime — channel/spawn ops
declare i64 @nova_rt_channel_create() nounwind
declare i64 @nova_rt_channel_send(i64, i64) nounwind
declare i64 @nova_rt_channel_recv(i64) nounwind
declare i64 @nova_rt_channel_close(i64) nounwind
declare i64 @nova_rt_channel_select(i64, i64) nounwind
declare i64 @nova_rt_channel_recv_timeout(i64, i64) nounwind
declare i64 @nova_rt_spawn(i64, i64) nounwind
declare i64 @nova_rt_monitor(i64) nounwind
declare void @nova_rt_wait_all() nounwind
; nova runtime — math (trig/log via C runtime for non-intrinsic functions)
declare i64 @nova_rt_tan(i64) nounwind
declare i64 @nova_rt_asin(i64) nounwind
declare i64 @nova_rt_acos(i64) nounwind
declare i64 @nova_rt_atan(i64) nounwind
declare i64 @nova_rt_atan2(i64, i64) nounwind
declare i64 @nova_rt_fmod(i64, i64) nounwind
declare i64 @nova_rt_int_pow(i64, i64) nounwind
; nova runtime — memory management
declare void @nova_rt_cleanup() nounwind
declare void @nova_rt_track_raw(ptr) nounwind
declare i64 @nova_rt_alloc_count() nounwind readonly
declare i64 @nova_rt_live_count() nounwind readonly
; nova runtime — reference counting
declare void @nova_rc_inc(i64) nounwind
declare void @nova_rc_dec(i64) nounwind
; nova error state — thread-local flag (safe for spawn/concurrent programs)
@__nova_error_flag = thread_local global i64 0
@__nova_error_msg = thread_local global i64 0

@.str.0 = private unnamed_addr constant [1 x i8] c"\00"
@.str.1 = private unnamed_addr constant [10 x i8] c"FizzBuzz \00"
@.str.2 = private unnamed_addr constant [6 x i8] c"Fizz \00"
@.str.3 = private unnamed_addr constant [6 x i8] c"Buzz \00"
@.str.4 = private unnamed_addr constant [2 x i8] c" \00"
@.str.5 = private unnamed_addr constant [6 x i8] c"%lld\0A\00"
@.str.6 = private unnamed_addr constant [4 x i8] c"%f\0A\00"
@.str.7 = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.str.8 = private unnamed_addr constant [5 x i8] c"true\00"
@.str.9 = private unnamed_addr constant [6 x i8] c"false\00"

define i64 @fizzbuzz(i64 %p0) nounwind {
entry0:
  %slot.n = alloca i64, align 8
  %slot.i = alloca i64, align 8
  %slot.result = alloca i64, align 8
  %slot.__ifb_2 = alloca i64, align 8
  store i64 0, ptr %slot.result, align 8
  store i64 %p0, ptr %slot.n, align 8
  store i64 1, ptr %slot.i, align 8
  %t0 = getelementptr inbounds [1 x i8], ptr @.str.0, i64 0, i64 0
  %r9 = ptrtoint ptr %t0 to i64
  %t1 = load i64, ptr %slot.result, align 8
  call void @nova_rc_dec(i64 %t1)
  store i64 %r9, ptr %slot.result, align 8
  %r78 = load i64, ptr %slot.n, align 8
  br label %while_header1

while_header1:
  %r13 = load i64, ptr %slot.i, align 8
  %t2 = icmp sle i64 %r13, %r78
  br i1 %t2, label %while_body2, label %while_exit3, !prof !90

while_body2:
  %r17 = load i64, ptr %slot.i, align 8
  %r19 = srem i64 %r17, 15
  %t3 = icmp eq i64 %r19, 0
  br i1 %t3, label %ifb_then4, label %ifb_else5

while_exit3:
  %r77 = load i64, ptr %slot.result, align 8
  call void @nova_rc_inc(i64 %r77)
  %t4 = load i64, ptr %slot.result, align 8
  call void @nova_rc_dec(i64 %t4)
  ret i64 %r77

ifb_then4:
  %r24 = load i64, ptr %slot.result, align 8
  %t5 = getelementptr inbounds [10 x i8], ptr @.str.1, i64 0, i64 0
  %r25 = ptrtoint ptr %t5 to i64
  %t6 = call i64 @nova_rt_str_concat(i64 %r24, i64 %r25)
  %t7 = load i64, ptr %slot.result, align 8
  call void @nova_rc_dec(i64 %t7)
  store i64 %t6, ptr %slot.result, align 8
  br label %ifb_merge6

ifb_else5:
  %r30 = load i64, ptr %slot.i, align 8
  %r32 = srem i64 %r30, 3
  %t8 = icmp eq i64 %r32, 0
  br i1 %t8, label %ifb_then7, label %ifb_else8

ifb_merge6:
  %r71 = load i64, ptr %slot.i, align 8
  %r73 = add i64 %r71, 1
  store i64 %r73, ptr %slot.i, align 8
  br label %while_header1, !llvm.loop !91

ifb_then7:
  %r37 = load i64, ptr %slot.result, align 8
  %t9 = getelementptr inbounds [6 x i8], ptr @.str.2, i64 0, i64 0
  %r38 = ptrtoint ptr %t9 to i64
  %t10 = call i64 @nova_rt_str_concat(i64 %r37, i64 %r38)
  %t11 = load i64, ptr %slot.result, align 8
  call void @nova_rc_dec(i64 %t11)
  store i64 %t10, ptr %slot.result, align 8
  br label %ifb_merge9

ifb_else8:
  %r43 = load i64, ptr %slot.i, align 8
  %r45 = srem i64 %r43, 5
  %t12 = icmp eq i64 %r45, 0
  br i1 %t12, label %ifb_then10, label %ifb_else11

ifb_merge9:
  br label %ifb_merge6, !llvm.loop !91

ifb_then10:
  %r50 = load i64, ptr %slot.result, align 8
  %t13 = getelementptr inbounds [6 x i8], ptr @.str.3, i64 0, i64 0
  %r51 = ptrtoint ptr %t13 to i64
  %t14 = call i64 @nova_rt_str_concat(i64 %r50, i64 %r51)
  %t15 = load i64, ptr %slot.result, align 8
  call void @nova_rc_dec(i64 %t15)
  store i64 %t14, ptr %slot.result, align 8
  store i64 0, ptr %slot.__ifb_2, align 8
  br label %ifb_merge12

ifb_else11:
  %r57 = load i64, ptr %slot.result, align 8
  %r58 = load i64, ptr %slot.i, align 8
  %r59 = call i64 @nova_rt_int_to_str(i64 %r58)
  %t16 = call i64 @nova_rt_str_concat(i64 %r57, i64 %r59)
  call void @nova_rc_dec(i64 %r59)
  %t17 = getelementptr inbounds [2 x i8], ptr @.str.4, i64 0, i64 0
  %r61 = ptrtoint ptr %t17 to i64
  %t18 = call i64 @nova_rt_str_concat(i64 %t16, i64 %r61)
  call void @nova_rc_dec(i64 %t16)
  %t19 = load i64, ptr %slot.result, align 8
  call void @nova_rc_dec(i64 %t19)
  store i64 %t18, ptr %slot.result, align 8
  store i64 0, ptr %slot.__ifb_2, align 8
  br label %ifb_merge12

ifb_merge12:
  %r66 = load i64, ptr %slot.__ifb_2, align 8
  br label %ifb_merge9, !llvm.loop !91
}

define i64 @nova_main() nounwind {
entry0:
  %r2 = call i64 @fizzbuzz(i64 15)
  %t0 = inttoptr i64 %r2 to ptr
  call i32 @puts(ptr %t0)
  ret i64 0
}

define i32 @main(i32 %argc, ptr %argv) nounwind {
entry:
  %argc64 = sext i32 %argc to i64
  %argv64 = ptrtoint ptr %argv to i64
  call void @nova_rt_init_args(i64 %argc64, i64 %argv64)
  call i64 @nova_main()
  call void @nova_rt_wait_all()
  call void @nova_rt_cleanup()
  ret i32 0
}

!0 = !{!"NOVA TBAA"}
!1 = !{!"list_data_ptr", !0}
!2 = !{!1, !1, i64 0}
!3 = !{!"list_elem", !0}
!4 = !{!3, !3, i64 0}
!5 = !{!"list_size", !0}
!6 = !{!5, !5, i64 0}
!7 = !{!"list_cap", !0}
!8 = !{!7, !7, i64 0}
!90 = !{!"branch_weights", i32 2000, i32 1}
!91 = distinct !{!91, !92, !93}
!92 = !{!"llvm.loop.unroll.enable"}
!93 = !{!"llvm.loop.vectorize.enable", i1 true}
