; Generated by NOVA compiler
target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"

declare i32 @printf(ptr, ...)
declare i32 @puts(ptr)
declare noalias ptr @malloc(i64) nounwind allocsize(0)
declare noalias ptr @calloc(i64, i64) nounwind
declare ptr @realloc(ptr, i64) nounwind allocsize(1)
declare void @free(ptr) nounwind
declare i64 @llvm.smax.i64(i64, i64) nounwind readnone
; nova runtime — list ops
declare i64 @nova_rt_list_create() nounwind
declare i64 @nova_rt_list_create_filled(i64, i64) nounwind
declare i64 @nova_rt_list_append(i64, i64) nounwind
declare i64 @nova_rt_list_get(i64, i64) nounwind readonly
declare i64 @nova_rt_list_set(i64, i64, i64) nounwind
declare i64 @nova_rt_list_len(i64) nounwind readonly
declare i64 @nova_rt_list_print(i64) nounwind
declare i64 @nova_rt_iter_has_next(i64, i64) nounwind readonly
declare i64 @nova_rt_iter_get(i64, i64) nounwind readonly
declare i64 @nova_rt_list_iter_has_next(i64, i64) nounwind readonly
declare i64 @nova_rt_list_iter_get(i64, i64) nounwind readonly
; nova runtime — string ops
declare i64 @nova_rt_str_concat(i64, i64) nounwind
declare i64 @nova_rt_int_to_str(i64) nounwind
declare i64 @nova_rt_float_to_str(i64) nounwind
declare i64 @nova_rt_bool_to_str(i64) nounwind
declare i64 @nova_rt_str_len(i64) nounwind readonly
declare i64 @nova_rt_len(i64) nounwind readonly
declare i64 @nova_rt_contains(i64, i64) nounwind readonly
declare i64 @nova_rt_slice(i64, i64, i64) nounwind
declare i64 @nova_rt_upper(i64) nounwind
declare i64 @nova_rt_lower(i64) nounwind
declare i64 @nova_rt_trim(i64) nounwind
declare i64 @nova_rt_repeat(i64, i64) nounwind
declare i64 @nova_rt_split(i64, i64) nounwind
declare i64 @nova_rt_replace(i64, i64, i64) nounwind
declare i64 @nova_rt_starts_with(i64, i64) nounwind readonly
declare i64 @nova_rt_ends_with(i64, i64) nounwind readonly
declare i64 @nova_rt_find(i64, i64) nounwind readonly
declare i64 @nova_rt_join(i64, i64) nounwind
declare i64 @nova_rt_chars(i64) nounwind
; nova runtime — list stdlib
declare i64 @nova_rt_list_reverse(i64) nounwind
declare i64 @nova_rt_list_sort(i64) nounwind
declare i64 @nova_rt_list_map(i64, i64) nounwind
declare i64 @nova_rt_list_filter(i64, i64) nounwind
declare i64 @nova_rt_list_concat(i64, i64) nounwind
declare i64 @nova_rt_list_slice(i64, i64, i64) nounwind
declare i64 @nova_rt_list_to_str(i64) nounwind
declare i64 @nova_rt_len_any(i64) nounwind readonly
; nova runtime — type conversions
declare i64 @nova_rt_parse_int(i64) nounwind
declare i64 @nova_rt_parse_float(i64) nounwind
; nova runtime — character ops
declare i64 @nova_rt_ord(i64) nounwind readonly
declare i64 @nova_rt_chr(i64) nounwind
; nova runtime — process control
declare void @nova_rt_exit(i64) noreturn nounwind
declare i32 @strcmp(ptr, ptr) nounwind readonly
; nova runtime — dict ops (hash map, O(1) avg lookup)
declare i64 @nova_rt_dict_create() nounwind
declare i64 @nova_rt_dict_set(i64, i64, i64) nounwind
declare i64 @nova_rt_dict_get(i64, i64) nounwind readonly
declare i64 @nova_rt_dict_get_concat2(i64, i64, i64) nounwind readonly
declare i64 @nova_rt_dict_set_concat2(i64, i64, i64, i64) nounwind
declare i64 @nova_rt_dict_has(i64, i64) nounwind readonly
declare i64 @nova_rt_dict_del(i64, i64) nounwind
declare i64 @nova_rt_dict_len(i64) nounwind readonly
declare i64 @nova_rt_dict_keys(i64) nounwind
declare i64 @nova_rt_dict_values(i64) nounwind
declare i64 @nova_rt_dict_items(i64) nounwind
; nova runtime — IO ops
declare i64 @nova_rt_read_line() nounwind
declare i64 @nova_rt_read_file(i64) nounwind
declare i64 @nova_rt_write_file(i64, i64) nounwind
declare i64 @nova_rt_append_file(i64, i64) nounwind
declare i64 @nova_rt_file_exists(i64) nounwind readonly
; nova runtime — JSON ops
declare i64 @nova_rt_json_parse(i64) nounwind
declare i64 @nova_rt_json_stringify(i64) nounwind
; nova runtime — HTTP ops
declare i64 @nova_rt_http_get(i64) nounwind
declare i64 @nova_rt_http_post(i64, i64, i64) nounwind
; nova runtime — time ops
declare i64 @nova_rt_time_ms() nounwind
declare i64 @nova_rt_clock_ns() nounwind
declare void @nova_rt_sleep_ms(i64) nounwind
declare void @nova_rt_assert(i64, i64) nounwind
; nova runtime — type dispatch
declare i64 @nova_rt_any_to_str(i64) nounwind
declare i64 @nova_rt_str_concat_safe(i64, i64) nounwind
declare i64 @nova_rt_str_char_at(i64, i64) nounwind
declare void @nova_rt_init() nounwind
declare void @nova_rt_init_args(i64, i64) nounwind
; nova runtime — system ops
declare i64 @nova_rt_args() nounwind
declare i64 @nova_rt_env(i64) nounwind
declare i64 @nova_rt_random_int(i64, i64) nounwind
declare i64 @nova_rt_random_float() nounwind
declare i64 @nova_rt_shell(i64) nounwind
declare i64 @nova_rt_path_join(i64, i64) nounwind
declare i64 @nova_rt_path_parent(i64) nounwind
declare i64 @nova_rt_path_name(i64) nounwind
declare i64 @nova_rt_path_ext(i64) nounwind
; nova runtime — regex ops
declare i64 @nova_rt_regex_match(i64, i64) nounwind readonly
declare i64 @nova_rt_regex_find(i64, i64) nounwind
declare i64 @nova_rt_regex_replace(i64, i64, i64) nounwind
declare i64 @nova_rt_regex_split(i64, i64) nounwind
; nova runtime — network ops
declare i64 @nova_rt_tcp_connect(i64, i64) nounwind
declare i64 @nova_rt_tcp_listen(i64) nounwind
declare i64 @nova_rt_tcp_accept(i64) nounwind
declare i64 @nova_rt_tcp_send(i64, i64) nounwind
declare i64 @nova_rt_tcp_recv(i64) nounwind
declare void @nova_rt_tcp_close(i64) nounwind
declare i64 @nova_rt_udp_bind(i64) nounwind
declare i64 @nova_rt_udp_send(i64, i64, i64, i64) nounwind
declare i64 @nova_rt_udp_recv(i64) nounwind
; nova runtime — HTTP server
declare i64 @nova_rt_http_listen(i64) nounwind
declare i64 @nova_rt_http_accept(i64) nounwind
declare void @nova_rt_http_respond(i64, i64, i64) nounwind
; nova runtime — byte arrays
declare i64 @nova_rt_bytes_create(i64) nounwind
declare i64 @nova_rt_bytes_get(i64, i64) nounwind
declare void @nova_rt_bytes_set(i64, i64, i64) nounwind
declare i64 @nova_rt_bytes_len(i64) nounwind
declare i64 @nova_rt_bytes_slice(i64, i64, i64) nounwind
declare i64 @nova_rt_bytes_to_str(i64) nounwind
declare i64 @nova_rt_str_to_bytes(i64) nounwind
; nova runtime — channel/spawn ops
declare i64 @nova_rt_channel_create() nounwind
declare i64 @nova_rt_channel_send(i64, i64) nounwind
declare i64 @nova_rt_channel_recv(i64) nounwind
declare i64 @nova_rt_channel_close(i64) nounwind
declare i64 @nova_rt_channel_select(i64, i64) nounwind
declare i64 @nova_rt_channel_recv_timeout(i64, i64) nounwind
declare i64 @nova_rt_spawn(i64, i64) nounwind
declare i64 @nova_rt_monitor(i64) nounwind
declare void @nova_rt_wait_all() nounwind
; nova runtime — math (trig/log via C runtime for non-intrinsic functions)
declare i64 @nova_rt_tan(i64) nounwind
declare i64 @nova_rt_asin(i64) nounwind
declare i64 @nova_rt_acos(i64) nounwind
declare i64 @nova_rt_atan(i64) nounwind
declare i64 @nova_rt_atan2(i64, i64) nounwind
declare i64 @nova_rt_fmod(i64, i64) nounwind
declare i64 @nova_rt_int_pow(i64, i64) nounwind
; nova runtime — memory management
declare void @nova_rt_cleanup() nounwind
declare void @nova_rt_track_raw(ptr) nounwind
declare i64 @nova_rt_alloc_count() nounwind readonly
declare i64 @nova_rt_live_count() nounwind readonly
; nova runtime — reference counting
declare void @nova_rc_inc(i64) nounwind
declare void @nova_rc_dec(i64) nounwind
; nova error state — thread-local flag (safe for spawn/concurrent programs)
@__nova_error_flag = thread_local global i64 0
@__nova_error_msg = thread_local global i64 0

@.str.0 = private unnamed_addr constant [14 x i8] c"Hello, World!\00"
@.str.1 = private unnamed_addr constant [2 x i8] c"H\00"
@.str.2 = private unnamed_addr constant [11 x i8] c"first char\00"
@.str.3 = private unnamed_addr constant [2 x i8] c"!\00"
@.str.4 = private unnamed_addr constant [10 x i8] c"last char\00"
@.str.5 = private unnamed_addr constant [7 x i8] c"length\00"
@.str.6 = private unnamed_addr constant [14 x i8] c"HELLO, WORLD!\00"
@.str.7 = private unnamed_addr constant [6 x i8] c"upper\00"
@.str.8 = private unnamed_addr constant [14 x i8] c"hello, world!\00"
@.str.9 = private unnamed_addr constant [6 x i8] c"lower\00"
@.str.10 = private unnamed_addr constant [7 x i8] c"  hi  \00"
@.str.11 = private unnamed_addr constant [3 x i8] c"hi\00"
@.str.12 = private unnamed_addr constant [5 x i8] c"trim\00"
@.str.13 = private unnamed_addr constant [3 x i8] c"ab\00"
@.str.14 = private unnamed_addr constant [7 x i8] c"ababab\00"
@.str.15 = private unnamed_addr constant [7 x i8] c"repeat\00"
@.str.16 = private unnamed_addr constant [3 x i8] c"  \00"
@.str.17 = private unnamed_addr constant [9 x i8] c"        \00"
@.str.18 = private unnamed_addr constant [14 x i8] c"indent repeat\00"
@.str.19 = private unnamed_addr constant [23 x i8] c"string iteration count\00"
@.str.20 = private unnamed_addr constant [1 x i8] c"\00"
@.str.21 = private unnamed_addr constant [5 x i8] c"nova\00"
@.str.22 = private unnamed_addr constant [5 x i8] c"avon\00"
@.str.23 = private unnamed_addr constant [22 x i8] c"reverse via iteration\00"
@.str.24 = private unnamed_addr constant [6 x i8] c"Hello\00"
@.str.25 = private unnamed_addr constant [6 x i8] c"slice\00"
@.str.26 = private unnamed_addr constant [12 x i8] c"starts_with\00"
@.str.27 = private unnamed_addr constant [7 x i8] c"World!\00"
@.str.28 = private unnamed_addr constant [10 x i8] c"ends_with\00"
@.str.29 = private unnamed_addr constant [6 x i8] c"World\00"
@.str.30 = private unnamed_addr constant [9 x i8] c"contains\00"
@.str.31 = private unnamed_addr constant [5 x i8] c"find\00"
@.str.32 = private unnamed_addr constant [5 x i8] c"NOVA\00"
@.str.33 = private unnamed_addr constant [13 x i8] c"Hello, NOVA!\00"
@.str.34 = private unnamed_addr constant [8 x i8] c"replace\00"
@.str.35 = private unnamed_addr constant [6 x i8] c"a,b,c\00"
@.str.36 = private unnamed_addr constant [2 x i8] c",\00"
@.str.37 = private unnamed_addr constant [13 x i8] c"split length\00"
@.str.38 = private unnamed_addr constant [2 x i8] c"a\00"
@.str.39 = private unnamed_addr constant [9 x i8] c"split[0]\00"
@.str.40 = private unnamed_addr constant [2 x i8] c"c\00"
@.str.41 = private unnamed_addr constant [9 x i8] c"split[2]\00"
@.str.42 = private unnamed_addr constant [2 x i8] c"-\00"
@.str.43 = private unnamed_addr constant [6 x i8] c"a-b-c\00"
@.str.44 = private unnamed_addr constant [5 x i8] c"join\00"
@.str.45 = private unnamed_addr constant [30 x i8] c"All string operations passed!\00"
@.str.46 = private unnamed_addr constant [6 x i8] c"%lld\0A\00"
@.str.47 = private unnamed_addr constant [4 x i8] c"%f\0A\00"
@.str.48 = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.str.49 = private unnamed_addr constant [5 x i8] c"true\00"
@.str.50 = private unnamed_addr constant [6 x i8] c"false\00"

define i64 @nova_main() nounwind {
entry0:
  %slot.s = alloca i64, align 8
  %slot.count = alloca i64, align 8
  %slot.__for_iter_7 = alloca i64, align 8
  %slot.__for_idx_7 = alloca i64, align 8
  %slot.__for_len_7 = alloca i64, align 8
  %slot.reversed = alloca i64, align 8
  %slot.__for_iter_9 = alloca i64, align 8
  %slot.__for_idx_9 = alloca i64, align 8
  %slot.__for_len_9 = alloca i64, align 8
  store i64 0, ptr %slot.s, align 8
  store i64 0, ptr %slot.__for_iter_7, align 8
  store i64 0, ptr %slot.reversed, align 8
  store i64 0, ptr %slot.__for_iter_9, align 8
  %t0 = getelementptr inbounds [14 x i8], ptr @.str.0, i64 0, i64 0
  %r1 = ptrtoint ptr %t0 to i64
  %t1 = load i64, ptr %slot.s, align 8
  call void @nova_rc_dec(i64 %t1)
  store i64 %r1, ptr %slot.s, align 8
  %r7 = call i64 @nova_rt_str_char_at(i64 %r1, i64 0)
  %t2 = getelementptr inbounds [2 x i8], ptr @.str.1, i64 0, i64 0
  %r8 = ptrtoint ptr %t2 to i64
  %t3 = inttoptr i64 %r7 to ptr
  %t4 = inttoptr i64 %r8 to ptr
  %t5 = call i32 @strcmp(ptr %t3, ptr %t4)
  %t6 = icmp eq i32 %t5, 0
  %r9 = zext i1 %t6 to i64
  %t7 = getelementptr inbounds [11 x i8], ptr @.str.2, i64 0, i64 0
  %r10 = ptrtoint ptr %t7 to i64
  call void @nova_rt_assert(i64 %r9, i64 %r10)
  %r13 = call i64 @nova_rt_len(i64 %r1)
  %r15 = add i64 %r13, -1
  %r16 = call i64 @nova_rt_str_char_at(i64 %r1, i64 %r15)
  %t8 = getelementptr inbounds [2 x i8], ptr @.str.3, i64 0, i64 0
  %r17 = ptrtoint ptr %t8 to i64
  %t9 = inttoptr i64 %r16 to ptr
  %t10 = inttoptr i64 %r17 to ptr
  %t11 = call i32 @strcmp(ptr %t9, ptr %t10)
  %t12 = icmp eq i32 %t11, 0
  %r18 = zext i1 %t12 to i64
  %t13 = getelementptr inbounds [10 x i8], ptr @.str.4, i64 0, i64 0
  %r19 = ptrtoint ptr %t13 to i64
  call void @nova_rt_assert(i64 %r18, i64 %r19)
  %r22 = call i64 @nova_rt_len(i64 %r1)
  %t14 = icmp eq i64 %r22, 13
  %r24 = zext i1 %t14 to i64
  %t15 = getelementptr inbounds [7 x i8], ptr @.str.5, i64 0, i64 0
  %r25 = ptrtoint ptr %t15 to i64
  call void @nova_rt_assert(i64 %r24, i64 %r25)
  %r29 = call i64 @nova_rt_upper(i64 %r1)
  %t16 = getelementptr inbounds [14 x i8], ptr @.str.6, i64 0, i64 0
  %r34 = ptrtoint ptr %t16 to i64
  %t17 = inttoptr i64 %r29 to ptr
  %t18 = inttoptr i64 %r34 to ptr
  %t19 = call i32 @strcmp(ptr %t17, ptr %t18)
  %t20 = icmp eq i32 %t19, 0
  %r35 = zext i1 %t20 to i64
  call void @nova_rc_dec(i64 %r29)
  %t21 = getelementptr inbounds [6 x i8], ptr @.str.7, i64 0, i64 0
  %r36 = ptrtoint ptr %t21 to i64
  call void @nova_rt_assert(i64 %r35, i64 %r36)
  %r40 = call i64 @nova_rt_lower(i64 %r1)
  %t22 = getelementptr inbounds [14 x i8], ptr @.str.8, i64 0, i64 0
  %r45 = ptrtoint ptr %t22 to i64
  %t23 = inttoptr i64 %r40 to ptr
  %t24 = inttoptr i64 %r45 to ptr
  %t25 = call i32 @strcmp(ptr %t23, ptr %t24)
  %t26 = icmp eq i32 %t25, 0
  %r46 = zext i1 %t26 to i64
  call void @nova_rc_dec(i64 %r40)
  %t27 = getelementptr inbounds [6 x i8], ptr @.str.9, i64 0, i64 0
  %r47 = ptrtoint ptr %t27 to i64
  call void @nova_rt_assert(i64 %r46, i64 %r47)
  %t28 = getelementptr inbounds [7 x i8], ptr @.str.10, i64 0, i64 0
  %r50 = ptrtoint ptr %t28 to i64
  %r51 = call i64 @nova_rt_trim(i64 %r50)
  %t29 = getelementptr inbounds [3 x i8], ptr @.str.11, i64 0, i64 0
  %r56 = ptrtoint ptr %t29 to i64
  %t30 = inttoptr i64 %r51 to ptr
  %t31 = inttoptr i64 %r56 to ptr
  %t32 = call i32 @strcmp(ptr %t30, ptr %t31)
  %t33 = icmp eq i32 %t32, 0
  %r57 = zext i1 %t33 to i64
  call void @nova_rc_dec(i64 %r51)
  %t34 = getelementptr inbounds [5 x i8], ptr @.str.12, i64 0, i64 0
  %r58 = ptrtoint ptr %t34 to i64
  call void @nova_rt_assert(i64 %r57, i64 %r58)
  %t35 = getelementptr inbounds [3 x i8], ptr @.str.13, i64 0, i64 0
  %r61 = ptrtoint ptr %t35 to i64
  %r63 = call i64 @nova_rt_repeat(i64 %r61, i64 3)
  %t36 = getelementptr inbounds [7 x i8], ptr @.str.14, i64 0, i64 0
  %r68 = ptrtoint ptr %t36 to i64
  %t37 = inttoptr i64 %r63 to ptr
  %t38 = inttoptr i64 %r68 to ptr
  %t39 = call i32 @strcmp(ptr %t37, ptr %t38)
  %t40 = icmp eq i32 %t39, 0
  %r69 = zext i1 %t40 to i64
  %t41 = getelementptr inbounds [7 x i8], ptr @.str.15, i64 0, i64 0
  %r70 = ptrtoint ptr %t41 to i64
  call void @nova_rt_assert(i64 %r69, i64 %r70)
  %t42 = getelementptr inbounds [3 x i8], ptr @.str.16, i64 0, i64 0
  %r73 = ptrtoint ptr %t42 to i64
  %r75 = call i64 @nova_rt_repeat(i64 %r73, i64 4)
  %t43 = getelementptr inbounds [9 x i8], ptr @.str.17, i64 0, i64 0
  %r80 = ptrtoint ptr %t43 to i64
  %t44 = inttoptr i64 %r75 to ptr
  %t45 = inttoptr i64 %r80 to ptr
  %t46 = call i32 @strcmp(ptr %t44, ptr %t45)
  %t47 = icmp eq i32 %t46, 0
  %r81 = zext i1 %t47 to i64
  %t48 = getelementptr inbounds [14 x i8], ptr @.str.18, i64 0, i64 0
  %r82 = ptrtoint ptr %t48 to i64
  call void @nova_rt_assert(i64 %r81, i64 %r82)
  store i64 0, ptr %slot.count, align 8
  %t49 = load i64, ptr %slot.__for_iter_7, align 8
  call void @nova_rc_dec(i64 %t49)
  store i64 %r1, ptr %slot.__for_iter_7, align 8
  store i64 0, ptr %slot.__for_idx_7, align 8
  %r96 = call i64 @nova_rt_len(i64 %r1)
  store i64 %r96, ptr %slot.__for_len_7, align 8
  %r254 = load i64, ptr %slot.__for_len_7, align 8
  %r255 = load i64, ptr %slot.__for_iter_7, align 8
  br label %for_header1

for_header1:
  %r99 = load i64, ptr %slot.__for_idx_7, align 8
  %t50 = icmp slt i64 %r99, %r254
  br i1 %t50, label %for_body2, label %for_exit3, !prof !90

for_body2:
  %r103 = load i64, ptr %slot.__for_idx_7, align 8
  %r104 = call i64 @nova_rt_str_char_at(i64 %r255, i64 %r103)
  %r108 = load i64, ptr %slot.count, align 8
  %r110 = add i64 %r108, 1
  store i64 %r110, ptr %slot.count, align 8
  %r113 = add i64 %r103, 1
  store i64 %r113, ptr %slot.__for_idx_7, align 8
  br label %for_header1, !llvm.loop !91

for_exit3:
  %r117 = load i64, ptr %slot.count, align 8
  %t51 = icmp eq i64 %r117, 13
  %r119 = zext i1 %t51 to i64
  %t52 = getelementptr inbounds [23 x i8], ptr @.str.19, i64 0, i64 0
  %r120 = ptrtoint ptr %t52 to i64
  call void @nova_rt_assert(i64 %r119, i64 %r120)
  %t53 = getelementptr inbounds [1 x i8], ptr @.str.20, i64 0, i64 0
  %r123 = ptrtoint ptr %t53 to i64
  %t54 = load i64, ptr %slot.reversed, align 8
  call void @nova_rc_dec(i64 %t54)
  store i64 %r123, ptr %slot.reversed, align 8
  %t55 = getelementptr inbounds [5 x i8], ptr @.str.21, i64 0, i64 0
  %r127 = ptrtoint ptr %t55 to i64
  %t56 = load i64, ptr %slot.__for_iter_9, align 8
  call void @nova_rc_dec(i64 %t56)
  store i64 %r127, ptr %slot.__for_iter_9, align 8
  store i64 0, ptr %slot.__for_idx_9, align 8
  %r134 = call i64 @nova_rt_len(i64 %r127)
  store i64 %r134, ptr %slot.__for_len_9, align 8
  %r256 = load i64, ptr %slot.__for_len_9, align 8
  %r257 = load i64, ptr %slot.__for_iter_9, align 8
  br label %for_header4

for_header4:
  %r137 = load i64, ptr %slot.__for_idx_9, align 8
  %t57 = icmp slt i64 %r137, %r256
  br i1 %t57, label %for_body5, label %for_exit6, !prof !90

for_body5:
  %r141 = load i64, ptr %slot.__for_idx_9, align 8
  %r142 = call i64 @nova_rt_str_char_at(i64 %r257, i64 %r141)
  %r146 = load i64, ptr %slot.reversed, align 8
  %t58 = call i64 @nova_rt_str_concat(i64 %r142, i64 %r146)
  %t59 = load i64, ptr %slot.reversed, align 8
  call void @nova_rc_dec(i64 %t59)
  store i64 %t58, ptr %slot.reversed, align 8
  %r150 = add i64 %r141, 1
  store i64 %r150, ptr %slot.__for_idx_9, align 8
  br label %for_header4, !llvm.loop !91

for_exit6:
  %r154 = load i64, ptr %slot.reversed, align 8
  %t60 = getelementptr inbounds [5 x i8], ptr @.str.22, i64 0, i64 0
  %r155 = ptrtoint ptr %t60 to i64
  %t61 = inttoptr i64 %r154 to ptr
  %t62 = inttoptr i64 %r155 to ptr
  %t63 = call i32 @strcmp(ptr %t61, ptr %t62)
  %t64 = icmp eq i32 %t63, 0
  %r156 = zext i1 %t64 to i64
  %t65 = getelementptr inbounds [22 x i8], ptr @.str.23, i64 0, i64 0
  %r157 = ptrtoint ptr %t65 to i64
  call void @nova_rt_assert(i64 %r156, i64 %r157)
  %r160 = load i64, ptr %slot.s, align 8
  %r163 = call i64 @nova_rt_slice(i64 %r160, i64 0, i64 5)
  %t66 = getelementptr inbounds [6 x i8], ptr @.str.24, i64 0, i64 0
  %r168 = ptrtoint ptr %t66 to i64
  %t67 = inttoptr i64 %r163 to ptr
  %t68 = inttoptr i64 %r168 to ptr
  %t69 = call i32 @strcmp(ptr %t67, ptr %t68)
  %t70 = icmp eq i32 %t69, 0
  %r169 = zext i1 %t70 to i64
  call void @nova_rc_dec(i64 %r163)
  %t71 = getelementptr inbounds [6 x i8], ptr @.str.25, i64 0, i64 0
  %r170 = ptrtoint ptr %t71 to i64
  call void @nova_rt_assert(i64 %r169, i64 %r170)
  %r172 = load i64, ptr %slot.s, align 8
  %t72 = getelementptr inbounds [6 x i8], ptr @.str.24, i64 0, i64 0
  %r173 = ptrtoint ptr %t72 to i64
  %r174 = call i64 @nova_rt_starts_with(i64 %r172, i64 %r173)
  %t73 = getelementptr inbounds [12 x i8], ptr @.str.26, i64 0, i64 0
  %r175 = ptrtoint ptr %t73 to i64
  call void @nova_rt_assert(i64 %r174, i64 %r175)
  %r177 = load i64, ptr %slot.s, align 8
  %t74 = getelementptr inbounds [7 x i8], ptr @.str.27, i64 0, i64 0
  %r178 = ptrtoint ptr %t74 to i64
  %r179 = call i64 @nova_rt_ends_with(i64 %r177, i64 %r178)
  %t75 = getelementptr inbounds [10 x i8], ptr @.str.28, i64 0, i64 0
  %r180 = ptrtoint ptr %t75 to i64
  call void @nova_rt_assert(i64 %r179, i64 %r180)
  %r182 = load i64, ptr %slot.s, align 8
  %t76 = getelementptr inbounds [6 x i8], ptr @.str.29, i64 0, i64 0
  %r183 = ptrtoint ptr %t76 to i64
  %r184 = call i64 @nova_rt_contains(i64 %r182, i64 %r183)
  %t77 = getelementptr inbounds [9 x i8], ptr @.str.30, i64 0, i64 0
  %r185 = ptrtoint ptr %t77 to i64
  call void @nova_rt_assert(i64 %r184, i64 %r185)
  %r188 = load i64, ptr %slot.s, align 8
  %t78 = getelementptr inbounds [6 x i8], ptr @.str.29, i64 0, i64 0
  %r189 = ptrtoint ptr %t78 to i64
  %r190 = call i64 @nova_rt_find(i64 %r188, i64 %r189)
  %t79 = icmp eq i64 %r190, 7
  %r196 = zext i1 %t79 to i64
  %t80 = getelementptr inbounds [5 x i8], ptr @.str.31, i64 0, i64 0
  %r197 = ptrtoint ptr %t80 to i64
  call void @nova_rt_assert(i64 %r196, i64 %r197)
  %r200 = load i64, ptr %slot.s, align 8
  %t81 = getelementptr inbounds [6 x i8], ptr @.str.29, i64 0, i64 0
  %r201 = ptrtoint ptr %t81 to i64
  %t82 = getelementptr inbounds [5 x i8], ptr @.str.32, i64 0, i64 0
  %r202 = ptrtoint ptr %t82 to i64
  %r203 = call i64 @nova_rt_replace(i64 %r200, i64 %r201, i64 %r202)
  %t83 = getelementptr inbounds [13 x i8], ptr @.str.33, i64 0, i64 0
  %r208 = ptrtoint ptr %t83 to i64
  %t84 = inttoptr i64 %r203 to ptr
  %t85 = inttoptr i64 %r208 to ptr
  %t86 = call i32 @strcmp(ptr %t84, ptr %t85)
  %t87 = icmp eq i32 %t86, 0
  %r209 = zext i1 %t87 to i64
  call void @nova_rc_dec(i64 %r203)
  %t88 = getelementptr inbounds [8 x i8], ptr @.str.34, i64 0, i64 0
  %r210 = ptrtoint ptr %t88 to i64
  call void @nova_rt_assert(i64 %r209, i64 %r210)
  %t89 = getelementptr inbounds [6 x i8], ptr @.str.35, i64 0, i64 0
  %r213 = ptrtoint ptr %t89 to i64
  %t90 = getelementptr inbounds [2 x i8], ptr @.str.36, i64 0, i64 0
  %r214 = ptrtoint ptr %t90 to i64
  %r215 = call i64 @nova_rt_split(i64 %r213, i64 %r214)
  %r220 = call i64 @nova_rt_list_len(i64 %r215)
  %t91 = icmp eq i64 %r220, 3
  %r222 = zext i1 %t91 to i64
  %t92 = getelementptr inbounds [13 x i8], ptr @.str.37, i64 0, i64 0
  %r223 = ptrtoint ptr %t92 to i64
  call void @nova_rt_assert(i64 %r222, i64 %r223)
  %t93 = inttoptr i64 %r215 to ptr
  %t94 = load ptr, ptr %t93, align 8, !tbaa !2
  %t95 = getelementptr i64, ptr %t94, i64 0
  %r227 = load i64, ptr %t95, align 8, !tbaa !4
  %t96 = getelementptr inbounds [2 x i8], ptr @.str.38, i64 0, i64 0
  %r228 = ptrtoint ptr %t96 to i64
  %t97 = inttoptr i64 %r227 to ptr
  %t98 = inttoptr i64 %r228 to ptr
  %t99 = call i32 @strcmp(ptr %t97, ptr %t98)
  %t100 = icmp eq i32 %t99, 0
  %r229 = zext i1 %t100 to i64
  %t101 = getelementptr inbounds [9 x i8], ptr @.str.39, i64 0, i64 0
  %r230 = ptrtoint ptr %t101 to i64
  call void @nova_rt_assert(i64 %r229, i64 %r230)
  %t102 = inttoptr i64 %r215 to ptr
  %t103 = load ptr, ptr %t102, align 8, !tbaa !2
  %t104 = getelementptr i64, ptr %t103, i64 2
  %r234 = load i64, ptr %t104, align 8, !tbaa !4
  %t105 = getelementptr inbounds [2 x i8], ptr @.str.40, i64 0, i64 0
  %r235 = ptrtoint ptr %t105 to i64
  %t106 = inttoptr i64 %r234 to ptr
  %t107 = inttoptr i64 %r235 to ptr
  %t108 = call i32 @strcmp(ptr %t106, ptr %t107)
  %t109 = icmp eq i32 %t108, 0
  %r236 = zext i1 %t109 to i64
  %t110 = getelementptr inbounds [9 x i8], ptr @.str.41, i64 0, i64 0
  %r237 = ptrtoint ptr %t110 to i64
  call void @nova_rt_assert(i64 %r236, i64 %r237)
  %t111 = getelementptr inbounds [2 x i8], ptr @.str.42, i64 0, i64 0
  %r241 = ptrtoint ptr %t111 to i64
  %r242 = call i64 @nova_rt_join(i64 %r215, i64 %r241)
  %t112 = getelementptr inbounds [6 x i8], ptr @.str.43, i64 0, i64 0
  %r247 = ptrtoint ptr %t112 to i64
  %t113 = inttoptr i64 %r242 to ptr
  %t114 = inttoptr i64 %r247 to ptr
  %t115 = call i32 @strcmp(ptr %t113, ptr %t114)
  %t116 = icmp eq i32 %t115, 0
  %r248 = zext i1 %t116 to i64
  call void @nova_rc_dec(i64 %r242)
  %t117 = getelementptr inbounds [5 x i8], ptr @.str.44, i64 0, i64 0
  %r249 = ptrtoint ptr %t117 to i64
  call void @nova_rt_assert(i64 %r248, i64 %r249)
  %t118 = getelementptr inbounds [30 x i8], ptr @.str.45, i64 0, i64 0
  %r251 = ptrtoint ptr %t118 to i64
  %t119 = inttoptr i64 %r251 to ptr
  call i32 @puts(ptr %t119)
  %t120 = load i64, ptr %slot.s, align 8
  call void @nova_rc_dec(i64 %t120)
  %t121 = load i64, ptr %slot.__for_iter_7, align 8
  call void @nova_rc_dec(i64 %t121)
  %t122 = load i64, ptr %slot.reversed, align 8
  call void @nova_rc_dec(i64 %t122)
  %t123 = load i64, ptr %slot.__for_iter_9, align 8
  call void @nova_rc_dec(i64 %t123)
  ret i64 0
}

define i32 @main(i32 %argc, ptr %argv) nounwind {
entry:
  %argc64 = sext i32 %argc to i64
  %argv64 = ptrtoint ptr %argv to i64
  call void @nova_rt_init_args(i64 %argc64, i64 %argv64)
  call i64 @nova_main()
  call void @nova_rt_wait_all()
  call void @nova_rt_cleanup()
  ret i32 0
}

!0 = !{!"NOVA TBAA"}
!1 = !{!"list_data_ptr", !0}
!2 = !{!1, !1, i64 0}
!3 = !{!"list_elem", !0}
!4 = !{!3, !3, i64 0}
!5 = !{!"list_size", !0}
!6 = !{!5, !5, i64 0}
!7 = !{!"list_cap", !0}
!8 = !{!7, !7, i64 0}
!90 = !{!"branch_weights", i32 2000, i32 1}
!91 = distinct !{!91, !92, !93}
!92 = !{!"llvm.loop.unroll.enable"}
!93 = !{!"llvm.loop.vectorize.enable", i1 true}
