; Generated by NOVA compiler
target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"

declare i32 @printf(ptr, ...)
declare i32 @puts(ptr)
declare noalias ptr @malloc(i64) nounwind allocsize(0)
declare noalias ptr @calloc(i64, i64) nounwind
declare ptr @realloc(ptr, i64) nounwind allocsize(1)
declare void @free(ptr) nounwind
declare i64 @llvm.smax.i64(i64, i64) nounwind readnone
; nova runtime — list ops
declare i64 @nova_rt_list_create() nounwind
declare i64 @nova_rt_list_create_filled(i64, i64) nounwind
declare i64 @nova_rt_list_append(i64, i64) nounwind
declare i64 @nova_rt_list_get(i64, i64) nounwind readonly
declare i64 @nova_rt_list_set(i64, i64, i64) nounwind
declare i64 @nova_rt_list_len(i64) nounwind readonly
declare i64 @nova_rt_list_print(i64) nounwind
declare i64 @nova_rt_iter_has_next(i64, i64) nounwind readonly
declare i64 @nova_rt_iter_get(i64, i64) nounwind readonly
declare i64 @nova_rt_list_iter_has_next(i64, i64) nounwind readonly
declare i64 @nova_rt_list_iter_get(i64, i64) nounwind readonly
; nova runtime — string ops
declare i64 @nova_rt_str_concat(i64, i64) nounwind
declare i64 @nova_rt_int_to_str(i64) nounwind
declare i64 @nova_rt_float_to_str(i64) nounwind
declare i64 @nova_rt_bool_to_str(i64) nounwind
declare i64 @nova_rt_str_len(i64) nounwind readonly
declare i64 @nova_rt_len(i64) nounwind readonly
declare i64 @nova_rt_contains(i64, i64) nounwind readonly
declare i64 @nova_rt_slice(i64, i64, i64) nounwind
declare i64 @nova_rt_upper(i64) nounwind
declare i64 @nova_rt_lower(i64) nounwind
declare i64 @nova_rt_trim(i64) nounwind
declare i64 @nova_rt_repeat(i64, i64) nounwind
declare i64 @nova_rt_split(i64, i64) nounwind
declare i64 @nova_rt_replace(i64, i64, i64) nounwind
declare i64 @nova_rt_starts_with(i64, i64) nounwind readonly
declare i64 @nova_rt_ends_with(i64, i64) nounwind readonly
declare i64 @nova_rt_find(i64, i64) nounwind readonly
declare i64 @nova_rt_join(i64, i64) nounwind
declare i64 @nova_rt_chars(i64) nounwind
; nova runtime — list stdlib
declare i64 @nova_rt_list_reverse(i64) nounwind
declare i64 @nova_rt_list_sort(i64) nounwind
declare i64 @nova_rt_list_map(i64, i64) nounwind
declare i64 @nova_rt_list_filter(i64, i64) nounwind
declare i64 @nova_rt_list_concat(i64, i64) nounwind
declare i64 @nova_rt_list_slice(i64, i64, i64) nounwind
declare i64 @nova_rt_list_to_str(i64) nounwind
declare i64 @nova_rt_len_any(i64) nounwind readonly
; nova runtime — type conversions
declare i64 @nova_rt_parse_int(i64) nounwind
declare i64 @nova_rt_parse_float(i64) nounwind
; nova runtime — character ops
declare i64 @nova_rt_ord(i64) nounwind readonly
declare i64 @nova_rt_chr(i64) nounwind
; nova runtime — process control
declare void @nova_rt_exit(i64) noreturn nounwind
declare i32 @strcmp(ptr, ptr) nounwind readonly
; nova runtime — dict ops (hash map, O(1) avg lookup)
declare i64 @nova_rt_dict_create() nounwind
declare i64 @nova_rt_dict_set(i64, i64, i64) nounwind
declare i64 @nova_rt_dict_get(i64, i64) nounwind readonly
declare i64 @nova_rt_dict_get_concat2(i64, i64, i64) nounwind readonly
declare i64 @nova_rt_dict_set_concat2(i64, i64, i64, i64) nounwind
declare i64 @nova_rt_dict_has(i64, i64) nounwind readonly
declare i64 @nova_rt_dict_del(i64, i64) nounwind
declare i64 @nova_rt_dict_len(i64) nounwind readonly
declare i64 @nova_rt_dict_keys(i64) nounwind
declare i64 @nova_rt_dict_values(i64) nounwind
declare i64 @nova_rt_dict_items(i64) nounwind
; nova runtime — IO ops
declare i64 @nova_rt_read_line() nounwind
declare i64 @nova_rt_read_file(i64) nounwind
declare i64 @nova_rt_write_file(i64, i64) nounwind
declare i64 @nova_rt_append_file(i64, i64) nounwind
declare i64 @nova_rt_file_exists(i64) nounwind readonly
; nova runtime — JSON ops
declare i64 @nova_rt_json_parse(i64) nounwind
declare i64 @nova_rt_json_stringify(i64) nounwind
; nova runtime — HTTP ops
declare i64 @nova_rt_http_get(i64) nounwind
declare i64 @nova_rt_http_post(i64, i64, i64) nounwind
; nova runtime — time ops
declare i64 @nova_rt_time_ms() nounwind
declare i64 @nova_rt_clock_ns() nounwind
declare void @nova_rt_sleep_ms(i64) nounwind
declare void @nova_rt_assert(i64, i64) nounwind
; nova runtime — type dispatch
declare i64 @nova_rt_any_to_str(i64) nounwind
declare i64 @nova_rt_str_concat_safe(i64, i64) nounwind
declare i64 @nova_rt_str_char_at(i64, i64) nounwind
declare void @nova_rt_init() nounwind
declare void @nova_rt_init_args(i64, i64) nounwind
; nova runtime — system ops
declare i64 @nova_rt_args() nounwind
declare i64 @nova_rt_env(i64) nounwind
declare i64 @nova_rt_random_int(i64, i64) nounwind
declare i64 @nova_rt_random_float() nounwind
declare i64 @nova_rt_shell(i64) nounwind
declare i64 @nova_rt_path_join(i64, i64) nounwind
declare i64 @nova_rt_path_parent(i64) nounwind
declare i64 @nova_rt_path_name(i64) nounwind
declare i64 @nova_rt_path_ext(i64) nounwind
; nova runtime — regex ops
declare i64 @nova_rt_regex_match(i64, i64) nounwind readonly
declare i64 @nova_rt_regex_find(i64, i64) nounwind
declare i64 @nova_rt_regex_replace(i64, i64, i64) nounwind
declare i64 @nova_rt_regex_split(i64, i64) nounwind
; nova runtime — network ops
declare i64 @nova_rt_tcp_connect(i64, i64) nounwind
declare i64 @nova_rt_tcp_listen(i64) nounwind
declare i64 @nova_rt_tcp_accept(i64) nounwind
declare i64 @nova_rt_tcp_send(i64, i64) nounwind
declare i64 @nova_rt_tcp_recv(i64) nounwind
declare void @nova_rt_tcp_close(i64) nounwind
declare i64 @nova_rt_udp_bind(i64) nounwind
declare i64 @nova_rt_udp_send(i64, i64, i64, i64) nounwind
declare i64 @nova_rt_udp_recv(i64) nounwind
; nova runtime — HTTP server
declare i64 @nova_rt_http_listen(i64) nounwind
declare i64 @nova_rt_http_accept(i64) nounwind
declare void @nova_rt_http_respond(i64, i64, i64) nounwind
; nova runtime — byte arrays
declare i64 @nova_rt_bytes_create(i64) nounwind
declare i64 @nova_rt_bytes_get(i64, i64) nounwind
declare void @nova_rt_bytes_set(i64, i64, i64) nounwind
declare i64 @nova_rt_bytes_len(i64) nounwind
declare i64 @nova_rt_bytes_slice(i64, i64, i64) nounwind
declare i64 @nova_rt_bytes_to_str(i64) nounwind
declare i64 @nova_rt_str_to_bytes(i64) nounwind
; nova runtime — channel/spawn ops
declare i64 @nova_rt_channel_create() nounwind
declare i64 @nova_rt_channel_send(i64, i64) nounwind
declare i64 @nova_rt_channel_recv(i64) nounwind
declare i64 @nova_rt_channel_close(i64) nounwind
declare i64 @nova_rt_channel_select(i64, i64) nounwind
declare i64 @nova_rt_channel_recv_timeout(i64, i64) nounwind
declare i64 @nova_rt_spawn(i64, i64) nounwind
declare i64 @nova_rt_monitor(i64) nounwind
declare void @nova_rt_wait_all() nounwind
; nova runtime — math (trig/log via C runtime for non-intrinsic functions)
declare i64 @nova_rt_tan(i64) nounwind
declare i64 @nova_rt_asin(i64) nounwind
declare i64 @nova_rt_acos(i64) nounwind
declare i64 @nova_rt_atan(i64) nounwind
declare i64 @nova_rt_atan2(i64, i64) nounwind
declare i64 @nova_rt_fmod(i64, i64) nounwind
declare i64 @nova_rt_int_pow(i64, i64) nounwind
; nova runtime — memory management
declare void @nova_rt_cleanup() nounwind
declare void @nova_rt_track_raw(ptr) nounwind
declare i64 @nova_rt_alloc_count() nounwind readonly
declare i64 @nova_rt_live_count() nounwind readonly
; nova runtime — reference counting
declare void @nova_rc_inc(i64) nounwind
declare void @nova_rc_dec(i64) nounwind
; nova error state — thread-local flag (safe for spawn/concurrent programs)
@__nova_error_flag = thread_local global i64 0
@__nova_error_msg = thread_local global i64 0

@.str.0 = private unnamed_addr constant [2 x i8] c"x\00"
@.str.1 = private unnamed_addr constant [2 x i8] c"w\00"
@.str.2 = private unnamed_addr constant [2 x i8] c"y\00"
@.str.3 = private unnamed_addr constant [2 x i8] c"h\00"
@.str.4 = private unnamed_addr constant [2 x i8] c"(\00"
@.str.5 = private unnamed_addr constant [3 x i8] c", \00"
@.str.6 = private unnamed_addr constant [2 x i8] c")\00"
@.str.7 = private unnamed_addr constant [6 x i8] c"%lld\0A\00"
@.str.8 = private unnamed_addr constant [4 x i8] c"%f\0A\00"
@.str.9 = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.str.10 = private unnamed_addr constant [5 x i8] c"true\00"
@.str.11 = private unnamed_addr constant [6 x i8] c"false\00"

define i64 @Rect__contains(i64 %p0, i64 %p1, i64 %p2) nounwind {
entry0:
  %slot.self = alloca i64, align 8
  %slot.px = alloca i64, align 8
  %slot.py = alloca i64, align 8
  %slot.__sc_and_1 = alloca i64, align 8
  %slot.__sc_and_2 = alloca i64, align 8
  %slot.__sc_and_3 = alloca i64, align 8
  store i64 %p0, ptr %slot.self, align 8
  store i64 %p1, ptr %slot.px, align 8
  store i64 %p2, ptr %slot.py, align 8
  %t0 = inttoptr i64 %p0 to ptr
  %t1 = getelementptr i64, ptr %t0, i64 0
  %r9 = load i64, ptr %t1
  %t2 = icmp sge i64 %p1, %r9
  %r10 = zext i1 %t2 to i64
  store i64 0, ptr %slot.__sc_and_1, align 8
  %t3 = icmp ne i64 %r10, 0
  br i1 %t3, label %sc_and_right1, label %sc_and_merge2

sc_and_right1:
  %r16 = load i64, ptr %slot.px, align 8
  %r17 = load i64, ptr %slot.self, align 8
  %t4 = inttoptr i64 %r17 to ptr
  %t5 = getelementptr i64, ptr %t4, i64 0
  %r18 = load i64, ptr %t5
  %r19 = load i64, ptr %slot.self, align 8
  %t6 = inttoptr i64 %r19 to ptr
  %t7 = getelementptr i64, ptr %t6, i64 2
  %r20 = load i64, ptr %t7
  %r21 = add i64 %r18, %r20
  %t8 = icmp slt i64 %r16, %r21
  %r22 = zext i1 %t8 to i64
  store i64 %r22, ptr %slot.__sc_and_1, align 8
  br label %sc_and_merge2

sc_and_merge2:
  %r24 = load i64, ptr %slot.__sc_and_1, align 8
  store i64 0, ptr %slot.__sc_and_2, align 8
  %t9 = icmp ne i64 %r24, 0
  br i1 %t9, label %sc_and_right3, label %sc_and_merge4

sc_and_right3:
  %r30 = load i64, ptr %slot.py, align 8
  %r31 = load i64, ptr %slot.self, align 8
  %t10 = inttoptr i64 %r31 to ptr
  %t11 = getelementptr i64, ptr %t10, i64 1
  %r32 = load i64, ptr %t11
  %t12 = icmp sge i64 %r30, %r32
  %r33 = zext i1 %t12 to i64
  store i64 %r33, ptr %slot.__sc_and_2, align 8
  br label %sc_and_merge4

sc_and_merge4:
  %r35 = load i64, ptr %slot.__sc_and_2, align 8
  store i64 0, ptr %slot.__sc_and_3, align 8
  %t13 = icmp ne i64 %r35, 0
  br i1 %t13, label %sc_and_right5, label %sc_and_merge6

sc_and_right5:
  %r41 = load i64, ptr %slot.py, align 8
  %r42 = load i64, ptr %slot.self, align 8
  %t14 = inttoptr i64 %r42 to ptr
  %t15 = getelementptr i64, ptr %t14, i64 1
  %r43 = load i64, ptr %t15
  %r44 = load i64, ptr %slot.self, align 8
  %t16 = inttoptr i64 %r44 to ptr
  %t17 = getelementptr i64, ptr %t16, i64 3
  %r45 = load i64, ptr %t17
  %r46 = add i64 %r43, %r45
  %t18 = icmp slt i64 %r41, %r46
  %r47 = zext i1 %t18 to i64
  store i64 %r47, ptr %slot.__sc_and_3, align 8
  br label %sc_and_merge6

sc_and_merge6:
  %r49 = load i64, ptr %slot.__sc_and_3, align 8
  ret i64 %r49
}

define i64 @nova_main() nounwind {
entry0:
  %slot.p = alloca i64, align 8
  %slot.__mb0_ret = alloca i64, align 8
  %slot.__mb0_self = alloca i64, align 8
  %slot.__mb0_other = alloca i64, align 8
  %slot.__mb0___sc_and_0 = alloca i64, align 8
  %slot.__mb1_ret = alloca i64, align 8
  %slot.__mb1_self = alloca i64, align 8
  %slot.__mb1_other = alloca i64, align 8
  %slot.__mb1___sc_and_0 = alloca i64, align 8
  store i64 0, ptr %slot.p, align 8
  store i64 0, ptr %slot.__mb0_self, align 8
  store i64 0, ptr %slot.__mb0_other, align 8
  store i64 0, ptr %slot.__mb1_self, align 8
  store i64 0, ptr %slot.__mb1_other, align 8
  %t0 = alloca i64, i64 2, align 8
  %t1 = getelementptr i64, ptr %t0, i64 0
  store i64 3, ptr %t1
  %t2 = getelementptr i64, ptr %t0, i64 1
  store i64 4, ptr %t2
  %r4 = ptrtoint ptr %t0 to i64
  %t3 = load i64, ptr %slot.p, align 8
  call void @nova_rc_dec(i64 %t3)
  store i64 %r4, ptr %slot.p, align 8
  %t4 = inttoptr i64 %r4 to ptr
  %t5 = getelementptr i64, ptr %t4, i64 0
  %r9 = load i64, ptr %t5
  %t6 = getelementptr inbounds [5 x i8], ptr @.str.7, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t6, i64 %r9)
  %t7 = inttoptr i64 %r4 to ptr
  %t8 = getelementptr i64, ptr %t7, i64 1
  %r12 = load i64, ptr %t8
  %t9 = getelementptr inbounds [5 x i8], ptr @.str.7, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t9, i64 %r12)
  %t10 = inttoptr i64 %r4 to ptr
  %t11 = getelementptr i64, ptr %t10, i64 0
  %r97 = load i64, ptr %t11
  %t12 = icmp slt i64 %r97, 0
  %t13 = sub i64 0, %r97
  %r98 = select i1 %t12, i64 %t13, i64 %r97
  %t14 = inttoptr i64 %r4 to ptr
  %t15 = getelementptr i64, ptr %t14, i64 1
  %r100 = load i64, ptr %t15
  %t16 = icmp slt i64 %r100, 0
  %t17 = sub i64 0, %r100
  %r101 = select i1 %t16, i64 %t17, i64 %r100
  %r102 = add i64 %r98, %r101
  %t18 = getelementptr inbounds [5 x i8], ptr @.str.7, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t18, i64 %r102)
  %t19 = inttoptr i64 %r4 to ptr
  %t20 = getelementptr i64, ptr %t19, i64 0
  %r111 = load i64, ptr %t20
  %r113 = add i64 %r111, 1
  %t21 = inttoptr i64 %r4 to ptr
  %t22 = getelementptr i64, ptr %t21, i64 1
  %r115 = load i64, ptr %t22
  %r117 = add i64 %r115, 2
  %t23 = alloca i64, i64 2, align 8
  %t24 = getelementptr i64, ptr %t23, i64 0
  store i64 %r113, ptr %t24
  %t25 = getelementptr i64, ptr %t23, i64 1
  store i64 %r117, ptr %t25
  %r118 = ptrtoint ptr %t23 to i64
  %t26 = inttoptr i64 %r118 to ptr
  %t27 = getelementptr i64, ptr %t26, i64 0
  %r25 = load i64, ptr %t27
  %t28 = getelementptr inbounds [5 x i8], ptr @.str.7, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t28, i64 %r25)
  %t29 = inttoptr i64 %r118 to ptr
  %t30 = getelementptr i64, ptr %t29, i64 1
  %r28 = load i64, ptr %t30
  %t31 = getelementptr inbounds [5 x i8], ptr @.str.7, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t31, i64 %r28)
  %t32 = inttoptr i64 %r4 to ptr
  %t33 = getelementptr i64, ptr %t32, i64 0
  %r125 = load i64, ptr %t33
  %r127 = add i64 %r125, %r125
  %t34 = inttoptr i64 %r4 to ptr
  %t35 = getelementptr i64, ptr %t34, i64 1
  %r129 = load i64, ptr %t35
  %r131 = add i64 %r129, %r129
  %t36 = alloca i64, i64 2, align 8
  %t37 = getelementptr i64, ptr %t36, i64 0
  store i64 %r127, ptr %t37
  %t38 = getelementptr i64, ptr %t36, i64 1
  store i64 %r131, ptr %t38
  %r132 = ptrtoint ptr %t36 to i64
  %t39 = inttoptr i64 %r132 to ptr
  %t40 = getelementptr i64, ptr %t39, i64 0
  %r37 = load i64, ptr %t40
  %t41 = getelementptr inbounds [5 x i8], ptr @.str.7, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t41, i64 %r37)
  %t42 = inttoptr i64 %r132 to ptr
  %t43 = getelementptr i64, ptr %t42, i64 1
  %r40 = load i64, ptr %t43
  %t44 = getelementptr inbounds [5 x i8], ptr @.str.7, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t44, i64 %r40)
  %r42 = load i64, ptr %slot.p, align 8
  %t45 = alloca i64, i64 2, align 8
  %t46 = getelementptr i64, ptr %t45, i64 0
  store i64 3, ptr %t46
  %t47 = getelementptr i64, ptr %t45, i64 1
  store i64 4, ptr %t47
  %r45 = ptrtoint ptr %t45 to i64
  call void @nova_rc_dec(i64 %r45)
  br label %__mb0_entry0

__mb0_entry0:
  %t48 = load i64, ptr %slot.__mb0_self, align 8
  call void @nova_rc_dec(i64 %t48)
  call void @nova_rc_inc(i64 %r42)
  store i64 %r42, ptr %slot.__mb0_self, align 8
  %t49 = load i64, ptr %slot.__mb0_other, align 8
  call void @nova_rc_dec(i64 %t49)
  store i64 %r45, ptr %slot.__mb0_other, align 8
  %t50 = inttoptr i64 %r42 to ptr
  %t51 = getelementptr i64, ptr %t50, i64 0
  %r229 = load i64, ptr %t51
  %t52 = inttoptr i64 %r45 to ptr
  %t53 = getelementptr i64, ptr %t52, i64 0
  %r231 = load i64, ptr %t53
  %t54 = icmp eq i64 %r229, %r231
  %r232 = zext i1 %t54 to i64
  store i64 0, ptr %slot.__mb0___sc_and_0, align 8
  %t55 = icmp ne i64 %r232, 0
  br i1 %t55, label %__mb0_sc_and_right1, label %__mb0_sc_and_merge2

__mb0_sc_and_right1:
  %r238 = load i64, ptr %slot.__mb0_self, align 8
  %t56 = inttoptr i64 %r238 to ptr
  %t57 = getelementptr i64, ptr %t56, i64 1
  %r239 = load i64, ptr %t57
  %r240 = load i64, ptr %slot.__mb0_other, align 8
  %t58 = inttoptr i64 %r240 to ptr
  %t59 = getelementptr i64, ptr %t58, i64 1
  %r241 = load i64, ptr %t59
  %t60 = icmp eq i64 %r239, %r241
  %r242 = zext i1 %t60 to i64
  store i64 %r242, ptr %slot.__mb0___sc_and_0, align 8
  br label %__mb0_sc_and_merge2

__mb0_sc_and_merge2:
  %r244 = load i64, ptr %slot.__mb0___sc_and_0, align 8
  store i64 %r244, ptr %slot.__mb0_ret, align 8
  br label %__mb0_merge

__mb0_merge:
  %r245 = load i64, ptr %slot.__mb0_ret, align 8
  %t61 = icmp ne i64 %r245, 0
  %t62 = getelementptr inbounds [5 x i8], ptr @.str.10, i64 0, i64 0
  %t63 = getelementptr inbounds [6 x i8], ptr @.str.11, i64 0, i64 0
  %t64 = select i1 %t61, ptr %t62, ptr %t63
  call i32 @puts(ptr %t64)
  %r48 = load i64, ptr %slot.p, align 8
  %t65 = alloca i64, i64 2, align 8
  %t66 = getelementptr i64, ptr %t65, i64 0
  store i64 0, ptr %t66
  %t67 = getelementptr i64, ptr %t65, i64 1
  store i64 0, ptr %t67
  %r51 = ptrtoint ptr %t65 to i64
  call void @nova_rc_dec(i64 %r51)
  br label %__mb1_entry0

__mb1_entry0:
  %t68 = load i64, ptr %slot.__mb1_self, align 8
  call void @nova_rc_dec(i64 %t68)
  call void @nova_rc_inc(i64 %r48)
  store i64 %r48, ptr %slot.__mb1_self, align 8
  %t69 = load i64, ptr %slot.__mb1_other, align 8
  call void @nova_rc_dec(i64 %t69)
  store i64 %r51, ptr %slot.__mb1_other, align 8
  %t70 = inttoptr i64 %r48 to ptr
  %t71 = getelementptr i64, ptr %t70, i64 0
  %r254 = load i64, ptr %t71
  %t72 = inttoptr i64 %r51 to ptr
  %t73 = getelementptr i64, ptr %t72, i64 0
  %r256 = load i64, ptr %t73
  %t74 = icmp eq i64 %r254, %r256
  %r257 = zext i1 %t74 to i64
  store i64 0, ptr %slot.__mb1___sc_and_0, align 8
  %t75 = icmp ne i64 %r257, 0
  br i1 %t75, label %__mb1_sc_and_right1, label %__mb1_sc_and_merge2

__mb1_sc_and_right1:
  %r263 = load i64, ptr %slot.__mb1_self, align 8
  %t76 = inttoptr i64 %r263 to ptr
  %t77 = getelementptr i64, ptr %t76, i64 1
  %r264 = load i64, ptr %t77
  %r265 = load i64, ptr %slot.__mb1_other, align 8
  %t78 = inttoptr i64 %r265 to ptr
  %t79 = getelementptr i64, ptr %t78, i64 1
  %r266 = load i64, ptr %t79
  %t80 = icmp eq i64 %r264, %r266
  %r267 = zext i1 %t80 to i64
  store i64 %r267, ptr %slot.__mb1___sc_and_0, align 8
  br label %__mb1_sc_and_merge2

__mb1_sc_and_merge2:
  %r269 = load i64, ptr %slot.__mb1___sc_and_0, align 8
  store i64 %r269, ptr %slot.__mb1_ret, align 8
  br label %__mb1_merge

__mb1_merge:
  %r270 = load i64, ptr %slot.__mb1_ret, align 8
  %t81 = icmp ne i64 %r270, 0
  %t82 = getelementptr inbounds [5 x i8], ptr @.str.10, i64 0, i64 0
  %t83 = getelementptr inbounds [6 x i8], ptr @.str.11, i64 0, i64 0
  %t84 = select i1 %t81, ptr %t82, ptr %t83
  call i32 @puts(ptr %t84)
  %r54 = load i64, ptr %slot.p, align 8
  %t85 = getelementptr inbounds [2 x i8], ptr @.str.4, i64 0, i64 0
  %r136 = ptrtoint ptr %t85 to i64
  %t86 = inttoptr i64 %r54 to ptr
  %t87 = getelementptr i64, ptr %t86, i64 0
  %r138 = load i64, ptr %t87
  %r139 = call i64 @nova_rt_int_to_str(i64 %r138)
  %t88 = call i64 @nova_rt_str_concat(i64 %r136, i64 %r139)
  call void @nova_rc_dec(i64 %r139)
  %t89 = getelementptr inbounds [3 x i8], ptr @.str.5, i64 0, i64 0
  %r141 = ptrtoint ptr %t89 to i64
  %t90 = call i64 @nova_rt_str_concat(i64 %t88, i64 %r141)
  call void @nova_rc_dec(i64 %t88)
  %t91 = inttoptr i64 %r54 to ptr
  %t92 = getelementptr i64, ptr %t91, i64 1
  %r144 = load i64, ptr %t92
  %r145 = call i64 @nova_rt_int_to_str(i64 %r144)
  %t93 = call i64 @nova_rt_str_concat(i64 %t90, i64 %r145)
  call void @nova_rc_dec(i64 %t90)
  call void @nova_rc_dec(i64 %r145)
  %t94 = getelementptr inbounds [2 x i8], ptr @.str.6, i64 0, i64 0
  %r147 = ptrtoint ptr %t94 to i64
  %t95 = call i64 @nova_rt_str_concat(i64 %t93, i64 %r147)
  call void @nova_rc_dec(i64 %t93)
  %t96 = inttoptr i64 %t95 to ptr
  call i32 @puts(ptr %t96)
  call void @nova_rc_dec(i64 %t95)
  %r57 = load i64, ptr %slot.p, align 8
  %t97 = inttoptr i64 %r57 to ptr
  %t98 = getelementptr i64, ptr %t97, i64 0
  %r157 = load i64, ptr %t98
  %r159 = add i64 %r157, 10
  %t99 = inttoptr i64 %r57 to ptr
  %t100 = getelementptr i64, ptr %t99, i64 1
  %r161 = load i64, ptr %t100
  %r163 = add i64 %r161, 20
  %t101 = alloca i64, i64 2, align 8
  %t102 = getelementptr i64, ptr %t101, i64 0
  store i64 %r159, ptr %t102
  %t103 = getelementptr i64, ptr %t101, i64 1
  store i64 %r163, ptr %t103
  %r164 = ptrtoint ptr %t101 to i64
  %t104 = inttoptr i64 %r164 to ptr
  %t105 = getelementptr i64, ptr %t104, i64 0
  %r169 = load i64, ptr %t105
  %t106 = icmp slt i64 %r169, 0
  %t107 = sub i64 0, %r169
  %r170 = select i1 %t106, i64 %t107, i64 %r169
  %t108 = inttoptr i64 %r164 to ptr
  %t109 = getelementptr i64, ptr %t108, i64 1
  %r172 = load i64, ptr %t109
  %t110 = icmp slt i64 %r172, 0
  %t111 = sub i64 0, %r172
  %r173 = select i1 %t110, i64 %t111, i64 %r172
  %r174 = add i64 %r170, %r173
  %t112 = getelementptr inbounds [5 x i8], ptr @.str.7, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t112, i64 %r174)
  %r63 = load i64, ptr %slot.p, align 8
  %t113 = inttoptr i64 %r63 to ptr
  %t114 = getelementptr i64, ptr %t113, i64 0
  %r181 = load i64, ptr %t114
  %r183 = mul i64 %r181, 3
  %t115 = inttoptr i64 %r63 to ptr
  %t116 = getelementptr i64, ptr %t115, i64 1
  %r185 = load i64, ptr %t116
  %r187 = mul i64 %r185, 3
  %t117 = alloca i64, i64 2, align 8
  %t118 = getelementptr i64, ptr %t117, i64 0
  store i64 %r183, ptr %t118
  %t119 = getelementptr i64, ptr %t117, i64 1
  store i64 %r187, ptr %t119
  %r188 = ptrtoint ptr %t117 to i64
  %t120 = inttoptr i64 %r188 to ptr
  %t121 = getelementptr i64, ptr %t120, i64 0
  %r197 = load i64, ptr %t121
  %r199 = add i64 %r197, 1
  %t122 = inttoptr i64 %r188 to ptr
  %t123 = getelementptr i64, ptr %t122, i64 1
  %r201 = load i64, ptr %t123
  %r203 = add i64 %r201, 1
  %t124 = alloca i64, i64 2, align 8
  %t125 = getelementptr i64, ptr %t124, i64 0
  store i64 %r199, ptr %t125
  %t126 = getelementptr i64, ptr %t124, i64 1
  store i64 %r203, ptr %t126
  %r204 = ptrtoint ptr %t124 to i64
  %t127 = inttoptr i64 %r204 to ptr
  %t128 = getelementptr i64, ptr %t127, i64 0
  %r209 = load i64, ptr %t128
  %t129 = icmp slt i64 %r209, 0
  %t130 = sub i64 0, %r209
  %r210 = select i1 %t129, i64 %t130, i64 %r209
  %t131 = inttoptr i64 %r204 to ptr
  %t132 = getelementptr i64, ptr %t131, i64 1
  %r212 = load i64, ptr %t132
  %t133 = icmp slt i64 %r212, 0
  %t134 = sub i64 0, %r212
  %r213 = select i1 %t133, i64 %t134, i64 %r212
  %r214 = add i64 %r210, %r213
  %t135 = getelementptr inbounds [5 x i8], ptr @.str.7, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t135, i64 %r214)
  %t136 = call ptr @malloc(i64 32)
  call void @nova_rt_track_raw(ptr %t136)
  %t137 = getelementptr i64, ptr %t136, i64 0
  store i64 0, ptr %t137
  %t138 = getelementptr i64, ptr %t136, i64 1
  store i64 0, ptr %t138
  %t139 = getelementptr i64, ptr %t136, i64 2
  store i64 10, ptr %t139
  %t140 = getelementptr i64, ptr %t136, i64 3
  store i64 5, ptr %t140
  %r75 = ptrtoint ptr %t136 to i64
  %t141 = inttoptr i64 %r75 to ptr
  %t142 = getelementptr i64, ptr %t141, i64 2
  %r219 = load i64, ptr %t142
  %t143 = inttoptr i64 %r75 to ptr
  %t144 = getelementptr i64, ptr %t143, i64 3
  %r221 = load i64, ptr %t144
  %r222 = mul i64 %r219, %r221
  %t145 = getelementptr inbounds [5 x i8], ptr @.str.7, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t145, i64 %r222)
  %r85 = call i64 @Rect__contains(i64 %r75, i64 5, i64 3)
  %t146 = icmp ne i64 %r85, 0
  %t147 = getelementptr inbounds [5 x i8], ptr @.str.10, i64 0, i64 0
  %t148 = getelementptr inbounds [6 x i8], ptr @.str.11, i64 0, i64 0
  %t149 = select i1 %t146, ptr %t147, ptr %t148
  call i32 @puts(ptr %t149)
  %r90 = call i64 @Rect__contains(i64 %r75, i64 15, i64 3)
  %t150 = icmp ne i64 %r90, 0
  %t151 = getelementptr inbounds [5 x i8], ptr @.str.10, i64 0, i64 0
  %t152 = getelementptr inbounds [6 x i8], ptr @.str.11, i64 0, i64 0
  %t153 = select i1 %t150, ptr %t151, ptr %t152
  call i32 @puts(ptr %t153)
  %t154 = load i64, ptr %slot.p, align 8
  call void @nova_rc_dec(i64 %t154)
  %t155 = load i64, ptr %slot.__mb0_self, align 8
  call void @nova_rc_dec(i64 %t155)
  %t156 = load i64, ptr %slot.__mb0_other, align 8
  call void @nova_rc_dec(i64 %t156)
  %t157 = load i64, ptr %slot.__mb1_self, align 8
  call void @nova_rc_dec(i64 %t157)
  %t158 = load i64, ptr %slot.__mb1_other, align 8
  call void @nova_rc_dec(i64 %t158)
  ret i64 0
}

define i32 @main(i32 %argc, ptr %argv) nounwind {
entry:
  %argc64 = sext i32 %argc to i64
  %argv64 = ptrtoint ptr %argv to i64
  call void @nova_rt_init_args(i64 %argc64, i64 %argv64)
  call i64 @nova_main()
  call void @nova_rt_wait_all()
  call void @nova_rt_cleanup()
  ret i32 0
}

!0 = !{!"NOVA TBAA"}
!1 = !{!"list_data_ptr", !0}
!2 = !{!1, !1, i64 0}
!3 = !{!"list_elem", !0}
!4 = !{!3, !3, i64 0}
!5 = !{!"list_size", !0}
!6 = !{!5, !5, i64 0}
!7 = !{!"list_cap", !0}
!8 = !{!7, !7, i64 0}
!90 = !{!"branch_weights", i32 2000, i32 1}
!91 = distinct !{!91, !92, !93}
!92 = !{!"llvm.loop.unroll.enable"}
!93 = !{!"llvm.loop.vectorize.enable", i1 true}
