; Generated by NOVA compiler
target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"

declare i32 @printf(ptr, ...)
declare i32 @puts(ptr)
declare noalias ptr @malloc(i64) nounwind allocsize(0)
declare noalias ptr @calloc(i64, i64) nounwind
declare ptr @realloc(ptr, i64) nounwind allocsize(1)
declare void @free(ptr) nounwind
declare i64 @llvm.smax.i64(i64, i64) nounwind readnone
; nova runtime — list ops
declare i64 @nova_rt_list_create() nounwind
declare i64 @nova_rt_list_create_filled(i64, i64) nounwind
declare i64 @nova_rt_list_append(i64, i64) nounwind
declare i64 @nova_rt_list_get(i64, i64) nounwind readonly
declare i64 @nova_rt_list_set(i64, i64, i64) nounwind
declare i64 @nova_rt_list_len(i64) nounwind readonly
declare i64 @nova_rt_list_print(i64) nounwind
declare i64 @nova_rt_iter_has_next(i64, i64) nounwind readonly
declare i64 @nova_rt_iter_get(i64, i64) nounwind readonly
declare i64 @nova_rt_list_iter_has_next(i64, i64) nounwind readonly
declare i64 @nova_rt_list_iter_get(i64, i64) nounwind readonly
; nova runtime — string ops
declare i64 @nova_rt_str_concat(i64, i64) nounwind
declare i64 @nova_rt_int_to_str(i64) nounwind
declare i64 @nova_rt_float_to_str(i64) nounwind
declare i64 @nova_rt_bool_to_str(i64) nounwind
declare i64 @nova_rt_str_len(i64) nounwind readonly
declare i64 @nova_rt_len(i64) nounwind readonly
declare i64 @nova_rt_contains(i64, i64) nounwind readonly
declare i64 @nova_rt_slice(i64, i64, i64) nounwind
declare i64 @nova_rt_upper(i64) nounwind
declare i64 @nova_rt_lower(i64) nounwind
declare i64 @nova_rt_trim(i64) nounwind
declare i64 @nova_rt_repeat(i64, i64) nounwind
declare i64 @nova_rt_split(i64, i64) nounwind
declare i64 @nova_rt_replace(i64, i64, i64) nounwind
declare i64 @nova_rt_starts_with(i64, i64) nounwind readonly
declare i64 @nova_rt_ends_with(i64, i64) nounwind readonly
declare i64 @nova_rt_find(i64, i64) nounwind readonly
declare i64 @nova_rt_join(i64, i64) nounwind
declare i64 @nova_rt_chars(i64) nounwind
; nova runtime — list stdlib
declare i64 @nova_rt_list_reverse(i64) nounwind
declare i64 @nova_rt_list_sort(i64) nounwind
declare i64 @nova_rt_list_map(i64, i64) nounwind
declare i64 @nova_rt_list_filter(i64, i64) nounwind
declare i64 @nova_rt_list_concat(i64, i64) nounwind
declare i64 @nova_rt_list_slice(i64, i64, i64) nounwind
declare i64 @nova_rt_list_to_str(i64) nounwind
declare i64 @nova_rt_len_any(i64) nounwind readonly
; nova runtime — type conversions
declare i64 @nova_rt_parse_int(i64) nounwind
declare i64 @nova_rt_parse_float(i64) nounwind
; nova runtime — character ops
declare i64 @nova_rt_ord(i64) nounwind readonly
declare i64 @nova_rt_chr(i64) nounwind
; nova runtime — process control
declare void @nova_rt_exit(i64) noreturn nounwind
declare i32 @strcmp(ptr, ptr) nounwind readonly
; nova runtime — dict ops (hash map, O(1) avg lookup)
declare i64 @nova_rt_dict_create() nounwind
declare i64 @nova_rt_dict_set(i64, i64, i64) nounwind
declare i64 @nova_rt_dict_get(i64, i64) nounwind readonly
declare i64 @nova_rt_dict_get_concat2(i64, i64, i64) nounwind readonly
declare i64 @nova_rt_dict_set_concat2(i64, i64, i64, i64) nounwind
declare i64 @nova_rt_dict_has(i64, i64) nounwind readonly
declare i64 @nova_rt_dict_del(i64, i64) nounwind
declare i64 @nova_rt_dict_len(i64) nounwind readonly
declare i64 @nova_rt_dict_keys(i64) nounwind
declare i64 @nova_rt_dict_values(i64) nounwind
declare i64 @nova_rt_dict_items(i64) nounwind
; nova runtime — IO ops
declare i64 @nova_rt_read_line() nounwind
declare i64 @nova_rt_read_file(i64) nounwind
declare i64 @nova_rt_write_file(i64, i64) nounwind
declare i64 @nova_rt_append_file(i64, i64) nounwind
declare i64 @nova_rt_file_exists(i64) nounwind readonly
; nova runtime — JSON ops
declare i64 @nova_rt_json_parse(i64) nounwind
declare i64 @nova_rt_json_stringify(i64) nounwind
; nova runtime — HTTP ops
declare i64 @nova_rt_http_get(i64) nounwind
declare i64 @nova_rt_http_post(i64, i64, i64) nounwind
; nova runtime — time ops
declare i64 @nova_rt_time_ms() nounwind
declare i64 @nova_rt_clock_ns() nounwind
declare void @nova_rt_sleep_ms(i64) nounwind
declare void @nova_rt_assert(i64, i64) nounwind
; nova runtime — type dispatch
declare i64 @nova_rt_any_to_str(i64) nounwind
declare i64 @nova_rt_str_concat_safe(i64, i64) nounwind
declare i64 @nova_rt_str_char_at(i64, i64) nounwind
declare void @nova_rt_init() nounwind
declare void @nova_rt_init_args(i64, i64) nounwind
; nova runtime — system ops
declare i64 @nova_rt_args() nounwind
declare i64 @nova_rt_env(i64) nounwind
declare i64 @nova_rt_random_int(i64, i64) nounwind
declare i64 @nova_rt_random_float() nounwind
declare i64 @nova_rt_shell(i64) nounwind
declare i64 @nova_rt_path_join(i64, i64) nounwind
declare i64 @nova_rt_path_parent(i64) nounwind
declare i64 @nova_rt_path_name(i64) nounwind
declare i64 @nova_rt_path_ext(i64) nounwind
; nova runtime — regex ops
declare i64 @nova_rt_regex_match(i64, i64) nounwind readonly
declare i64 @nova_rt_regex_find(i64, i64) nounwind
declare i64 @nova_rt_regex_replace(i64, i64, i64) nounwind
declare i64 @nova_rt_regex_split(i64, i64) nounwind
; nova runtime — network ops
declare i64 @nova_rt_tcp_connect(i64, i64) nounwind
declare i64 @nova_rt_tcp_listen(i64) nounwind
declare i64 @nova_rt_tcp_accept(i64) nounwind
declare i64 @nova_rt_tcp_send(i64, i64) nounwind
declare i64 @nova_rt_tcp_recv(i64) nounwind
declare void @nova_rt_tcp_close(i64) nounwind
declare i64 @nova_rt_udp_bind(i64) nounwind
declare i64 @nova_rt_udp_send(i64, i64, i64, i64) nounwind
declare i64 @nova_rt_udp_recv(i64) nounwind
; nova runtime — HTTP server
declare i64 @nova_rt_http_listen(i64) nounwind
declare i64 @nova_rt_http_accept(i64) nounwind
declare void @nova_rt_http_respond(i64, i64, i64) nounwind
; nova runtime — byte arrays
declare i64 @nova_rt_bytes_create(i64) nounwind
declare i64 @nova_rt_bytes_get(i64, i64) nounwind
declare void @nova_rt_bytes_set(i64, i64, i64) nounwind
declare i64 @nova_rt_bytes_len(i64) nounwind
declare i64 @nova_rt_bytes_slice(i64, i64, i64) nounwind
declare i64 @nova_rt_bytes_to_str(i64) nounwind
declare i64 @nova_rt_str_to_bytes(i64) nounwind
; nova runtime — channel/spawn ops
declare i64 @nova_rt_channel_create() nounwind
declare i64 @nova_rt_channel_send(i64, i64) nounwind
declare i64 @nova_rt_channel_recv(i64) nounwind
declare i64 @nova_rt_channel_close(i64) nounwind
declare i64 @nova_rt_channel_select(i64, i64) nounwind
declare i64 @nova_rt_channel_recv_timeout(i64, i64) nounwind
declare i64 @nova_rt_spawn(i64, i64) nounwind
declare i64 @nova_rt_monitor(i64) nounwind
declare void @nova_rt_wait_all() nounwind
; nova runtime — math (trig/log via C runtime for non-intrinsic functions)
declare i64 @nova_rt_tan(i64) nounwind
declare i64 @nova_rt_asin(i64) nounwind
declare i64 @nova_rt_acos(i64) nounwind
declare i64 @nova_rt_atan(i64) nounwind
declare i64 @nova_rt_atan2(i64, i64) nounwind
declare i64 @nova_rt_fmod(i64, i64) nounwind
declare i64 @nova_rt_int_pow(i64, i64) nounwind
; nova runtime — memory management
declare void @nova_rt_cleanup() nounwind
declare void @nova_rt_track_raw(ptr) nounwind
declare i64 @nova_rt_alloc_count() nounwind readonly
declare i64 @nova_rt_live_count() nounwind readonly
; nova runtime — reference counting
declare void @nova_rc_inc(i64) nounwind
declare void @nova_rc_dec(i64) nounwind
; nova error state — thread-local flag (safe for spawn/concurrent programs)
@__nova_error_flag = thread_local global i64 0
@__nova_error_msg = thread_local global i64 0

@.str.0 = private unnamed_addr constant [2 x i8] c" \00"
@.str.1 = private unnamed_addr constant [2 x i8] c"\0A\00"
@.str.2 = private unnamed_addr constant [2 x i8] c"/\00"
@.str.3 = private unnamed_addr constant [2 x i8] c"\22\00"
@.str.4 = private unnamed_addr constant [1 x i8] c"\00"
@.str.5 = private unnamed_addr constant [2 x i8] c"=\00"
@.str.6 = private unnamed_addr constant [2 x i8] c"\\\00"
@.str.7 = private unnamed_addr constant [2 x i8] c"n\00"
@.str.8 = private unnamed_addr constant [2 x i8] c"t\00"
@.str.9 = private unnamed_addr constant [2 x i8] c"\09\00"
@.str.10 = private unnamed_addr constant [2 x i8] c">\00"
@.str.11 = private unnamed_addr constant [3 x i8] c"=>\00"
@.str.12 = private unnamed_addr constant [2 x i8] c"!\00"
@.str.13 = private unnamed_addr constant [3 x i8] c"!=\00"
@.str.14 = private unnamed_addr constant [2 x i8] c"<\00"
@.str.15 = private unnamed_addr constant [3 x i8] c"<=\00"
@.str.16 = private unnamed_addr constant [3 x i8] c">=\00"
@.str.17 = private unnamed_addr constant [138 x i8] c"fn hello(name)\0A    // greet\0A    let msg = \22Hello \22 + name\0A    if x >= 10 and y != 5\0A        return msg\0A    else\0A        return \22default\22\0A\00"
@.str.18 = private unnamed_addr constant [5 x i8] c"DONE\00"
@.str.19 = private unnamed_addr constant [6 x i8] c"%lld\0A\00"
@.str.20 = private unnamed_addr constant [4 x i8] c"%f\0A\00"
@.str.21 = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.str.22 = private unnamed_addr constant [5 x i8] c"true\00"
@.str.23 = private unnamed_addr constant [6 x i8] c"false\00"

define i64 @tokenize_heavy(i64 %p0) nounwind {
entry0:
  %slot.source = alloca i64, align 8
  %slot.tokens = alloca i64, align 8
  %slot.pos = alloca i64, align 8
  %slot.length = alloca i64, align 8
  %slot.ch = alloca i64, align 8
  %slot.s = alloca i64, align 8
  %slot.esc = alloca i64, align 8
  %slot.word = alloca i64, align 8
  %slot.__ifb_2 = alloca i64, align 8
  %slot.__sc_and_0 = alloca i64, align 8
  %slot.__ifb_4 = alloca i64, align 8
  %slot.__ifb_3 = alloca i64, align 8
  %slot.__sc_and_1 = alloca i64, align 8
  %slot.__sc_and_3 = alloca i64, align 8
  %slot.__sc_and_2 = alloca i64, align 8
  %slot.__ifb_7 = alloca i64, align 8
  %slot.__ifb_8 = alloca i64, align 8
  %slot.__sc_and_4 = alloca i64, align 8
  %slot.__ifb_10 = alloca i64, align 8
  %slot.__sc_and_5 = alloca i64, align 8
  %slot.__sc_and_6 = alloca i64, align 8
  %slot.__ifb_11 = alloca i64, align 8
  %slot.__sc_and_7 = alloca i64, align 8
  %slot.__sc_and_8 = alloca i64, align 8
  %slot.__ifb_12 = alloca i64, align 8
  %slot.__sc_and_9 = alloca i64, align 8
  %slot.__sc_and_10 = alloca i64, align 8
  %slot.__ifb_13 = alloca i64, align 8
  %slot.__sc_and_11 = alloca i64, align 8
  %slot.__sc_and_12 = alloca i64, align 8
  store i64 0, ptr %slot.tokens, align 8
  store i64 0, ptr %slot.ch, align 8
  store i64 0, ptr %slot.__ifb_2, align 8
  store i64 0, ptr %slot.s, align 8
  store i64 0, ptr %slot.esc, align 8
  store i64 0, ptr %slot.__ifb_7, align 8
  store i64 0, ptr %slot.__ifb_4, align 8
  store i64 0, ptr %slot.__ifb_10, align 8
  store i64 0, ptr %slot.__ifb_11, align 8
  store i64 0, ptr %slot.word, align 8
  store i64 0, ptr %slot.__ifb_12, align 8
  store i64 0, ptr %slot.__ifb_13, align 8
  store i64 %p0, ptr %slot.source, align 8
  %r4 = call i64 @nova_rt_list_create()
  %t0 = load i64, ptr %slot.tokens, align 8
  call void @nova_rc_dec(i64 %t0)
  store i64 %r4, ptr %slot.tokens, align 8
  store i64 0, ptr %slot.pos, align 8
  %r15 = call i64 @nova_rt_len(i64 %p0)
  store i64 %r15, ptr %slot.length, align 8
  %r464 = load i64, ptr %slot.length, align 8
  %r465 = load i64, ptr %slot.source, align 8
  %r466 = load i64, ptr %slot.tokens, align 8
  br label %while_header1

while_header1:
  %r19 = load i64, ptr %slot.pos, align 8
  %t1 = icmp slt i64 %r19, %r464
  br i1 %t1, label %while_body2, label %while_exit3, !prof !90

while_body2:
  %r25 = load i64, ptr %slot.pos, align 8
  %r26 = call i64 @nova_rt_str_char_at(i64 %r465, i64 %r25)
  %t2 = load i64, ptr %slot.ch, align 8
  call void @nova_rc_dec(i64 %t2)
  call void @nova_rc_inc(i64 %r26)
  store i64 %r26, ptr %slot.ch, align 8
  %t3 = getelementptr inbounds [2 x i8], ptr @.str.0, i64 0, i64 0
  %r31 = ptrtoint ptr %t3 to i64
  %t4 = inttoptr i64 %r26 to ptr
  %t5 = inttoptr i64 %r31 to ptr
  %t6 = call i32 @strcmp(ptr %t4, ptr %t5)
  %t7 = icmp eq i32 %t6, 0
  br i1 %t7, label %ifb_then4, label %ifb_else5

while_exit3:
  %r463 = load i64, ptr %slot.tokens, align 8
  call void @nova_rc_inc(i64 %r463)
  %t8 = load i64, ptr %slot.tokens, align 8
  call void @nova_rc_dec(i64 %t8)
  %t9 = load i64, ptr %slot.ch, align 8
  call void @nova_rc_dec(i64 %t9)
  %t10 = load i64, ptr %slot.__ifb_2, align 8
  call void @nova_rc_dec(i64 %t10)
  %t11 = load i64, ptr %slot.s, align 8
  call void @nova_rc_dec(i64 %t11)
  %t12 = load i64, ptr %slot.esc, align 8
  call void @nova_rc_dec(i64 %t12)
  %t13 = load i64, ptr %slot.__ifb_7, align 8
  call void @nova_rc_dec(i64 %t13)
  %t14 = load i64, ptr %slot.__ifb_4, align 8
  call void @nova_rc_dec(i64 %t14)
  %t15 = load i64, ptr %slot.__ifb_10, align 8
  call void @nova_rc_dec(i64 %t15)
  %t16 = load i64, ptr %slot.__ifb_11, align 8
  call void @nova_rc_dec(i64 %t16)
  %t17 = load i64, ptr %slot.word, align 8
  call void @nova_rc_dec(i64 %t17)
  %t18 = load i64, ptr %slot.__ifb_12, align 8
  call void @nova_rc_dec(i64 %t18)
  %t19 = load i64, ptr %slot.__ifb_13, align 8
  call void @nova_rc_dec(i64 %t19)
  ret i64 %r463

ifb_then4:
  %r35 = load i64, ptr %slot.pos, align 8
  %r37 = add i64 %r35, 1
  store i64 %r37, ptr %slot.pos, align 8
  br label %ifb_merge6

ifb_else5:
  %r41 = load i64, ptr %slot.ch, align 8
  %t20 = getelementptr inbounds [2 x i8], ptr @.str.1, i64 0, i64 0
  %r42 = ptrtoint ptr %t20 to i64
  %t21 = inttoptr i64 %r41 to ptr
  %t22 = inttoptr i64 %r42 to ptr
  %t23 = call i32 @strcmp(ptr %t21, ptr %t22)
  %t24 = icmp eq i32 %t23, 0
  br i1 %t24, label %ifb_then7, label %ifb_else8

ifb_merge6:
  br label %while_header1, !llvm.loop !91

ifb_then7:
  %r46 = load i64, ptr %slot.pos, align 8
  %r48 = add i64 %r46, 1
  store i64 %r48, ptr %slot.pos, align 8
  br label %ifb_merge9

ifb_else8:
  %r52 = load i64, ptr %slot.ch, align 8
  %t25 = getelementptr inbounds [2 x i8], ptr @.str.2, i64 0, i64 0
  %r53 = ptrtoint ptr %t25 to i64
  %t26 = inttoptr i64 %r52 to ptr
  %t27 = inttoptr i64 %r53 to ptr
  %t28 = call i32 @strcmp(ptr %t26, ptr %t27)
  %t29 = icmp eq i32 %t28, 0
  br i1 %t29, label %ifb_then10, label %ifb_else11

ifb_merge9:
  br label %ifb_merge6, !llvm.loop !91

ifb_then10:
  %r57 = load i64, ptr %slot.pos, align 8
  %r59 = add i64 %r57, 1
  %t30 = icmp slt i64 %r59, %r464
  %r61 = zext i1 %t30 to i64
  store i64 0, ptr %slot.__sc_and_0, align 8
  %t31 = icmp ne i64 %r61, 0
  br i1 %t31, label %sc_and_right13, label %sc_and_merge14

ifb_else11:
  %r110 = load i64, ptr %slot.ch, align 8
  %t32 = getelementptr inbounds [2 x i8], ptr @.str.3, i64 0, i64 0
  %r111 = ptrtoint ptr %t32 to i64
  %t33 = inttoptr i64 %r110 to ptr
  %t34 = inttoptr i64 %r111 to ptr
  %t35 = call i32 @strcmp(ptr %t33, ptr %t34)
  %t36 = icmp eq i32 %t35, 0
  br i1 %t36, label %ifb_then23, label %ifb_else24

ifb_merge12:
  %r457 = load i64, ptr %slot.__ifb_2, align 8
  br label %ifb_merge9, !llvm.loop !91

sc_and_right13:
  %r68 = load i64, ptr %slot.pos, align 8
  %r70 = add i64 %r68, 1
  %r71 = call i64 @nova_rt_str_char_at(i64 %r465, i64 %r70)
  %t37 = getelementptr inbounds [2 x i8], ptr @.str.2, i64 0, i64 0
  %r72 = ptrtoint ptr %t37 to i64
  %t38 = inttoptr i64 %r71 to ptr
  %t39 = inttoptr i64 %r72 to ptr
  %t40 = call i32 @strcmp(ptr %t38, ptr %t39)
  %t41 = icmp eq i32 %t40, 0
  %r73 = zext i1 %t41 to i64
  store i64 %r73, ptr %slot.__sc_and_0, align 8
  br label %sc_and_merge14

sc_and_merge14:
  %r75 = load i64, ptr %slot.__sc_and_0, align 8
  %t42 = trunc i64 %r75 to i1
  br i1 %t42, label %ifb_then15, label %ifb_else16

ifb_then15:
  br label %while_header18

ifb_else16:
  %r102 = load i64, ptr %slot.pos, align 8
  %r104 = add i64 %r102, 1
  store i64 %r104, ptr %slot.pos, align 8
  store i64 0, ptr %slot.__ifb_3, align 8
  br label %ifb_merge17

ifb_merge17:
  %r108 = load i64, ptr %slot.__ifb_3, align 8
  %t43 = load i64, ptr %slot.__ifb_2, align 8
  call void @nova_rc_dec(i64 %t43)
  call void @nova_rc_inc(i64 %r108)
  store i64 %r108, ptr %slot.__ifb_2, align 8
  br label %ifb_merge12, !llvm.loop !91

while_header18:
  %r78 = load i64, ptr %slot.pos, align 8
  %t44 = icmp slt i64 %r78, %r464
  %r80 = zext i1 %t44 to i64
  store i64 0, ptr %slot.__sc_and_1, align 8
  %t45 = icmp ne i64 %r80, 0
  br i1 %t45, label %sc_and_right21, label %sc_and_merge22, !prof !90

while_body19:
  %r94 = load i64, ptr %slot.pos, align 8
  %r96 = add i64 %r94, 1
  store i64 %r96, ptr %slot.pos, align 8
  br label %while_header18, !llvm.loop !91

while_exit20:
  store i64 0, ptr %slot.__ifb_3, align 8
  br label %ifb_merge17, !llvm.loop !91

sc_and_right21:
  %r87 = load i64, ptr %slot.pos, align 8
  %r88 = call i64 @nova_rt_str_char_at(i64 %r465, i64 %r87)
  %t46 = getelementptr inbounds [2 x i8], ptr @.str.1, i64 0, i64 0
  %r89 = ptrtoint ptr %t46 to i64
  %t47 = inttoptr i64 %r88 to ptr
  %t48 = inttoptr i64 %r89 to ptr
  %t49 = call i32 @strcmp(ptr %t47, ptr %t48)
  %t50 = icmp ne i32 %t49, 0
  %r90 = zext i1 %t50 to i64
  store i64 %r90, ptr %slot.__sc_and_1, align 8
  br label %sc_and_merge22

sc_and_merge22:
  %r92 = load i64, ptr %slot.__sc_and_1, align 8
  %t51 = trunc i64 %r92 to i1
  br i1 %t51, label %while_body19, label %while_exit20

ifb_then23:
  %r115 = load i64, ptr %slot.pos, align 8
  %r117 = add i64 %r115, 1
  store i64 %r117, ptr %slot.pos, align 8
  %t52 = getelementptr inbounds [1 x i8], ptr @.str.4, i64 0, i64 0
  %r121 = ptrtoint ptr %t52 to i64
  %t53 = load i64, ptr %slot.s, align 8
  call void @nova_rc_dec(i64 %t53)
  store i64 %r121, ptr %slot.s, align 8
  br label %while_header26

ifb_else24:
  %r236 = load i64, ptr %slot.ch, align 8
  %t54 = getelementptr inbounds [2 x i8], ptr @.str.5, i64 0, i64 0
  %r237 = ptrtoint ptr %t54 to i64
  %t55 = inttoptr i64 %r236 to ptr
  %t56 = inttoptr i64 %r237 to ptr
  %t57 = call i32 @strcmp(ptr %t55, ptr %t56)
  %t58 = icmp eq i32 %t57, 0
  %r238 = zext i1 %t58 to i64
  store i64 0, ptr %slot.__sc_and_3, align 8
  %t59 = icmp ne i64 %r238, 0
  br i1 %t59, label %sc_and_right46, label %sc_and_merge47

ifb_merge25:
  %r455 = load i64, ptr %slot.__ifb_4, align 8
  %t60 = load i64, ptr %slot.__ifb_2, align 8
  call void @nova_rc_dec(i64 %t60)
  call void @nova_rc_inc(i64 %r455)
  store i64 %r455, ptr %slot.__ifb_2, align 8
  br label %ifb_merge12, !llvm.loop !91

while_header26:
  %r125 = load i64, ptr %slot.pos, align 8
  %t61 = icmp slt i64 %r125, %r464
  %r127 = zext i1 %t61 to i64
  store i64 0, ptr %slot.__sc_and_2, align 8
  %t62 = icmp ne i64 %r127, 0
  br i1 %t62, label %sc_and_right29, label %sc_and_merge30, !prof !90

while_body27:
  %r142 = load i64, ptr %slot.pos, align 8
  %r143 = call i64 @nova_rt_str_char_at(i64 %r465, i64 %r142)
  %t63 = getelementptr inbounds [2 x i8], ptr @.str.6, i64 0, i64 0
  %r144 = ptrtoint ptr %t63 to i64
  %t64 = inttoptr i64 %r143 to ptr
  %t65 = inttoptr i64 %r144 to ptr
  %t66 = call i32 @strcmp(ptr %t64, ptr %t65)
  %t67 = icmp eq i32 %t66, 0
  br i1 %t67, label %ifb_then31, label %ifb_else32, !prof !90

while_exit28:
  %r218 = load i64, ptr %slot.pos, align 8
  %t68 = icmp slt i64 %r218, %r464
  br i1 %t68, label %ifb_then43, label %ifb_else44, !prof !90

sc_and_right29:
  %r134 = load i64, ptr %slot.pos, align 8
  %r135 = call i64 @nova_rt_str_char_at(i64 %r465, i64 %r134)
  %t69 = getelementptr inbounds [2 x i8], ptr @.str.3, i64 0, i64 0
  %r136 = ptrtoint ptr %t69 to i64
  %t70 = inttoptr i64 %r135 to ptr
  %t71 = inttoptr i64 %r136 to ptr
  %t72 = call i32 @strcmp(ptr %t70, ptr %t71)
  %t73 = icmp ne i32 %t72, 0
  %r137 = zext i1 %t73 to i64
  store i64 %r137, ptr %slot.__sc_and_2, align 8
  br label %sc_and_merge30

sc_and_merge30:
  %r139 = load i64, ptr %slot.__sc_and_2, align 8
  %t74 = trunc i64 %r139 to i1
  br i1 %t74, label %while_body27, label %while_exit28

ifb_then31:
  %r148 = load i64, ptr %slot.pos, align 8
  %r150 = add i64 %r148, 1
  store i64 %r150, ptr %slot.pos, align 8
  %t75 = icmp slt i64 %r150, %r464
  br i1 %t75, label %ifb_then34, label %ifb_else35

ifb_else32:
  %r203 = load i64, ptr %slot.s, align 8
  %r205 = load i64, ptr %slot.pos, align 8
  %r206 = call i64 @nova_rt_str_char_at(i64 %r465, i64 %r205)
  %t76 = call i64 @nova_rt_str_concat(i64 %r203, i64 %r206)
  %t77 = load i64, ptr %slot.s, align 8
  call void @nova_rc_dec(i64 %t77)
  store i64 %t76, ptr %slot.s, align 8
  br label %ifb_merge33

ifb_merge33:
  %r212 = load i64, ptr %slot.pos, align 8
  %r214 = add i64 %r212, 1
  store i64 %r214, ptr %slot.pos, align 8
  br label %while_header26, !llvm.loop !91

ifb_then34:
  %r160 = load i64, ptr %slot.pos, align 8
  %r161 = call i64 @nova_rt_str_char_at(i64 %r465, i64 %r160)
  %t78 = load i64, ptr %slot.esc, align 8
  call void @nova_rc_dec(i64 %t78)
  call void @nova_rc_inc(i64 %r161)
  store i64 %r161, ptr %slot.esc, align 8
  %t79 = getelementptr inbounds [2 x i8], ptr @.str.7, i64 0, i64 0
  %r166 = ptrtoint ptr %t79 to i64
  %t80 = inttoptr i64 %r161 to ptr
  %t81 = inttoptr i64 %r166 to ptr
  %t82 = call i32 @strcmp(ptr %t80, ptr %t81)
  %t83 = icmp eq i32 %t82, 0
  br i1 %t83, label %ifb_then37, label %ifb_else38

ifb_else35:
  br label %ifb_merge36

ifb_merge36:
  br label %ifb_merge33, !llvm.loop !91

ifb_then37:
  %r170 = load i64, ptr %slot.s, align 8
  %t84 = getelementptr inbounds [2 x i8], ptr @.str.1, i64 0, i64 0
  %r171 = ptrtoint ptr %t84 to i64
  %t85 = call i64 @nova_rt_str_concat(i64 %r170, i64 %r171)
  %t86 = load i64, ptr %slot.s, align 8
  call void @nova_rc_dec(i64 %t86)
  store i64 %t85, ptr %slot.s, align 8
  store i64 0, ptr %slot.__ifb_7, align 8
  br label %ifb_merge39

ifb_else38:
  %r176 = load i64, ptr %slot.esc, align 8
  %t87 = getelementptr inbounds [2 x i8], ptr @.str.8, i64 0, i64 0
  %r177 = ptrtoint ptr %t87 to i64
  %t88 = inttoptr i64 %r176 to ptr
  %t89 = inttoptr i64 %r177 to ptr
  %t90 = call i32 @strcmp(ptr %t88, ptr %t89)
  %t91 = icmp eq i32 %t90, 0
  br i1 %t91, label %ifb_then40, label %ifb_else41

ifb_merge39:
  %r196 = load i64, ptr %slot.__ifb_7, align 8
  br label %ifb_merge36, !llvm.loop !91

ifb_then40:
  %r181 = load i64, ptr %slot.s, align 8
  %t92 = getelementptr inbounds [2 x i8], ptr @.str.9, i64 0, i64 0
  %r182 = ptrtoint ptr %t92 to i64
  %t93 = call i64 @nova_rt_str_concat(i64 %r181, i64 %r182)
  %t94 = load i64, ptr %slot.s, align 8
  call void @nova_rc_dec(i64 %t94)
  store i64 %t93, ptr %slot.s, align 8
  store i64 0, ptr %slot.__ifb_8, align 8
  br label %ifb_merge42

ifb_else41:
  %r188 = load i64, ptr %slot.s, align 8
  %r189 = load i64, ptr %slot.esc, align 8
  %t95 = call i64 @nova_rt_str_concat(i64 %r188, i64 %r189)
  %t96 = load i64, ptr %slot.s, align 8
  call void @nova_rc_dec(i64 %t96)
  store i64 %t95, ptr %slot.s, align 8
  store i64 0, ptr %slot.__ifb_8, align 8
  br label %ifb_merge42

ifb_merge42:
  %r194 = load i64, ptr %slot.__ifb_8, align 8
  %t97 = load i64, ptr %slot.__ifb_7, align 8
  call void @nova_rc_dec(i64 %t97)
  call void @nova_rc_inc(i64 %r194)
  store i64 %r194, ptr %slot.__ifb_7, align 8
  br label %ifb_merge39, !llvm.loop !91

ifb_then43:
  %r223 = load i64, ptr %slot.pos, align 8
  %r225 = add i64 %r223, 1
  store i64 %r225, ptr %slot.pos, align 8
  br label %ifb_merge45

ifb_else44:
  br label %ifb_merge45

ifb_merge45:
  %r233 = load i64, ptr %slot.s, align 8
  %t98 = inttoptr i64 %r466 to ptr
  %t99 = getelementptr i64, ptr %t98, i64 1
  %t100 = getelementptr i64, ptr %t98, i64 2
  %t101 = load i64, ptr %t99, align 8, !tbaa !6
  %t102 = load i64, ptr %t100, align 8, !tbaa !8
  %t103 = icmp sge i64 %t101, %t102
  br i1 %t103, label %list_grow_104, label %list_append_104

list_grow_104:
  %t104 = shl i64 %t102, 1
  %t105 = shl i64 %t104, 3
  %t106 = load ptr, ptr %t98, align 8, !tbaa !2
  %t107 = call ptr @realloc(ptr %t106, i64 %t105)
  store ptr %t107, ptr %t98, align 8, !tbaa !2
  store i64 %t104, ptr %t100, align 8, !tbaa !8
  br label %list_append_104

list_append_104:
  %t108 = load ptr, ptr %t98, align 8, !tbaa !2
  %t109 = getelementptr i64, ptr %t108, i64 %t101
  store i64 %r233, ptr %t109, align 8, !tbaa !4
  call void @nova_rc_inc(i64 %r233)
  %t110 = add i64 %t101, 1
  store i64 %t110, ptr %t99, align 8, !tbaa !6
  %t111 = load i64, ptr %slot.__ifb_4, align 8
  call void @nova_rc_dec(i64 %t111)
  store i64 0, ptr %slot.__ifb_4, align 8
  br label %ifb_merge25, !llvm.loop !91

sc_and_right46:
  %r244 = load i64, ptr %slot.pos, align 8
  %r246 = add i64 %r244, 1
  %t112 = icmp slt i64 %r246, %r464
  %r248 = zext i1 %t112 to i64
  store i64 %r248, ptr %slot.__sc_and_3, align 8
  br label %sc_and_merge47

sc_and_merge47:
  %r250 = load i64, ptr %slot.__sc_and_3, align 8
  store i64 0, ptr %slot.__sc_and_4, align 8
  %t113 = icmp ne i64 %r250, 0
  br i1 %t113, label %sc_and_right48, label %sc_and_merge49

sc_and_right48:
  %r257 = load i64, ptr %slot.pos, align 8
  %r259 = add i64 %r257, 1
  %r260 = call i64 @nova_rt_str_char_at(i64 %r465, i64 %r259)
  %t114 = getelementptr inbounds [2 x i8], ptr @.str.10, i64 0, i64 0
  %r261 = ptrtoint ptr %t114 to i64
  %t115 = inttoptr i64 %r260 to ptr
  %t116 = inttoptr i64 %r261 to ptr
  %t117 = call i32 @strcmp(ptr %t115, ptr %t116)
  %t118 = icmp eq i32 %t117, 0
  %r262 = zext i1 %t118 to i64
  store i64 %r262, ptr %slot.__sc_and_4, align 8
  br label %sc_and_merge49

sc_and_merge49:
  %r264 = load i64, ptr %slot.__sc_and_4, align 8
  %t119 = trunc i64 %r264 to i1
  br i1 %t119, label %ifb_then50, label %ifb_else51

ifb_then50:
  %t120 = getelementptr inbounds [3 x i8], ptr @.str.11, i64 0, i64 0
  %r268 = ptrtoint ptr %t120 to i64
  %t121 = inttoptr i64 %r466 to ptr
  %t122 = getelementptr i64, ptr %t121, i64 1
  %t123 = getelementptr i64, ptr %t121, i64 2
  %t124 = load i64, ptr %t122, align 8, !tbaa !6
  %t125 = load i64, ptr %t123, align 8, !tbaa !8
  %t126 = icmp sge i64 %t124, %t125
  br i1 %t126, label %list_grow_127, label %list_append_127

list_grow_127:
  %t127 = shl i64 %t125, 1
  %t128 = shl i64 %t127, 3
  %t129 = load ptr, ptr %t121, align 8, !tbaa !2
  %t130 = call ptr @realloc(ptr %t129, i64 %t128)
  store ptr %t130, ptr %t121, align 8, !tbaa !2
  store i64 %t127, ptr %t123, align 8, !tbaa !8
  br label %list_append_127

list_append_127:
  %t131 = load ptr, ptr %t121, align 8, !tbaa !2
  %t132 = getelementptr i64, ptr %t131, i64 %t124
  store i64 %r268, ptr %t132, align 8, !tbaa !4
  call void @nova_rc_inc(i64 %r268)
  %t133 = add i64 %t124, 1
  store i64 %t133, ptr %t122, align 8, !tbaa !6
  %r270 = load i64, ptr %slot.pos, align 8
  %r272 = add i64 %r270, 2
  store i64 %r272, ptr %slot.pos, align 8
  store i64 0, ptr %slot.__ifb_10, align 8
  br label %ifb_merge52

ifb_else51:
  %r276 = load i64, ptr %slot.ch, align 8
  %t134 = getelementptr inbounds [2 x i8], ptr @.str.12, i64 0, i64 0
  %r277 = ptrtoint ptr %t134 to i64
  %t135 = inttoptr i64 %r276 to ptr
  %t136 = inttoptr i64 %r277 to ptr
  %t137 = call i32 @strcmp(ptr %t135, ptr %t136)
  %t138 = icmp eq i32 %t137, 0
  %r278 = zext i1 %t138 to i64
  store i64 0, ptr %slot.__sc_and_5, align 8
  %t139 = icmp ne i64 %r278, 0
  br i1 %t139, label %sc_and_right53, label %sc_and_merge54

ifb_merge52:
  %r453 = load i64, ptr %slot.__ifb_10, align 8
  %t140 = load i64, ptr %slot.__ifb_4, align 8
  call void @nova_rc_dec(i64 %t140)
  call void @nova_rc_inc(i64 %r453)
  store i64 %r453, ptr %slot.__ifb_4, align 8
  br label %ifb_merge25, !llvm.loop !91

sc_and_right53:
  %r284 = load i64, ptr %slot.pos, align 8
  %r286 = add i64 %r284, 1
  %t141 = icmp slt i64 %r286, %r464
  %r288 = zext i1 %t141 to i64
  store i64 %r288, ptr %slot.__sc_and_5, align 8
  br label %sc_and_merge54

sc_and_merge54:
  %r290 = load i64, ptr %slot.__sc_and_5, align 8
  store i64 0, ptr %slot.__sc_and_6, align 8
  %t142 = icmp ne i64 %r290, 0
  br i1 %t142, label %sc_and_right55, label %sc_and_merge56

sc_and_right55:
  %r297 = load i64, ptr %slot.pos, align 8
  %r299 = add i64 %r297, 1
  %r300 = call i64 @nova_rt_str_char_at(i64 %r465, i64 %r299)
  %t143 = getelementptr inbounds [2 x i8], ptr @.str.5, i64 0, i64 0
  %r301 = ptrtoint ptr %t143 to i64
  %t144 = inttoptr i64 %r300 to ptr
  %t145 = inttoptr i64 %r301 to ptr
  %t146 = call i32 @strcmp(ptr %t144, ptr %t145)
  %t147 = icmp eq i32 %t146, 0
  %r302 = zext i1 %t147 to i64
  store i64 %r302, ptr %slot.__sc_and_6, align 8
  br label %sc_and_merge56

sc_and_merge56:
  %r304 = load i64, ptr %slot.__sc_and_6, align 8
  %t148 = trunc i64 %r304 to i1
  br i1 %t148, label %ifb_then57, label %ifb_else58

ifb_then57:
  %t149 = getelementptr inbounds [3 x i8], ptr @.str.13, i64 0, i64 0
  %r308 = ptrtoint ptr %t149 to i64
  %t150 = inttoptr i64 %r466 to ptr
  %t151 = getelementptr i64, ptr %t150, i64 1
  %t152 = getelementptr i64, ptr %t150, i64 2
  %t153 = load i64, ptr %t151, align 8, !tbaa !6
  %t154 = load i64, ptr %t152, align 8, !tbaa !8
  %t155 = icmp sge i64 %t153, %t154
  br i1 %t155, label %list_grow_156, label %list_append_156

list_grow_156:
  %t156 = shl i64 %t154, 1
  %t157 = shl i64 %t156, 3
  %t158 = load ptr, ptr %t150, align 8, !tbaa !2
  %t159 = call ptr @realloc(ptr %t158, i64 %t157)
  store ptr %t159, ptr %t150, align 8, !tbaa !2
  store i64 %t156, ptr %t152, align 8, !tbaa !8
  br label %list_append_156

list_append_156:
  %t160 = load ptr, ptr %t150, align 8, !tbaa !2
  %t161 = getelementptr i64, ptr %t160, i64 %t153
  store i64 %r308, ptr %t161, align 8, !tbaa !4
  call void @nova_rc_inc(i64 %r308)
  %t162 = add i64 %t153, 1
  store i64 %t162, ptr %t151, align 8, !tbaa !6
  %r310 = load i64, ptr %slot.pos, align 8
  %r312 = add i64 %r310, 2
  store i64 %r312, ptr %slot.pos, align 8
  store i64 0, ptr %slot.__ifb_11, align 8
  br label %ifb_merge59

ifb_else58:
  %r316 = load i64, ptr %slot.ch, align 8
  %t163 = getelementptr inbounds [2 x i8], ptr @.str.14, i64 0, i64 0
  %r317 = ptrtoint ptr %t163 to i64
  %t164 = inttoptr i64 %r316 to ptr
  %t165 = inttoptr i64 %r317 to ptr
  %t166 = call i32 @strcmp(ptr %t164, ptr %t165)
  %t167 = icmp eq i32 %t166, 0
  %r318 = zext i1 %t167 to i64
  store i64 0, ptr %slot.__sc_and_7, align 8
  %t168 = icmp ne i64 %r318, 0
  br i1 %t168, label %sc_and_right60, label %sc_and_merge61

ifb_merge59:
  %r451 = load i64, ptr %slot.__ifb_11, align 8
  %t169 = load i64, ptr %slot.__ifb_10, align 8
  call void @nova_rc_dec(i64 %t169)
  call void @nova_rc_inc(i64 %r451)
  store i64 %r451, ptr %slot.__ifb_10, align 8
  br label %ifb_merge52, !llvm.loop !91

sc_and_right60:
  %r324 = load i64, ptr %slot.pos, align 8
  %r326 = add i64 %r324, 1
  %t170 = icmp slt i64 %r326, %r464
  %r328 = zext i1 %t170 to i64
  store i64 %r328, ptr %slot.__sc_and_7, align 8
  br label %sc_and_merge61

sc_and_merge61:
  %r330 = load i64, ptr %slot.__sc_and_7, align 8
  store i64 0, ptr %slot.__sc_and_8, align 8
  %t171 = icmp ne i64 %r330, 0
  br i1 %t171, label %sc_and_right62, label %sc_and_merge63

sc_and_right62:
  %r337 = load i64, ptr %slot.pos, align 8
  %r339 = add i64 %r337, 1
  %r340 = call i64 @nova_rt_str_char_at(i64 %r465, i64 %r339)
  %t172 = getelementptr inbounds [2 x i8], ptr @.str.5, i64 0, i64 0
  %r341 = ptrtoint ptr %t172 to i64
  %t173 = inttoptr i64 %r340 to ptr
  %t174 = inttoptr i64 %r341 to ptr
  %t175 = call i32 @strcmp(ptr %t173, ptr %t174)
  %t176 = icmp eq i32 %t175, 0
  %r342 = zext i1 %t176 to i64
  store i64 %r342, ptr %slot.__sc_and_8, align 8
  br label %sc_and_merge63

sc_and_merge63:
  %r344 = load i64, ptr %slot.__sc_and_8, align 8
  %t177 = trunc i64 %r344 to i1
  br i1 %t177, label %ifb_then64, label %ifb_else65

ifb_then64:
  %t178 = getelementptr inbounds [3 x i8], ptr @.str.15, i64 0, i64 0
  %r348 = ptrtoint ptr %t178 to i64
  %t179 = inttoptr i64 %r466 to ptr
  %t180 = getelementptr i64, ptr %t179, i64 1
  %t181 = getelementptr i64, ptr %t179, i64 2
  %t182 = load i64, ptr %t180, align 8, !tbaa !6
  %t183 = load i64, ptr %t181, align 8, !tbaa !8
  %t184 = icmp sge i64 %t182, %t183
  br i1 %t184, label %list_grow_185, label %list_append_185

list_grow_185:
  %t185 = shl i64 %t183, 1
  %t186 = shl i64 %t185, 3
  %t187 = load ptr, ptr %t179, align 8, !tbaa !2
  %t188 = call ptr @realloc(ptr %t187, i64 %t186)
  store ptr %t188, ptr %t179, align 8, !tbaa !2
  store i64 %t185, ptr %t181, align 8, !tbaa !8
  br label %list_append_185

list_append_185:
  %t189 = load ptr, ptr %t179, align 8, !tbaa !2
  %t190 = getelementptr i64, ptr %t189, i64 %t182
  store i64 %r348, ptr %t190, align 8, !tbaa !4
  call void @nova_rc_inc(i64 %r348)
  %t191 = add i64 %t182, 1
  store i64 %t191, ptr %t180, align 8, !tbaa !6
  %r350 = load i64, ptr %slot.pos, align 8
  %r352 = add i64 %r350, 2
  store i64 %r352, ptr %slot.pos, align 8
  store i64 0, ptr %slot.__ifb_12, align 8
  br label %ifb_merge66

ifb_else65:
  %r356 = load i64, ptr %slot.ch, align 8
  %t192 = getelementptr inbounds [2 x i8], ptr @.str.10, i64 0, i64 0
  %r357 = ptrtoint ptr %t192 to i64
  %t193 = inttoptr i64 %r356 to ptr
  %t194 = inttoptr i64 %r357 to ptr
  %t195 = call i32 @strcmp(ptr %t193, ptr %t194)
  %t196 = icmp eq i32 %t195, 0
  %r358 = zext i1 %t196 to i64
  store i64 0, ptr %slot.__sc_and_9, align 8
  %t197 = icmp ne i64 %r358, 0
  br i1 %t197, label %sc_and_right67, label %sc_and_merge68

ifb_merge66:
  %r449 = load i64, ptr %slot.__ifb_12, align 8
  %t198 = load i64, ptr %slot.__ifb_11, align 8
  call void @nova_rc_dec(i64 %t198)
  call void @nova_rc_inc(i64 %r449)
  store i64 %r449, ptr %slot.__ifb_11, align 8
  br label %ifb_merge59, !llvm.loop !91

sc_and_right67:
  %r364 = load i64, ptr %slot.pos, align 8
  %r366 = add i64 %r364, 1
  %t199 = icmp slt i64 %r366, %r464
  %r368 = zext i1 %t199 to i64
  store i64 %r368, ptr %slot.__sc_and_9, align 8
  br label %sc_and_merge68

sc_and_merge68:
  %r370 = load i64, ptr %slot.__sc_and_9, align 8
  store i64 0, ptr %slot.__sc_and_10, align 8
  %t200 = icmp ne i64 %r370, 0
  br i1 %t200, label %sc_and_right69, label %sc_and_merge70

sc_and_right69:
  %r377 = load i64, ptr %slot.pos, align 8
  %r379 = add i64 %r377, 1
  %r380 = call i64 @nova_rt_str_char_at(i64 %r465, i64 %r379)
  %t201 = getelementptr inbounds [2 x i8], ptr @.str.5, i64 0, i64 0
  %r381 = ptrtoint ptr %t201 to i64
  %t202 = inttoptr i64 %r380 to ptr
  %t203 = inttoptr i64 %r381 to ptr
  %t204 = call i32 @strcmp(ptr %t202, ptr %t203)
  %t205 = icmp eq i32 %t204, 0
  %r382 = zext i1 %t205 to i64
  store i64 %r382, ptr %slot.__sc_and_10, align 8
  br label %sc_and_merge70

sc_and_merge70:
  %r384 = load i64, ptr %slot.__sc_and_10, align 8
  %t206 = trunc i64 %r384 to i1
  br i1 %t206, label %ifb_then71, label %ifb_else72

ifb_then71:
  %t207 = getelementptr inbounds [3 x i8], ptr @.str.16, i64 0, i64 0
  %r388 = ptrtoint ptr %t207 to i64
  %t208 = inttoptr i64 %r466 to ptr
  %t209 = getelementptr i64, ptr %t208, i64 1
  %t210 = getelementptr i64, ptr %t208, i64 2
  %t211 = load i64, ptr %t209, align 8, !tbaa !6
  %t212 = load i64, ptr %t210, align 8, !tbaa !8
  %t213 = icmp sge i64 %t211, %t212
  br i1 %t213, label %list_grow_214, label %list_append_214

list_grow_214:
  %t214 = shl i64 %t212, 1
  %t215 = shl i64 %t214, 3
  %t216 = load ptr, ptr %t208, align 8, !tbaa !2
  %t217 = call ptr @realloc(ptr %t216, i64 %t215)
  store ptr %t217, ptr %t208, align 8, !tbaa !2
  store i64 %t214, ptr %t210, align 8, !tbaa !8
  br label %list_append_214

list_append_214:
  %t218 = load ptr, ptr %t208, align 8, !tbaa !2
  %t219 = getelementptr i64, ptr %t218, i64 %t211
  store i64 %r388, ptr %t219, align 8, !tbaa !4
  call void @nova_rc_inc(i64 %r388)
  %t220 = add i64 %t211, 1
  store i64 %t220, ptr %t209, align 8, !tbaa !6
  %r390 = load i64, ptr %slot.pos, align 8
  %r392 = add i64 %r390, 2
  store i64 %r392, ptr %slot.pos, align 8
  store i64 0, ptr %slot.__ifb_13, align 8
  br label %ifb_merge73

ifb_else72:
  %t221 = getelementptr inbounds [1 x i8], ptr @.str.4, i64 0, i64 0
  %r398 = ptrtoint ptr %t221 to i64
  %t222 = load i64, ptr %slot.word, align 8
  call void @nova_rc_dec(i64 %t222)
  store i64 %r398, ptr %slot.word, align 8
  br label %while_header74

ifb_merge73:
  %r447 = load i64, ptr %slot.__ifb_13, align 8
  %t223 = load i64, ptr %slot.__ifb_12, align 8
  call void @nova_rc_dec(i64 %t223)
  call void @nova_rc_inc(i64 %r447)
  store i64 %r447, ptr %slot.__ifb_12, align 8
  br label %ifb_merge66, !llvm.loop !91

while_header74:
  %r402 = load i64, ptr %slot.pos, align 8
  %t224 = icmp slt i64 %r402, %r464
  %r404 = zext i1 %t224 to i64
  store i64 0, ptr %slot.__sc_and_11, align 8
  %t225 = icmp ne i64 %r404, 0
  br i1 %t225, label %sc_and_right77, label %sc_and_merge78, !prof !90

while_body75:
  %r430 = load i64, ptr %slot.word, align 8
  %r432 = load i64, ptr %slot.pos, align 8
  %r433 = call i64 @nova_rt_str_char_at(i64 %r465, i64 %r432)
  %t226 = call i64 @nova_rt_str_concat(i64 %r430, i64 %r433)
  %t227 = load i64, ptr %slot.word, align 8
  call void @nova_rc_dec(i64 %t227)
  store i64 %t226, ptr %slot.word, align 8
  %r437 = load i64, ptr %slot.pos, align 8
  %r439 = add i64 %r437, 1
  store i64 %r439, ptr %slot.pos, align 8
  br label %while_header74, !llvm.loop !91

while_exit76:
  %r444 = load i64, ptr %slot.word, align 8
  %t228 = inttoptr i64 %r466 to ptr
  %t229 = getelementptr i64, ptr %t228, i64 1
  %t230 = getelementptr i64, ptr %t228, i64 2
  %t231 = load i64, ptr %t229, align 8, !tbaa !6
  %t232 = load i64, ptr %t230, align 8, !tbaa !8
  %t233 = icmp sge i64 %t231, %t232
  br i1 %t233, label %list_grow_234, label %list_append_234

list_grow_234:
  %t234 = shl i64 %t232, 1
  %t235 = shl i64 %t234, 3
  %t236 = load ptr, ptr %t228, align 8, !tbaa !2
  %t237 = call ptr @realloc(ptr %t236, i64 %t235)
  store ptr %t237, ptr %t228, align 8, !tbaa !2
  store i64 %t234, ptr %t230, align 8, !tbaa !8
  br label %list_append_234

list_append_234:
  %t238 = load ptr, ptr %t228, align 8, !tbaa !2
  %t239 = getelementptr i64, ptr %t238, i64 %t231
  store i64 %r444, ptr %t239, align 8, !tbaa !4
  call void @nova_rc_inc(i64 %r444)
  %t240 = add i64 %t231, 1
  store i64 %t240, ptr %t229, align 8, !tbaa !6
  %t241 = load i64, ptr %slot.__ifb_13, align 8
  call void @nova_rc_dec(i64 %t241)
  store i64 0, ptr %slot.__ifb_13, align 8
  br label %ifb_merge73, !llvm.loop !91

sc_and_right77:
  %r411 = load i64, ptr %slot.pos, align 8
  %r412 = call i64 @nova_rt_str_char_at(i64 %r465, i64 %r411)
  %t242 = getelementptr inbounds [2 x i8], ptr @.str.0, i64 0, i64 0
  %r413 = ptrtoint ptr %t242 to i64
  %t243 = inttoptr i64 %r412 to ptr
  %t244 = inttoptr i64 %r413 to ptr
  %t245 = call i32 @strcmp(ptr %t243, ptr %t244)
  %t246 = icmp ne i32 %t245, 0
  %r414 = zext i1 %t246 to i64
  store i64 %r414, ptr %slot.__sc_and_11, align 8
  br label %sc_and_merge78

sc_and_merge78:
  %r416 = load i64, ptr %slot.__sc_and_11, align 8
  store i64 0, ptr %slot.__sc_and_12, align 8
  %t247 = icmp ne i64 %r416, 0
  br i1 %t247, label %sc_and_right79, label %sc_and_merge80

sc_and_right79:
  %r423 = load i64, ptr %slot.pos, align 8
  %r424 = call i64 @nova_rt_str_char_at(i64 %r465, i64 %r423)
  %t248 = getelementptr inbounds [2 x i8], ptr @.str.1, i64 0, i64 0
  %r425 = ptrtoint ptr %t248 to i64
  %t249 = inttoptr i64 %r424 to ptr
  %t250 = inttoptr i64 %r425 to ptr
  %t251 = call i32 @strcmp(ptr %t249, ptr %t250)
  %t252 = icmp ne i32 %t251, 0
  %r426 = zext i1 %t252 to i64
  store i64 %r426, ptr %slot.__sc_and_12, align 8
  br label %sc_and_merge80

sc_and_merge80:
  %r428 = load i64, ptr %slot.__sc_and_12, align 8
  %t253 = trunc i64 %r428 to i1
  br i1 %t253, label %while_body75, label %while_exit76
}

define i64 @nova_main() nounwind {
entry0:
  %slot.__for_iter_2 = alloca i64, align 8
  %slot.__for_idx_2 = alloca i64, align 8
  store i64 0, ptr %slot.__for_iter_2, align 8
  %t0 = getelementptr inbounds [138 x i8], ptr @.str.17, i64 0, i64 0
  %r1 = ptrtoint ptr %t0 to i64
  %r7 = call i64 @tokenize_heavy(i64 %r1)
  %r12 = call i64 @nova_rt_list_len(i64 %r7)
  %t1 = getelementptr inbounds [5 x i8], ptr @.str.19, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t1, i64 %r12)
  %t2 = load i64, ptr %slot.__for_iter_2, align 8
  call void @nova_rc_dec(i64 %t2)
  store i64 %r7, ptr %slot.__for_iter_2, align 8
  store i64 0, ptr %slot.__for_idx_2, align 8
  %r38 = load i64, ptr %slot.__for_iter_2, align 8
  br label %for_header1

for_header1:
  %r22 = load i64, ptr %slot.__for_idx_2, align 8
  %t3 = inttoptr i64 %r38 to ptr
  %t4 = getelementptr i64, ptr %t3, i64 1
  %t5 = load i64, ptr %t4, align 8
  %t6 = icmp slt i64 %r22, %t5
  %r21 = zext i1 %t6 to i64
  %t7 = trunc i64 %r21 to i1
  br i1 %t7, label %for_body2, label %for_exit3, !prof !90

for_body2:
  %r24 = load i64, ptr %slot.__for_idx_2, align 8
  %t8 = inttoptr i64 %r38 to ptr
  %t9 = load ptr, ptr %t8, align 8, !tbaa !2
  %t10 = getelementptr i64, ptr %t9, i64 %r24
  %r25 = load i64, ptr %t10, align 8, !tbaa !4
  %t11 = call i64 @nova_rt_any_to_str(i64 %r25)
  %t12 = inttoptr i64 %t11 to ptr
  call i32 @puts(ptr %t12)
  %r31 = add i64 %r24, 1
  store i64 %r31, ptr %slot.__for_idx_2, align 8
  br label %for_header1, !llvm.loop !91

for_exit3:
  %t13 = getelementptr inbounds [5 x i8], ptr @.str.18, i64 0, i64 0
  %r35 = ptrtoint ptr %t13 to i64
  %t14 = inttoptr i64 %r35 to ptr
  call i32 @puts(ptr %t14)
  %t15 = load i64, ptr %slot.__for_iter_2, align 8
  call void @nova_rc_dec(i64 %t15)
  ret i64 0
}

define i32 @main(i32 %argc, ptr %argv) nounwind {
entry:
  %argc64 = sext i32 %argc to i64
  %argv64 = ptrtoint ptr %argv to i64
  call void @nova_rt_init_args(i64 %argc64, i64 %argv64)
  call i64 @nova_main()
  call void @nova_rt_wait_all()
  call void @nova_rt_cleanup()
  ret i32 0
}

!0 = !{!"NOVA TBAA"}
!1 = !{!"list_data_ptr", !0}
!2 = !{!1, !1, i64 0}
!3 = !{!"list_elem", !0}
!4 = !{!3, !3, i64 0}
!5 = !{!"list_size", !0}
!6 = !{!5, !5, i64 0}
!7 = !{!"list_cap", !0}
!8 = !{!7, !7, i64 0}
!90 = !{!"branch_weights", i32 2000, i32 1}
!91 = distinct !{!91, !92, !93}
!92 = !{!"llvm.loop.unroll.enable"}
!93 = !{!"llvm.loop.vectorize.enable", i1 true}
