; Generated by NOVA compiler
target triple = "x86_64-pc-windows-msvc"

declare i32 @printf(ptr, ...)
declare i32 @puts(ptr)
declare noalias ptr @malloc(i64) nounwind allocsize(0)
declare noalias ptr @calloc(i64, i64) nounwind
declare ptr @realloc(ptr, i64) nounwind allocsize(1)
declare void @free(ptr)
declare i64 @llvm.smax.i64(i64, i64) nounwind readnone
; nova runtime — list ops
declare i64 @nova_rt_list_create()
declare i64 @nova_rt_list_create_filled(i64, i64)
declare i64 @nova_rt_list_append(i64, i64)
declare i64 @nova_rt_list_get(i64, i64)
declare i64 @nova_rt_list_set(i64, i64, i64)
declare i64 @nova_rt_list_len(i64)
declare i64 @nova_rt_list_print(i64)
declare i64 @nova_rt_iter_has_next(i64, i64)
declare i64 @nova_rt_iter_get(i64, i64)
; nova runtime — string ops
declare i64 @nova_rt_str_concat(i64, i64)
declare i64 @nova_rt_int_to_str(i64)
declare i64 @nova_rt_float_to_str(i64)
declare i64 @nova_rt_bool_to_str(i64)
declare i64 @nova_rt_str_len(i64)
declare i64 @nova_rt_len(i64)
declare i64 @nova_rt_contains(i64, i64)
declare i64 @nova_rt_slice(i64, i64, i64)
declare i64 @nova_rt_upper(i64)
declare i64 @nova_rt_lower(i64)
declare i64 @nova_rt_trim(i64)
declare i64 @nova_rt_split(i64, i64)
declare i64 @nova_rt_replace(i64, i64, i64)
declare i64 @nova_rt_starts_with(i64, i64)
declare i64 @nova_rt_ends_with(i64, i64)
declare i64 @nova_rt_find(i64, i64)
declare i64 @nova_rt_join(i64, i64)
declare i64 @nova_rt_chars(i64)
; nova runtime — list stdlib
declare i64 @nova_rt_list_reverse(i64)
declare i64 @nova_rt_list_sort(i64)
declare i64 @nova_rt_list_map(i64, i64)
declare i64 @nova_rt_list_filter(i64, i64)
declare i64 @nova_rt_list_concat(i64, i64)
declare i64 @nova_rt_list_slice(i64, i64, i64)
declare i64 @nova_rt_list_to_str(i64)
declare i64 @nova_rt_len_any(i64)
; nova runtime — type conversions
declare i64 @nova_rt_parse_int(i64)
declare i64 @nova_rt_parse_float(i64)
; nova runtime — character ops
declare i64 @nova_rt_ord(i64)
declare i64 @nova_rt_chr(i64)
; nova runtime — process control
declare void @nova_rt_exit(i64)
declare i32 @strcmp(ptr, ptr)
; nova runtime — dict ops (Phase 1: ordered array, O(n) lookup)
declare i64 @nova_rt_dict_create()
declare i64 @nova_rt_dict_set(i64, i64, i64)
declare i64 @nova_rt_dict_get(i64, i64)
declare i64 @nova_rt_dict_has(i64, i64)
declare i64 @nova_rt_dict_del(i64, i64)
declare i64 @nova_rt_dict_len(i64)
declare i64 @nova_rt_dict_keys(i64)
declare i64 @nova_rt_dict_values(i64)
declare i64 @nova_rt_dict_items(i64)
; nova runtime — IO ops
declare i64 @nova_rt_read_line()
declare i64 @nova_rt_read_file(i64)
declare i64 @nova_rt_write_file(i64, i64)
declare i64 @nova_rt_append_file(i64, i64)
declare i64 @nova_rt_file_exists(i64)
; nova runtime — JSON ops
declare i64 @nova_rt_json_parse(i64)
declare i64 @nova_rt_json_stringify(i64)
; nova runtime — HTTP ops
declare i64 @nova_rt_http_get(i64)
declare i64 @nova_rt_http_post(i64, i64, i64)
; nova runtime — type dispatch
declare i64 @nova_rt_any_to_str(i64)
declare i64 @nova_rt_str_concat_safe(i64, i64)
declare void @nova_rt_init()
; nova runtime — channel/spawn ops
declare i64 @nova_rt_channel_create()
declare i64 @nova_rt_channel_send(i64, i64)
declare i64 @nova_rt_channel_recv(i64)
declare i64 @nova_rt_channel_close(i64)
declare i64 @nova_rt_channel_select(i64, i64)
declare i64 @nova_rt_channel_recv_timeout(i64, i64)
declare i64 @nova_rt_spawn(i64, i64)
declare i64 @nova_rt_monitor(i64)
declare void @nova_rt_wait_all()
; nova runtime — math (trig/log via C runtime for non-intrinsic functions)
declare i64 @nova_rt_tan(i64)
declare i64 @nova_rt_asin(i64)
declare i64 @nova_rt_acos(i64)
declare i64 @nova_rt_atan(i64)
declare i64 @nova_rt_atan2(i64, i64)
declare i64 @nova_rt_fmod(i64, i64)
declare i64 @nova_rt_int_pow(i64, i64)
; nova runtime — memory management
declare void @nova_rt_cleanup()
declare void @nova_rt_track_raw(ptr)
declare i64 @nova_rt_alloc_count()
declare i64 @nova_rt_live_count()
; nova runtime — reference counting
declare void @nova_rc_inc(i64)
declare void @nova_rc_dec(i64)
; nova error state — thread-local flag (safe for spawn/concurrent programs)
@__nova_error_flag = thread_local global i64 0
@__nova_error_msg = thread_local global i64 0

@.str.0 = private unnamed_addr constant [6 x i8] c"%lld\0A\00"
@.str.1 = private unnamed_addr constant [4 x i8] c"%f\0A\00"
@.str.2 = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.str.3 = private unnamed_addr constant [5 x i8] c"true\00"
@.str.4 = private unnamed_addr constant [6 x i8] c"false\00"

define i64 @apply(i64 %p0, i64 %p1) {
entry0:
  %slot.f = alloca i64, align 8
  %slot.x = alloca i64, align 8
  store i64 %p0, ptr %slot.f, align 8
  store i64 %p1, ptr %slot.x, align 8
  %t0 = inttoptr i64 %p0 to ptr
  %t1 = load i64, ptr %t0
  %t2 = inttoptr i64 %t1 to ptr
  %r7 = call i64 %t2(i64 %p0, i64 %p1)
  ret i64 %r7
}

define i64 @double(i64 %p0) {
entry0:
  %slot.n = alloca i64, align 8
  store i64 %p0, ptr %slot.n, align 8
  %r5 = mul i64 %p0, 2
  ret i64 %r5
}

define i64 @square(i64 %p0) {
entry0:
  %slot.n = alloca i64, align 8
  store i64 %p0, ptr %slot.n, align 8
  %r5 = mul i64 %p0, %p0
  ret i64 %r5
}

define i64 @map_first(i64 %p0, i64 %p1, i64 %p2) {
entry0:
  %slot.f = alloca i64, align 8
  %slot.a = alloca i64, align 8
  %slot.b = alloca i64, align 8
  store i64 %p0, ptr %slot.f, align 8
  store i64 %p1, ptr %slot.a, align 8
  store i64 %p2, ptr %slot.b, align 8
  %t0 = inttoptr i64 %p0 to ptr
  %t1 = load i64, ptr %t0
  %t2 = inttoptr i64 %t1 to ptr
  %r9 = call i64 %t2(i64 %p0, i64 %p1)
  %t3 = inttoptr i64 %p0 to ptr
  %t4 = load i64, ptr %t3
  %t5 = inttoptr i64 %t4 to ptr
  %r12 = call i64 %t5(i64 %p0, i64 %p2)
  %t6 = call ptr @malloc(i64 16)
  call void @nova_rt_track_raw(ptr %t6)
  %t7 = getelementptr i64, ptr %t6, i64 0
  store i64 %r9, ptr %t7
  %t8 = getelementptr i64, ptr %t6, i64 1
  store i64 %r12, ptr %t8
  %r13 = ptrtoint ptr %t6 to i64
  ret i64 %r13
}

define i64 @compose(i64 %p0, i64 %p1, i64 %p2) {
entry0:
  %slot.f = alloca i64, align 8
  %slot.g = alloca i64, align 8
  %slot.x = alloca i64, align 8
  store i64 %p0, ptr %slot.f, align 8
  store i64 %p1, ptr %slot.g, align 8
  store i64 %p2, ptr %slot.x, align 8
  %t0 = inttoptr i64 %p1 to ptr
  %t1 = load i64, ptr %t0
  %t2 = inttoptr i64 %t1 to ptr
  %r10 = call i64 %t2(i64 %p1, i64 %p2)
  %t3 = inttoptr i64 %p0 to ptr
  %t4 = load i64, ptr %t3
  %t5 = inttoptr i64 %t4 to ptr
  %r11 = call i64 %t5(i64 %p0, i64 %r10)
  ret i64 %r11
}

define i64 @make_adder(i64 %p0) {
entry0:
  %slot.n = alloca i64, align 8
  store i64 %p0, ptr %slot.n, align 8
  %t0 = call ptr @malloc(i64 16)
  call void @nova_rt_track_raw(ptr %t0)
  %t1 = ptrtoint ptr @make_adder_lambda0_tramp to i64
  store i64 %t1, ptr %t0
  %t2 = getelementptr i64, ptr %t0, i64 1
  store i64 %p0, ptr %t2
  %r4 = ptrtoint ptr %t0 to i64
  ret i64 %r4
}

define i64 @make_adder_lambda0(i64 %p0, i64 %p1) {
entry0:
  %slot.x = alloca i64, align 8
  %slot.n = alloca i64, align 8
  store i64 %p0, ptr %slot.x, align 8
  store i64 %p1, ptr %slot.n, align 8
  %r9 = add i64 %p0, %p1
  ret i64 %r9
}

define i64 @nova_main() {
entry0:
  %slot.p = alloca i64, align 8
  %slot.q = alloca i64, align 8
  %slot.add3 = alloca i64, align 8
  %slot.multiplier = alloca i64, align 8
  %slot.times5 = alloca i64, align 8
  %slot.add10 = alloca i64, align 8
  store i64 0, ptr %slot.p, align 8
  store i64 0, ptr %slot.q, align 8
  store i64 0, ptr %slot.add3, align 8
  store i64 0, ptr %slot.times5, align 8
  store i64 0, ptr %slot.add10, align 8
  %t0 = call ptr @malloc(i64 8)
  call void @nova_rt_track_raw(ptr %t0)
  %t1 = ptrtoint ptr @double_tramp to i64
  store i64 %t1, ptr %t0
  %r0 = ptrtoint ptr %t0 to i64
  %r2 = call i64 @apply(i64 %r0, i64 5)
  %t2 = call i64 @nova_rt_any_to_str(i64 %r2)
  %t3 = inttoptr i64 %t2 to ptr
  call i32 @puts(ptr %t3)
  %t4 = call ptr @malloc(i64 8)
  call void @nova_rt_track_raw(ptr %t4)
  %t5 = ptrtoint ptr @square_tramp to i64
  store i64 %t5, ptr %t4
  %r4 = ptrtoint ptr %t4 to i64
  %r6 = call i64 @apply(i64 %r4, i64 4)
  %t6 = call i64 @nova_rt_any_to_str(i64 %r6)
  %t7 = inttoptr i64 %t6 to ptr
  call i32 @puts(ptr %t7)
  %t8 = call ptr @malloc(i64 8)
  call void @nova_rt_track_raw(ptr %t8)
  %t9 = ptrtoint ptr @double_tramp to i64
  store i64 %t9, ptr %t8
  %r8 = ptrtoint ptr %t8 to i64
  %r10 = call i64 @apply(i64 %r8, i64 0)
  %t10 = call i64 @nova_rt_any_to_str(i64 %r10)
  %t11 = inttoptr i64 %t10 to ptr
  call i32 @puts(ptr %t11)
  %t12 = call ptr @malloc(i64 8)
  call void @nova_rt_track_raw(ptr %t12)
  %t13 = ptrtoint ptr @double_tramp to i64
  store i64 %t13, ptr %t12
  %r12 = ptrtoint ptr %t12 to i64
  %r15 = call i64 @map_first(i64 %r12, i64 3, i64 7)
  %t14 = inttoptr i64 %r15 to ptr
  %t15 = getelementptr i64, ptr %t14, i64 0
  %r17 = load i64, ptr %t15
  %t16 = load i64, ptr %slot.p, align 8
  call void @nova_rc_dec(i64 %t16)
  call void @nova_rc_inc(i64 %r17)
  store i64 %r17, ptr %slot.p, align 8
  %t17 = inttoptr i64 %r15 to ptr
  %t18 = getelementptr i64, ptr %t17, i64 1
  %r21 = load i64, ptr %t18
  %t19 = load i64, ptr %slot.q, align 8
  call void @nova_rc_dec(i64 %t19)
  call void @nova_rc_inc(i64 %r21)
  store i64 %r21, ptr %slot.q, align 8
  %t20 = call i64 @nova_rt_any_to_str(i64 %r17)
  %t21 = inttoptr i64 %t20 to ptr
  call i32 @puts(ptr %t21)
  %t22 = call i64 @nova_rt_any_to_str(i64 %r21)
  %t23 = inttoptr i64 %t22 to ptr
  call i32 @puts(ptr %t23)
  %t24 = call ptr @malloc(i64 8)
  call void @nova_rt_track_raw(ptr %t24)
  %t25 = ptrtoint ptr @double_tramp to i64
  store i64 %t25, ptr %t24
  %r29 = ptrtoint ptr %t24 to i64
  %t26 = call ptr @malloc(i64 8)
  call void @nova_rt_track_raw(ptr %t26)
  %t27 = ptrtoint ptr @square_tramp to i64
  store i64 %t27, ptr %t26
  %r30 = ptrtoint ptr %t26 to i64
  %r32 = call i64 @compose(i64 %r29, i64 %r30, i64 3)
  %t28 = call i64 @nova_rt_any_to_str(i64 %r32)
  %t29 = inttoptr i64 %t28 to ptr
  call i32 @puts(ptr %t29)
  %t30 = call ptr @malloc(i64 8)
  call void @nova_rt_track_raw(ptr %t30)
  %t31 = ptrtoint ptr @square_tramp to i64
  store i64 %t31, ptr %t30
  %r34 = ptrtoint ptr %t30 to i64
  %t32 = call ptr @malloc(i64 8)
  call void @nova_rt_track_raw(ptr %t32)
  %t33 = ptrtoint ptr @double_tramp to i64
  store i64 %t33, ptr %t32
  %r35 = ptrtoint ptr %t32 to i64
  %r37 = call i64 @compose(i64 %r34, i64 %r35, i64 3)
  %t34 = call i64 @nova_rt_any_to_str(i64 %r37)
  %t35 = inttoptr i64 %t34 to ptr
  call i32 @puts(ptr %t35)
  %t36 = call ptr @malloc(i64 8)
  call void @nova_rt_track_raw(ptr %t36)
  %t37 = ptrtoint ptr @nova_main_lambda1_tramp to i64
  store i64 %t37, ptr %t36
  %r39 = ptrtoint ptr %t36 to i64
  %t38 = load i64, ptr %slot.add3, align 8
  call void @nova_rc_dec(i64 %t38)
  store i64 %r39, ptr %slot.add3, align 8
  %r45 = call i64 @apply(i64 %r39, i64 10)
  %t39 = call i64 @nova_rt_any_to_str(i64 %r45)
  %t40 = inttoptr i64 %t39 to ptr
  call i32 @puts(ptr %t40)
  store i64 5, ptr %slot.multiplier, align 8
  %t41 = call ptr @malloc(i64 16)
  call void @nova_rt_track_raw(ptr %t41)
  %t42 = ptrtoint ptr @nova_main_lambda2_tramp to i64
  store i64 %t42, ptr %t41
  %t43 = getelementptr i64, ptr %t41, i64 1
  store i64 5, ptr %t43
  %r52 = ptrtoint ptr %t41 to i64
  %t44 = load i64, ptr %slot.times5, align 8
  call void @nova_rc_dec(i64 %t44)
  store i64 %r52, ptr %slot.times5, align 8
  %r58 = call i64 @apply(i64 %r52, i64 7)
  %t45 = call i64 @nova_rt_any_to_str(i64 %r58)
  %t46 = inttoptr i64 %t45 to ptr
  call i32 @puts(ptr %t46)
  %r61 = call i64 @make_adder(i64 10)
  %t47 = load i64, ptr %slot.add10, align 8
  call void @nova_rc_dec(i64 %t47)
  store i64 %r61, ptr %slot.add10, align 8
  %t48 = inttoptr i64 %r61 to ptr
  %t49 = load i64, ptr %t48
  %t50 = inttoptr i64 %t49 to ptr
  %r67 = call i64 %t50(i64 %r61, i64 3)
  %t51 = call i64 @nova_rt_any_to_str(i64 %r67)
  %t52 = inttoptr i64 %t51 to ptr
  call i32 @puts(ptr %t52)
  %r71 = call i64 @apply(i64 %r61, i64 20)
  %t53 = call i64 @nova_rt_any_to_str(i64 %r71)
  %t54 = inttoptr i64 %t53 to ptr
  call i32 @puts(ptr %t54)
  %t55 = load i64, ptr %slot.p, align 8
  call void @nova_rc_dec(i64 %t55)
  %t56 = load i64, ptr %slot.q, align 8
  call void @nova_rc_dec(i64 %t56)
  %t57 = load i64, ptr %slot.add3, align 8
  call void @nova_rc_dec(i64 %t57)
  %t58 = load i64, ptr %slot.times5, align 8
  call void @nova_rc_dec(i64 %t58)
  %t59 = load i64, ptr %slot.add10, align 8
  call void @nova_rc_dec(i64 %t59)
  ret i64 0
}

define i64 @nova_main_lambda1(i64 %p0) {
entry0:
  %slot.x = alloca i64, align 8
  store i64 %p0, ptr %slot.x, align 8
  %r43 = add i64 %p0, 3
  ret i64 %r43
}

define i64 @nova_main_lambda2(i64 %p0, i64 %p1) {
entry0:
  %slot.x = alloca i64, align 8
  %slot.multiplier = alloca i64, align 8
  store i64 %p0, ptr %slot.x, align 8
  store i64 %p1, ptr %slot.multiplier, align 8
  %r57 = mul i64 %p0, %p1
  ret i64 %r57
}

define i64 @make_adder_lambda0_tramp(i64 %p0, i64 %p1) {
entry_tramp:
  %env_ptr = inttoptr i64 %p0 to ptr
  %cap0_gep = getelementptr i64, ptr %env_ptr, i64 1
  %cap0 = load i64, ptr %cap0_gep
  %tramp_result = call i64 @make_adder_lambda0(i64 %p1, i64 %cap0)
  ret i64 %tramp_result
}

define i64 @double_tramp(i64 %p0, i64 %p1) {
entry_tramp:
  %env_ptr = inttoptr i64 %p0 to ptr
  %tramp_result = call i64 @double(i64 %p1)
  ret i64 %tramp_result
}

define i64 @square_tramp(i64 %p0, i64 %p1) {
entry_tramp:
  %env_ptr = inttoptr i64 %p0 to ptr
  %tramp_result = call i64 @square(i64 %p1)
  ret i64 %tramp_result
}

define i64 @nova_main_lambda1_tramp(i64 %p0, i64 %p1) {
entry_tramp:
  %env_ptr = inttoptr i64 %p0 to ptr
  %tramp_result = call i64 @nova_main_lambda1(i64 %p1)
  ret i64 %tramp_result
}

define i64 @nova_main_lambda2_tramp(i64 %p0, i64 %p1) {
entry_tramp:
  %env_ptr = inttoptr i64 %p0 to ptr
  %cap0_gep = getelementptr i64, ptr %env_ptr, i64 1
  %cap0 = load i64, ptr %cap0_gep
  %tramp_result = call i64 @nova_main_lambda2(i64 %p1, i64 %cap0)
  ret i64 %tramp_result
}

define i32 @main() {
entry:
  call void @nova_rt_init()
  call i64 @nova_main()
  call void @nova_rt_wait_all()
  call void @nova_rt_cleanup()
  ret i32 0
}

!0 = !{!"NOVA TBAA"}
!1 = !{!"list_data_ptr", !0}
!2 = !{!1, !1, i64 0}
!3 = !{!"list_elem", !0}
!4 = !{!3, !3, i64 0}
!5 = !{!"list_size", !0}
!6 = !{!5, !5, i64 0}
!7 = !{!"list_cap", !0}
!8 = !{!7, !7, i64 0}
