; Generated by NOVA compiler
target triple = "x86_64-pc-windows-msvc"

declare i32 @printf(ptr, ...)
declare i32 @puts(ptr)
declare noalias ptr @malloc(i64) nounwind allocsize(0)
declare noalias ptr @calloc(i64, i64) nounwind
declare ptr @realloc(ptr, i64) nounwind allocsize(1)
declare void @free(ptr)
declare i64 @llvm.smax.i64(i64, i64) nounwind readnone
; nova runtime — list ops
declare i64 @nova_rt_list_create()
declare i64 @nova_rt_list_create_filled(i64, i64)
declare i64 @nova_rt_list_append(i64, i64)
declare i64 @nova_rt_list_get(i64, i64)
declare i64 @nova_rt_list_set(i64, i64, i64)
declare i64 @nova_rt_list_len(i64)
declare i64 @nova_rt_list_print(i64)
declare i64 @nova_rt_iter_has_next(i64, i64)
declare i64 @nova_rt_iter_get(i64, i64)
; nova runtime — string ops
declare i64 @nova_rt_str_concat(i64, i64)
declare i64 @nova_rt_int_to_str(i64)
declare i64 @nova_rt_float_to_str(i64)
declare i64 @nova_rt_bool_to_str(i64)
declare i64 @nova_rt_str_len(i64)
declare i64 @nova_rt_len(i64)
declare i64 @nova_rt_contains(i64, i64)
declare i64 @nova_rt_slice(i64, i64, i64)
declare i64 @nova_rt_upper(i64)
declare i64 @nova_rt_lower(i64)
declare i64 @nova_rt_trim(i64)
declare i64 @nova_rt_split(i64, i64)
declare i64 @nova_rt_replace(i64, i64, i64)
declare i64 @nova_rt_starts_with(i64, i64)
declare i64 @nova_rt_ends_with(i64, i64)
declare i64 @nova_rt_find(i64, i64)
declare i64 @nova_rt_join(i64, i64)
declare i64 @nova_rt_chars(i64)
; nova runtime — list stdlib
declare i64 @nova_rt_list_reverse(i64)
declare i64 @nova_rt_list_sort(i64)
declare i64 @nova_rt_list_map(i64, i64)
declare i64 @nova_rt_list_filter(i64, i64)
declare i64 @nova_rt_list_concat(i64, i64)
declare i64 @nova_rt_list_slice(i64, i64, i64)
declare i64 @nova_rt_list_to_str(i64)
declare i64 @nova_rt_len_any(i64)
; nova runtime — type conversions
declare i64 @nova_rt_parse_int(i64)
declare i64 @nova_rt_parse_float(i64)
; nova runtime — character ops
declare i64 @nova_rt_ord(i64)
declare i64 @nova_rt_chr(i64)
; nova runtime — process control
declare void @nova_rt_exit(i64)
declare i32 @strcmp(ptr, ptr)
; nova runtime — dict ops (Phase 1: ordered array, O(n) lookup)
declare i64 @nova_rt_dict_create()
declare i64 @nova_rt_dict_set(i64, i64, i64)
declare i64 @nova_rt_dict_get(i64, i64)
declare i64 @nova_rt_dict_has(i64, i64)
declare i64 @nova_rt_dict_del(i64, i64)
declare i64 @nova_rt_dict_len(i64)
declare i64 @nova_rt_dict_keys(i64)
declare i64 @nova_rt_dict_values(i64)
declare i64 @nova_rt_dict_items(i64)
; nova runtime — IO ops
declare i64 @nova_rt_read_line()
declare i64 @nova_rt_read_file(i64)
declare i64 @nova_rt_write_file(i64, i64)
declare i64 @nova_rt_append_file(i64, i64)
declare i64 @nova_rt_file_exists(i64)
; nova runtime — JSON ops
declare i64 @nova_rt_json_parse(i64)
declare i64 @nova_rt_json_stringify(i64)
; nova runtime — HTTP ops
declare i64 @nova_rt_http_get(i64)
declare i64 @nova_rt_http_post(i64, i64, i64)
; nova runtime — type dispatch
declare i64 @nova_rt_any_to_str(i64)
declare i64 @nova_rt_str_concat_safe(i64, i64)
declare void @nova_rt_init()
; nova runtime — channel/spawn ops
declare i64 @nova_rt_channel_create()
declare i64 @nova_rt_channel_send(i64, i64)
declare i64 @nova_rt_channel_recv(i64)
declare i64 @nova_rt_channel_close(i64)
declare i64 @nova_rt_channel_select(i64, i64)
declare i64 @nova_rt_channel_recv_timeout(i64, i64)
declare i64 @nova_rt_spawn(i64, i64)
declare i64 @nova_rt_monitor(i64)
declare void @nova_rt_wait_all()
; nova runtime — math (trig/log via C runtime for non-intrinsic functions)
declare i64 @nova_rt_tan(i64)
declare i64 @nova_rt_asin(i64)
declare i64 @nova_rt_acos(i64)
declare i64 @nova_rt_atan(i64)
declare i64 @nova_rt_atan2(i64, i64)
declare i64 @nova_rt_fmod(i64, i64)
declare i64 @nova_rt_int_pow(i64, i64)
; nova runtime — memory management
declare void @nova_rt_cleanup()
declare void @nova_rt_track_raw(ptr)
declare i64 @nova_rt_alloc_count()
declare i64 @nova_rt_live_count()
; nova runtime — reference counting
declare void @nova_rc_inc(i64)
declare void @nova_rc_dec(i64)
; nova error state — thread-local flag (safe for spawn/concurrent programs)
@__nova_error_flag = thread_local global i64 0
@__nova_error_msg = thread_local global i64 0

@.str.0 = private unnamed_addr constant [9 x i8] c"FizzBuzz\00"
@.str.1 = private unnamed_addr constant [5 x i8] c"Fizz\00"
@.str.2 = private unnamed_addr constant [5 x i8] c"Buzz\00"
@.str.3 = private unnamed_addr constant [1 x i8] c"\00"
@.str.4 = private unnamed_addr constant [8 x i8] c"perfect\00"
@.str.5 = private unnamed_addr constant [2 x i8] c"A\00"
@.str.6 = private unnamed_addr constant [2 x i8] c"B\00"
@.str.7 = private unnamed_addr constant [2 x i8] c"C\00"
@.str.8 = private unnamed_addr constant [6 x i8] c"%lld\0A\00"
@.str.9 = private unnamed_addr constant [4 x i8] c"%f\0A\00"
@.str.10 = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.str.11 = private unnamed_addr constant [5 x i8] c"true\00"
@.str.12 = private unnamed_addr constant [6 x i8] c"false\00"

define i64 @fizzbuzz(i64 %p0) {
entry0:
  %slot.n = alloca i64, align 8
  %slot.__match_0 = alloca i64, align 8
  %slot.__match_1 = alloca i64, align 8
  %slot.__match_2 = alloca i64, align 8
  store i64 0, ptr %slot.__match_0, align 8
  store i64 0, ptr %slot.__match_1, align 8
  store i64 0, ptr %slot.__match_2, align 8
  store i64 %p0, ptr %slot.n, align 8
  %r5 = srem i64 %p0, 15
  %t0 = icmp eq i64 %r5, 0
  br i1 %t0, label %arm0_body2, label %arm0_next3

arm0_body2:
  %t1 = getelementptr inbounds [9 x i8], ptr @.str.0, i64 0, i64 0
  %r9 = ptrtoint ptr %t1 to i64
  %t2 = load i64, ptr %slot.__match_0, align 8
  call void @nova_rc_dec(i64 %t2)
  store i64 %r9, ptr %slot.__match_0, align 8
  br label %match_merge1

arm0_next3:
  br label %arm1_body4

arm1_body4:
  %r11 = load i64, ptr %slot.n, align 8
  %r13 = srem i64 %r11, 3
  %t3 = icmp eq i64 %r13, 0
  br i1 %t3, label %arm0_body6, label %arm0_next7

arm0_body6:
  %t4 = getelementptr inbounds [5 x i8], ptr @.str.1, i64 0, i64 0
  %r17 = ptrtoint ptr %t4 to i64
  %t5 = load i64, ptr %slot.__match_1, align 8
  call void @nova_rc_dec(i64 %t5)
  store i64 %r17, ptr %slot.__match_1, align 8
  br label %match_merge5

arm0_next7:
  br label %arm1_body8

arm1_body8:
  %r19 = load i64, ptr %slot.n, align 8
  %r21 = srem i64 %r19, 5
  %t6 = icmp eq i64 %r21, 0
  br i1 %t6, label %arm0_body10, label %arm0_next11

arm0_body10:
  %t7 = getelementptr inbounds [5 x i8], ptr @.str.2, i64 0, i64 0
  %r25 = ptrtoint ptr %t7 to i64
  %t8 = load i64, ptr %slot.__match_2, align 8
  call void @nova_rc_dec(i64 %t8)
  store i64 %r25, ptr %slot.__match_2, align 8
  br label %match_merge9

arm0_next11:
  br label %arm1_body12

arm1_body12:
  %t9 = getelementptr inbounds [1 x i8], ptr @.str.3, i64 0, i64 0
  %r27 = ptrtoint ptr %t9 to i64
  %r28 = load i64, ptr %slot.n, align 8
  %r29 = call i64 @nova_rt_int_to_str(i64 %r28)
  %t10 = getelementptr inbounds [1 x i8], ptr @.str.3, i64 0, i64 0
  %r30 = ptrtoint ptr %t10 to i64
  %t11 = call i64 @nova_rt_str_concat(i64 %r27, i64 %r29)
  %t12 = call i64 @nova_rt_str_concat(i64 %t11, i64 %r30)
  call void @nova_rc_dec(i64 %t11)
  call void @nova_rc_dec(i64 %r29)
  %t13 = load i64, ptr %slot.__match_2, align 8
  call void @nova_rc_dec(i64 %t13)
  store i64 %t12, ptr %slot.__match_2, align 8
  br label %match_merge9

match_merge9:
  %r33 = load i64, ptr %slot.__match_2, align 8
  %t14 = load i64, ptr %slot.__match_1, align 8
  call void @nova_rc_dec(i64 %t14)
  call void @nova_rc_inc(i64 %r33)
  store i64 %r33, ptr %slot.__match_1, align 8
  br label %match_merge5

match_merge5:
  %r35 = load i64, ptr %slot.__match_1, align 8
  %t15 = load i64, ptr %slot.__match_0, align 8
  call void @nova_rc_dec(i64 %t15)
  call void @nova_rc_inc(i64 %r35)
  store i64 %r35, ptr %slot.__match_0, align 8
  br label %match_merge1

match_merge1:
  %r37 = load i64, ptr %slot.__match_0, align 8
  call void @nova_rc_inc(i64 %r37)
  %t16 = load i64, ptr %slot.__match_0, align 8
  call void @nova_rc_dec(i64 %t16)
  %t17 = load i64, ptr %slot.__match_1, align 8
  call void @nova_rc_dec(i64 %t17)
  %t18 = load i64, ptr %slot.__match_2, align 8
  call void @nova_rc_dec(i64 %t18)
  ret i64 %r37
}

define i64 @grade(i64 %p0) {
entry0:
  %slot.score = alloca i64, align 8
  %slot.__match_3 = alloca i64, align 8
  %slot.__match_4 = alloca i64, align 8
  %slot.__match_5 = alloca i64, align 8
  store i64 0, ptr %slot.__match_3, align 8
  store i64 0, ptr %slot.__match_4, align 8
  store i64 0, ptr %slot.__match_5, align 8
  store i64 %p0, ptr %slot.score, align 8
  %t0 = icmp eq i64 %p0, 100
  br i1 %t0, label %arm0_body2, label %arm0_next3

arm0_body2:
  %t1 = getelementptr inbounds [8 x i8], ptr @.str.4, i64 0, i64 0
  %r7 = ptrtoint ptr %t1 to i64
  %t2 = load i64, ptr %slot.__match_3, align 8
  call void @nova_rc_dec(i64 %t2)
  store i64 %r7, ptr %slot.__match_3, align 8
  br label %match_merge1

arm0_next3:
  br label %arm1_body4

arm1_body4:
  %r9 = load i64, ptr %slot.score, align 8
  %t3 = icmp sge i64 %r9, 90
  %r11 = zext i1 %t3 to i64
  %t4 = icmp eq i64 %r11, 1
  br i1 %t4, label %arm0_body6, label %arm0_next7

arm0_body6:
  %t5 = getelementptr inbounds [2 x i8], ptr @.str.5, i64 0, i64 0
  %r15 = ptrtoint ptr %t5 to i64
  %t6 = load i64, ptr %slot.__match_4, align 8
  call void @nova_rc_dec(i64 %t6)
  store i64 %r15, ptr %slot.__match_4, align 8
  br label %match_merge5

arm0_next7:
  br label %arm1_body8

arm1_body8:
  %r17 = load i64, ptr %slot.score, align 8
  %t7 = icmp sge i64 %r17, 80
  %r19 = zext i1 %t7 to i64
  %t8 = icmp eq i64 %r19, 1
  br i1 %t8, label %arm0_body10, label %arm0_next11

arm0_body10:
  %t9 = getelementptr inbounds [2 x i8], ptr @.str.6, i64 0, i64 0
  %r23 = ptrtoint ptr %t9 to i64
  %t10 = load i64, ptr %slot.__match_5, align 8
  call void @nova_rc_dec(i64 %t10)
  store i64 %r23, ptr %slot.__match_5, align 8
  br label %match_merge9

arm0_next11:
  br label %arm1_body12

arm1_body12:
  %t11 = getelementptr inbounds [2 x i8], ptr @.str.7, i64 0, i64 0
  %r25 = ptrtoint ptr %t11 to i64
  %t12 = load i64, ptr %slot.__match_5, align 8
  call void @nova_rc_dec(i64 %t12)
  store i64 %r25, ptr %slot.__match_5, align 8
  br label %match_merge9

match_merge9:
  %r27 = load i64, ptr %slot.__match_5, align 8
  %t13 = load i64, ptr %slot.__match_4, align 8
  call void @nova_rc_dec(i64 %t13)
  call void @nova_rc_inc(i64 %r27)
  store i64 %r27, ptr %slot.__match_4, align 8
  br label %match_merge5

match_merge5:
  %r29 = load i64, ptr %slot.__match_4, align 8
  %t14 = load i64, ptr %slot.__match_3, align 8
  call void @nova_rc_dec(i64 %t14)
  call void @nova_rc_inc(i64 %r29)
  store i64 %r29, ptr %slot.__match_3, align 8
  br label %match_merge1

match_merge1:
  %r31 = load i64, ptr %slot.__match_3, align 8
  call void @nova_rc_inc(i64 %r31)
  %t15 = load i64, ptr %slot.__match_3, align 8
  call void @nova_rc_dec(i64 %t15)
  %t16 = load i64, ptr %slot.__match_4, align 8
  call void @nova_rc_dec(i64 %t16)
  %t17 = load i64, ptr %slot.__match_5, align 8
  call void @nova_rc_dec(i64 %t17)
  ret i64 %r31
}

define i64 @nova_main() {
entry0:
  %r1 = call i64 @fizzbuzz(i64 15)
  %t0 = inttoptr i64 %r1 to ptr
  call i32 @puts(ptr %t0)
  %r4 = call i64 @fizzbuzz(i64 9)
  %t1 = inttoptr i64 %r4 to ptr
  call i32 @puts(ptr %t1)
  %r7 = call i64 @fizzbuzz(i64 10)
  %t2 = inttoptr i64 %r7 to ptr
  call i32 @puts(ptr %t2)
  %r10 = call i64 @fizzbuzz(i64 7)
  %t3 = inttoptr i64 %r10 to ptr
  call i32 @puts(ptr %t3)
  %r13 = call i64 @grade(i64 100)
  %t4 = inttoptr i64 %r13 to ptr
  call i32 @puts(ptr %t4)
  %r16 = call i64 @grade(i64 95)
  %t5 = inttoptr i64 %r16 to ptr
  call i32 @puts(ptr %t5)
  %r19 = call i64 @grade(i64 85)
  %t6 = inttoptr i64 %r19 to ptr
  call i32 @puts(ptr %t6)
  %r22 = call i64 @grade(i64 70)
  %t7 = inttoptr i64 %r22 to ptr
  call i32 @puts(ptr %t7)
  ret i64 0
}

define i32 @main() {
entry:
  call void @nova_rt_init()
  call i64 @nova_main()
  call void @nova_rt_wait_all()
  call void @nova_rt_cleanup()
  ret i32 0
}

!0 = !{!"NOVA TBAA"}
!1 = !{!"list_data_ptr", !0}
!2 = !{!1, !1, i64 0}
!3 = !{!"list_elem", !0}
!4 = !{!3, !3, i64 0}
!5 = !{!"list_size", !0}
!6 = !{!5, !5, i64 0}
!7 = !{!"list_cap", !0}
!8 = !{!7, !7, i64 0}
