; Generated by NOVA compiler
target triple = "x86_64-pc-windows-msvc"

declare i32 @printf(ptr, ...)
declare i32 @puts(ptr)
declare noalias ptr @malloc(i64) nounwind allocsize(0)
declare noalias ptr @calloc(i64, i64) nounwind
declare ptr @realloc(ptr, i64) nounwind allocsize(1)
declare void @free(ptr)
declare i64 @llvm.smax.i64(i64, i64) nounwind readnone
; nova runtime — list ops
declare i64 @nova_rt_list_create()
declare i64 @nova_rt_list_create_filled(i64, i64)
declare i64 @nova_rt_list_append(i64, i64)
declare i64 @nova_rt_list_get(i64, i64)
declare i64 @nova_rt_list_set(i64, i64, i64)
declare i64 @nova_rt_list_len(i64)
declare i64 @nova_rt_list_print(i64)
declare i64 @nova_rt_iter_has_next(i64, i64)
declare i64 @nova_rt_iter_get(i64, i64)
; nova runtime — string ops
declare i64 @nova_rt_str_concat(i64, i64)
declare i64 @nova_rt_int_to_str(i64)
declare i64 @nova_rt_float_to_str(i64)
declare i64 @nova_rt_bool_to_str(i64)
declare i64 @nova_rt_str_len(i64)
declare i64 @nova_rt_len(i64)
declare i64 @nova_rt_contains(i64, i64)
declare i64 @nova_rt_slice(i64, i64, i64)
declare i64 @nova_rt_upper(i64)
declare i64 @nova_rt_lower(i64)
declare i64 @nova_rt_trim(i64)
declare i64 @nova_rt_split(i64, i64)
declare i64 @nova_rt_replace(i64, i64, i64)
declare i64 @nova_rt_starts_with(i64, i64)
declare i64 @nova_rt_ends_with(i64, i64)
declare i64 @nova_rt_find(i64, i64)
declare i64 @nova_rt_join(i64, i64)
declare i64 @nova_rt_chars(i64)
; nova runtime — list stdlib
declare i64 @nova_rt_list_reverse(i64)
declare i64 @nova_rt_list_sort(i64)
declare i64 @nova_rt_list_map(i64, i64)
declare i64 @nova_rt_list_filter(i64, i64)
declare i64 @nova_rt_list_concat(i64, i64)
declare i64 @nova_rt_list_slice(i64, i64, i64)
declare i64 @nova_rt_list_to_str(i64)
declare i64 @nova_rt_len_any(i64)
; nova runtime — type conversions
declare i64 @nova_rt_parse_int(i64)
declare i64 @nova_rt_parse_float(i64)
; nova runtime — character ops
declare i64 @nova_rt_ord(i64)
declare i64 @nova_rt_chr(i64)
; nova runtime — process control
declare void @nova_rt_exit(i64)
declare i32 @strcmp(ptr, ptr)
; nova runtime — dict ops (Phase 1: ordered array, O(n) lookup)
declare i64 @nova_rt_dict_create()
declare i64 @nova_rt_dict_set(i64, i64, i64)
declare i64 @nova_rt_dict_get(i64, i64)
declare i64 @nova_rt_dict_has(i64, i64)
declare i64 @nova_rt_dict_del(i64, i64)
declare i64 @nova_rt_dict_len(i64)
declare i64 @nova_rt_dict_keys(i64)
declare i64 @nova_rt_dict_values(i64)
declare i64 @nova_rt_dict_items(i64)
; nova runtime — IO ops
declare i64 @nova_rt_read_line()
declare i64 @nova_rt_read_file(i64)
declare i64 @nova_rt_write_file(i64, i64)
declare i64 @nova_rt_append_file(i64, i64)
declare i64 @nova_rt_file_exists(i64)
; nova runtime — JSON ops
declare i64 @nova_rt_json_parse(i64)
declare i64 @nova_rt_json_stringify(i64)
; nova runtime — HTTP ops
declare i64 @nova_rt_http_get(i64)
declare i64 @nova_rt_http_post(i64, i64, i64)
; nova runtime — type dispatch
declare i64 @nova_rt_any_to_str(i64)
declare i64 @nova_rt_str_concat_safe(i64, i64)
declare void @nova_rt_init()
; nova runtime — channel/spawn ops
declare i64 @nova_rt_channel_create()
declare i64 @nova_rt_channel_send(i64, i64)
declare i64 @nova_rt_channel_recv(i64)
declare i64 @nova_rt_channel_close(i64)
declare i64 @nova_rt_channel_select(i64, i64)
declare i64 @nova_rt_channel_recv_timeout(i64, i64)
declare i64 @nova_rt_spawn(i64, i64)
declare i64 @nova_rt_monitor(i64)
declare void @nova_rt_wait_all()
; nova runtime — math (trig/log via C runtime for non-intrinsic functions)
declare i64 @nova_rt_tan(i64)
declare i64 @nova_rt_asin(i64)
declare i64 @nova_rt_acos(i64)
declare i64 @nova_rt_atan(i64)
declare i64 @nova_rt_atan2(i64, i64)
declare i64 @nova_rt_fmod(i64, i64)
declare i64 @nova_rt_int_pow(i64, i64)
; nova runtime — memory management
declare void @nova_rt_cleanup()
declare void @nova_rt_track_raw(ptr)
declare i64 @nova_rt_alloc_count()
declare i64 @nova_rt_live_count()
; nova runtime — reference counting
declare void @nova_rc_inc(i64)
declare void @nova_rc_dec(i64)
; nova error state — thread-local flag (safe for spawn/concurrent programs)
@__nova_error_flag = thread_local global i64 0
@__nova_error_msg = thread_local global i64 0

@.str.0 = private unnamed_addr constant [20 x i8] c"--- Integer ops ---\00"
@.str.1 = private unnamed_addr constant [18 x i8] c"--- Float ops ---\00"
@.str.2 = private unnamed_addr constant [26 x i8] c"--- Mixed computation ---\00"
@.str.3 = private unnamed_addr constant [6 x i8] c"%lld\0A\00"
@.str.4 = private unnamed_addr constant [4 x i8] c"%f\0A\00"
@.str.5 = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.str.6 = private unnamed_addr constant [5 x i8] c"true\00"
@.str.7 = private unnamed_addr constant [6 x i8] c"false\00"

define i64 @isEven(i64 %p0) {
entry0:
  %slot.n = alloca i64, align 8
  store i64 %p0, ptr %slot.n, align 8
  %r5 = srem i64 %p0, 2
  %t0 = icmp eq i64 %r5, 0
  %r7 = zext i1 %t0 to i64
  ret i64 %r7
}

define i64 @toFloat(i64 %p0) {
entry0:
  %slot.n = alloca i64, align 8
  store i64 %p0, ptr %slot.n, align 8
  %t0 = sitofp i64 %p0 to double
  %t1 = bitcast i64 4607182418800017408 to double
  %t2 = fmul double %t0, %t1
  %r5 = bitcast double %t2 to i64
  ret i64 %r5
}

define i64 @sqrtApprox(i64 %p0) {
entry0:
  %slot.x = alloca i64, align 8
  %slot.g = alloca i64, align 8
  store i64 %p0, ptr %slot.x, align 8
  %t0 = bitcast i64 %p0 to double
  %t1 = bitcast i64 4611686018427387904 to double
  %t2 = fdiv double %t0, %t1
  %r5 = bitcast double %t2 to i64
  store i64 %r5, ptr %slot.g, align 8
  %t3 = bitcast i64 %p0 to double
  %t4 = bitcast i64 %r5 to double
  %t5 = fdiv double %t3, %t4
  %r12 = bitcast double %t5 to i64
  %t6 = bitcast i64 %r5 to double
  %t7 = bitcast i64 %r12 to double
  %t8 = fadd double %t6, %t7
  %r13 = bitcast double %t8 to i64
  %t9 = bitcast i64 %r13 to double
  %t10 = bitcast i64 4611686018427387904 to double
  %t11 = fdiv double %t9, %t10
  %r15 = bitcast double %t11 to i64
  store i64 %r15, ptr %slot.g, align 8
  %t12 = bitcast i64 %p0 to double
  %t13 = bitcast i64 %r15 to double
  %t14 = fdiv double %t12, %t13
  %r21 = bitcast double %t14 to i64
  %t15 = bitcast i64 %r15 to double
  %t16 = bitcast i64 %r21 to double
  %t17 = fadd double %t15, %t16
  %r22 = bitcast double %t17 to i64
  %t18 = bitcast i64 %r22 to double
  %t19 = bitcast i64 4611686018427387904 to double
  %t20 = fdiv double %t18, %t19
  %r24 = bitcast double %t20 to i64
  store i64 %r24, ptr %slot.g, align 8
  %t21 = bitcast i64 %p0 to double
  %t22 = bitcast i64 %r24 to double
  %t23 = fdiv double %t21, %t22
  %r30 = bitcast double %t23 to i64
  %t24 = bitcast i64 %r24 to double
  %t25 = bitcast i64 %r30 to double
  %t26 = fadd double %t24, %t25
  %r31 = bitcast double %t26 to i64
  %t27 = bitcast i64 %r31 to double
  %t28 = bitcast i64 4611686018427387904 to double
  %t29 = fdiv double %t27, %t28
  %r33 = bitcast double %t29 to i64
  store i64 %r33, ptr %slot.g, align 8
  %t30 = bitcast i64 %p0 to double
  %t31 = bitcast i64 %r33 to double
  %t32 = fdiv double %t30, %t31
  %r39 = bitcast double %t32 to i64
  %t33 = bitcast i64 %r33 to double
  %t34 = bitcast i64 %r39 to double
  %t35 = fadd double %t33, %t34
  %r40 = bitcast double %t35 to i64
  %t36 = bitcast i64 %r40 to double
  %t37 = bitcast i64 4611686018427387904 to double
  %t38 = fdiv double %t36, %t37
  %r42 = bitcast double %t38 to i64
  store i64 %r42, ptr %slot.g, align 8
  %t39 = bitcast i64 %p0 to double
  %t40 = bitcast i64 %r42 to double
  %t41 = fdiv double %t39, %t40
  %r48 = bitcast double %t41 to i64
  %t42 = bitcast i64 %r42 to double
  %t43 = bitcast i64 %r48 to double
  %t44 = fadd double %t42, %t43
  %r49 = bitcast double %t44 to i64
  %t45 = bitcast i64 %r49 to double
  %t46 = bitcast i64 4611686018427387904 to double
  %t47 = fdiv double %t45, %t46
  %r51 = bitcast double %t47 to i64
  store i64 %r51, ptr %slot.g, align 8
  ret i64 %r51
}

define i64 @distance(i64 %p0, i64 %p1, i64 %p2, i64 %p3) {
entry0:
  %slot.x1 = alloca i64, align 8
  %slot.y1 = alloca i64, align 8
  %slot.x2 = alloca i64, align 8
  %slot.y2 = alloca i64, align 8
  %slot.dx = alloca i64, align 8
  %slot.dy = alloca i64, align 8
  store i64 %p0, ptr %slot.x1, align 8
  store i64 %p1, ptr %slot.y1, align 8
  store i64 %p2, ptr %slot.x2, align 8
  store i64 %p3, ptr %slot.y2, align 8
  %t0 = bitcast i64 %p2 to double
  %t1 = bitcast i64 %p0 to double
  %t2 = fsub double %t0, %t1
  %r11 = bitcast double %t2 to i64
  store i64 %r11, ptr %slot.dx, align 8
  %t3 = bitcast i64 %p3 to double
  %t4 = bitcast i64 %p1 to double
  %t5 = fsub double %t3, %t4
  %r17 = bitcast double %t5 to i64
  store i64 %r17, ptr %slot.dy, align 8
  %t6 = bitcast i64 %r11 to double
  %t7 = bitcast i64 %r11 to double
  %t8 = fmul double %t6, %t7
  %r23 = bitcast double %t8 to i64
  %t9 = bitcast i64 %r17 to double
  %t10 = bitcast i64 %r17 to double
  %t11 = fmul double %t9, %t10
  %r26 = bitcast double %t11 to i64
  %t12 = bitcast i64 %r23 to double
  %t13 = bitcast i64 %r26 to double
  %t14 = fadd double %t12, %t13
  %r27 = bitcast double %t14 to i64
  %r28 = call i64 @sqrtApprox(i64 %r27)
  ret i64 %r28
}

define i64 @power(i64 %p0, i64 %p1) {
entry0:
  %slot.base = alloca i64, align 8
  %slot.exp = alloca i64, align 8
  %slot.result = alloca i64, align 8
  %slot.i = alloca i64, align 8
  store i64 %p0, ptr %slot.base, align 8
  store i64 %p1, ptr %slot.exp, align 8
  store i64 1, ptr %slot.result, align 8
  store i64 0, ptr %slot.i, align 8
  %r29 = load i64, ptr %slot.exp, align 8
  %r30 = load i64, ptr %slot.base, align 8
  br label %while_header1

while_header1:
  %r13 = load i64, ptr %slot.i, align 8
  %t0 = icmp slt i64 %r13, %r29
  br i1 %t0, label %while_body2, label %while_exit3

while_body2:
  %r17 = load i64, ptr %slot.result, align 8
  %r19 = mul i64 %r17, %r30
  store i64 %r19, ptr %slot.result, align 8
  %r22 = load i64, ptr %slot.i, align 8
  %r24 = add i64 %r22, 1
  store i64 %r24, ptr %slot.i, align 8
  br label %while_header1

while_exit3:
  %r28 = load i64, ptr %slot.result, align 8
  ret i64 %r28
}

define i64 @nova_main() {
entry0:
  %t0 = getelementptr inbounds [20 x i8], ptr @.str.0, i64 0, i64 0
  %r0 = ptrtoint ptr %t0 to i64
  %t1 = inttoptr i64 %r0 to ptr
  call i32 @puts(ptr %t1)
  %r4 = call i64 @power(i64 2, i64 10)
  %t2 = getelementptr inbounds [5 x i8], ptr @.str.3, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t2, i64 %r4)
  %r8 = call i64 @power(i64 3, i64 5)
  %t3 = getelementptr inbounds [5 x i8], ptr @.str.3, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t3, i64 %r8)
  %r11 = call i64 @isEven(i64 42)
  %t4 = icmp ne i64 %r11, 0
  %t5 = getelementptr inbounds [5 x i8], ptr @.str.6, i64 0, i64 0
  %t6 = getelementptr inbounds [6 x i8], ptr @.str.7, i64 0, i64 0
  %t7 = select i1 %t4, ptr %t5, ptr %t6
  call i32 @puts(ptr %t7)
  %r14 = call i64 @isEven(i64 17)
  %t8 = icmp ne i64 %r14, 0
  %t9 = getelementptr inbounds [5 x i8], ptr @.str.6, i64 0, i64 0
  %t10 = getelementptr inbounds [6 x i8], ptr @.str.7, i64 0, i64 0
  %t11 = select i1 %t8, ptr %t9, ptr %t10
  call i32 @puts(ptr %t11)
  %t12 = getelementptr inbounds [18 x i8], ptr @.str.1, i64 0, i64 0
  %r16 = ptrtoint ptr %t12 to i64
  %t13 = inttoptr i64 %r16 to ptr
  call i32 @puts(ptr %t13)
  %r22 = call i64 @distance(i64 0, i64 0, i64 4613937818241073152, i64 4616189618054758400)
  %t14 = bitcast i64 %r22 to double
  %t15 = getelementptr inbounds [4 x i8], ptr @.str.4, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t15, double %t14)
  %r25 = call i64 @toFloat(i64 42)
  %t16 = bitcast i64 %r25 to double
  %t17 = getelementptr inbounds [4 x i8], ptr @.str.4, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t17, double %t16)
  %t18 = getelementptr inbounds [26 x i8], ptr @.str.2, i64 0, i64 0
  %r27 = ptrtoint ptr %t18 to i64
  %t19 = inttoptr i64 %r27 to ptr
  call i32 @puts(ptr %t19)
  %r31 = call i64 @power(i64 2, i64 20)
  %t20 = getelementptr inbounds [5 x i8], ptr @.str.3, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t20, i64 %r31)
  ret i64 0
}

define i32 @main() {
entry:
  call void @nova_rt_init()
  call i64 @nova_main()
  call void @nova_rt_wait_all()
  call void @nova_rt_cleanup()
  ret i32 0
}

!0 = !{!"NOVA TBAA"}
!1 = !{!"list_data_ptr", !0}
!2 = !{!1, !1, i64 0}
!3 = !{!"list_elem", !0}
!4 = !{!3, !3, i64 0}
!5 = !{!"list_size", !0}
!6 = !{!5, !5, i64 0}
!7 = !{!"list_cap", !0}
!8 = !{!7, !7, i64 0}
