[package]
name = "nova-compiler"
version = "0.1.0"
description = "The NOVA self-hosted compiler"
author = "mangesh.mane"

[dependencies]
# Dependencies are listed as name = "version"
# Example:
# json = "0.1.0"
# http = "0.2.1"
