; Generated by NOVA compiler
target triple = "x86_64-pc-windows-msvc"

declare i32 @printf(ptr, ...)
declare i32 @puts(ptr)
declare noalias ptr @malloc(i64) nounwind allocsize(0)
declare noalias ptr @calloc(i64, i64) nounwind
declare ptr @realloc(ptr, i64) nounwind allocsize(1)
declare void @free(ptr)
declare i64 @llvm.smax.i64(i64, i64) nounwind readnone
; nova runtime — list ops
declare i64 @nova_rt_list_create()
declare i64 @nova_rt_list_create_filled(i64, i64)
declare i64 @nova_rt_list_append(i64, i64)
declare i64 @nova_rt_list_get(i64, i64)
declare i64 @nova_rt_list_set(i64, i64, i64)
declare i64 @nova_rt_list_len(i64)
declare i64 @nova_rt_list_print(i64)
declare i64 @nova_rt_iter_has_next(i64, i64)
declare i64 @nova_rt_iter_get(i64, i64)
; nova runtime — string ops
declare i64 @nova_rt_str_concat(i64, i64)
declare i64 @nova_rt_int_to_str(i64)
declare i64 @nova_rt_float_to_str(i64)
declare i64 @nova_rt_bool_to_str(i64)
declare i64 @nova_rt_str_len(i64)
declare i64 @nova_rt_len(i64)
declare i64 @nova_rt_contains(i64, i64)
declare i64 @nova_rt_slice(i64, i64, i64)
declare i64 @nova_rt_upper(i64)
declare i64 @nova_rt_lower(i64)
declare i64 @nova_rt_trim(i64)
declare i64 @nova_rt_split(i64, i64)
declare i64 @nova_rt_replace(i64, i64, i64)
declare i64 @nova_rt_starts_with(i64, i64)
declare i64 @nova_rt_ends_with(i64, i64)
declare i64 @nova_rt_find(i64, i64)
declare i64 @nova_rt_join(i64, i64)
declare i64 @nova_rt_chars(i64)
; nova runtime — list stdlib
declare i64 @nova_rt_list_reverse(i64)
declare i64 @nova_rt_list_sort(i64)
declare i64 @nova_rt_list_map(i64, i64)
declare i64 @nova_rt_list_filter(i64, i64)
declare i64 @nova_rt_list_concat(i64, i64)
declare i64 @nova_rt_list_slice(i64, i64, i64)
declare i64 @nova_rt_list_to_str(i64)
declare i64 @nova_rt_len_any(i64)
; nova runtime — type conversions
declare i64 @nova_rt_parse_int(i64)
declare i64 @nova_rt_parse_float(i64)
; nova runtime — character ops
declare i64 @nova_rt_ord(i64)
declare i64 @nova_rt_chr(i64)
; nova runtime — process control
declare void @nova_rt_exit(i64)
declare i32 @strcmp(ptr, ptr)
; nova runtime — dict ops (Phase 1: ordered array, O(n) lookup)
declare i64 @nova_rt_dict_create()
declare i64 @nova_rt_dict_set(i64, i64, i64)
declare i64 @nova_rt_dict_get(i64, i64)
declare i64 @nova_rt_dict_has(i64, i64)
declare i64 @nova_rt_dict_del(i64, i64)
declare i64 @nova_rt_dict_len(i64)
declare i64 @nova_rt_dict_keys(i64)
declare i64 @nova_rt_dict_values(i64)
declare i64 @nova_rt_dict_items(i64)
; nova runtime — IO ops
declare i64 @nova_rt_read_line()
declare i64 @nova_rt_read_file(i64)
declare i64 @nova_rt_write_file(i64, i64)
declare i64 @nova_rt_append_file(i64, i64)
declare i64 @nova_rt_file_exists(i64)
; nova runtime — JSON ops
declare i64 @nova_rt_json_parse(i64)
declare i64 @nova_rt_json_stringify(i64)
; nova runtime — HTTP ops
declare i64 @nova_rt_http_get(i64)
declare i64 @nova_rt_http_post(i64, i64, i64)
; nova runtime — type dispatch
declare i64 @nova_rt_any_to_str(i64)
declare i64 @nova_rt_str_concat_safe(i64, i64)
declare void @nova_rt_init()
; nova runtime — channel/spawn ops
declare i64 @nova_rt_channel_create()
declare i64 @nova_rt_channel_send(i64, i64)
declare i64 @nova_rt_channel_recv(i64)
declare i64 @nova_rt_channel_close(i64)
declare i64 @nova_rt_channel_select(i64, i64)
declare i64 @nova_rt_channel_recv_timeout(i64, i64)
declare i64 @nova_rt_spawn(i64, i64)
declare i64 @nova_rt_monitor(i64)
declare void @nova_rt_wait_all()
; nova runtime — math (trig/log via C runtime for non-intrinsic functions)
declare i64 @nova_rt_tan(i64)
declare i64 @nova_rt_asin(i64)
declare i64 @nova_rt_acos(i64)
declare i64 @nova_rt_atan(i64)
declare i64 @nova_rt_atan2(i64, i64)
declare i64 @nova_rt_fmod(i64, i64)
declare i64 @nova_rt_int_pow(i64, i64)
; nova runtime — memory management
declare void @nova_rt_cleanup()
declare void @nova_rt_track_raw(ptr)
declare i64 @nova_rt_alloc_count()
declare i64 @nova_rt_live_count()
; nova runtime — reference counting
declare void @nova_rc_inc(i64)
declare void @nova_rc_dec(i64)
; nova error state — thread-local flag (safe for spawn/concurrent programs)
@__nova_error_flag = thread_local global i64 0
@__nova_error_msg = thread_local global i64 0

@.str.0 = private unnamed_addr constant [6 x i8] c"hello\00"
@.str.1 = private unnamed_addr constant [6 x i8] c"WORLD\00"
@.str.2 = private unnamed_addr constant [10 x i8] c"unused_ok\00"
@.str.3 = private unnamed_addr constant [3 x i8] c"hi\00"
@.str.4 = private unnamed_addr constant [4 x i8] c"BYE\00"
@.str.5 = private unnamed_addr constant [17 x i8] c"all_rc_stress_ok\00"
@.str.6 = private unnamed_addr constant [6 x i8] c"%lld\0A\00"
@.str.7 = private unnamed_addr constant [4 x i8] c"%f\0A\00"
@.str.8 = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.str.9 = private unnamed_addr constant [5 x i8] c"true\00"
@.str.10 = private unnamed_addr constant [6 x i8] c"false\00"

define i64 @test_loop_temps() {
entry0:
  %slot.total = alloca i64, align 8
  %slot.__range_idx_1 = alloca i64, align 8
  %slot.__range_end_1 = alloca i64, align 8
  %slot.i = alloca i64, align 8
  store i64 0, ptr %slot.total, align 8
  store i64 0, ptr %slot.__range_idx_1, align 8
  store i64 999, ptr %slot.__range_end_1, align 8
  %r38 = load i64, ptr %slot.__range_end_1, align 8
  br label %range_header1

range_header1:
  %r11 = load i64, ptr %slot.__range_idx_1, align 8
  %t0 = icmp sle i64 %r11, %r38
  br i1 %t0, label %range_body2, label %range_exit3

range_body2:
  %r14 = load i64, ptr %slot.__range_idx_1, align 8
  store i64 %r14, ptr %slot.i, align 8
  %r18 = load i64, ptr %slot.total, align 8
  %r22 = add i64 %r14, 1
  %r25 = add i64 %r14, 2
  %r26 = call i64 @nova_rt_list_create()
  %t1 = call i64 @nova_rt_list_append(i64 %r26, i64 %r14)
  %t2 = call i64 @nova_rt_list_append(i64 %r26, i64 %r22)
  %t3 = call i64 @nova_rt_list_append(i64 %r26, i64 %r25)
  %r27 = call i64 @nova_rt_list_len(i64 %r26)
  call void @nova_rc_dec(i64 %r26)
  %r28 = add i64 %r18, %r27
  store i64 %r28, ptr %slot.total, align 8
  %r31 = load i64, ptr %slot.__range_idx_1, align 8
  %r32 = add i64 %r31, 1
  store i64 %r32, ptr %slot.__range_idx_1, align 8
  br label %range_header1

range_exit3:
  %r36 = load i64, ptr %slot.total, align 8
  %t4 = getelementptr inbounds [5 x i8], ptr @.str.6, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t4, i64 %r36)
  ret i64 0
}

define i64 @test_nested_chains() {
entry0:
  %slot.result = alloca i64, align 8
  %r6 = call i64 @nova_rt_list_create()
  %t0 = call i64 @nova_rt_list_append(i64 %r6, i64 5)
  %t1 = call i64 @nova_rt_list_append(i64 %r6, i64 4)
  %t2 = call i64 @nova_rt_list_append(i64 %r6, i64 3)
  %t3 = call i64 @nova_rt_list_append(i64 %r6, i64 2)
  %t4 = call i64 @nova_rt_list_append(i64 %r6, i64 1)
  %r7 = call i64 @nova_rt_list_reverse(i64 %r6)
  call void @nova_rc_dec(i64 %r6)
  %r8 = call i64 @nova_rt_list_reverse(i64 %r7)
  call void @nova_rc_dec(i64 %r7)
  %r9 = call i64 @nova_rt_list_reverse(i64 %r8)
  call void @nova_rc_dec(i64 %r8)
  %r10 = call i64 @nova_rt_list_len(i64 %r9)
  call void @nova_rc_dec(i64 %r9)
  store i64 %r10, ptr %slot.result, align 8
  %t5 = getelementptr inbounds [5 x i8], ptr @.str.6, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t5, i64 %r10)
  ret i64 0
}

define i64 @test_string_loop() {
entry0:
  %slot.count = alloca i64, align 8
  %slot.__range_idx_1 = alloca i64, align 8
  %slot.__range_end_1 = alloca i64, align 8
  %slot.i = alloca i64, align 8
  %slot.n = alloca i64, align 8
  store i64 0, ptr %slot.count, align 8
  store i64 0, ptr %slot.__range_idx_1, align 8
  store i64 99, ptr %slot.__range_end_1, align 8
  %r39 = load i64, ptr %slot.__range_end_1, align 8
  br label %range_header1

range_header1:
  %r11 = load i64, ptr %slot.__range_idx_1, align 8
  %t0 = icmp sle i64 %r11, %r39
  br i1 %t0, label %range_body2, label %range_exit3

range_body2:
  %r14 = load i64, ptr %slot.__range_idx_1, align 8
  store i64 %r14, ptr %slot.i, align 8
  %t1 = getelementptr inbounds [6 x i8], ptr @.str.0, i64 0, i64 0
  %r18 = ptrtoint ptr %t1 to i64
  %r19 = call i64 @nova_rt_upper(i64 %r18)
  %t2 = getelementptr inbounds [6 x i8], ptr @.str.1, i64 0, i64 0
  %r20 = ptrtoint ptr %t2 to i64
  %r21 = call i64 @nova_rt_lower(i64 %r20)
  %r22 = call i64 @nova_rt_str_concat(i64 %r19, i64 %r21)
  call void @nova_rc_dec(i64 %r19)
  call void @nova_rc_dec(i64 %r21)
  %r23 = call i64 @nova_rt_len(i64 %r22)
  call void @nova_rc_dec(i64 %r22)
  store i64 %r23, ptr %slot.n, align 8
  %r27 = load i64, ptr %slot.count, align 8
  %r29 = add i64 %r27, %r23
  store i64 %r29, ptr %slot.count, align 8
  %r32 = load i64, ptr %slot.__range_idx_1, align 8
  %r33 = add i64 %r32, 1
  store i64 %r33, ptr %slot.__range_idx_1, align 8
  br label %range_header1

range_exit3:
  %r37 = load i64, ptr %slot.count, align 8
  %t3 = getelementptr inbounds [5 x i8], ptr @.str.6, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t3, i64 %r37)
  ret i64 0
}

define i64 @test_unused_temps() {
entry0:
  %t0 = getelementptr inbounds [6 x i8], ptr @.str.0, i64 0, i64 0
  %r5 = ptrtoint ptr %t0 to i64
  %r6 = call i64 @nova_rt_upper(i64 %r5)
  call void @nova_rc_dec(i64 %r6)
  %r9 = call i64 @nova_rt_list_create()
  %t1 = call i64 @nova_rt_list_append(i64 %r9, i64 10)
  %t2 = call i64 @nova_rt_list_append(i64 %r9, i64 20)
  %r10 = call i64 @nova_rt_list_reverse(i64 %r9)
  call void @nova_rc_dec(i64 %r9)
  call void @nova_rc_dec(i64 %r10)
  %t3 = getelementptr inbounds [10 x i8], ptr @.str.2, i64 0, i64 0
  %r11 = ptrtoint ptr %t3 to i64
  %t4 = inttoptr i64 %r11 to ptr
  call i32 @puts(ptr %t4)
  ret i64 0
}

define i64 @test_mixed_types() {
entry0:
  %slot.a = alloca i64, align 8
  %slot.b = alloca i64, align 8
  %slot.c = alloca i64, align 8
  %r6 = call i64 @nova_rt_list_create()
  %t0 = call i64 @nova_rt_list_append(i64 %r6, i64 1)
  %t1 = call i64 @nova_rt_list_append(i64 %r6, i64 2)
  %t2 = call i64 @nova_rt_list_append(i64 %r6, i64 3)
  %t3 = call i64 @nova_rt_list_append(i64 %r6, i64 4)
  %t4 = call i64 @nova_rt_list_append(i64 %r6, i64 5)
  %r7 = call i64 @nova_rt_list_len(i64 %r6)
  call void @nova_rc_dec(i64 %r6)
  store i64 %r7, ptr %slot.a, align 8
  %t5 = getelementptr inbounds [3 x i8], ptr @.str.3, i64 0, i64 0
  %r11 = ptrtoint ptr %t5 to i64
  %r12 = call i64 @nova_rt_upper(i64 %r11)
  %t6 = getelementptr inbounds [4 x i8], ptr @.str.4, i64 0, i64 0
  %r13 = ptrtoint ptr %t6 to i64
  %r14 = call i64 @nova_rt_lower(i64 %r13)
  %r15 = call i64 @nova_rt_str_concat(i64 %r12, i64 %r14)
  call void @nova_rc_dec(i64 %r12)
  call void @nova_rc_dec(i64 %r14)
  %r16 = call i64 @nova_rt_len(i64 %r15)
  call void @nova_rc_dec(i64 %r15)
  store i64 %r16, ptr %slot.b, align 8
  %r23 = call i64 @nova_rt_list_create()
  %t7 = call i64 @nova_rt_list_append(i64 %r23, i64 10)
  %t8 = call i64 @nova_rt_list_append(i64 %r23, i64 20)
  %t9 = call i64 @nova_rt_list_append(i64 %r23, i64 30)
  %r24 = call i64 @nova_rt_list_reverse(i64 %r23)
  call void @nova_rc_dec(i64 %r23)
  %r25 = call i64 @nova_rt_list_len(i64 %r24)
  call void @nova_rc_dec(i64 %r24)
  store i64 %r25, ptr %slot.c, align 8
  %r31 = add i64 %r7, %r16
  %r33 = add i64 %r31, %r25
  %t10 = getelementptr inbounds [5 x i8], ptr @.str.6, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t10, i64 %r33)
  ret i64 0
}

define i64 @test_reassignment() {
entry0:
  %slot.x = alloca i64, align 8
  store i64 0, ptr %slot.x, align 8
  %r4 = call i64 @nova_rt_list_create()
  %t0 = call i64 @nova_rt_list_append(i64 %r4, i64 1)
  %t1 = call i64 @nova_rt_list_append(i64 %r4, i64 2)
  %t2 = call i64 @nova_rt_list_append(i64 %r4, i64 3)
  %t3 = load i64, ptr %slot.x, align 8
  call void @nova_rc_dec(i64 %t3)
  store i64 %r4, ptr %slot.x, align 8
  %r12 = call i64 @nova_rt_list_create()
  %t4 = call i64 @nova_rt_list_append(i64 %r12, i64 4)
  %t5 = call i64 @nova_rt_list_append(i64 %r12, i64 5)
  %t6 = call i64 @nova_rt_list_append(i64 %r12, i64 6)
  %t7 = call i64 @nova_rt_list_append(i64 %r12, i64 7)
  %t8 = load i64, ptr %slot.x, align 8
  call void @nova_rc_dec(i64 %t8)
  store i64 %r12, ptr %slot.x, align 8
  %r17 = call i64 @nova_rt_list_create()
  %t9 = call i64 @nova_rt_list_append(i64 %r17, i64 8)
  %t10 = call i64 @nova_rt_list_append(i64 %r17, i64 9)
  %t11 = load i64, ptr %slot.x, align 8
  call void @nova_rc_dec(i64 %t11)
  store i64 %r17, ptr %slot.x, align 8
  %r21 = call i64 @nova_rt_list_len(i64 %r17)
  %t12 = getelementptr inbounds [5 x i8], ptr @.str.6, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t12, i64 %r21)
  call void @nova_rc_inc(i64 0)
  %t13 = load i64, ptr %slot.x, align 8
  call void @nova_rc_dec(i64 %t13)
  ret i64 0
}

define i64 @nova_main() {
entry0:
  %r0 = call i64 @test_loop_temps()
  %r1 = call i64 @test_nested_chains()
  %r2 = call i64 @test_string_loop()
  %r3 = call i64 @test_unused_temps()
  %r4 = call i64 @test_mixed_types()
  %r5 = call i64 @test_reassignment()
  %t0 = getelementptr inbounds [17 x i8], ptr @.str.5, i64 0, i64 0
  %r6 = ptrtoint ptr %t0 to i64
  %t1 = inttoptr i64 %r6 to ptr
  call i32 @puts(ptr %t1)
  ret i64 0
}

define i32 @main() {
entry:
  call void @nova_rt_init()
  call i64 @nova_main()
  call void @nova_rt_wait_all()
  call void @nova_rt_cleanup()
  ret i32 0
}

!0 = !{!"NOVA TBAA"}
!1 = !{!"list_data_ptr", !0}
!2 = !{!1, !1, i64 0}
!3 = !{!"list_elem", !0}
!4 = !{!3, !3, i64 0}
!5 = !{!"list_size", !0}
!6 = !{!5, !5, i64 0}
!7 = !{!"list_cap", !0}
!8 = !{!7, !7, i64 0}
