; Generated by NOVA compiler
target triple = "x86_64-pc-windows-msvc"

declare i32 @printf(ptr, ...)
declare i32 @puts(ptr)
declare noalias ptr @malloc(i64) nounwind allocsize(0)
declare noalias ptr @calloc(i64, i64) nounwind
declare ptr @realloc(ptr, i64) nounwind allocsize(1)
declare void @free(ptr)
declare i64 @llvm.smax.i64(i64, i64) nounwind readnone
; nova runtime — list ops
declare i64 @nova_rt_list_create()
declare i64 @nova_rt_list_create_filled(i64, i64)
declare i64 @nova_rt_list_append(i64, i64)
declare i64 @nova_rt_list_get(i64, i64)
declare i64 @nova_rt_list_set(i64, i64, i64)
declare i64 @nova_rt_list_len(i64)
declare i64 @nova_rt_list_print(i64)
declare i64 @nova_rt_iter_has_next(i64, i64)
declare i64 @nova_rt_iter_get(i64, i64)
; nova runtime — string ops
declare i64 @nova_rt_str_concat(i64, i64)
declare i64 @nova_rt_int_to_str(i64)
declare i64 @nova_rt_float_to_str(i64)
declare i64 @nova_rt_bool_to_str(i64)
declare i64 @nova_rt_str_len(i64)
declare i64 @nova_rt_len(i64)
declare i64 @nova_rt_contains(i64, i64)
declare i64 @nova_rt_slice(i64, i64, i64)
declare i64 @nova_rt_upper(i64)
declare i64 @nova_rt_lower(i64)
declare i64 @nova_rt_trim(i64)
declare i64 @nova_rt_split(i64, i64)
declare i64 @nova_rt_replace(i64, i64, i64)
declare i64 @nova_rt_starts_with(i64, i64)
declare i64 @nova_rt_ends_with(i64, i64)
declare i64 @nova_rt_find(i64, i64)
declare i64 @nova_rt_join(i64, i64)
declare i64 @nova_rt_chars(i64)
; nova runtime — list stdlib
declare i64 @nova_rt_list_reverse(i64)
declare i64 @nova_rt_list_sort(i64)
declare i64 @nova_rt_list_map(i64, i64)
declare i64 @nova_rt_list_filter(i64, i64)
declare i64 @nova_rt_list_concat(i64, i64)
declare i64 @nova_rt_list_slice(i64, i64, i64)
declare i64 @nova_rt_list_to_str(i64)
declare i64 @nova_rt_len_any(i64)
; nova runtime — type conversions
declare i64 @nova_rt_parse_int(i64)
declare i64 @nova_rt_parse_float(i64)
; nova runtime — character ops
declare i64 @nova_rt_ord(i64)
declare i64 @nova_rt_chr(i64)
; nova runtime — process control
declare void @nova_rt_exit(i64)
declare i32 @strcmp(ptr, ptr)
; nova runtime — dict ops (Phase 1: ordered array, O(n) lookup)
declare i64 @nova_rt_dict_create()
declare i64 @nova_rt_dict_set(i64, i64, i64)
declare i64 @nova_rt_dict_get(i64, i64)
declare i64 @nova_rt_dict_has(i64, i64)
declare i64 @nova_rt_dict_del(i64, i64)
declare i64 @nova_rt_dict_len(i64)
declare i64 @nova_rt_dict_keys(i64)
declare i64 @nova_rt_dict_values(i64)
declare i64 @nova_rt_dict_items(i64)
; nova runtime — IO ops
declare i64 @nova_rt_read_line()
declare i64 @nova_rt_read_file(i64)
declare i64 @nova_rt_write_file(i64, i64)
declare i64 @nova_rt_append_file(i64, i64)
declare i64 @nova_rt_file_exists(i64)
; nova runtime — JSON ops
declare i64 @nova_rt_json_parse(i64)
declare i64 @nova_rt_json_stringify(i64)
; nova runtime — HTTP ops
declare i64 @nova_rt_http_get(i64)
declare i64 @nova_rt_http_post(i64, i64, i64)
; nova runtime — type dispatch
declare i64 @nova_rt_any_to_str(i64)
declare i64 @nova_rt_str_concat_safe(i64, i64)
declare void @nova_rt_init()
; nova runtime — channel/spawn ops
declare i64 @nova_rt_channel_create()
declare i64 @nova_rt_channel_send(i64, i64)
declare i64 @nova_rt_channel_recv(i64)
declare i64 @nova_rt_channel_close(i64)
declare i64 @nova_rt_channel_select(i64, i64)
declare i64 @nova_rt_channel_recv_timeout(i64, i64)
declare i64 @nova_rt_spawn(i64, i64)
declare i64 @nova_rt_monitor(i64)
declare void @nova_rt_wait_all()
; nova runtime — math (trig/log via C runtime for non-intrinsic functions)
declare i64 @nova_rt_tan(i64)
declare i64 @nova_rt_asin(i64)
declare i64 @nova_rt_acos(i64)
declare i64 @nova_rt_atan(i64)
declare i64 @nova_rt_atan2(i64, i64)
declare i64 @nova_rt_fmod(i64, i64)
declare i64 @nova_rt_int_pow(i64, i64)
; nova runtime — memory management
declare void @nova_rt_cleanup()
declare void @nova_rt_track_raw(ptr)
declare i64 @nova_rt_alloc_count()
declare i64 @nova_rt_live_count()
; nova runtime — reference counting
declare void @nova_rc_inc(i64)
declare void @nova_rc_dec(i64)
; nova error state — thread-local flag (safe for spawn/concurrent programs)
@__nova_error_flag = thread_local global i64 0
@__nova_error_msg = thread_local global i64 0

@.str.0 = private unnamed_addr constant [6 x i8] c"%lld\0A\00"
@.str.1 = private unnamed_addr constant [4 x i8] c"%f\0A\00"
@.str.2 = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.str.3 = private unnamed_addr constant [5 x i8] c"true\00"
@.str.4 = private unnamed_addr constant [6 x i8] c"false\00"

define i64 @nova_main() {
entry0:
  %slot.ch1 = alloca i64, align 8
  %slot.ch2 = alloca i64, align 8
  %slot.a = alloca i64, align 8
  %slot.b = alloca i64, align 8
  store i64 0, ptr %slot.ch1, align 8
  store i64 0, ptr %slot.ch2, align 8
  store i64 0, ptr %slot.a, align 8
  store i64 0, ptr %slot.b, align 8
  %r0 = call i64 @nova_rt_channel_create()
  %t0 = load i64, ptr %slot.ch1, align 8
  call void @nova_rc_dec(i64 %t0)
  store i64 %r0, ptr %slot.ch1, align 8
  %r4 = call i64 @nova_rt_channel_create()
  %t1 = load i64, ptr %slot.ch2, align 8
  call void @nova_rc_dec(i64 %t1)
  store i64 %r4, ptr %slot.ch2, align 8
  %t2 = call ptr @malloc(i64 16)
  %t3 = ptrtoint ptr @nova_main_spawn0 to i64
  store i64 %t3, ptr %t2
  %t4 = getelementptr i64, ptr %t2, i32 1
  store i64 %r0, ptr %t4
  %t5 = ptrtoint ptr @__nova_spawn_tramp_1 to i64
  %t6 = ptrtoint ptr %t2 to i64
  %r9 = call i64 @nova_rt_spawn(i64 %t5, i64 %t6)
  %t7 = call ptr @malloc(i64 16)
  %t8 = ptrtoint ptr @nova_main_spawn1 to i64
  store i64 %t8, ptr %t7
  %t9 = getelementptr i64, ptr %t7, i32 1
  store i64 %r4, ptr %t9
  %t10 = ptrtoint ptr @__nova_spawn_tramp_1 to i64
  %t11 = ptrtoint ptr %t7 to i64
  %r11 = call i64 @nova_rt_spawn(i64 %t10, i64 %t11)
  %r13 = call i64 @nova_rt_channel_recv(i64 %r0)
  %t12 = load i64, ptr %slot.a, align 8
  call void @nova_rc_dec(i64 %t12)
  store i64 %r13, ptr %slot.a, align 8
  %r18 = call i64 @nova_rt_channel_recv(i64 %r4)
  %t13 = load i64, ptr %slot.b, align 8
  call void @nova_rc_dec(i64 %t13)
  store i64 %r18, ptr %slot.b, align 8
  %r24 = add i64 %r13, %r18
  %t14 = getelementptr inbounds [5 x i8], ptr @.str.0, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t14, i64 %r24)
  %t15 = load i64, ptr %slot.ch1, align 8
  call void @nova_rc_dec(i64 %t15)
  %t16 = load i64, ptr %slot.ch2, align 8
  call void @nova_rc_dec(i64 %t16)
  %t17 = load i64, ptr %slot.a, align 8
  call void @nova_rc_dec(i64 %t17)
  %t18 = load i64, ptr %slot.b, align 8
  call void @nova_rc_dec(i64 %t18)
  ret i64 0
}

define i64 @nova_main_spawn0(i64 %p0) {
entry0:
  %slot.ch1 = alloca i64, align 8
  %slot.sum = alloca i64, align 8
  %slot.i = alloca i64, align 8
  store i64 %p0, ptr %slot.ch1, align 8
  store i64 0, ptr %slot.sum, align 8
  store i64 1, ptr %slot.i, align 8
  br label %while_header1

while_header1:
  %r19 = load i64, ptr %slot.i, align 8
  %t0 = icmp sle i64 %r19, 50
  br i1 %t0, label %while_body2, label %while_exit3

while_body2:
  %r23 = load i64, ptr %slot.sum, align 8
  %r24 = load i64, ptr %slot.i, align 8
  %r25 = add i64 %r23, %r24
  store i64 %r25, ptr %slot.sum, align 8
  %r28 = load i64, ptr %slot.i, align 8
  %r30 = add i64 %r28, 1
  store i64 %r30, ptr %slot.i, align 8
  br label %while_header1

while_exit3:
  %r34 = load i64, ptr %slot.ch1, align 8
  %r35 = load i64, ptr %slot.sum, align 8
  %t1 = call i64 @nova_rt_channel_send(i64 %r34, i64 %r35)
  ret i64 0
}

define i64 @nova_main_spawn1(i64 %p0) {
entry0:
  %slot.ch2 = alloca i64, align 8
  %slot.sum = alloca i64, align 8
  %slot.i = alloca i64, align 8
  store i64 %p0, ptr %slot.ch2, align 8
  store i64 0, ptr %slot.sum, align 8
  store i64 51, ptr %slot.i, align 8
  br label %while_header1

while_header1:
  %r21 = load i64, ptr %slot.i, align 8
  %t0 = icmp sle i64 %r21, 100
  br i1 %t0, label %while_body2, label %while_exit3

while_body2:
  %r25 = load i64, ptr %slot.sum, align 8
  %r26 = load i64, ptr %slot.i, align 8
  %r27 = add i64 %r25, %r26
  store i64 %r27, ptr %slot.sum, align 8
  %r30 = load i64, ptr %slot.i, align 8
  %r32 = add i64 %r30, 1
  store i64 %r32, ptr %slot.i, align 8
  br label %while_header1

while_exit3:
  %r36 = load i64, ptr %slot.ch2, align 8
  %r37 = load i64, ptr %slot.sum, align 8
  %t1 = call i64 @nova_rt_channel_send(i64 %r36, i64 %r37)
  ret i64 0
}

define void @__nova_spawn_tramp_1(ptr %ctx) {
entry:
  %fn_i64 = load i64, ptr %ctx
  %fn = inttoptr i64 %fn_i64 to ptr
  %p1 = getelementptr i64, ptr %ctx, i32 1
  %a0 = load i64, ptr %p1
  call i64 %fn(i64 %a0)
  call void @free(ptr %ctx)
  ret void
}
define i32 @main() {
entry:
  call void @nova_rt_init()
  call i64 @nova_main()
  call void @nova_rt_wait_all()
  call void @nova_rt_cleanup()
  ret i32 0
}

!0 = !{!"NOVA TBAA"}
!1 = !{!"list_data_ptr", !0}
!2 = !{!1, !1, i64 0}
!3 = !{!"list_elem", !0}
!4 = !{!3, !3, i64 0}
!5 = !{!"list_size", !0}
!6 = !{!5, !5, i64 0}
!7 = !{!"list_cap", !0}
!8 = !{!7, !7, i64 0}
