; Generated by NOVA compiler
target triple = "x86_64-pc-windows-msvc"

declare i32 @printf(ptr, ...)
declare i32 @puts(ptr)
declare noalias ptr @malloc(i64) nounwind allocsize(0)
declare noalias ptr @calloc(i64, i64) nounwind
declare ptr @realloc(ptr, i64) nounwind allocsize(1)
declare void @free(ptr)
declare i64 @llvm.smax.i64(i64, i64) nounwind readnone
; nova runtime — list ops
declare i64 @nova_rt_list_create()
declare i64 @nova_rt_list_create_filled(i64, i64)
declare i64 @nova_rt_list_append(i64, i64)
declare i64 @nova_rt_list_get(i64, i64)
declare i64 @nova_rt_list_set(i64, i64, i64)
declare i64 @nova_rt_list_len(i64)
declare i64 @nova_rt_list_print(i64)
declare i64 @nova_rt_iter_has_next(i64, i64)
declare i64 @nova_rt_iter_get(i64, i64)
; nova runtime — string ops
declare i64 @nova_rt_str_concat(i64, i64)
declare i64 @nova_rt_int_to_str(i64)
declare i64 @nova_rt_float_to_str(i64)
declare i64 @nova_rt_bool_to_str(i64)
declare i64 @nova_rt_str_len(i64)
declare i64 @nova_rt_len(i64)
declare i64 @nova_rt_contains(i64, i64)
declare i64 @nova_rt_slice(i64, i64, i64)
declare i64 @nova_rt_upper(i64)
declare i64 @nova_rt_lower(i64)
declare i64 @nova_rt_trim(i64)
declare i64 @nova_rt_split(i64, i64)
declare i64 @nova_rt_replace(i64, i64, i64)
declare i64 @nova_rt_starts_with(i64, i64)
declare i64 @nova_rt_ends_with(i64, i64)
declare i64 @nova_rt_find(i64, i64)
declare i64 @nova_rt_join(i64, i64)
declare i64 @nova_rt_chars(i64)
; nova runtime — list stdlib
declare i64 @nova_rt_list_reverse(i64)
declare i64 @nova_rt_list_sort(i64)
declare i64 @nova_rt_list_map(i64, i64)
declare i64 @nova_rt_list_filter(i64, i64)
declare i64 @nova_rt_list_concat(i64, i64)
declare i64 @nova_rt_list_slice(i64, i64, i64)
declare i64 @nova_rt_list_to_str(i64)
declare i64 @nova_rt_len_any(i64)
; nova runtime — type conversions
declare i64 @nova_rt_parse_int(i64)
declare i64 @nova_rt_parse_float(i64)
; nova runtime — character ops
declare i64 @nova_rt_ord(i64)
declare i64 @nova_rt_chr(i64)
; nova runtime — process control
declare void @nova_rt_exit(i64)
declare i32 @strcmp(ptr, ptr)
; nova runtime — dict ops (Phase 1: ordered array, O(n) lookup)
declare i64 @nova_rt_dict_create()
declare i64 @nova_rt_dict_set(i64, i64, i64)
declare i64 @nova_rt_dict_get(i64, i64)
declare i64 @nova_rt_dict_has(i64, i64)
declare i64 @nova_rt_dict_del(i64, i64)
declare i64 @nova_rt_dict_len(i64)
declare i64 @nova_rt_dict_keys(i64)
declare i64 @nova_rt_dict_values(i64)
declare i64 @nova_rt_dict_items(i64)
; nova runtime — IO ops
declare i64 @nova_rt_read_line()
declare i64 @nova_rt_read_file(i64)
declare i64 @nova_rt_write_file(i64, i64)
declare i64 @nova_rt_append_file(i64, i64)
declare i64 @nova_rt_file_exists(i64)
; nova runtime — JSON ops
declare i64 @nova_rt_json_parse(i64)
declare i64 @nova_rt_json_stringify(i64)
; nova runtime — HTTP ops
declare i64 @nova_rt_http_get(i64)
declare i64 @nova_rt_http_post(i64, i64, i64)
; nova runtime — type dispatch
declare i64 @nova_rt_any_to_str(i64)
declare i64 @nova_rt_str_concat_safe(i64, i64)
declare void @nova_rt_init()
; nova runtime — channel/spawn ops
declare i64 @nova_rt_channel_create()
declare i64 @nova_rt_channel_send(i64, i64)
declare i64 @nova_rt_channel_recv(i64)
declare i64 @nova_rt_channel_close(i64)
declare i64 @nova_rt_channel_select(i64, i64)
declare i64 @nova_rt_channel_recv_timeout(i64, i64)
declare i64 @nova_rt_spawn(i64, i64)
declare i64 @nova_rt_monitor(i64)
declare void @nova_rt_wait_all()
; nova runtime — math (trig/log via C runtime for non-intrinsic functions)
declare i64 @nova_rt_tan(i64)
declare i64 @nova_rt_asin(i64)
declare i64 @nova_rt_acos(i64)
declare i64 @nova_rt_atan(i64)
declare i64 @nova_rt_atan2(i64, i64)
declare i64 @nova_rt_fmod(i64, i64)
declare i64 @nova_rt_int_pow(i64, i64)
; nova runtime — memory management
declare void @nova_rt_cleanup()
declare void @nova_rt_track_raw(ptr)
declare i64 @nova_rt_alloc_count()
declare i64 @nova_rt_live_count()
; nova runtime — reference counting
declare void @nova_rc_inc(i64)
declare void @nova_rc_dec(i64)
; nova error state — thread-local flag (safe for spawn/concurrent programs)
@__nova_error_flag = thread_local global i64 0
@__nova_error_msg = thread_local global i64 0

@.str.0 = private unnamed_addr constant [14 x i8] c"/usr/bin/nova\00"
@.str.1 = private unnamed_addr constant [5 x i8] c"/usr\00"
@.str.2 = private unnamed_addr constant [5 x i8] c"/etc\00"
@.str.3 = private unnamed_addr constant [5 x i8] c"nova\00"
@.str.4 = private unnamed_addr constant [5 x i8] c".exe\00"
@.str.5 = private unnamed_addr constant [12 x i8] c"hello world\00"
@.str.6 = private unnamed_addr constant [6 x i8] c"world\00"
@.str.7 = private unnamed_addr constant [4 x i8] c"xyz\00"
@.str.8 = private unnamed_addr constant [5 x i8] c"NOVA\00"
@.str.9 = private unnamed_addr constant [6 x i8] c"hello\00"
@.str.10 = private unnamed_addr constant [10 x i8] c"beautiful\00"
@.str.11 = private unnamed_addr constant [2 x i8] c" \00"
@.str.12 = private unnamed_addr constant [2 x i8] c"-\00"
@.str.13 = private unnamed_addr constant [8 x i8] c"a,b,c,d\00"
@.str.14 = private unnamed_addr constant [2 x i8] c",\00"
@.str.15 = private unnamed_addr constant [4 x i8] c" | \00"
@.str.16 = private unnamed_addr constant [6 x i8] c"%lld\0A\00"
@.str.17 = private unnamed_addr constant [4 x i8] c"%f\0A\00"
@.str.18 = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.str.19 = private unnamed_addr constant [5 x i8] c"true\00"
@.str.20 = private unnamed_addr constant [6 x i8] c"false\00"

define i64 @nova_main() {
entry0:
  %slot.path = alloca i64, align 8
  %slot.msg = alloca i64, align 8
  %slot.word = alloca i64, align 8
  %slot.letters = alloca i64, align 8
  %slot.__for_iter_4 = alloca i64, align 8
  %slot.__for_idx_4 = alloca i64, align 8
  %slot.ch = alloca i64, align 8
  %slot.parts = alloca i64, align 8
  %slot.csv = alloca i64, align 8
  %slot.items = alloca i64, align 8
  store i64 0, ptr %slot.path, align 8
  store i64 0, ptr %slot.msg, align 8
  store i64 0, ptr %slot.word, align 8
  store i64 0, ptr %slot.letters, align 8
  store i64 0, ptr %slot.__for_iter_4, align 8
  store i64 0, ptr %slot.ch, align 8
  store i64 0, ptr %slot.parts, align 8
  store i64 0, ptr %slot.csv, align 8
  store i64 0, ptr %slot.items, align 8
  %t0 = getelementptr inbounds [14 x i8], ptr @.str.0, i64 0, i64 0
  %r0 = ptrtoint ptr %t0 to i64
  %t1 = load i64, ptr %slot.path, align 8
  call void @nova_rc_dec(i64 %t1)
  store i64 %r0, ptr %slot.path, align 8
  %t2 = getelementptr inbounds [5 x i8], ptr @.str.1, i64 0, i64 0
  %r5 = ptrtoint ptr %t2 to i64
  %r6 = call i64 @nova_rt_starts_with(i64 %r0, i64 %r5)
  %t3 = icmp ne i64 %r6, 0
  %t4 = getelementptr inbounds [5 x i8], ptr @.str.19, i64 0, i64 0
  %t5 = getelementptr inbounds [6 x i8], ptr @.str.20, i64 0, i64 0
  %t6 = select i1 %t3, ptr %t4, ptr %t5
  call i32 @puts(ptr %t6)
  %t7 = getelementptr inbounds [5 x i8], ptr @.str.2, i64 0, i64 0
  %r9 = ptrtoint ptr %t7 to i64
  %r10 = call i64 @nova_rt_starts_with(i64 %r0, i64 %r9)
  %t8 = icmp ne i64 %r10, 0
  %t9 = getelementptr inbounds [5 x i8], ptr @.str.19, i64 0, i64 0
  %t10 = getelementptr inbounds [6 x i8], ptr @.str.20, i64 0, i64 0
  %t11 = select i1 %t8, ptr %t9, ptr %t10
  call i32 @puts(ptr %t11)
  %t12 = getelementptr inbounds [5 x i8], ptr @.str.3, i64 0, i64 0
  %r13 = ptrtoint ptr %t12 to i64
  %r14 = call i64 @nova_rt_ends_with(i64 %r0, i64 %r13)
  %t13 = icmp ne i64 %r14, 0
  %t14 = getelementptr inbounds [5 x i8], ptr @.str.19, i64 0, i64 0
  %t15 = getelementptr inbounds [6 x i8], ptr @.str.20, i64 0, i64 0
  %t16 = select i1 %t13, ptr %t14, ptr %t15
  call i32 @puts(ptr %t16)
  %t17 = getelementptr inbounds [5 x i8], ptr @.str.4, i64 0, i64 0
  %r17 = ptrtoint ptr %t17 to i64
  %r18 = call i64 @nova_rt_ends_with(i64 %r0, i64 %r17)
  %t18 = icmp ne i64 %r18, 0
  %t19 = getelementptr inbounds [5 x i8], ptr @.str.19, i64 0, i64 0
  %t20 = getelementptr inbounds [6 x i8], ptr @.str.20, i64 0, i64 0
  %t21 = select i1 %t18, ptr %t19, ptr %t20
  call i32 @puts(ptr %t21)
  %t22 = getelementptr inbounds [12 x i8], ptr @.str.5, i64 0, i64 0
  %r20 = ptrtoint ptr %t22 to i64
  %t23 = load i64, ptr %slot.msg, align 8
  call void @nova_rc_dec(i64 %t23)
  store i64 %r20, ptr %slot.msg, align 8
  %t24 = getelementptr inbounds [6 x i8], ptr @.str.6, i64 0, i64 0
  %r25 = ptrtoint ptr %t24 to i64
  %r26 = call i64 @nova_rt_find(i64 %r20, i64 %r25)
  %t25 = getelementptr inbounds [5 x i8], ptr @.str.16, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t25, i64 %r26)
  %t26 = getelementptr inbounds [4 x i8], ptr @.str.7, i64 0, i64 0
  %r29 = ptrtoint ptr %t26 to i64
  %r30 = call i64 @nova_rt_find(i64 %r20, i64 %r29)
  %t27 = getelementptr inbounds [5 x i8], ptr @.str.16, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t27, i64 %r30)
  %t28 = getelementptr inbounds [5 x i8], ptr @.str.8, i64 0, i64 0
  %r32 = ptrtoint ptr %t28 to i64
  %t29 = load i64, ptr %slot.word, align 8
  call void @nova_rc_dec(i64 %t29)
  store i64 %r32, ptr %slot.word, align 8
  %r37 = call i64 @nova_rt_chars(i64 %r32)
  %t30 = load i64, ptr %slot.letters, align 8
  call void @nova_rc_dec(i64 %t30)
  store i64 %r37, ptr %slot.letters, align 8
  %t31 = load i64, ptr %slot.__for_iter_4, align 8
  call void @nova_rc_dec(i64 %t31)
  store i64 %r37, ptr %slot.__for_iter_4, align 8
  store i64 0, ptr %slot.__for_idx_4, align 8
  %r92 = load i64, ptr %slot.__for_iter_4, align 8
  br label %for_header1

for_header1:
  %r49 = load i64, ptr %slot.__for_idx_4, align 8
  %r48 = call i64 @nova_rt_iter_has_next(i64 %r92, i64 %r49)
  %t32 = trunc i64 %r48 to i1
  br i1 %t32, label %for_body2, label %for_exit3

for_body2:
  %r51 = load i64, ptr %slot.__for_idx_4, align 8
  %t33 = inttoptr i64 %r92 to ptr
  %t34 = load ptr, ptr %t33, align 8, !tbaa !2
  %t35 = getelementptr i64, ptr %t34, i64 %r51
  %r52 = load i64, ptr %t35, align 8, !tbaa !4
  %t36 = load i64, ptr %slot.ch, align 8
  call void @nova_rc_dec(i64 %t36)
  call void @nova_rc_inc(i64 %r52)
  store i64 %r52, ptr %slot.ch, align 8
  %t37 = inttoptr i64 %r52 to ptr
  call i32 @puts(ptr %t37)
  %r58 = add i64 %r51, 1
  store i64 %r58, ptr %slot.__for_idx_4, align 8
  br label %for_header1

for_exit3:
  %t38 = getelementptr inbounds [6 x i8], ptr @.str.9, i64 0, i64 0
  %r62 = ptrtoint ptr %t38 to i64
  %t39 = getelementptr inbounds [10 x i8], ptr @.str.10, i64 0, i64 0
  %r63 = ptrtoint ptr %t39 to i64
  %t40 = getelementptr inbounds [6 x i8], ptr @.str.6, i64 0, i64 0
  %r64 = ptrtoint ptr %t40 to i64
  %r65 = call i64 @nova_rt_list_create()
  %t41 = call i64 @nova_rt_list_append(i64 %r65, i64 %r62)
  %t42 = call i64 @nova_rt_list_append(i64 %r65, i64 %r63)
  %t43 = call i64 @nova_rt_list_append(i64 %r65, i64 %r64)
  %t44 = load i64, ptr %slot.parts, align 8
  call void @nova_rc_dec(i64 %t44)
  store i64 %r65, ptr %slot.parts, align 8
  %t45 = getelementptr inbounds [2 x i8], ptr @.str.11, i64 0, i64 0
  %r70 = ptrtoint ptr %t45 to i64
  %r71 = call i64 @nova_rt_join(i64 %r65, i64 %r70)
  %t46 = inttoptr i64 %r71 to ptr
  call i32 @puts(ptr %t46)
  call void @nova_rc_dec(i64 %r71)
  %t47 = getelementptr inbounds [2 x i8], ptr @.str.12, i64 0, i64 0
  %r74 = ptrtoint ptr %t47 to i64
  %r75 = call i64 @nova_rt_join(i64 %r65, i64 %r74)
  %t48 = inttoptr i64 %r75 to ptr
  call i32 @puts(ptr %t48)
  call void @nova_rc_dec(i64 %r75)
  %t49 = getelementptr inbounds [8 x i8], ptr @.str.13, i64 0, i64 0
  %r77 = ptrtoint ptr %t49 to i64
  %t50 = load i64, ptr %slot.csv, align 8
  call void @nova_rc_dec(i64 %t50)
  store i64 %r77, ptr %slot.csv, align 8
  %t51 = getelementptr inbounds [2 x i8], ptr @.str.14, i64 0, i64 0
  %r82 = ptrtoint ptr %t51 to i64
  %r83 = call i64 @nova_rt_split(i64 %r77, i64 %r82)
  %t52 = load i64, ptr %slot.items, align 8
  call void @nova_rc_dec(i64 %t52)
  store i64 %r83, ptr %slot.items, align 8
  %t53 = getelementptr inbounds [4 x i8], ptr @.str.15, i64 0, i64 0
  %r88 = ptrtoint ptr %t53 to i64
  %r89 = call i64 @nova_rt_join(i64 %r83, i64 %r88)
  %t54 = inttoptr i64 %r89 to ptr
  call i32 @puts(ptr %t54)
  call void @nova_rc_dec(i64 %r89)
  %t55 = load i64, ptr %slot.path, align 8
  call void @nova_rc_dec(i64 %t55)
  %t56 = load i64, ptr %slot.msg, align 8
  call void @nova_rc_dec(i64 %t56)
  %t57 = load i64, ptr %slot.word, align 8
  call void @nova_rc_dec(i64 %t57)
  %t58 = load i64, ptr %slot.letters, align 8
  call void @nova_rc_dec(i64 %t58)
  %t59 = load i64, ptr %slot.__for_iter_4, align 8
  call void @nova_rc_dec(i64 %t59)
  %t60 = load i64, ptr %slot.ch, align 8
  call void @nova_rc_dec(i64 %t60)
  %t61 = load i64, ptr %slot.parts, align 8
  call void @nova_rc_dec(i64 %t61)
  %t62 = load i64, ptr %slot.csv, align 8
  call void @nova_rc_dec(i64 %t62)
  %t63 = load i64, ptr %slot.items, align 8
  call void @nova_rc_dec(i64 %t63)
  ret i64 0
}

define i32 @main() {
entry:
  call void @nova_rt_init()
  call i64 @nova_main()
  call void @nova_rt_wait_all()
  call void @nova_rt_cleanup()
  ret i32 0
}

!0 = !{!"NOVA TBAA"}
!1 = !{!"list_data_ptr", !0}
!2 = !{!1, !1, i64 0}
!3 = !{!"list_elem", !0}
!4 = !{!3, !3, i64 0}
!5 = !{!"list_size", !0}
!6 = !{!5, !5, i64 0}
!7 = !{!"list_cap", !0}
!8 = !{!7, !7, i64 0}
