[package]
name = "forge"
version = "0.1.0"
nova-version = "0.1.0"
description = "NOVA's batteries-included web framework"
author = "mangesh.mane"
license = "Apache-2.0"
repository = "https://bitbucket.org/manemangesh/nova"

[dependencies]
