; Generated by NOVA compiler
target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"

declare i32 @printf(ptr, ...)
declare i32 @puts(ptr)
declare noalias ptr @malloc(i64) nounwind allocsize(0)
declare noalias ptr @calloc(i64, i64) nounwind
declare ptr @realloc(ptr, i64) nounwind allocsize(1)
declare void @free(ptr) nounwind
declare ptr @nova_rt_struct_alloc(i64) nounwind
declare i64 @llvm.smax.i64(i64, i64) nounwind readnone
; nova runtime — list ops
declare i64 @nova_rt_list_create() nounwind
declare i64 @nova_rt_list_create_filled(i64, i64) nounwind
declare i64 @nova_rt_list_append(i64, i64) nounwind
declare i64 @nova_rt_list_get(i64, i64) nounwind readonly
declare i64 @nova_rt_list_set(i64, i64, i64) nounwind
declare i64 @nova_rt_list_len(i64) nounwind readonly
declare i64 @nova_rt_list_print(i64) nounwind
declare i64 @nova_rt_iter_has_next(i64, i64) nounwind readonly
declare i64 @nova_rt_iter_get(i64, i64) nounwind readonly
declare i64 @nova_rt_list_iter_has_next(i64, i64) nounwind readonly
declare i64 @nova_rt_list_iter_get(i64, i64) nounwind readonly
; nova runtime — string ops
declare i64 @nova_rt_str_concat(i64, i64) nounwind
declare i64 @nova_rt_int_to_str(i64) nounwind
declare i64 @nova_rt_float_to_str(i64) nounwind
declare i64 @nova_rt_bool_to_str(i64) nounwind
declare i64 @nova_rt_str_len(i64) nounwind readonly
declare i64 @nova_rt_len(i64) nounwind readonly
declare i64 @nova_rt_contains(i64, i64) nounwind readonly
declare i64 @nova_rt_slice(i64, i64, i64) nounwind
declare i64 @nova_rt_upper(i64) nounwind
declare i64 @nova_rt_lower(i64) nounwind
declare i64 @nova_rt_trim(i64) nounwind
declare i64 @nova_rt_repeat(i64, i64) nounwind
declare i64 @nova_rt_split(i64, i64) nounwind
declare i64 @nova_rt_replace(i64, i64, i64) nounwind
declare i64 @nova_rt_starts_with(i64, i64) nounwind readonly
declare i64 @nova_rt_ends_with(i64, i64) nounwind readonly
declare i64 @nova_rt_find(i64, i64) nounwind readonly
declare i64 @nova_rt_join(i64, i64) nounwind
declare i64 @nova_rt_chars(i64) nounwind
; nova runtime — list stdlib
declare i64 @nova_rt_list_reverse(i64) nounwind
declare i64 @nova_rt_list_sort(i64) nounwind
declare i64 @nova_rt_list_map(i64, i64) nounwind
declare i64 @nova_rt_list_filter(i64, i64) nounwind
declare i64 @nova_rt_list_concat(i64, i64) nounwind
declare i64 @nova_rt_list_slice(i64, i64, i64) nounwind
declare i64 @nova_rt_list_to_str(i64) nounwind
declare i64 @nova_rt_len_any(i64) nounwind readonly
; nova runtime — type conversions
declare i64 @nova_rt_parse_int(i64) nounwind
declare i64 @nova_rt_parse_float(i64) nounwind
; nova runtime — character ops
declare i64 @nova_rt_ord(i64) nounwind readonly
declare i64 @nova_rt_chr(i64) nounwind
; nova runtime — process control
declare void @nova_rt_exit(i64) noreturn nounwind
declare i64 @nova_rt_system(i64) nounwind
declare i64 @nova_rt_exec(i64) nounwind
declare i32 @strcmp(ptr, ptr) nounwind readonly
; nova runtime — dict ops (hash map, O(1) avg lookup)
declare i64 @nova_rt_dict_create() nounwind
declare i64 @nova_rt_dict_set(i64, i64, i64) nounwind
declare i64 @nova_rt_dict_get(i64, i64) nounwind readonly
declare i64 @nova_rt_dict_get_concat2(i64, i64, i64) nounwind readonly
declare i64 @nova_rt_dict_set_concat2(i64, i64, i64, i64) nounwind
declare i64 @nova_rt_dict_has(i64, i64) nounwind readonly
declare i64 @nova_rt_dict_del(i64, i64) nounwind
declare i64 @nova_rt_dict_len(i64) nounwind readonly
declare i64 @nova_rt_dict_keys(i64) nounwind
declare i64 @nova_rt_dict_values(i64) nounwind
declare i64 @nova_rt_dict_items(i64) nounwind
; nova runtime — IO ops
declare i64 @nova_rt_read_line() nounwind
declare i64 @nova_rt_read_bytes(i64) nounwind
declare i64 @nova_rt_write_raw(i64) nounwind
declare i64 @nova_rt_read_file(i64) nounwind
declare i64 @nova_rt_write_file(i64, i64) nounwind
declare i64 @nova_rt_append_file(i64, i64) nounwind
declare i64 @nova_rt_file_exists(i64) nounwind readonly
; nova runtime — JSON ops
declare i64 @nova_rt_json_parse(i64) nounwind
declare i64 @nova_rt_json_stringify(i64) nounwind
; nova runtime — HTTP ops
declare i64 @nova_rt_http_get(i64) nounwind
declare i64 @nova_rt_http_post(i64, i64, i64) nounwind
; nova runtime — time ops
declare i64 @nova_rt_time_ms() nounwind
declare i64 @nova_rt_clock_ns() nounwind
declare void @nova_rt_sleep_ms(i64) nounwind
declare void @nova_rt_assert(i64, i64) nounwind
; nova runtime — type dispatch
declare i64 @nova_rt_any_to_str(i64) nounwind
declare i64 @nova_rt_str_concat_safe(i64, i64) nounwind
declare i64 @nova_rt_str_char_at(i64, i64) nounwind
declare i64 @nova_rt_type_of(i64) nounwind
declare i64 @nova_rt_range(i64) nounwind
declare i64 @nova_rt_range_from_to(i64, i64) nounwind
declare void @nova_rt_init() nounwind
declare void @nova_rt_init_args(i64, i64) nounwind
; nova runtime — system ops
declare i64 @nova_rt_args() nounwind
declare i64 @nova_rt_env(i64) nounwind
declare i64 @nova_rt_random_int(i64, i64) nounwind
declare i64 @nova_rt_random_float() nounwind
declare i64 @nova_rt_shell(i64) nounwind
declare i64 @nova_rt_path_join(i64, i64) nounwind
declare i64 @nova_rt_path_parent(i64) nounwind
declare i64 @nova_rt_path_name(i64) nounwind
declare i64 @nova_rt_path_ext(i64) nounwind
declare i64 @nova_rt_mkdir(i64) nounwind
declare i64 @nova_rt_mkdir_p(i64) nounwind
declare i64 @nova_rt_path_exists(i64) nounwind
; nova runtime — regex ops
declare i64 @nova_rt_regex_match(i64, i64) nounwind readonly
declare i64 @nova_rt_regex_find(i64, i64) nounwind
declare i64 @nova_rt_regex_replace(i64, i64, i64) nounwind
declare i64 @nova_rt_regex_split(i64, i64) nounwind
; nova runtime — collection utilities
declare i64 @nova_rt_enumerate(i64) nounwind
declare i64 @nova_rt_zip(i64, i64) nounwind
declare i64 @nova_rt_list_sum(i64) nounwind readonly
declare i64 @nova_rt_list_any(i64) nounwind readonly
declare i64 @nova_rt_list_all(i64) nounwind readonly
declare i64 @nova_rt_list_min(i64) nounwind readonly
declare i64 @nova_rt_list_max(i64) nounwind readonly
; nova runtime — set operations
declare i64 @nova_rt_set_create() nounwind
declare i64 @nova_rt_set_add(i64, i64) nounwind
declare i64 @nova_rt_set_has(i64, i64) nounwind readonly
declare i64 @nova_rt_set_remove(i64, i64) nounwind
declare i64 @nova_rt_set_len(i64) nounwind readonly
declare i64 @nova_rt_set_to_list(i64) nounwind
; nova runtime — datetime operations
declare i64 @nova_rt_datetime_now() nounwind
declare i64 @nova_rt_datetime_format(i64, i64) nounwind
declare i64 @nova_rt_datetime_year(i64) nounwind readonly
declare i64 @nova_rt_datetime_month(i64) nounwind readonly
declare i64 @nova_rt_datetime_day(i64) nounwind readonly
declare i64 @nova_rt_datetime_hour(i64) nounwind readonly
declare i64 @nova_rt_datetime_minute(i64) nounwind readonly
declare i64 @nova_rt_datetime_second(i64) nounwind readonly
; nova runtime — network ops
declare i64 @nova_rt_tcp_connect(i64, i64) nounwind
declare i64 @nova_rt_tcp_listen(i64) nounwind
declare i64 @nova_rt_tcp_accept(i64) nounwind
declare i64 @nova_rt_tcp_send(i64, i64) nounwind
declare i64 @nova_rt_tcp_recv(i64) nounwind
declare void @nova_rt_tcp_close(i64) nounwind
declare i64 @nova_rt_udp_bind(i64) nounwind
declare i64 @nova_rt_udp_send(i64, i64, i64, i64) nounwind
declare i64 @nova_rt_udp_recv(i64) nounwind
; nova runtime — HTTP server
declare i64 @nova_rt_http_listen(i64) nounwind
declare i64 @nova_rt_http_accept(i64) nounwind
declare void @nova_rt_http_respond(i64, i64, i64) nounwind
; nova runtime — byte arrays
declare i64 @nova_rt_bytes_create(i64) nounwind
declare i64 @nova_rt_bytes_get(i64, i64) nounwind
declare void @nova_rt_bytes_set(i64, i64, i64) nounwind
declare i64 @nova_rt_bytes_len(i64) nounwind
declare i64 @nova_rt_bytes_slice(i64, i64, i64) nounwind
declare i64 @nova_rt_bytes_to_str(i64) nounwind
declare i64 @nova_rt_str_to_bytes(i64) nounwind
; nova runtime — channel/spawn ops
declare i64 @nova_rt_channel_create() nounwind
declare i64 @nova_rt_channel_send(i64, i64) nounwind
declare i64 @nova_rt_channel_recv(i64) nounwind
declare i64 @nova_rt_channel_close(i64) nounwind
declare i64 @nova_rt_channel_select(i64, i64) nounwind
declare i64 @nova_rt_channel_recv_timeout(i64, i64) nounwind
declare i64 @nova_rt_spawn(i64, i64) nounwind
declare i64 @nova_rt_monitor(i64) nounwind
declare void @nova_rt_wait_all() nounwind
; nova runtime — math (trig/log via C runtime for non-intrinsic functions)
declare i64 @nova_rt_tan(i64) nounwind
declare i64 @nova_rt_asin(i64) nounwind
declare i64 @nova_rt_acos(i64) nounwind
declare i64 @nova_rt_atan(i64) nounwind
declare i64 @nova_rt_atan2(i64, i64) nounwind
declare i64 @nova_rt_fmod(i64, i64) nounwind
declare i64 @nova_rt_int_pow(i64, i64) nounwind
; nova runtime — memory management
declare void @nova_rt_cleanup() nounwind
declare void @nova_rt_track_raw(ptr) nounwind
declare i64 @nova_rt_alloc_count() nounwind readonly
declare i64 @nova_rt_live_count() nounwind readonly
; nova runtime — reference counting
declare void @nova_rc_inc(i64) nounwind
declare void @nova_rc_dec(i64) nounwind
; nova runtime — distributed computing
declare i64 @nova_rt_serialize(i64) nounwind
declare i64 @nova_rt_deserialize(i64) nounwind
declare i64 @nova_rt_serialize_to_hex(i64) nounwind
declare i64 @nova_rt_node_listen(i64) nounwind
declare i64 @nova_rt_node_accept(i64) nounwind
declare void @nova_rt_node_stop(i64) nounwind
declare i64 @nova_rt_node_connect(i64) nounwind
declare i64 @nova_rt_remote_channel_create(i64) nounwind
declare i64 @nova_rt_remote_send(i64, i64) nounwind
declare i64 @nova_rt_remote_recv(i64) nounwind
declare void @nova_rt_remote_close(i64) nounwind
declare i64 @nova_rt_remote_spawn(i64, i64, i64) nounwind
declare i64 @nova_rt_node_recv_spawn(i64) nounwind
; nova error state — thread-local flag (safe for spawn/concurrent programs)
@__nova_error_flag = thread_local global i64 0
@__nova_error_msg = thread_local global i64 0

@.str.0 = private unnamed_addr constant [12 x i8] c"__type_hash\00"
@.str.1 = private unnamed_addr constant [5 x i8] c"kind\00"
@.str.2 = private unnamed_addr constant [6 x i8] c"value\00"
@.str.3 = private unnamed_addr constant [9 x i8] c"children\00"
@.str.4 = private unnamed_addr constant [2 x i8] c"(\00"
@.str.5 = private unnamed_addr constant [2 x i8] c")\00"
@.str.6 = private unnamed_addr constant [2 x i8] c"[\00"
@.str.7 = private unnamed_addr constant [2 x i8] c"]\00"
@.str.8 = private unnamed_addr constant [3 x i8] c", \00"
@.str.9 = private unnamed_addr constant [2 x i8] c"?\00"
@.str.10 = private unnamed_addr constant [4 x i8] c"add\00"
@.str.11 = private unnamed_addr constant [4 x i8] c"int\00"
@.str.12 = private unnamed_addr constant [2 x i8] c"3\00"
@.str.13 = private unnamed_addr constant [2 x i8] c"4\00"
@.str.14 = private unnamed_addr constant [1 x i8] c"\00"
@.str.15 = private unnamed_addr constant [2 x i8] c"x\00"
@.str.16 = private unnamed_addr constant [7 x i8] c"string\00"
@.str.17 = private unnamed_addr constant [2 x i8] c"y\00"
@.str.18 = private unnamed_addr constant [5 x i8] c"bool\00"
@.str.19 = private unnamed_addr constant [2 x i8] c"z\00"
@.str.20 = private unnamed_addr constant [8 x i8] c"unknown\00"
@.str.21 = private unnamed_addr constant [2 x i8] c"w\00"
@.str.22 = private unnamed_addr constant [6 x i8] c"%lld\0A\00"
@.str.23 = private unnamed_addr constant [4 x i8] c"%f\0A\00"
@.str.24 = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.str.25 = private unnamed_addr constant [5 x i8] c"true\00"
@.str.26 = private unnamed_addr constant [6 x i8] c"false\00"

define i64 @node_to_str(i64 %p0) nounwind {
entry0:
  %slot.n = alloca i64, align 8
  %slot.k = alloca i64, align 8
  %slot.v = alloca i64, align 8
  %slot.ch = alloca i64, align 8
  %slot.parts = alloca i64, align 8
  %slot.i = alloca i64, align 8
  store i64 0, ptr %slot.k, align 8
  store i64 0, ptr %slot.v, align 8
  store i64 0, ptr %slot.ch, align 8
  store i64 0, ptr %slot.parts, align 8
  store i64 %p0, ptr %slot.n, align 8
  %r3 = load i64, ptr %slot.n, align 8
  %t0 = inttoptr i64 %r3 to ptr
  %t1 = getelementptr i64, ptr %t0, i64 0
  %r5 = load i64, ptr %t1
  %t2 = icmp eq i64 %r5, 6384368267
  br i1 %t2, label %arm0_body2, label %match_merge1

arm0_body2:
  %t3 = inttoptr i64 %r3 to ptr
  %t4 = getelementptr i64, ptr %t3, i64 1
  %r8 = load i64, ptr %t4
  %t5 = load i64, ptr %slot.k, align 8
  call void @nova_rc_dec(i64 %t5)
  call void @nova_rc_inc(i64 %r8)
  store i64 %r8, ptr %slot.k, align 8
  %t6 = inttoptr i64 %r3 to ptr
  %t7 = getelementptr i64, ptr %t6, i64 2
  %r11 = load i64, ptr %t7
  %t8 = load i64, ptr %slot.v, align 8
  call void @nova_rc_dec(i64 %t8)
  call void @nova_rc_inc(i64 %r11)
  store i64 %r11, ptr %slot.v, align 8
  %t9 = inttoptr i64 %r3 to ptr
  %t10 = getelementptr i64, ptr %t9, i64 3
  %r14 = load i64, ptr %t10
  %t11 = load i64, ptr %slot.ch, align 8
  call void @nova_rc_dec(i64 %t11)
  call void @nova_rc_inc(i64 %r14)
  store i64 %r14, ptr %slot.ch, align 8
  %r19 = call i64 @nova_rt_list_len(i64 %r14)
  %t12 = icmp eq i64 %r19, 0
  br i1 %t12, label %ifb_then3, label %ifb_else4

ifb_then3:
  %r24 = load i64, ptr %slot.k, align 8
  %t13 = getelementptr inbounds [2 x i8], ptr @.str.4, i64 0, i64 0
  %r25 = ptrtoint ptr %t13 to i64
  %t14 = call i64 @nova_rt_str_concat(i64 %r24, i64 %r25)
  %r27 = load i64, ptr %slot.v, align 8
  %t15 = call i64 @nova_rt_str_concat(i64 %t14, i64 %r27)
  call void @nova_rc_dec(i64 %t14)
  %t16 = getelementptr inbounds [2 x i8], ptr @.str.5, i64 0, i64 0
  %r29 = ptrtoint ptr %t16 to i64
  %t17 = call i64 @nova_rt_str_concat(i64 %t15, i64 %r29)
  call void @nova_rc_dec(i64 %t15)
  call void @nova_rc_inc(i64 %t17)
  %t18 = load i64, ptr %slot.k, align 8
  call void @nova_rc_dec(i64 %t18)
  %t19 = load i64, ptr %slot.v, align 8
  call void @nova_rc_dec(i64 %t19)
  %t20 = load i64, ptr %slot.ch, align 8
  call void @nova_rc_dec(i64 %t20)
  %t21 = load i64, ptr %slot.parts, align 8
  call void @nova_rc_dec(i64 %t21)
  ret i64 %t17

ifb_else4:
  br label %ifb_merge5

ifb_merge5:
  %r36 = load i64, ptr %slot.k, align 8
  %t22 = getelementptr inbounds [2 x i8], ptr @.str.6, i64 0, i64 0
  %r37 = ptrtoint ptr %t22 to i64
  %t23 = call i64 @nova_rt_str_concat(i64 %r36, i64 %r37)
  %t24 = load i64, ptr %slot.parts, align 8
  call void @nova_rc_dec(i64 %t24)
  store i64 %t23, ptr %slot.parts, align 8
  store i64 0, ptr %slot.i, align 8
  %r86 = load i64, ptr %slot.ch, align 8
  br label %while_header7

while_header7:
  %r47 = load i64, ptr %slot.i, align 8
  %r49 = call i64 @nova_rt_list_len(i64 %r86)
  %t25 = icmp slt i64 %r47, %r49
  br i1 %t25, label %while_body8, label %while_exit9, !prof !90

while_body8:
  %r52 = load i64, ptr %slot.i, align 8
  %t26 = icmp sgt i64 %r52, 0
  br i1 %t26, label %ifb_then10, label %ifb_else11

while_exit9:
  %r80 = load i64, ptr %slot.parts, align 8
  %t27 = getelementptr inbounds [2 x i8], ptr @.str.7, i64 0, i64 0
  %r81 = ptrtoint ptr %t27 to i64
  %t28 = call i64 @nova_rt_str_concat(i64 %r80, i64 %r81)
  call void @nova_rc_inc(i64 %t28)
  %t29 = load i64, ptr %slot.k, align 8
  call void @nova_rc_dec(i64 %t29)
  %t30 = load i64, ptr %slot.v, align 8
  call void @nova_rc_dec(i64 %t30)
  %t31 = load i64, ptr %slot.ch, align 8
  call void @nova_rc_dec(i64 %t31)
  %t32 = load i64, ptr %slot.parts, align 8
  call void @nova_rc_dec(i64 %t32)
  ret i64 %t28

ifb_then10:
  %r57 = load i64, ptr %slot.parts, align 8
  %t33 = getelementptr inbounds [3 x i8], ptr @.str.8, i64 0, i64 0
  %r58 = ptrtoint ptr %t33 to i64
  %t34 = call i64 @nova_rt_str_concat(i64 %r57, i64 %r58)
  %t35 = load i64, ptr %slot.parts, align 8
  call void @nova_rc_dec(i64 %t35)
  store i64 %t34, ptr %slot.parts, align 8
  br label %ifb_merge12

ifb_else11:
  br label %ifb_merge12

ifb_merge12:
  %r66 = load i64, ptr %slot.parts, align 8
  %r68 = load i64, ptr %slot.i, align 8
  %t36 = inttoptr i64 %r86 to ptr
  %t37 = load ptr, ptr %t36, align 8, !tbaa !2
  %t38 = getelementptr i64, ptr %t37, i64 %r68
  %r69 = load i64, ptr %t38, align 8, !tbaa !4
  %r70 = call i64 @node_to_str(i64 %r69)
  %t39 = call i64 @nova_rt_str_concat(i64 %r66, i64 %r70)
  %t40 = load i64, ptr %slot.parts, align 8
  call void @nova_rc_dec(i64 %t40)
  store i64 %t39, ptr %slot.parts, align 8
  %r74 = load i64, ptr %slot.i, align 8
  %r76 = add i64 %r74, 1
  store i64 %r76, ptr %slot.i, align 8
  br label %while_header7, !llvm.loop !91

match_merge1:
  %t41 = getelementptr inbounds [2 x i8], ptr @.str.9, i64 0, i64 0
  %r85 = ptrtoint ptr %t41 to i64
  call void @nova_rc_inc(i64 %r85)
  %t42 = load i64, ptr %slot.k, align 8
  call void @nova_rc_dec(i64 %t42)
  %t43 = load i64, ptr %slot.v, align 8
  call void @nova_rc_dec(i64 %t43)
  %t44 = load i64, ptr %slot.ch, align 8
  call void @nova_rc_dec(i64 %t44)
  %t45 = load i64, ptr %slot.parts, align 8
  call void @nova_rc_dec(i64 %t45)
  ret i64 %r85
}

define i64 @nova_main() nounwind {
entry0:
  %slot.syms = alloca i64, align 8
  %slot.__mb0_ret = alloca i64, align 8
  %slot.__mb0_table = alloca i64, align 8
  %slot.__mb0_name = alloca i64, align 8
  %slot.__mb1_ret = alloca i64, align 8
  %slot.__mb1_table = alloca i64, align 8
  %slot.__mb1_name = alloca i64, align 8
  store i64 0, ptr %slot.syms, align 8
  store i64 0, ptr %slot.__mb0_table, align 8
  store i64 0, ptr %slot.__mb0_name, align 8
  store i64 0, ptr %slot.__mb0_ret, align 8
  store i64 0, ptr %slot.__mb1_table, align 8
  store i64 0, ptr %slot.__mb1_name, align 8
  store i64 0, ptr %slot.__mb1_ret, align 8
  %t0 = getelementptr inbounds [4 x i8], ptr @.str.10, i64 0, i64 0
  %r2 = ptrtoint ptr %t0 to i64
  %t1 = getelementptr inbounds [4 x i8], ptr @.str.11, i64 0, i64 0
  %r3 = ptrtoint ptr %t1 to i64
  %t2 = getelementptr inbounds [2 x i8], ptr @.str.12, i64 0, i64 0
  %r4 = ptrtoint ptr %t2 to i64
  %r53 = call i64 @nova_rt_list_create()
  %t3 = call ptr @nova_rt_struct_alloc(i64 32)
  %t4 = getelementptr i64, ptr %t3, i64 0
  store i64 6384368267, ptr %t4
  %t5 = getelementptr i64, ptr %t3, i64 1
  store i64 %r3, ptr %t5
  %t6 = getelementptr i64, ptr %t3, i64 2
  store i64 %r4, ptr %t6
  %t7 = getelementptr i64, ptr %t3, i64 3
  store i64 %r53, ptr %t7
  %r54 = ptrtoint ptr %t3 to i64
  %t8 = getelementptr inbounds [4 x i8], ptr @.str.11, i64 0, i64 0
  %r6 = ptrtoint ptr %t8 to i64
  %t9 = getelementptr inbounds [2 x i8], ptr @.str.13, i64 0, i64 0
  %r7 = ptrtoint ptr %t9 to i64
  %r62 = call i64 @nova_rt_list_create()
  %t10 = call ptr @nova_rt_struct_alloc(i64 32)
  %t11 = getelementptr i64, ptr %t10, i64 0
  store i64 6384368267, ptr %t11
  %t12 = getelementptr i64, ptr %t10, i64 1
  store i64 %r6, ptr %t12
  %t13 = getelementptr i64, ptr %t10, i64 2
  store i64 %r7, ptr %t13
  %t14 = getelementptr i64, ptr %t10, i64 3
  store i64 %r62, ptr %t14
  %r63 = ptrtoint ptr %t10 to i64
  %r9 = call i64 @nova_rt_list_create()
  %t15 = call i64 @nova_rt_list_append(i64 %r9, i64 %r54)
  %t16 = call i64 @nova_rt_list_append(i64 %r9, i64 %r63)
  %t17 = getelementptr inbounds [1 x i8], ptr @.str.14, i64 0, i64 0
  %r70 = ptrtoint ptr %t17 to i64
  %t18 = call ptr @nova_rt_struct_alloc(i64 32)
  %t19 = getelementptr i64, ptr %t18, i64 0
  store i64 6384368267, ptr %t19
  %t20 = getelementptr i64, ptr %t18, i64 1
  store i64 %r2, ptr %t20
  %t21 = getelementptr i64, ptr %t18, i64 2
  store i64 %r70, ptr %t21
  %t22 = getelementptr i64, ptr %t18, i64 3
  store i64 %r9, ptr %t22
  %r72 = ptrtoint ptr %t18 to i64
  %r15 = call i64 @node_to_str(i64 %r72)
  %t23 = inttoptr i64 %r15 to ptr
  call i32 @puts(ptr %t23)
  %r18 = call i64 @nova_rt_dict_create()
  %t24 = load i64, ptr %slot.syms, align 8
  call void @nova_rc_dec(i64 %t24)
  store i64 %r18, ptr %slot.syms, align 8
  %t25 = getelementptr inbounds [4 x i8], ptr @.str.11, i64 0, i64 0
  %r22 = ptrtoint ptr %t25 to i64
  %t26 = getelementptr inbounds [2 x i8], ptr @.str.15, i64 0, i64 0
  %r24 = ptrtoint ptr %t26 to i64
  %t27 = call i64 @nova_rt_dict_set(i64 %r18, i64 %r24, i64 %r22)
  %t28 = getelementptr inbounds [7 x i8], ptr @.str.16, i64 0, i64 0
  %r27 = ptrtoint ptr %t28 to i64
  %t29 = getelementptr inbounds [2 x i8], ptr @.str.17, i64 0, i64 0
  %r29 = ptrtoint ptr %t29 to i64
  %t30 = call i64 @nova_rt_dict_set(i64 %r18, i64 %r29, i64 %r27)
  %t31 = getelementptr inbounds [5 x i8], ptr @.str.18, i64 0, i64 0
  %r32 = ptrtoint ptr %t31 to i64
  %t32 = getelementptr inbounds [2 x i8], ptr @.str.19, i64 0, i64 0
  %r34 = ptrtoint ptr %t32 to i64
  %t33 = call i64 @nova_rt_dict_set(i64 %r18, i64 %r34, i64 %r32)
  %r37 = load i64, ptr %slot.syms, align 8
  %t34 = getelementptr inbounds [2 x i8], ptr @.str.15, i64 0, i64 0
  %r38 = ptrtoint ptr %t34 to i64
  br label %__mb0_entry0

__mb0_entry0:
  %t35 = load i64, ptr %slot.__mb0_table, align 8
  call void @nova_rc_dec(i64 %t35)
  call void @nova_rc_inc(i64 %r37)
  store i64 %r37, ptr %slot.__mb0_table, align 8
  %t36 = load i64, ptr %slot.__mb0_name, align 8
  call void @nova_rc_dec(i64 %t36)
  store i64 %r38, ptr %slot.__mb0_name, align 8
  %r80 = call i64 @nova_rt_contains(i64 %r37, i64 %r38)
  %t37 = trunc i64 %r80 to i1
  br i1 %t37, label %__mb0_ifb_then1, label %__mb0_ifb_else2

__mb0_ifb_then1:
  %r83 = load i64, ptr %slot.__mb0_table, align 8
  %r84 = load i64, ptr %slot.__mb0_name, align 8
  %r85 = call i64 @nova_rt_dict_get(i64 %r83, i64 %r84)
  %t38 = load i64, ptr %slot.__mb0_ret, align 8
  call void @nova_rc_dec(i64 %t38)
  call void @nova_rc_inc(i64 %r85)
  store i64 %r85, ptr %slot.__mb0_ret, align 8
  br label %__mb0_merge

__mb0_ifb_else2:
  br label %__mb0_ifb_merge3

__mb0_ifb_merge3:
  %t39 = getelementptr inbounds [8 x i8], ptr @.str.20, i64 0, i64 0
  %r89 = ptrtoint ptr %t39 to i64
  %t40 = load i64, ptr %slot.__mb0_ret, align 8
  call void @nova_rc_dec(i64 %t40)
  store i64 %r89, ptr %slot.__mb0_ret, align 8
  br label %__mb0_merge

__mb0_merge:
  %r90 = load i64, ptr %slot.__mb0_ret, align 8
  %t41 = inttoptr i64 %r90 to ptr
  call i32 @puts(ptr %t41)
  %r41 = load i64, ptr %slot.syms, align 8
  %t42 = getelementptr inbounds [2 x i8], ptr @.str.21, i64 0, i64 0
  %r42 = ptrtoint ptr %t42 to i64
  br label %__mb1_entry0

__mb1_entry0:
  %t43 = load i64, ptr %slot.__mb1_table, align 8
  call void @nova_rc_dec(i64 %t43)
  call void @nova_rc_inc(i64 %r41)
  store i64 %r41, ptr %slot.__mb1_table, align 8
  %t44 = load i64, ptr %slot.__mb1_name, align 8
  call void @nova_rc_dec(i64 %t44)
  store i64 %r42, ptr %slot.__mb1_name, align 8
  %r101 = call i64 @nova_rt_contains(i64 %r41, i64 %r42)
  %t45 = trunc i64 %r101 to i1
  br i1 %t45, label %__mb1_ifb_then1, label %__mb1_ifb_else2

__mb1_ifb_then1:
  %r104 = load i64, ptr %slot.__mb1_table, align 8
  %r105 = load i64, ptr %slot.__mb1_name, align 8
  %r106 = call i64 @nova_rt_dict_get(i64 %r104, i64 %r105)
  %t46 = load i64, ptr %slot.__mb1_ret, align 8
  call void @nova_rc_dec(i64 %t46)
  call void @nova_rc_inc(i64 %r106)
  store i64 %r106, ptr %slot.__mb1_ret, align 8
  br label %__mb1_merge

__mb1_ifb_else2:
  br label %__mb1_ifb_merge3

__mb1_ifb_merge3:
  %t47 = getelementptr inbounds [8 x i8], ptr @.str.20, i64 0, i64 0
  %r110 = ptrtoint ptr %t47 to i64
  %t48 = load i64, ptr %slot.__mb1_ret, align 8
  call void @nova_rc_dec(i64 %t48)
  store i64 %r110, ptr %slot.__mb1_ret, align 8
  br label %__mb1_merge

__mb1_merge:
  %r111 = load i64, ptr %slot.__mb1_ret, align 8
  %t49 = inttoptr i64 %r111 to ptr
  call i32 @puts(ptr %t49)
  %t50 = load i64, ptr %slot.syms, align 8
  call void @nova_rc_dec(i64 %t50)
  %t51 = load i64, ptr %slot.__mb0_table, align 8
  call void @nova_rc_dec(i64 %t51)
  %t52 = load i64, ptr %slot.__mb0_name, align 8
  call void @nova_rc_dec(i64 %t52)
  %t53 = load i64, ptr %slot.__mb0_ret, align 8
  call void @nova_rc_dec(i64 %t53)
  %t54 = load i64, ptr %slot.__mb1_table, align 8
  call void @nova_rc_dec(i64 %t54)
  %t55 = load i64, ptr %slot.__mb1_name, align 8
  call void @nova_rc_dec(i64 %t55)
  %t56 = load i64, ptr %slot.__mb1_ret, align 8
  call void @nova_rc_dec(i64 %t56)
  ret i64 0
}

define i32 @main(i32 %argc, ptr %argv) nounwind {
entry:
  %argc64 = sext i32 %argc to i64
  %argv64 = ptrtoint ptr %argv to i64
  call void @nova_rt_init_args(i64 %argc64, i64 %argv64)
  call i64 @nova_main()
  call void @nova_rt_wait_all()
  call void @nova_rt_cleanup()
  ret i32 0
}

!0 = !{!"NOVA TBAA"}
!1 = !{!"list_data_ptr", !0}
!2 = !{!1, !1, i64 0}
!3 = !{!"list_elem", !0}
!4 = !{!3, !3, i64 0}
!5 = !{!"list_size", !0}
!6 = !{!5, !5, i64 0}
!7 = !{!"list_cap", !0}
!8 = !{!7, !7, i64 0}
!90 = !{!"branch_weights", i32 2000, i32 1}
!91 = distinct !{!91, !92, !93}
!92 = !{!"llvm.loop.unroll.enable"}
!93 = !{!"llvm.loop.vectorize.enable", i1 true}
