; Generated by NOVA compiler
target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"

declare i32 @printf(ptr, ...)
declare i32 @puts(ptr)
declare noalias ptr @malloc(i64) nounwind allocsize(0)
declare noalias ptr @calloc(i64, i64) nounwind
declare ptr @realloc(ptr, i64) nounwind allocsize(1)
declare void @free(ptr) nounwind
declare ptr @nova_rt_struct_alloc(i64) nounwind
declare i64 @llvm.smax.i64(i64, i64) nounwind readnone
; nova runtime — list ops
declare i64 @nova_rt_list_create() nounwind
declare i64 @nova_rt_list_create_filled(i64, i64) nounwind
declare i64 @nova_rt_list_append(i64, i64) nounwind
declare i64 @nova_rt_list_get(i64, i64) nounwind readonly
declare i64 @nova_rt_list_set(i64, i64, i64) nounwind
declare i64 @nova_rt_list_len(i64) nounwind readonly
declare i64 @nova_rt_list_print(i64) nounwind
declare i64 @nova_rt_iter_has_next(i64, i64) nounwind readonly
declare i64 @nova_rt_iter_get(i64, i64) nounwind readonly
declare i64 @nova_rt_list_iter_has_next(i64, i64) nounwind readonly
declare i64 @nova_rt_list_iter_get(i64, i64) nounwind readonly
; nova runtime — string ops
declare i64 @nova_rt_str_concat(i64, i64) nounwind
declare i64 @nova_rt_int_to_str(i64) nounwind
declare i64 @nova_rt_float_to_str(i64) nounwind
declare i64 @nova_rt_bool_to_str(i64) nounwind
declare i64 @nova_rt_str_len(i64) nounwind readonly
declare i64 @nova_rt_len(i64) nounwind readonly
declare i64 @nova_rt_contains(i64, i64) nounwind readonly
declare i64 @nova_rt_slice(i64, i64, i64) nounwind
declare i64 @nova_rt_upper(i64) nounwind
declare i64 @nova_rt_lower(i64) nounwind
declare i64 @nova_rt_trim(i64) nounwind
declare i64 @nova_rt_repeat(i64, i64) nounwind
declare i64 @nova_rt_split(i64, i64) nounwind
declare i64 @nova_rt_replace(i64, i64, i64) nounwind
declare i64 @nova_rt_starts_with(i64, i64) nounwind readonly
declare i64 @nova_rt_ends_with(i64, i64) nounwind readonly
declare i64 @nova_rt_find(i64, i64) nounwind readonly
declare i64 @nova_rt_join(i64, i64) nounwind
declare i64 @nova_rt_chars(i64) nounwind
; nova runtime — list stdlib
declare i64 @nova_rt_list_reverse(i64) nounwind
declare i64 @nova_rt_list_sort(i64) nounwind
declare i64 @nova_rt_list_map(i64, i64) nounwind
declare i64 @nova_rt_list_filter(i64, i64) nounwind
declare i64 @nova_rt_list_concat(i64, i64) nounwind
declare i64 @nova_rt_list_slice(i64, i64, i64) nounwind
declare i64 @nova_rt_list_to_str(i64) nounwind
declare i64 @nova_rt_len_any(i64) nounwind readonly
; nova runtime — type conversions
declare i64 @nova_rt_parse_int(i64) nounwind
declare i64 @nova_rt_parse_float(i64) nounwind
; nova runtime — character ops
declare i64 @nova_rt_ord(i64) nounwind readonly
declare i64 @nova_rt_chr(i64) nounwind
; nova runtime — process control
declare void @nova_rt_exit(i64) noreturn nounwind
declare i64 @nova_rt_system(i64) nounwind
declare i64 @nova_rt_exec(i64) nounwind
declare i32 @strcmp(ptr, ptr) nounwind readonly
; nova runtime — dict ops (hash map, O(1) avg lookup)
declare i64 @nova_rt_dict_create() nounwind
declare i64 @nova_rt_dict_set(i64, i64, i64) nounwind
declare i64 @nova_rt_dict_get(i64, i64) nounwind readonly
declare i64 @nova_rt_dict_get_concat2(i64, i64, i64) nounwind readonly
declare i64 @nova_rt_dict_set_concat2(i64, i64, i64, i64) nounwind
declare i64 @nova_rt_dict_has(i64, i64) nounwind readonly
declare i64 @nova_rt_dict_del(i64, i64) nounwind
declare i64 @nova_rt_dict_len(i64) nounwind readonly
declare i64 @nova_rt_dict_keys(i64) nounwind
declare i64 @nova_rt_dict_values(i64) nounwind
declare i64 @nova_rt_dict_items(i64) nounwind
; nova runtime — IO ops
declare i64 @nova_rt_read_line() nounwind
declare i64 @nova_rt_read_bytes(i64) nounwind
declare i64 @nova_rt_write_raw(i64) nounwind
declare i64 @nova_rt_read_file(i64) nounwind
declare i64 @nova_rt_write_file(i64, i64) nounwind
declare i64 @nova_rt_append_file(i64, i64) nounwind
declare i64 @nova_rt_file_exists(i64) nounwind readonly
; nova runtime — JSON ops
declare i64 @nova_rt_json_parse(i64) nounwind
declare i64 @nova_rt_json_stringify(i64) nounwind
; nova runtime — HTTP ops
declare i64 @nova_rt_http_get(i64) nounwind
declare i64 @nova_rt_http_post(i64, i64, i64) nounwind
; nova runtime — time ops
declare i64 @nova_rt_time_ms() nounwind
declare i64 @nova_rt_clock_ns() nounwind
declare void @nova_rt_sleep_ms(i64) nounwind
declare void @nova_rt_assert(i64, i64) nounwind
; nova runtime — type dispatch
declare i64 @nova_rt_any_to_str(i64) nounwind
declare i64 @nova_rt_str_concat_safe(i64, i64) nounwind
declare i64 @nova_rt_str_char_at(i64, i64) nounwind
declare i64 @nova_rt_type_of(i64) nounwind
declare i64 @nova_rt_range(i64) nounwind
declare i64 @nova_rt_range_from_to(i64, i64) nounwind
declare void @nova_rt_init() nounwind
declare void @nova_rt_init_args(i64, i64) nounwind
; nova runtime — system ops
declare i64 @nova_rt_args() nounwind
declare i64 @nova_rt_env(i64) nounwind
declare i64 @nova_rt_random_int(i64, i64) nounwind
declare i64 @nova_rt_random_float() nounwind
declare i64 @nova_rt_shell(i64) nounwind
declare i64 @nova_rt_path_join(i64, i64) nounwind
declare i64 @nova_rt_path_parent(i64) nounwind
declare i64 @nova_rt_path_name(i64) nounwind
declare i64 @nova_rt_path_ext(i64) nounwind
declare i64 @nova_rt_mkdir(i64) nounwind
declare i64 @nova_rt_mkdir_p(i64) nounwind
declare i64 @nova_rt_path_exists(i64) nounwind
; nova runtime — regex ops
declare i64 @nova_rt_regex_match(i64, i64) nounwind readonly
declare i64 @nova_rt_regex_find(i64, i64) nounwind
declare i64 @nova_rt_regex_replace(i64, i64, i64) nounwind
declare i64 @nova_rt_regex_split(i64, i64) nounwind
; nova runtime — collection utilities
declare i64 @nova_rt_enumerate(i64) nounwind
declare i64 @nova_rt_zip(i64, i64) nounwind
declare i64 @nova_rt_list_sum(i64) nounwind readonly
declare i64 @nova_rt_list_any(i64) nounwind readonly
declare i64 @nova_rt_list_all(i64) nounwind readonly
declare i64 @nova_rt_list_min(i64) nounwind readonly
declare i64 @nova_rt_list_max(i64) nounwind readonly
; nova runtime — set operations
declare i64 @nova_rt_set_create() nounwind
declare i64 @nova_rt_set_add(i64, i64) nounwind
declare i64 @nova_rt_set_has(i64, i64) nounwind readonly
declare i64 @nova_rt_set_remove(i64, i64) nounwind
declare i64 @nova_rt_set_len(i64) nounwind readonly
declare i64 @nova_rt_set_to_list(i64) nounwind
; nova runtime — datetime operations
declare i64 @nova_rt_datetime_now() nounwind
declare i64 @nova_rt_datetime_format(i64, i64) nounwind
declare i64 @nova_rt_datetime_year(i64) nounwind readonly
declare i64 @nova_rt_datetime_month(i64) nounwind readonly
declare i64 @nova_rt_datetime_day(i64) nounwind readonly
declare i64 @nova_rt_datetime_hour(i64) nounwind readonly
declare i64 @nova_rt_datetime_minute(i64) nounwind readonly
declare i64 @nova_rt_datetime_second(i64) nounwind readonly
; nova runtime — network ops
declare i64 @nova_rt_tcp_connect(i64, i64) nounwind
declare i64 @nova_rt_tcp_listen(i64) nounwind
declare i64 @nova_rt_tcp_accept(i64) nounwind
declare i64 @nova_rt_tcp_send(i64, i64) nounwind
declare i64 @nova_rt_tcp_recv(i64) nounwind
declare void @nova_rt_tcp_close(i64) nounwind
declare i64 @nova_rt_udp_bind(i64) nounwind
declare i64 @nova_rt_udp_send(i64, i64, i64, i64) nounwind
declare i64 @nova_rt_udp_recv(i64) nounwind
; nova runtime — HTTP server
declare i64 @nova_rt_http_listen(i64) nounwind
declare i64 @nova_rt_http_accept(i64) nounwind
declare void @nova_rt_http_respond(i64, i64, i64) nounwind
; nova runtime — byte arrays
declare i64 @nova_rt_bytes_create(i64) nounwind
declare i64 @nova_rt_bytes_get(i64, i64) nounwind
declare void @nova_rt_bytes_set(i64, i64, i64) nounwind
declare i64 @nova_rt_bytes_len(i64) nounwind
declare i64 @nova_rt_bytes_slice(i64, i64, i64) nounwind
declare i64 @nova_rt_bytes_to_str(i64) nounwind
declare i64 @nova_rt_str_to_bytes(i64) nounwind
; nova runtime — channel/spawn ops
declare i64 @nova_rt_channel_create() nounwind
declare i64 @nova_rt_channel_send(i64, i64) nounwind
declare i64 @nova_rt_channel_recv(i64) nounwind
declare i64 @nova_rt_channel_close(i64) nounwind
declare i64 @nova_rt_channel_select(i64, i64) nounwind
declare i64 @nova_rt_channel_recv_timeout(i64, i64) nounwind
declare i64 @nova_rt_spawn(i64, i64) nounwind
declare i64 @nova_rt_monitor(i64) nounwind
declare void @nova_rt_wait_all() nounwind
; nova runtime — math (trig/log via C runtime for non-intrinsic functions)
declare i64 @nova_rt_tan(i64) nounwind
declare i64 @nova_rt_asin(i64) nounwind
declare i64 @nova_rt_acos(i64) nounwind
declare i64 @nova_rt_atan(i64) nounwind
declare i64 @nova_rt_atan2(i64, i64) nounwind
declare i64 @nova_rt_fmod(i64, i64) nounwind
declare i64 @nova_rt_int_pow(i64, i64) nounwind
; nova runtime — memory management
declare void @nova_rt_cleanup() nounwind
declare void @nova_rt_track_raw(ptr) nounwind
declare i64 @nova_rt_alloc_count() nounwind readonly
declare i64 @nova_rt_live_count() nounwind readonly
; nova runtime — reference counting
declare void @nova_rc_inc(i64) nounwind
declare void @nova_rc_dec(i64) nounwind
; nova runtime — distributed computing
declare i64 @nova_rt_serialize(i64) nounwind
declare i64 @nova_rt_deserialize(i64) nounwind
declare i64 @nova_rt_serialize_to_hex(i64) nounwind
declare i64 @nova_rt_node_listen(i64) nounwind
declare i64 @nova_rt_node_accept(i64) nounwind
declare void @nova_rt_node_stop(i64) nounwind
declare i64 @nova_rt_node_connect(i64) nounwind
declare i64 @nova_rt_remote_channel_create(i64) nounwind
declare i64 @nova_rt_remote_send(i64, i64) nounwind
declare i64 @nova_rt_remote_recv(i64) nounwind
declare void @nova_rt_remote_close(i64) nounwind
declare i64 @nova_rt_remote_spawn(i64, i64, i64) nounwind
declare i64 @nova_rt_node_recv_spawn(i64) nounwind
; nova error state — thread-local flag (safe for spawn/concurrent programs)
@__nova_error_flag = thread_local global i64 0
@__nova_error_msg = thread_local global i64 0

@.str.0 = private unnamed_addr constant [6 x i8] c"ident\00"
@.str.1 = private unnamed_addr constant [6 x i8] c"hello\00"
@.str.2 = private unnamed_addr constant [12 x i8] c"__type_hash\00"
@.str.3 = private unnamed_addr constant [5 x i8] c"kind\00"
@.str.4 = private unnamed_addr constant [6 x i8] c"value\00"
@.str.5 = private unnamed_addr constant [2 x i8] c":\00"
@.str.6 = private unnamed_addr constant [8 x i8] c"unknown\00"
@.str.7 = private unnamed_addr constant [4 x i8] c"num\00"
@.str.8 = private unnamed_addr constant [3 x i8] c"42\00"
@.str.9 = private unnamed_addr constant [6 x i8] c"%lld\0A\00"
@.str.10 = private unnamed_addr constant [4 x i8] c"%f\0A\00"
@.str.11 = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.str.12 = private unnamed_addr constant [5 x i8] c"true\00"
@.str.13 = private unnamed_addr constant [6 x i8] c"false\00"

define i64 @nova_main() nounwind {
entry0:
  %slot.t = alloca i64, align 8
  %slot.__mb0_ret = alloca i64, align 8
  %slot.__mb0_tok = alloca i64, align 8
  %slot.t2 = alloca i64, align 8
  %slot.__mb1_ret = alloca i64, align 8
  %slot.__mb1_tok = alloca i64, align 8
  store i64 0, ptr %slot.t, align 8
  store i64 0, ptr %slot.__mb0_tok, align 8
  store i64 0, ptr %slot.__mb0_ret, align 8
  store i64 0, ptr %slot.t2, align 8
  store i64 0, ptr %slot.__mb1_tok, align 8
  store i64 0, ptr %slot.__mb1_ret, align 8
  %t0 = getelementptr inbounds [6 x i8], ptr @.str.0, i64 0, i64 0
  %r2 = ptrtoint ptr %t0 to i64
  %t1 = getelementptr inbounds [6 x i8], ptr @.str.1, i64 0, i64 0
  %r3 = ptrtoint ptr %t1 to i64
  %t2 = alloca i64, i64 3, align 8
  %t3 = getelementptr i64, ptr %t2, i64 0
  store i64 210691276070, ptr %t3
  %t4 = getelementptr i64, ptr %t2, i64 1
  store i64 %r2, ptr %t4
  %t5 = getelementptr i64, ptr %t2, i64 2
  store i64 %r3, ptr %t5
  %r4 = ptrtoint ptr %t2 to i64
  %t6 = load i64, ptr %slot.t, align 8
  call void @nova_rc_dec(i64 %t6)
  store i64 %r4, ptr %slot.t, align 8
  %r8 = load i64, ptr %slot.t, align 8
  br label %__mb0_entry0

__mb0_entry0:
  %t7 = load i64, ptr %slot.__mb0_tok, align 8
  call void @nova_rc_dec(i64 %t7)
  call void @nova_rc_inc(i64 %r8)
  store i64 %r8, ptr %slot.__mb0_tok, align 8
  %r25 = load i64, ptr %slot.__mb0_tok, align 8
  %t8 = inttoptr i64 %r25 to ptr
  %t9 = getelementptr i64, ptr %t8, i64 0
  %r27 = load i64, ptr %t9
  %t10 = icmp eq i64 %r27, 210691276070
  br i1 %t10, label %__mb0_arm0_body2, label %__mb0_match_merge1

__mb0_arm0_body2:
  %t11 = inttoptr i64 %r25 to ptr
  %t12 = getelementptr i64, ptr %t11, i64 1
  %r32 = load i64, ptr %t12
  %t13 = inttoptr i64 %r25 to ptr
  %t14 = getelementptr i64, ptr %t13, i64 2
  %r34 = load i64, ptr %t14
  %t15 = getelementptr inbounds [2 x i8], ptr @.str.5, i64 0, i64 0
  %r38 = ptrtoint ptr %t15 to i64
  %t16 = call i64 @nova_rt_str_concat(i64 %r32, i64 %r38)
  %t17 = call i64 @nova_rt_str_concat(i64 %t16, i64 %r34)
  call void @nova_rc_dec(i64 %t16)
  %t18 = load i64, ptr %slot.__mb0_ret, align 8
  call void @nova_rc_dec(i64 %t18)
  store i64 %t17, ptr %slot.__mb0_ret, align 8
  br label %__mb0_merge

__mb0_match_merge1:
  %t19 = getelementptr inbounds [8 x i8], ptr @.str.6, i64 0, i64 0
  %r43 = ptrtoint ptr %t19 to i64
  %t20 = load i64, ptr %slot.__mb0_ret, align 8
  call void @nova_rc_dec(i64 %t20)
  store i64 %r43, ptr %slot.__mb0_ret, align 8
  br label %__mb0_merge

__mb0_merge:
  %r44 = load i64, ptr %slot.__mb0_ret, align 8
  %t21 = inttoptr i64 %r44 to ptr
  call i32 @puts(ptr %t21)
  %t22 = getelementptr inbounds [4 x i8], ptr @.str.7, i64 0, i64 0
  %r12 = ptrtoint ptr %t22 to i64
  %t23 = getelementptr inbounds [3 x i8], ptr @.str.8, i64 0, i64 0
  %r13 = ptrtoint ptr %t23 to i64
  %t24 = alloca i64, i64 3, align 8
  %t25 = getelementptr i64, ptr %t24, i64 0
  store i64 210691276070, ptr %t25
  %t26 = getelementptr i64, ptr %t24, i64 1
  store i64 %r12, ptr %t26
  %t27 = getelementptr i64, ptr %t24, i64 2
  store i64 %r13, ptr %t27
  %r14 = ptrtoint ptr %t24 to i64
  %t28 = load i64, ptr %slot.t2, align 8
  call void @nova_rc_dec(i64 %t28)
  store i64 %r14, ptr %slot.t2, align 8
  %r18 = load i64, ptr %slot.t2, align 8
  br label %__mb1_entry0

__mb1_entry0:
  %t29 = load i64, ptr %slot.__mb1_tok, align 8
  call void @nova_rc_dec(i64 %t29)
  call void @nova_rc_inc(i64 %r18)
  store i64 %r18, ptr %slot.__mb1_tok, align 8
  %r51 = load i64, ptr %slot.__mb1_tok, align 8
  %t30 = inttoptr i64 %r51 to ptr
  %t31 = getelementptr i64, ptr %t30, i64 0
  %r53 = load i64, ptr %t31
  %t32 = icmp eq i64 %r53, 210691276070
  br i1 %t32, label %__mb1_arm0_body2, label %__mb1_match_merge1

__mb1_arm0_body2:
  %t33 = inttoptr i64 %r51 to ptr
  %t34 = getelementptr i64, ptr %t33, i64 1
  %r58 = load i64, ptr %t34
  %t35 = inttoptr i64 %r51 to ptr
  %t36 = getelementptr i64, ptr %t35, i64 2
  %r60 = load i64, ptr %t36
  %t37 = getelementptr inbounds [2 x i8], ptr @.str.5, i64 0, i64 0
  %r64 = ptrtoint ptr %t37 to i64
  %t38 = call i64 @nova_rt_str_concat(i64 %r58, i64 %r64)
  %t39 = call i64 @nova_rt_str_concat(i64 %t38, i64 %r60)
  call void @nova_rc_dec(i64 %t38)
  %t40 = load i64, ptr %slot.__mb1_ret, align 8
  call void @nova_rc_dec(i64 %t40)
  store i64 %t39, ptr %slot.__mb1_ret, align 8
  br label %__mb1_merge

__mb1_match_merge1:
  %t41 = getelementptr inbounds [8 x i8], ptr @.str.6, i64 0, i64 0
  %r69 = ptrtoint ptr %t41 to i64
  %t42 = load i64, ptr %slot.__mb1_ret, align 8
  call void @nova_rc_dec(i64 %t42)
  store i64 %r69, ptr %slot.__mb1_ret, align 8
  br label %__mb1_merge

__mb1_merge:
  %r70 = load i64, ptr %slot.__mb1_ret, align 8
  %t43 = inttoptr i64 %r70 to ptr
  call i32 @puts(ptr %t43)
  %t44 = load i64, ptr %slot.t, align 8
  call void @nova_rc_dec(i64 %t44)
  %t45 = load i64, ptr %slot.__mb0_tok, align 8
  call void @nova_rc_dec(i64 %t45)
  %t46 = load i64, ptr %slot.__mb0_ret, align 8
  call void @nova_rc_dec(i64 %t46)
  %t47 = load i64, ptr %slot.t2, align 8
  call void @nova_rc_dec(i64 %t47)
  %t48 = load i64, ptr %slot.__mb1_tok, align 8
  call void @nova_rc_dec(i64 %t48)
  %t49 = load i64, ptr %slot.__mb1_ret, align 8
  call void @nova_rc_dec(i64 %t49)
  ret i64 0
}

define i32 @main(i32 %argc, ptr %argv) nounwind {
entry:
  %argc64 = sext i32 %argc to i64
  %argv64 = ptrtoint ptr %argv to i64
  call void @nova_rt_init_args(i64 %argc64, i64 %argv64)
  call i64 @nova_main()
  call void @nova_rt_wait_all()
  call void @nova_rt_cleanup()
  ret i32 0
}

!0 = !{!"NOVA TBAA"}
!1 = !{!"list_data_ptr", !0}
!2 = !{!1, !1, i64 0}
!3 = !{!"list_elem", !0}
!4 = !{!3, !3, i64 0}
!5 = !{!"list_size", !0}
!6 = !{!5, !5, i64 0}
!7 = !{!"list_cap", !0}
!8 = !{!7, !7, i64 0}
!90 = !{!"branch_weights", i32 2000, i32 1}
!91 = distinct !{!91, !92, !93}
!92 = !{!"llvm.loop.unroll.enable"}
!93 = !{!"llvm.loop.vectorize.enable", i1 true}
