; Generated by NOVA compiler
target triple = "x86_64-pc-windows-msvc"

declare i32 @printf(ptr, ...)
declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare ptr @realloc(ptr, i64)
declare void @free(ptr)
; nova runtime — list ops
declare i64 @nova_rt_list_create()
declare i64 @nova_rt_list_append(i64, i64)
declare i64 @nova_rt_list_get(i64, i64)
declare i64 @nova_rt_list_set(i64, i64, i64)
declare i64 @nova_rt_list_len(i64)
declare i64 @nova_rt_list_print(i64)
declare i64 @nova_rt_iter_has_next(i64, i64)
; nova runtime — string ops
declare i64 @nova_rt_str_concat(i64, i64)
declare i64 @nova_rt_int_to_str(i64)
declare i64 @nova_rt_float_to_str(i64)
declare i64 @nova_rt_bool_to_str(i64)
declare i64 @nova_rt_str_len(i64)
declare i64 @nova_rt_len(i64)
declare i64 @nova_rt_contains(i64, i64)
declare i64 @nova_rt_slice(i64, i64, i64)
declare i64 @nova_rt_upper(i64)
declare i64 @nova_rt_lower(i64)
declare i64 @nova_rt_trim(i64)
declare i64 @nova_rt_split(i64, i64)
declare i64 @nova_rt_replace(i64, i64, i64)
declare i64 @nova_rt_starts_with(i64, i64)
declare i64 @nova_rt_ends_with(i64, i64)
declare i64 @nova_rt_find(i64, i64)
declare i64 @nova_rt_join(i64, i64)
declare i64 @nova_rt_chars(i64)
; nova runtime — list stdlib
declare i64 @nova_rt_list_reverse(i64)
declare i64 @nova_rt_list_sort(i64)
declare i64 @nova_rt_list_map(i64, i64)
declare i64 @nova_rt_list_filter(i64, i64)
declare i64 @nova_rt_list_concat(i64, i64)
declare i64 @nova_rt_list_to_str(i64)
declare i64 @nova_rt_len_any(i64)
; nova runtime — type conversions
declare i64 @nova_rt_parse_int(i64)
declare i64 @nova_rt_parse_float(i64)
declare i32 @strcmp(ptr, ptr)
; nova runtime — dict ops (Phase 1: ordered array, O(n) lookup)
declare i64 @nova_rt_dict_create()
declare i64 @nova_rt_dict_set(i64, i64, i64)
declare i64 @nova_rt_dict_get(i64, i64)
declare i64 @nova_rt_dict_has(i64, i64)
declare i64 @nova_rt_dict_del(i64, i64)
declare i64 @nova_rt_dict_len(i64)
declare i64 @nova_rt_dict_keys(i64)
; nova runtime — IO ops
declare i64 @nova_rt_read_line()
declare i64 @nova_rt_read_file(i64)
declare i64 @nova_rt_write_file(i64, i64)
; nova runtime — channel/spawn ops
declare i64 @nova_rt_channel_create()
declare i64 @nova_rt_channel_send(i64, i64)
declare i64 @nova_rt_channel_recv(i64)
declare i64 @nova_rt_channel_close(i64)
declare i64 @nova_rt_channel_select(i64, i64)
declare i64 @nova_rt_channel_recv_timeout(i64, i64)
declare i64 @nova_rt_spawn(i64, i64)
declare i64 @nova_rt_monitor(i64)
declare void @nova_rt_wait_all()
; nova runtime — math (trig/log via C runtime for non-intrinsic functions)
declare i64 @nova_rt_tan(i64)
declare i64 @nova_rt_asin(i64)
declare i64 @nova_rt_acos(i64)
declare i64 @nova_rt_atan(i64)
declare i64 @nova_rt_atan2(i64, i64)
declare i64 @nova_rt_fmod(i64, i64)
declare i64 @nova_rt_int_pow(i64, i64)
; nova error state — global flag (errno-style)
@__nova_error_flag = global i64 0
@__nova_error_msg = global i64 0

@.str.0 = private unnamed_addr constant [25 x i8] c"Sum of squares 1..100 = \00"
@.str.1 = private unnamed_addr constant [22 x i8] c"Primes up to 10000 = \00"
@.str.2 = private unnamed_addr constant [52 x i8] c"Primes remaining after sieve(2,3,5,7) from 2..50 = \00"
@.str.3 = private unnamed_addr constant [16 x i8] c"Producer sum = \00"
@.str.4 = private unnamed_addr constant [19 x i8] c"Closure captures: \00"
@.str.5 = private unnamed_addr constant [6 x i8] c" and \00"
@.str.6 = private unnamed_addr constant [1 x i8] c"\00"
@.str.7 = private unnamed_addr constant [29 x i8] c"All concurrent tests passed!\00"
@.str.8 = private unnamed_addr constant [6 x i8] c"%lld\0A\00"
@.str.9 = private unnamed_addr constant [4 x i8] c"%f\0A\00"
@.str.10 = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.str.11 = private unnamed_addr constant [5 x i8] c"true\00"
@.str.12 = private unnamed_addr constant [6 x i8] c"false\00"

define i64 @compute_squares(i64 %p0, i64 %p1, i64 %p2) {
entry0:
  %slot.ch = alloca i64
  store i64 %p0, ptr %slot.ch
  %slot.start = alloca i64
  store i64 %p1, ptr %slot.start
  %slot.count = alloca i64
  store i64 %p2, ptr %slot.count
  %slot.total = alloca i64
  store i64 0, ptr %slot.total
  %slot.i = alloca i64
  store i64 %p1, ptr %slot.i
  br label %while_header1

while_header1:
  %r15 = load i64, ptr %slot.i
  %r16 = load i64, ptr %slot.start
  %r17 = load i64, ptr %slot.count
  %r18 = add i64 %r16, %r17
  %t0 = icmp slt i64 %r15, %r18
  %r19 = zext i1 %t0 to i64
  %t1 = trunc i64 %r19 to i1
  br i1 %t1, label %while_body2, label %while_exit3

while_body2:
  %r21 = load i64, ptr %slot.total
  %r22 = load i64, ptr %slot.i
  %r23 = load i64, ptr %slot.i
  %r24 = mul i64 %r22, %r23
  %r25 = add i64 %r21, %r24
  store i64 %r25, ptr %slot.total
  %r28 = load i64, ptr %slot.i
  %r30 = add i64 %r28, 1
  store i64 %r30, ptr %slot.i
  br label %while_header1

while_exit3:
  %r34 = load i64, ptr %slot.ch
  %r35 = load i64, ptr %slot.total
  %t2 = call i64 @nova_rt_channel_send(i64 %r34, i64 %r35)
  ret i64 0
}

define i64 @is_prime(i64 %p0) {
entry0:
  %slot.n = alloca i64
  store i64 %p0, ptr %slot.n
  %t0 = icmp slt i64 %p0, 2
  %r5 = zext i1 %t0 to i64
  %slot.__ifb_0 = alloca i64
  %slot.d = alloca i64
  %t1 = trunc i64 %r5 to i1
  br i1 %t1, label %ifb_then1, label %ifb_else2

ifb_then1:
  ret i64 0

ifb_else2:
  store i64 0, ptr %slot.__ifb_0
  br label %ifb_merge3

ifb_merge3:
  %r13 = load i64, ptr %slot.n
  %t2 = icmp eq i64 %r13, 2
  %r15 = zext i1 %t2 to i64
  %slot.__ifb_1 = alloca i64
  %t3 = trunc i64 %r15 to i1
  br i1 %t3, label %ifb_then5, label %ifb_else6

ifb_then5:
  ret i64 1

ifb_else6:
  store i64 0, ptr %slot.__ifb_1
  br label %ifb_merge7

ifb_merge7:
  %r23 = load i64, ptr %slot.n
  %r25 = srem i64 %r23, 2
  %t4 = icmp eq i64 %r25, 0
  %r27 = zext i1 %t4 to i64
  %slot.__ifb_2 = alloca i64
  %t5 = trunc i64 %r27 to i1
  br i1 %t5, label %ifb_then9, label %ifb_else10

ifb_then9:
  ret i64 0

ifb_else10:
  store i64 0, ptr %slot.__ifb_2
  br label %ifb_merge11

ifb_merge11:
  store i64 3, ptr %slot.d
  br label %while_header13

while_header13:
  %r39 = load i64, ptr %slot.d
  %r40 = load i64, ptr %slot.d
  %r41 = mul i64 %r39, %r40
  %r42 = load i64, ptr %slot.n
  %t6 = icmp sle i64 %r41, %r42
  %r43 = zext i1 %t6 to i64
  %t7 = trunc i64 %r43 to i1
  br i1 %t7, label %while_body14, label %while_exit15

while_body14:
  %r45 = load i64, ptr %slot.n
  %r46 = load i64, ptr %slot.d
  %r47 = srem i64 %r45, %r46
  %t8 = icmp eq i64 %r47, 0
  %r49 = zext i1 %t8 to i64
  %slot.__ifb_3 = alloca i64
  %t9 = trunc i64 %r49 to i1
  br i1 %t9, label %ifb_then16, label %ifb_else17

while_exit15:
  ret i64 1

ifb_then16:
  ret i64 0

ifb_else17:
  store i64 0, ptr %slot.__ifb_3
  br label %ifb_merge18

ifb_merge18:
  %r57 = load i64, ptr %slot.d
  %r59 = add i64 %r57, 2
  store i64 %r59, ptr %slot.d
  br label %while_header13
}

define i64 @count_primes_range(i64 %p0, i64 %p1, i64 %p2) {
entry0:
  %slot.ch = alloca i64
  store i64 %p0, ptr %slot.ch
  %slot.lo = alloca i64
  store i64 %p1, ptr %slot.lo
  %slot.hi = alloca i64
  store i64 %p2, ptr %slot.hi
  %slot.count = alloca i64
  store i64 0, ptr %slot.count
  %slot.i = alloca i64
  store i64 %p1, ptr %slot.i
  br label %while_header1

while_header1:
  %r15 = load i64, ptr %slot.i
  %r16 = load i64, ptr %slot.hi
  %t0 = icmp sle i64 %r15, %r16
  %r17 = zext i1 %t0 to i64
  %t1 = trunc i64 %r17 to i1
  br i1 %t1, label %while_body2, label %while_exit3

while_body2:
  %r19 = load i64, ptr %slot.count
  %r20 = load i64, ptr %slot.i
  %r21 = call i64 @is_prime(i64 %r20)
  %r22 = add i64 %r19, %r21
  store i64 %r22, ptr %slot.count
  %r25 = load i64, ptr %slot.i
  %r27 = add i64 %r25, 1
  store i64 %r27, ptr %slot.i
  br label %while_header1

while_exit3:
  %r31 = load i64, ptr %slot.ch
  %r32 = load i64, ptr %slot.count
  %t2 = call i64 @nova_rt_channel_send(i64 %r31, i64 %r32)
  ret i64 0
}

define i64 @generate(i64 %p0, i64 %p1) {
entry0:
  %slot.out = alloca i64
  store i64 %p0, ptr %slot.out
  %slot.n = alloca i64
  store i64 %p1, ptr %slot.n
  %slot.i = alloca i64
  store i64 2, ptr %slot.i
  br label %while_header1

while_header1:
  %r9 = load i64, ptr %slot.i
  %r10 = load i64, ptr %slot.n
  %t0 = icmp sle i64 %r9, %r10
  %r11 = zext i1 %t0 to i64
  %t1 = trunc i64 %r11 to i1
  br i1 %t1, label %while_body2, label %while_exit3

while_body2:
  %r13 = load i64, ptr %slot.out
  %r14 = load i64, ptr %slot.i
  %t2 = call i64 @nova_rt_channel_send(i64 %r13, i64 %r14)
  %r16 = load i64, ptr %slot.i
  %r18 = add i64 %r16, 1
  store i64 %r18, ptr %slot.i
  br label %while_header1

while_exit3:
  %r22 = load i64, ptr %slot.out
  %t3 = call i64 @nova_rt_channel_send(i64 %r22, i64 -1)
  ret i64 0
}

define i64 @filter_stage(i64 %p0, i64 %p1, i64 %p2) {
entry0:
  %slot.in_ch = alloca i64
  store i64 %p0, ptr %slot.in_ch
  %slot.out = alloca i64
  store i64 %p1, ptr %slot.out
  %slot.prime = alloca i64
  store i64 %p2, ptr %slot.prime
  %slot.val = alloca i64
  br label %while_header1

while_header1:
  %t0 = trunc i64 1 to i1
  br i1 %t0, label %while_body2, label %while_exit3

while_body2:
  %r9 = load i64, ptr %slot.in_ch
  %r10 = call i64 @nova_rt_channel_recv(i64 %r9)
  store i64 %r10, ptr %slot.val
  %t1 = icmp eq i64 %r10, -1
  %r17 = zext i1 %t1 to i64
  %slot.__ifb_0 = alloca i64
  %t2 = trunc i64 %r17 to i1
  br i1 %t2, label %ifb_then4, label %ifb_else5

while_exit3:
  ret i64 0

ifb_then4:
  %r20 = load i64, ptr %slot.out
  %t3 = call i64 @nova_rt_channel_send(i64 %r20, i64 -1)
  ret i64 0

ifb_else5:
  store i64 0, ptr %slot.__ifb_0
  br label %ifb_merge6

ifb_merge6:
  %r29 = load i64, ptr %slot.val
  %r30 = load i64, ptr %slot.prime
  %r31 = srem i64 %r29, %r30
  %t4 = icmp ne i64 %r31, 0
  %r33 = zext i1 %t4 to i64
  %slot.__ifb_1 = alloca i64
  %t5 = trunc i64 %r33 to i1
  br i1 %t5, label %ifb_then8, label %ifb_else9

ifb_then8:
  %r36 = load i64, ptr %slot.out
  %r37 = load i64, ptr %slot.val
  %t6 = call i64 @nova_rt_channel_send(i64 %r36, i64 %r37)
  store i64 0, ptr %slot.__ifb_1
  br label %ifb_merge10

ifb_else9:
  store i64 0, ptr %slot.__ifb_1
  br label %ifb_merge10

ifb_merge10:
  br label %while_header1
}

define i64 @collect_primes(i64 %p0, i64 %p1, i64 %p2) {
entry0:
  %slot.in_ch = alloca i64
  store i64 %p0, ptr %slot.in_ch
  %slot.result_ch = alloca i64
  store i64 %p1, ptr %slot.result_ch
  %slot.limit = alloca i64
  store i64 %p2, ptr %slot.limit
  %slot.count = alloca i64
  store i64 0, ptr %slot.count
  %slot.val = alloca i64
  br label %while_header1

while_header1:
  %t0 = trunc i64 1 to i1
  br i1 %t0, label %while_body2, label %while_exit3

while_body2:
  %r13 = load i64, ptr %slot.in_ch
  %r14 = call i64 @nova_rt_channel_recv(i64 %r13)
  store i64 %r14, ptr %slot.val
  %t1 = icmp eq i64 %r14, -1
  %r21 = zext i1 %t1 to i64
  %slot.__ifb_0 = alloca i64
  %t2 = trunc i64 %r21 to i1
  br i1 %t2, label %ifb_then4, label %ifb_else5

while_exit3:
  ret i64 0

ifb_then4:
  %r24 = load i64, ptr %slot.result_ch
  %r25 = load i64, ptr %slot.count
  %t3 = call i64 @nova_rt_channel_send(i64 %r24, i64 %r25)
  ret i64 0

ifb_else5:
  store i64 0, ptr %slot.__ifb_0
  br label %ifb_merge6

ifb_merge6:
  %r32 = load i64, ptr %slot.count
  %r34 = add i64 %r32, 1
  store i64 %r34, ptr %slot.count
  %r38 = load i64, ptr %slot.limit
  %t4 = icmp sge i64 %r34, %r38
  %r39 = zext i1 %t4 to i64
  %slot.__ifb_1 = alloca i64
  %t5 = trunc i64 %r39 to i1
  br i1 %t5, label %ifb_then8, label %ifb_else9

ifb_then8:
  %r42 = load i64, ptr %slot.result_ch
  %r43 = load i64, ptr %slot.count
  %t6 = call i64 @nova_rt_channel_send(i64 %r42, i64 %r43)
  ret i64 0

ifb_else9:
  store i64 0, ptr %slot.__ifb_1
  br label %ifb_merge10

ifb_merge10:
  br label %while_header1
}

define i64 @producer(i64 %p0, i64 %p1) {
entry0:
  %slot.ch = alloca i64
  store i64 %p0, ptr %slot.ch
  %slot.n = alloca i64
  store i64 %p1, ptr %slot.n
  %slot.i = alloca i64
  store i64 1, ptr %slot.i
  br label %while_header1

while_header1:
  %r9 = load i64, ptr %slot.i
  %r10 = load i64, ptr %slot.n
  %t0 = icmp sle i64 %r9, %r10
  %r11 = zext i1 %t0 to i64
  %t1 = trunc i64 %r11 to i1
  br i1 %t1, label %while_body2, label %while_exit3

while_body2:
  %r13 = load i64, ptr %slot.ch
  %r14 = load i64, ptr %slot.i
  %r16 = mul i64 %r14, 10
  %t2 = call i64 @nova_rt_channel_send(i64 %r13, i64 %r16)
  %r18 = load i64, ptr %slot.i
  %r20 = add i64 %r18, 1
  store i64 %r20, ptr %slot.i
  br label %while_header1

while_exit3:
  %r24 = load i64, ptr %slot.ch
  %t3 = call i64 @nova_rt_channel_close(i64 %r24)
  ret i64 0
}

define i64 @make_worker(i64 %p0) {
entry0:
  %slot.multiplier = alloca i64
  store i64 %p0, ptr %slot.multiplier
  %t0 = call ptr @malloc(i64 16)
  %t1 = ptrtoint ptr @make_worker_lambda0_tramp to i64
  store i64 %t1, ptr %t0
  %t2 = getelementptr i64, ptr %t0, i64 1
  store i64 %p0, ptr %t2
  %r4 = ptrtoint ptr %t0 to i64
  ret i64 %r4
}

define i64 @make_worker_lambda0(i64 %p0, i64 %p1, i64 %p2) {
entry0:
  %slot.ch = alloca i64
  store i64 %p0, ptr %slot.ch
  %slot.value = alloca i64
  store i64 %p1, ptr %slot.value
  %slot.multiplier = alloca i64
  store i64 %p2, ptr %slot.multiplier
  %r12 = mul i64 %p1, %p2
  %t0 = call i64 @nova_rt_channel_send(i64 %p0, i64 %r12)
  ret i64 0
}

define i64 @nova_main() {
entry0:
  %r0 = call i64 @nova_rt_channel_create()
  %slot.results = alloca i64
  store i64 %r0, ptr %slot.results
  %t0 = call ptr @malloc(i64 16)
  %t1 = ptrtoint ptr @nova_main_spawn1 to i64
  store i64 %t1, ptr %t0
  %t2 = getelementptr i64, ptr %t0, i32 1
  store i64 %r0, ptr %t2
  %t3 = ptrtoint ptr @__nova_spawn_tramp_1 to i64
  %t4 = ptrtoint ptr %t0 to i64
  %r5 = call i64 @nova_rt_spawn(i64 %t3, i64 %t4)
  %t5 = call ptr @malloc(i64 16)
  %t6 = ptrtoint ptr @nova_main_spawn2 to i64
  store i64 %t6, ptr %t5
  %t7 = getelementptr i64, ptr %t5, i32 1
  store i64 %r0, ptr %t7
  %t8 = ptrtoint ptr @__nova_spawn_tramp_1 to i64
  %t9 = ptrtoint ptr %t5 to i64
  %r7 = call i64 @nova_rt_spawn(i64 %t8, i64 %t9)
  %r9 = call i64 @nova_rt_channel_recv(i64 %r0)
  %slot.r1 = alloca i64
  store i64 %r9, ptr %slot.r1
  %r14 = call i64 @nova_rt_channel_recv(i64 %r0)
  %slot.r2 = alloca i64
  store i64 %r14, ptr %slot.r2
  %t10 = getelementptr inbounds [25 x i8], ptr @.str.0, i64 0, i64 0
  %r19 = ptrtoint ptr %t10 to i64
  %r22 = add i64 %r9, %r14
  %r23 = call i64 @nova_rt_int_to_str(i64 %r22)
  %t11 = call i64 @nova_rt_str_concat(i64 %r19, i64 %r23)
  %t12 = inttoptr i64 %t11 to ptr
  call i32 @puts(ptr %t12)
  %r26 = call i64 @nova_rt_channel_create()
  %slot.prime_ch = alloca i64
  store i64 %r26, ptr %slot.prime_ch
  %t13 = call ptr @malloc(i64 16)
  %t14 = ptrtoint ptr @nova_main_spawn3 to i64
  store i64 %t14, ptr %t13
  %t15 = getelementptr i64, ptr %t13, i32 1
  store i64 %r26, ptr %t15
  %t16 = ptrtoint ptr @__nova_spawn_tramp_1 to i64
  %t17 = ptrtoint ptr %t13 to i64
  %r31 = call i64 @nova_rt_spawn(i64 %t16, i64 %t17)
  %t18 = call ptr @malloc(i64 16)
  %t19 = ptrtoint ptr @nova_main_spawn4 to i64
  store i64 %t19, ptr %t18
  %t20 = getelementptr i64, ptr %t18, i32 1
  store i64 %r26, ptr %t20
  %t21 = ptrtoint ptr @__nova_spawn_tramp_1 to i64
  %t22 = ptrtoint ptr %t18 to i64
  %r33 = call i64 @nova_rt_spawn(i64 %t21, i64 %t22)
  %t23 = call ptr @malloc(i64 16)
  %t24 = ptrtoint ptr @nova_main_spawn5 to i64
  store i64 %t24, ptr %t23
  %t25 = getelementptr i64, ptr %t23, i32 1
  store i64 %r26, ptr %t25
  %t26 = ptrtoint ptr @__nova_spawn_tramp_1 to i64
  %t27 = ptrtoint ptr %t23 to i64
  %r35 = call i64 @nova_rt_spawn(i64 %t26, i64 %t27)
  %t28 = call ptr @malloc(i64 16)
  %t29 = ptrtoint ptr @nova_main_spawn6 to i64
  store i64 %t29, ptr %t28
  %t30 = getelementptr i64, ptr %t28, i32 1
  store i64 %r26, ptr %t30
  %t31 = ptrtoint ptr @__nova_spawn_tramp_1 to i64
  %t32 = ptrtoint ptr %t28 to i64
  %r37 = call i64 @nova_rt_spawn(i64 %t31, i64 %t32)
  %r39 = call i64 @nova_rt_channel_recv(i64 %r26)
  %slot.p1 = alloca i64
  store i64 %r39, ptr %slot.p1
  %r44 = call i64 @nova_rt_channel_recv(i64 %r26)
  %slot.p2 = alloca i64
  store i64 %r44, ptr %slot.p2
  %r49 = call i64 @nova_rt_channel_recv(i64 %r26)
  %slot.p3 = alloca i64
  store i64 %r49, ptr %slot.p3
  %r54 = call i64 @nova_rt_channel_recv(i64 %r26)
  %slot.p4 = alloca i64
  store i64 %r54, ptr %slot.p4
  %t33 = getelementptr inbounds [22 x i8], ptr @.str.1, i64 0, i64 0
  %r59 = ptrtoint ptr %t33 to i64
  %r62 = add i64 %r39, %r44
  %r64 = add i64 %r62, %r49
  %r66 = add i64 %r64, %r54
  %r67 = call i64 @nova_rt_int_to_str(i64 %r66)
  %t34 = call i64 @nova_rt_str_concat(i64 %r59, i64 %r67)
  %t35 = inttoptr i64 %t34 to ptr
  call i32 @puts(ptr %t35)
  %r70 = call i64 @nova_rt_channel_create()
  %slot.gen_out = alloca i64
  store i64 %r70, ptr %slot.gen_out
  %t36 = call ptr @malloc(i64 16)
  %t37 = ptrtoint ptr @nova_main_spawn7 to i64
  store i64 %t37, ptr %t36
  %t38 = getelementptr i64, ptr %t36, i32 1
  store i64 %r70, ptr %t38
  %t39 = ptrtoint ptr @__nova_spawn_tramp_1 to i64
  %t40 = ptrtoint ptr %t36 to i64
  %r75 = call i64 @nova_rt_spawn(i64 %t39, i64 %t40)
  %r76 = call i64 @nova_rt_channel_create()
  %slot.f2_out = alloca i64
  store i64 %r76, ptr %slot.f2_out
  %t41 = call ptr @malloc(i64 24)
  %t42 = ptrtoint ptr @nova_main_spawn8 to i64
  store i64 %t42, ptr %t41
  %t43 = getelementptr i64, ptr %t41, i32 1
  store i64 %r70, ptr %t43
  %t44 = getelementptr i64, ptr %t41, i32 2
  store i64 %r76, ptr %t44
  %t45 = ptrtoint ptr @__nova_spawn_tramp_2 to i64
  %t46 = ptrtoint ptr %t41 to i64
  %r82 = call i64 @nova_rt_spawn(i64 %t45, i64 %t46)
  %r83 = call i64 @nova_rt_channel_create()
  %slot.f3_out = alloca i64
  store i64 %r83, ptr %slot.f3_out
  %t47 = call ptr @malloc(i64 24)
  %t48 = ptrtoint ptr @nova_main_spawn9 to i64
  store i64 %t48, ptr %t47
  %t49 = getelementptr i64, ptr %t47, i32 1
  store i64 %r76, ptr %t49
  %t50 = getelementptr i64, ptr %t47, i32 2
  store i64 %r83, ptr %t50
  %t51 = ptrtoint ptr @__nova_spawn_tramp_2 to i64
  %t52 = ptrtoint ptr %t47 to i64
  %r89 = call i64 @nova_rt_spawn(i64 %t51, i64 %t52)
  %r90 = call i64 @nova_rt_channel_create()
  %slot.f5_out = alloca i64
  store i64 %r90, ptr %slot.f5_out
  %t53 = call ptr @malloc(i64 24)
  %t54 = ptrtoint ptr @nova_main_spawn10 to i64
  store i64 %t54, ptr %t53
  %t55 = getelementptr i64, ptr %t53, i32 1
  store i64 %r83, ptr %t55
  %t56 = getelementptr i64, ptr %t53, i32 2
  store i64 %r90, ptr %t56
  %t57 = ptrtoint ptr @__nova_spawn_tramp_2 to i64
  %t58 = ptrtoint ptr %t53 to i64
  %r96 = call i64 @nova_rt_spawn(i64 %t57, i64 %t58)
  %r97 = call i64 @nova_rt_channel_create()
  %slot.f7_out = alloca i64
  store i64 %r97, ptr %slot.f7_out
  %t59 = call ptr @malloc(i64 24)
  %t60 = ptrtoint ptr @nova_main_spawn11 to i64
  store i64 %t60, ptr %t59
  %t61 = getelementptr i64, ptr %t59, i32 1
  store i64 %r90, ptr %t61
  %t62 = getelementptr i64, ptr %t59, i32 2
  store i64 %r97, ptr %t62
  %t63 = ptrtoint ptr @__nova_spawn_tramp_2 to i64
  %t64 = ptrtoint ptr %t59 to i64
  %r103 = call i64 @nova_rt_spawn(i64 %t63, i64 %t64)
  %r104 = call i64 @nova_rt_channel_create()
  %slot.sieve_result = alloca i64
  store i64 %r104, ptr %slot.sieve_result
  %t65 = call ptr @malloc(i64 24)
  %t66 = ptrtoint ptr @nova_main_spawn12 to i64
  store i64 %t66, ptr %t65
  %t67 = getelementptr i64, ptr %t65, i32 1
  store i64 %r97, ptr %t67
  %t68 = getelementptr i64, ptr %t65, i32 2
  store i64 %r104, ptr %t68
  %t69 = ptrtoint ptr @__nova_spawn_tramp_2 to i64
  %t70 = ptrtoint ptr %t65 to i64
  %r110 = call i64 @nova_rt_spawn(i64 %t69, i64 %t70)
  %r112 = call i64 @nova_rt_channel_recv(i64 %r104)
  %slot.sieve_count = alloca i64
  store i64 %r112, ptr %slot.sieve_count
  %t71 = getelementptr inbounds [52 x i8], ptr @.str.2, i64 0, i64 0
  %r117 = ptrtoint ptr %t71 to i64
  %r119 = call i64 @nova_rt_int_to_str(i64 %r112)
  %t72 = call i64 @nova_rt_str_concat(i64 %r117, i64 %r119)
  %t73 = inttoptr i64 %t72 to ptr
  call i32 @puts(ptr %t73)
  %r122 = call i64 @nova_rt_channel_create()
  %slot.prod_ch = alloca i64
  store i64 %r122, ptr %slot.prod_ch
  %t74 = call ptr @malloc(i64 16)
  %t75 = ptrtoint ptr @nova_main_spawn13 to i64
  store i64 %t75, ptr %t74
  %t76 = getelementptr i64, ptr %t74, i32 1
  store i64 %r122, ptr %t76
  %t77 = ptrtoint ptr @__nova_spawn_tramp_1 to i64
  %t78 = ptrtoint ptr %t74 to i64
  %r127 = call i64 @nova_rt_spawn(i64 %t77, i64 %t78)
  %slot.sum = alloca i64
  store i64 0, ptr %slot.sum
  %r134 = call i64 @nova_rt_channel_recv(i64 %r122)
  %r135 = add i64 0, %r134
  store i64 %r135, ptr %slot.sum
  %r140 = call i64 @nova_rt_channel_recv(i64 %r122)
  %r141 = add i64 %r135, %r140
  store i64 %r141, ptr %slot.sum
  %r146 = call i64 @nova_rt_channel_recv(i64 %r122)
  %r147 = add i64 %r141, %r146
  store i64 %r147, ptr %slot.sum
  %r152 = call i64 @nova_rt_channel_recv(i64 %r122)
  %r153 = add i64 %r147, %r152
  store i64 %r153, ptr %slot.sum
  %r158 = call i64 @nova_rt_channel_recv(i64 %r122)
  %r159 = add i64 %r153, %r158
  store i64 %r159, ptr %slot.sum
  %t79 = getelementptr inbounds [16 x i8], ptr @.str.3, i64 0, i64 0
  %r163 = ptrtoint ptr %t79 to i64
  %r165 = call i64 @nova_rt_int_to_str(i64 %r159)
  %t80 = call i64 @nova_rt_str_concat(i64 %r163, i64 %r165)
  %t81 = inttoptr i64 %t80 to ptr
  call i32 @puts(ptr %t81)
  %r169 = call i64 @make_worker(i64 2)
  %slot.doubler = alloca i64
  store i64 %r169, ptr %slot.doubler
  %r174 = call i64 @make_worker(i64 3)
  %slot.tripler = alloca i64
  store i64 %r174, ptr %slot.tripler
  %r178 = call i64 @nova_rt_channel_create()
  %slot.cap_ch = alloca i64
  store i64 %r178, ptr %slot.cap_ch
  %t82 = call ptr @malloc(i64 24)
  %t83 = ptrtoint ptr @nova_main_spawn14 to i64
  store i64 %t83, ptr %t82
  %t84 = getelementptr i64, ptr %t82, i32 1
  store i64 %r169, ptr %t84
  %t85 = getelementptr i64, ptr %t82, i32 2
  store i64 %r178, ptr %t85
  %t86 = ptrtoint ptr @__nova_spawn_tramp_2 to i64
  %t87 = ptrtoint ptr %t82 to i64
  %r184 = call i64 @nova_rt_spawn(i64 %t86, i64 %t87)
  %t88 = call ptr @malloc(i64 24)
  %t89 = ptrtoint ptr @nova_main_spawn15 to i64
  store i64 %t89, ptr %t88
  %t90 = getelementptr i64, ptr %t88, i32 1
  store i64 %r174, ptr %t90
  %t91 = getelementptr i64, ptr %t88, i32 2
  store i64 %r178, ptr %t91
  %t92 = ptrtoint ptr @__nova_spawn_tramp_2 to i64
  %t93 = ptrtoint ptr %t88 to i64
  %r187 = call i64 @nova_rt_spawn(i64 %t92, i64 %t93)
  %r189 = call i64 @nova_rt_channel_recv(i64 %r178)
  %slot.c1 = alloca i64
  store i64 %r189, ptr %slot.c1
  %r194 = call i64 @nova_rt_channel_recv(i64 %r178)
  %slot.c2 = alloca i64
  store i64 %r194, ptr %slot.c2
  %t94 = getelementptr inbounds [19 x i8], ptr @.str.4, i64 0, i64 0
  %r199 = ptrtoint ptr %t94 to i64
  %r201 = call i64 @nova_rt_int_to_str(i64 %r189)
  %t95 = call i64 @nova_rt_str_concat(i64 %r199, i64 %r201)
  %t96 = getelementptr inbounds [6 x i8], ptr @.str.5, i64 0, i64 0
  %r203 = ptrtoint ptr %t96 to i64
  %t97 = call i64 @nova_rt_str_concat(i64 %t95, i64 %r203)
  %r206 = call i64 @nova_rt_int_to_str(i64 %r194)
  %t98 = call i64 @nova_rt_str_concat(i64 %t97, i64 %r206)
  %t99 = inttoptr i64 %t98 to ptr
  call i32 @puts(ptr %t99)
  %t100 = getelementptr inbounds [1 x i8], ptr @.str.6, i64 0, i64 0
  %r210 = ptrtoint ptr %t100 to i64
  %t101 = inttoptr i64 %r210 to ptr
  call i32 @puts(ptr %t101)
  %t102 = getelementptr inbounds [29 x i8], ptr @.str.7, i64 0, i64 0
  %r213 = ptrtoint ptr %t102 to i64
  %t103 = inttoptr i64 %r213 to ptr
  call i32 @puts(ptr %t103)
  ret i64 0
}

define i64 @nova_main_spawn1(i64 %p0) {
entry0:
  %slot.results = alloca i64
  store i64 %p0, ptr %slot.results
  %r9 = call i64 @compute_squares(i64 %p0, i64 1, i64 50)
  ret i64 0
}

define i64 @nova_main_spawn2(i64 %p0) {
entry0:
  %slot.results = alloca i64
  store i64 %p0, ptr %slot.results
  %r11 = call i64 @compute_squares(i64 %p0, i64 51, i64 50)
  ret i64 0
}

define i64 @nova_main_spawn3(i64 %p0) {
entry0:
  %slot.prime_ch = alloca i64
  store i64 %p0, ptr %slot.prime_ch
  %r35 = call i64 @count_primes_range(i64 %p0, i64 2, i64 2500)
  ret i64 0
}

define i64 @nova_main_spawn4(i64 %p0) {
entry0:
  %slot.prime_ch = alloca i64
  store i64 %p0, ptr %slot.prime_ch
  %r37 = call i64 @count_primes_range(i64 %p0, i64 2501, i64 5000)
  ret i64 0
}

define i64 @nova_main_spawn5(i64 %p0) {
entry0:
  %slot.prime_ch = alloca i64
  store i64 %p0, ptr %slot.prime_ch
  %r39 = call i64 @count_primes_range(i64 %p0, i64 5001, i64 7500)
  ret i64 0
}

define i64 @nova_main_spawn6(i64 %p0) {
entry0:
  %slot.prime_ch = alloca i64
  store i64 %p0, ptr %slot.prime_ch
  %r41 = call i64 @count_primes_range(i64 %p0, i64 7501, i64 10000)
  ret i64 0
}

define i64 @nova_main_spawn7(i64 %p0) {
entry0:
  %slot.gen_out = alloca i64
  store i64 %p0, ptr %slot.gen_out
  %r78 = call i64 @generate(i64 %p0, i64 50)
  ret i64 0
}

define i64 @nova_main_spawn8(i64 %p0, i64 %p1) {
entry0:
  %slot.gen_out = alloca i64
  store i64 %p0, ptr %slot.gen_out
  %slot.f2_out = alloca i64
  store i64 %p1, ptr %slot.f2_out
  %r87 = call i64 @filter_stage(i64 %p0, i64 %p1, i64 2)
  ret i64 0
}

define i64 @nova_main_spawn9(i64 %p0, i64 %p1) {
entry0:
  %slot.f2_out = alloca i64
  store i64 %p0, ptr %slot.f2_out
  %slot.f3_out = alloca i64
  store i64 %p1, ptr %slot.f3_out
  %r94 = call i64 @filter_stage(i64 %p0, i64 %p1, i64 3)
  ret i64 0
}

define i64 @nova_main_spawn10(i64 %p0, i64 %p1) {
entry0:
  %slot.f3_out = alloca i64
  store i64 %p0, ptr %slot.f3_out
  %slot.f5_out = alloca i64
  store i64 %p1, ptr %slot.f5_out
  %r101 = call i64 @filter_stage(i64 %p0, i64 %p1, i64 5)
  ret i64 0
}

define i64 @nova_main_spawn11(i64 %p0, i64 %p1) {
entry0:
  %slot.f5_out = alloca i64
  store i64 %p0, ptr %slot.f5_out
  %slot.f7_out = alloca i64
  store i64 %p1, ptr %slot.f7_out
  %r108 = call i64 @filter_stage(i64 %p0, i64 %p1, i64 7)
  ret i64 0
}

define i64 @nova_main_spawn12(i64 %p0, i64 %p1) {
entry0:
  %slot.f7_out = alloca i64
  store i64 %p0, ptr %slot.f7_out
  %slot.sieve_result = alloca i64
  store i64 %p1, ptr %slot.sieve_result
  %r115 = call i64 @collect_primes(i64 %p0, i64 %p1, i64 100)
  ret i64 0
}

define i64 @nova_main_spawn13(i64 %p0) {
entry0:
  %slot.prod_ch = alloca i64
  store i64 %p0, ptr %slot.prod_ch
  %r130 = call i64 @producer(i64 %p0, i64 5)
  ret i64 0
}

define i64 @nova_main_spawn14(i64 %p0, i64 %p1) {
entry0:
  %slot.doubler = alloca i64
  store i64 %p0, ptr %slot.doubler
  %slot.cap_ch = alloca i64
  store i64 %p1, ptr %slot.cap_ch
  %t0 = inttoptr i64 %p0 to ptr
  %t1 = load i64, ptr %t0
  %t2 = inttoptr i64 %t1 to ptr
  %r189 = call i64 %t2(i64 %p0, i64 %p1, i64 21)
  ret i64 0
}

define i64 @nova_main_spawn15(i64 %p0, i64 %p1) {
entry0:
  %slot.tripler = alloca i64
  store i64 %p0, ptr %slot.tripler
  %slot.cap_ch = alloca i64
  store i64 %p1, ptr %slot.cap_ch
  %t0 = inttoptr i64 %p0 to ptr
  %t1 = load i64, ptr %t0
  %t2 = inttoptr i64 %t1 to ptr
  %r192 = call i64 %t2(i64 %p0, i64 %p1, i64 14)
  ret i64 0
}

define i64 @make_worker_lambda0_tramp(i64 %p0, i64 %p1, i64 %p2) {
entry_tramp:
  %env_ptr = inttoptr i64 %p0 to ptr
  %cap0_gep = getelementptr i64, ptr %env_ptr, i64 1
  %cap0 = load i64, ptr %cap0_gep
  %tramp_result = call i64 @make_worker_lambda0(i64 %p1, i64 %p2, i64 %cap0)
  ret i64 %tramp_result
}

define void @__nova_spawn_tramp_1(ptr %ctx) {
entry:
  %fn_i64 = load i64, ptr %ctx
  %fn = inttoptr i64 %fn_i64 to ptr
  %p1 = getelementptr i64, ptr %ctx, i32 1
  %a0 = load i64, ptr %p1
  call i64 %fn(i64 %a0)
  call void @free(ptr %ctx)
  ret void
}
define void @__nova_spawn_tramp_2(ptr %ctx) {
entry:
  %fn_i64 = load i64, ptr %ctx
  %fn = inttoptr i64 %fn_i64 to ptr
  %p1 = getelementptr i64, ptr %ctx, i32 1
  %a0 = load i64, ptr %p1
  %p2 = getelementptr i64, ptr %ctx, i32 2
  %a1 = load i64, ptr %p2
  call i64 %fn(i64 %a0, i64 %a1)
  call void @free(ptr %ctx)
  ret void
}
define i32 @main() {
entry:
  call i64 @nova_main()
  call void @nova_rt_wait_all()
  ret i32 0
}
