; Generated by NOVA compiler
target triple = "x86_64-pc-windows-msvc"

declare i32 @printf(ptr, ...)
declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare ptr @realloc(ptr, i64)
declare void @free(ptr)
; nova runtime — list ops
declare i64 @nova_rt_list_create()
declare i64 @nova_rt_list_append(i64, i64)
declare i64 @nova_rt_list_get(i64, i64)
declare i64 @nova_rt_list_set(i64, i64, i64)
declare i64 @nova_rt_list_len(i64)
declare i64 @nova_rt_list_print(i64)
declare i64 @nova_rt_iter_has_next(i64, i64)
; nova runtime — string ops
declare i64 @nova_rt_str_concat(i64, i64)
declare i64 @nova_rt_int_to_str(i64)
declare i64 @nova_rt_float_to_str(i64)
declare i64 @nova_rt_bool_to_str(i64)
declare i64 @nova_rt_str_len(i64)
declare i64 @nova_rt_len(i64)
declare i64 @nova_rt_contains(i64, i64)
declare i64 @nova_rt_slice(i64, i64, i64)
declare i64 @nova_rt_upper(i64)
declare i64 @nova_rt_lower(i64)
declare i64 @nova_rt_trim(i64)
declare i64 @nova_rt_split(i64, i64)
declare i64 @nova_rt_replace(i64, i64, i64)
declare i64 @nova_rt_starts_with(i64, i64)
declare i64 @nova_rt_ends_with(i64, i64)
declare i64 @nova_rt_find(i64, i64)
declare i64 @nova_rt_join(i64, i64)
declare i64 @nova_rt_chars(i64)
; nova runtime — list stdlib
declare i64 @nova_rt_list_reverse(i64)
declare i64 @nova_rt_list_sort(i64)
declare i64 @nova_rt_list_map(i64, i64)
declare i64 @nova_rt_list_filter(i64, i64)
declare i64 @nova_rt_list_concat(i64, i64)
declare i64 @nova_rt_list_to_str(i64)
declare i64 @nova_rt_len_any(i64)
; nova runtime — type conversions
declare i64 @nova_rt_parse_int(i64)
declare i64 @nova_rt_parse_float(i64)
declare i32 @strcmp(ptr, ptr)
; nova runtime — dict ops (Phase 1: ordered array, O(n) lookup)
declare i64 @nova_rt_dict_create()
declare i64 @nova_rt_dict_set(i64, i64, i64)
declare i64 @nova_rt_dict_get(i64, i64)
declare i64 @nova_rt_dict_has(i64, i64)
declare i64 @nova_rt_dict_del(i64, i64)
declare i64 @nova_rt_dict_len(i64)
declare i64 @nova_rt_dict_keys(i64)
; nova runtime — IO ops
declare i64 @nova_rt_read_line()
declare i64 @nova_rt_read_file(i64)
declare i64 @nova_rt_write_file(i64, i64)
; nova runtime — channel/spawn ops
declare i64 @nova_rt_channel_create()
declare i64 @nova_rt_channel_send(i64, i64)
declare i64 @nova_rt_channel_recv(i64)
declare i64 @nova_rt_channel_close(i64)
declare i64 @nova_rt_channel_select(i64, i64)
declare i64 @nova_rt_channel_recv_timeout(i64, i64)
declare i64 @nova_rt_spawn(i64, i64)
declare i64 @nova_rt_monitor(i64)
declare void @nova_rt_wait_all()
; nova runtime — math (trig/log via C runtime for non-intrinsic functions)
declare i64 @nova_rt_tan(i64)
declare i64 @nova_rt_asin(i64)
declare i64 @nova_rt_acos(i64)
declare i64 @nova_rt_atan(i64)
declare i64 @nova_rt_atan2(i64, i64)
declare i64 @nova_rt_fmod(i64, i64)
declare i64 @nova_rt_int_pow(i64, i64)
; nova error state — global flag (errno-style)
@__nova_error_flag = global i64 0
@__nova_error_msg = global i64 0

@.str.0 = private unnamed_addr constant [5 x i8] c"zero\00"
@.str.1 = private unnamed_addr constant [4 x i8] c"one\00"
@.str.2 = private unnamed_addr constant [5 x i8] c"many\00"
@.str.3 = private unnamed_addr constant [9 x i8] c"FizzBuzz\00"
@.str.4 = private unnamed_addr constant [5 x i8] c"Fizz\00"
@.str.5 = private unnamed_addr constant [5 x i8] c"Buzz\00"
@.str.6 = private unnamed_addr constant [5 x i8] c"NOVA\00"
@.str.7 = private unnamed_addr constant [27 x i8] c"Welcome to NOVA version 1!\00"
@.str.8 = private unnamed_addr constant [10 x i8] c"2 + 2 = 4\00"
@.str.9 = private unnamed_addr constant [13 x i8] c"Sum 1..10 = \00"
@.str.10 = private unnamed_addr constant [6 x i8] c"apple\00"
@.str.11 = private unnamed_addr constant [7 x i8] c"banana\00"
@.str.12 = private unnamed_addr constant [7 x i8] c"cherry\00"
@.str.13 = private unnamed_addr constant [8 x i8] c"Fruit: \00"
@.str.14 = private unnamed_addr constant [12 x i8] c"add5(10) = \00"
@.str.15 = private unnamed_addr constant [6 x i8] c"alice\00"
@.str.16 = private unnamed_addr constant [4 x i8] c"bob\00"
@.str.17 = private unnamed_addr constant [8 x i8] c"charlie\00"
@.str.18 = private unnamed_addr constant [8 x i8] c"Alice: \00"
@.str.19 = private unnamed_addr constant [6 x i8] c"diana\00"
@.str.20 = private unnamed_addr constant [14 x i8] c"Diana added: \00"
@.str.21 = private unnamed_addr constant [10 x i8] c"Has bob? \00"
@.str.22 = private unnamed_addr constant [12 x i8] c"Dict size: \00"
@.str.23 = private unnamed_addr constant [15 x i8] c"describe(0) = \00"
@.str.24 = private unnamed_addr constant [15 x i8] c"describe(1) = \00"
@.str.25 = private unnamed_addr constant [16 x i8] c"describe(42) = \00"
@.str.26 = private unnamed_addr constant [26 x i8] c"5 |> double |> add_one = \00"
@.str.27 = private unnamed_addr constant [8 x i8] c"2^10 = \00"
@.str.28 = private unnamed_addr constant [17 x i8] c"  Hello, NOVA!  \00"
@.str.29 = private unnamed_addr constant [11 x i8] c"trimmed: '\00"
@.str.30 = private unnamed_addr constant [2 x i8] c"'\00"
@.str.31 = private unnamed_addr constant [8 x i8] c"upper: \00"
@.str.32 = private unnamed_addr constant [6 x i8] c"hello\00"
@.str.33 = private unnamed_addr constant [16 x i8] c"contains nova: \00"
@.str.34 = private unnamed_addr constant [11 x i8] c"Hello NOVA\00"
@.str.35 = private unnamed_addr constant [9 x i8] c"length: \00"
@.str.36 = private unnamed_addr constant [1 x i8] c"\00"
@.str.37 = private unnamed_addr constant [21 x i8] c"All features passed!\00"
@.str.38 = private unnamed_addr constant [6 x i8] c"%lld\0A\00"
@.str.39 = private unnamed_addr constant [4 x i8] c"%f\0A\00"
@.str.40 = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.str.41 = private unnamed_addr constant [5 x i8] c"true\00"
@.str.42 = private unnamed_addr constant [6 x i8] c"false\00"

define i64 @make_adder(i64 %p0) {
entry0:
  %slot.n = alloca i64
  store i64 %p0, ptr %slot.n
  %t0 = call ptr @malloc(i64 16)
  %t1 = ptrtoint ptr @make_adder_lambda0_tramp to i64
  store i64 %t1, ptr %t0
  %t2 = getelementptr i64, ptr %t0, i64 1
  store i64 %p0, ptr %t2
  %r4 = ptrtoint ptr %t0 to i64
  ret i64 %r4
}

define i64 @make_adder_lambda0(i64 %p0, i64 %p1) {
entry0:
  %slot.x = alloca i64
  store i64 %p0, ptr %slot.x
  %slot.n = alloca i64
  store i64 %p1, ptr %slot.n
  %r9 = add i64 %p1, %p0
  ret i64 %r9
}

define i64 @describe(i64 %p0) {
entry0:
  %slot.n = alloca i64
  store i64 %p0, ptr %slot.n
  %r3 = load i64, ptr %slot.n
  %slot.__match_0 = alloca i64
  %t0 = icmp eq i64 %r3, 0
  %r6 = zext i1 %t0 to i64
  %t1 = trunc i64 %r6 to i1
  br i1 %t1, label %arm0_body2, label %arm0_next3

arm0_body2:
  %t2 = getelementptr inbounds [5 x i8], ptr @.str.0, i64 0, i64 0
  %r7 = ptrtoint ptr %t2 to i64
  store i64 %r7, ptr %slot.__match_0
  br label %match_merge1

arm0_next3:
  %t3 = icmp eq i64 %r3, 1
  %r10 = zext i1 %t3 to i64
  %t4 = trunc i64 %r10 to i1
  br i1 %t4, label %arm1_body4, label %arm1_next5

arm1_body4:
  %t5 = getelementptr inbounds [4 x i8], ptr @.str.1, i64 0, i64 0
  %r11 = ptrtoint ptr %t5 to i64
  store i64 %r11, ptr %slot.__match_0
  br label %match_merge1

arm1_next5:
  br label %arm2_body6

arm2_body6:
  %t6 = getelementptr inbounds [5 x i8], ptr @.str.2, i64 0, i64 0
  %r13 = ptrtoint ptr %t6 to i64
  store i64 %r13, ptr %slot.__match_0
  br label %match_merge1

match_merge1:
  %r15 = load i64, ptr %slot.__match_0
  ret i64 %r15
}

define i64 @double(i64 %p0) {
entry0:
  %slot.x = alloca i64
  store i64 %p0, ptr %slot.x
  %r5 = mul i64 %p0, 2
  ret i64 %r5
}

define i64 @add_one(i64 %p0) {
entry0:
  %slot.x = alloca i64
  store i64 %p0, ptr %slot.x
  %r5 = add i64 %p0, 1
  ret i64 %r5
}

define i64 @power(i64 %p0, i64 %p1) {
entry0:
  %slot.base = alloca i64
  store i64 %p0, ptr %slot.base
  %slot.exp = alloca i64
  store i64 %p1, ptr %slot.exp
  %t0 = icmp eq i64 %p1, 0
  %r7 = zext i1 %t0 to i64
  %slot.__ifb_0 = alloca i64
  %t1 = trunc i64 %r7 to i1
  br i1 %t1, label %ifb_then1, label %ifb_else2

ifb_then1:
  ret i64 1

ifb_else2:
  store i64 0, ptr %slot.__ifb_0
  br label %ifb_merge3

ifb_merge3:
  %r15 = load i64, ptr %slot.base
  %r16 = load i64, ptr %slot.base
  %r17 = load i64, ptr %slot.exp
  %r19 = sub i64 %r17, 1
  %r20 = call i64 @power(i64 %r16, i64 %r19)
  %r21 = mul i64 %r15, %r20
  ret i64 %r21
}

define i64 @fizzbuzz(i64 %p0) {
entry0:
  %slot.n = alloca i64
  store i64 %p0, ptr %slot.n
  %r5 = srem i64 %p0, 15
  %t0 = icmp eq i64 %r5, 0
  %r7 = zext i1 %t0 to i64
  %slot.__ifb_0 = alloca i64
  %t1 = trunc i64 %r7 to i1
  br i1 %t1, label %ifb_then1, label %ifb_else2

ifb_then1:
  %t2 = getelementptr inbounds [9 x i8], ptr @.str.3, i64 0, i64 0
  %r10 = ptrtoint ptr %t2 to i64
  ret i64 %r10

ifb_else2:
  store i64 0, ptr %slot.__ifb_0
  br label %ifb_merge3

ifb_merge3:
  %r15 = load i64, ptr %slot.n
  %r17 = srem i64 %r15, 3
  %t3 = icmp eq i64 %r17, 0
  %r19 = zext i1 %t3 to i64
  %slot.__ifb_1 = alloca i64
  %t4 = trunc i64 %r19 to i1
  br i1 %t4, label %ifb_then5, label %ifb_else6

ifb_then5:
  %t5 = getelementptr inbounds [5 x i8], ptr @.str.4, i64 0, i64 0
  %r22 = ptrtoint ptr %t5 to i64
  ret i64 %r22

ifb_else6:
  store i64 0, ptr %slot.__ifb_1
  br label %ifb_merge7

ifb_merge7:
  %r27 = load i64, ptr %slot.n
  %r29 = srem i64 %r27, 5
  %t6 = icmp eq i64 %r29, 0
  %r31 = zext i1 %t6 to i64
  %slot.__ifb_2 = alloca i64
  %t7 = trunc i64 %r31 to i1
  br i1 %t7, label %ifb_then9, label %ifb_else10

ifb_then9:
  %t8 = getelementptr inbounds [5 x i8], ptr @.str.5, i64 0, i64 0
  %r34 = ptrtoint ptr %t8 to i64
  ret i64 %r34

ifb_else10:
  store i64 0, ptr %slot.__ifb_2
  br label %ifb_merge11

ifb_merge11:
  %r39 = load i64, ptr %slot.n
  %r40 = call i64 @nova_rt_int_to_str(i64 %r39)
  ret i64 %r40
}

define i64 @nova_main() {
entry0:
  %t0 = getelementptr inbounds [5 x i8], ptr @.str.6, i64 0, i64 0
  %r0 = ptrtoint ptr %t0 to i64
  %slot.name = alloca i64
  store i64 %r0, ptr %slot.name
  %slot.version = alloca i64
  store i64 1, ptr %slot.version
  %t1 = getelementptr inbounds [27 x i8], ptr @.str.7, i64 0, i64 0
  %r16 = ptrtoint ptr %t1 to i64
  %t2 = inttoptr i64 %r16 to ptr
  call i32 @puts(ptr %t2)
  %t3 = getelementptr inbounds [10 x i8], ptr @.str.8, i64 0, i64 0
  %r25 = ptrtoint ptr %t3 to i64
  %t4 = inttoptr i64 %r25 to ptr
  call i32 @puts(ptr %t4)
  %slot.total = alloca i64
  store i64 0, ptr %slot.total
  %slot.__range_idx_3 = alloca i64
  store i64 1, ptr %slot.__range_idx_3
  %slot.__range_end_3 = alloca i64
  store i64 10, ptr %slot.__range_end_3
  %slot.i = alloca i64
  %slot.fruits = alloca i64
  %slot.f = alloca i64
  %slot.add5 = alloca i64
  %slot.nums = alloca i64
  %slot.doubled = alloca i64
  %slot.evens = alloca i64
  %slot.scores = alloca i64
  %slot.result = alloca i64
  %slot.greeting = alloca i64
  br label %range_header1

range_header1:
  %r37 = load i64, ptr %slot.__range_idx_3
  %r38 = load i64, ptr %slot.__range_end_3
  %t5 = icmp sle i64 %r37, %r38
  %r39 = zext i1 %t5 to i64
  %t6 = trunc i64 %r39 to i1
  br i1 %t6, label %range_body2, label %range_exit3

range_body2:
  %r40 = load i64, ptr %slot.__range_idx_3
  store i64 %r40, ptr %slot.i
  %r44 = load i64, ptr %slot.total
  %r46 = add i64 %r44, %r40
  store i64 %r46, ptr %slot.total
  %r49 = load i64, ptr %slot.__range_idx_3
  %r50 = add i64 %r49, 1
  store i64 %r50, ptr %slot.__range_idx_3
  br label %range_header1

range_exit3:
  %t7 = getelementptr inbounds [13 x i8], ptr @.str.9, i64 0, i64 0
  %r55 = ptrtoint ptr %t7 to i64
  %r56 = load i64, ptr %slot.total
  %r57 = call i64 @nova_rt_int_to_str(i64 %r56)
  %t8 = call i64 @nova_rt_str_concat(i64 %r55, i64 %r57)
  %t9 = inttoptr i64 %t8 to ptr
  call i32 @puts(ptr %t9)
  %t10 = getelementptr inbounds [6 x i8], ptr @.str.10, i64 0, i64 0
  %r60 = ptrtoint ptr %t10 to i64
  %t11 = getelementptr inbounds [7 x i8], ptr @.str.11, i64 0, i64 0
  %r61 = ptrtoint ptr %t11 to i64
  %t12 = getelementptr inbounds [7 x i8], ptr @.str.12, i64 0, i64 0
  %r62 = ptrtoint ptr %t12 to i64
  %r63 = call i64 @nova_rt_list_create()
  %t13 = call i64 @nova_rt_list_append(i64 %r63, i64 %r60)
  %t14 = call i64 @nova_rt_list_append(i64 %r63, i64 %r61)
  %t15 = call i64 @nova_rt_list_append(i64 %r63, i64 %r62)
  store i64 %r63, ptr %slot.fruits
  %slot.__for_iter_5 = alloca i64
  store i64 %r63, ptr %slot.__for_iter_5
  %slot.__for_idx_5 = alloca i64
  store i64 0, ptr %slot.__for_idx_5
  br label %for_header4

for_header4:
  %r73 = load i64, ptr %slot.__for_iter_5
  %r75 = load i64, ptr %slot.__for_idx_5
  %r74 = call i64 @nova_rt_iter_has_next(i64 %r73, i64 %r75)
  %t16 = trunc i64 %r74 to i1
  br i1 %t16, label %for_body5, label %for_exit6

for_body5:
  %r76 = load i64, ptr %slot.__for_iter_5
  %r77 = load i64, ptr %slot.__for_idx_5
  %r78 = call i64 @nova_rt_list_get(i64 %r76, i64 %r77)
  store i64 %r78, ptr %slot.f
  %t17 = getelementptr inbounds [8 x i8], ptr @.str.13, i64 0, i64 0
  %r83 = ptrtoint ptr %t17 to i64
  %t18 = call i64 @nova_rt_str_concat(i64 %r83, i64 %r78)
  %t19 = inttoptr i64 %t18 to ptr
  call i32 @puts(ptr %t19)
  %r87 = add i64 %r77, 1
  store i64 %r87, ptr %slot.__for_idx_5
  br label %for_header4

for_exit6:
  %r92 = call i64 @make_adder(i64 5)
  store i64 %r92, ptr %slot.add5
  %t20 = getelementptr inbounds [12 x i8], ptr @.str.14, i64 0, i64 0
  %r97 = ptrtoint ptr %t20 to i64
  %t21 = inttoptr i64 %r92 to ptr
  %t22 = load i64, ptr %t21
  %t23 = inttoptr i64 %t22 to ptr
  %r100 = call i64 %t23(i64 %r92, i64 10)
  %r101 = call i64 @nova_rt_int_to_str(i64 %r100)
  %t24 = call i64 @nova_rt_str_concat(i64 %r97, i64 %r101)
  %t25 = inttoptr i64 %t24 to ptr
  call i32 @puts(ptr %t25)
  %r109 = call i64 @nova_rt_list_create()
  %t26 = call i64 @nova_rt_list_append(i64 %r109, i64 1)
  %t27 = call i64 @nova_rt_list_append(i64 %r109, i64 2)
  %t28 = call i64 @nova_rt_list_append(i64 %r109, i64 3)
  %t29 = call i64 @nova_rt_list_append(i64 %r109, i64 4)
  %t30 = call i64 @nova_rt_list_append(i64 %r109, i64 5)
  store i64 %r109, ptr %slot.nums
  %t31 = call ptr @malloc(i64 8)
  %t32 = ptrtoint ptr @nova_main_lambda1_tramp to i64
  store i64 %t32, ptr %t31
  %r114 = ptrtoint ptr %t31 to i64
  %r115 = call i64 @nova_rt_list_map(i64 %r109, i64 %r114)
  store i64 %r115, ptr %slot.doubled
  call i64 @nova_rt_list_print(i64 %r115)
  %t33 = call ptr @malloc(i64 8)
  %t34 = ptrtoint ptr @nova_main_lambda2_tramp to i64
  store i64 %t34, ptr %t33
  %r123 = ptrtoint ptr %t33 to i64
  %r124 = call i64 @nova_rt_list_filter(i64 %r109, i64 %r123)
  store i64 %r124, ptr %slot.evens
  call i64 @nova_rt_list_print(i64 %r124)
  %t35 = getelementptr inbounds [6 x i8], ptr @.str.15, i64 0, i64 0
  %r131 = ptrtoint ptr %t35 to i64
  %t36 = getelementptr inbounds [4 x i8], ptr @.str.16, i64 0, i64 0
  %r133 = ptrtoint ptr %t36 to i64
  %t37 = getelementptr inbounds [8 x i8], ptr @.str.17, i64 0, i64 0
  %r135 = ptrtoint ptr %t37 to i64
  %r137 = call i64 @nova_rt_dict_create()
  %t38 = call i64 @nova_rt_dict_set(i64 %r137, i64 %r131, i64 95)
  %t39 = call i64 @nova_rt_dict_set(i64 %r137, i64 %r133, i64 87)
  %t40 = call i64 @nova_rt_dict_set(i64 %r137, i64 %r135, i64 92)
  store i64 %r137, ptr %slot.scores
  %t41 = getelementptr inbounds [8 x i8], ptr @.str.18, i64 0, i64 0
  %r142 = ptrtoint ptr %t41 to i64
  %t42 = getelementptr inbounds [6 x i8], ptr @.str.15, i64 0, i64 0
  %r144 = ptrtoint ptr %t42 to i64
  %r145 = call i64 @nova_rt_dict_get(i64 %r137, i64 %r144)
  %r146 = call i64 @nova_rt_int_to_str(i64 %r145)
  %t43 = call i64 @nova_rt_str_concat(i64 %r142, i64 %r146)
  %t44 = inttoptr i64 %t43 to ptr
  call i32 @puts(ptr %t44)
  %t45 = getelementptr inbounds [6 x i8], ptr @.str.19, i64 0, i64 0
  %r151 = ptrtoint ptr %t45 to i64
  %t46 = call i64 @nova_rt_dict_set(i64 %r137, i64 %r151, i64 98)
  %t47 = getelementptr inbounds [14 x i8], ptr @.str.20, i64 0, i64 0
  %r155 = ptrtoint ptr %t47 to i64
  %t48 = getelementptr inbounds [6 x i8], ptr @.str.19, i64 0, i64 0
  %r157 = ptrtoint ptr %t48 to i64
  %r158 = call i64 @nova_rt_dict_get(i64 %r137, i64 %r157)
  %r159 = call i64 @nova_rt_int_to_str(i64 %r158)
  %t49 = call i64 @nova_rt_str_concat(i64 %r155, i64 %r159)
  %t50 = inttoptr i64 %t49 to ptr
  call i32 @puts(ptr %t50)
  %t51 = getelementptr inbounds [10 x i8], ptr @.str.21, i64 0, i64 0
  %r163 = ptrtoint ptr %t51 to i64
  %t52 = getelementptr inbounds [4 x i8], ptr @.str.16, i64 0, i64 0
  %r165 = ptrtoint ptr %t52 to i64
  %r166 = call i64 @nova_rt_dict_has(i64 %r137, i64 %r165)
  %r167 = call i64 @nova_rt_bool_to_str(i64 %r166)
  %t53 = call i64 @nova_rt_str_concat(i64 %r163, i64 %r167)
  %t54 = inttoptr i64 %t53 to ptr
  call i32 @puts(ptr %t54)
  %t55 = getelementptr inbounds [12 x i8], ptr @.str.22, i64 0, i64 0
  %r171 = ptrtoint ptr %t55 to i64
  %r174 = call i64 @nova_rt_dict_len(i64 %r137)
  %r175 = call i64 @nova_rt_int_to_str(i64 %r174)
  %t56 = call i64 @nova_rt_str_concat(i64 %r171, i64 %r175)
  %t57 = inttoptr i64 %t56 to ptr
  call i32 @puts(ptr %t57)
  %t58 = getelementptr inbounds [15 x i8], ptr @.str.23, i64 0, i64 0
  %r179 = ptrtoint ptr %t58 to i64
  %r181 = call i64 @describe(i64 0)
  %t59 = call i64 @nova_rt_str_concat(i64 %r179, i64 %r181)
  %t60 = inttoptr i64 %t59 to ptr
  call i32 @puts(ptr %t60)
  %t61 = getelementptr inbounds [15 x i8], ptr @.str.24, i64 0, i64 0
  %r185 = ptrtoint ptr %t61 to i64
  %r187 = call i64 @describe(i64 1)
  %t62 = call i64 @nova_rt_str_concat(i64 %r185, i64 %r187)
  %t63 = inttoptr i64 %t62 to ptr
  call i32 @puts(ptr %t63)
  %t64 = getelementptr inbounds [16 x i8], ptr @.str.25, i64 0, i64 0
  %r191 = ptrtoint ptr %t64 to i64
  %r193 = call i64 @describe(i64 42)
  %t65 = call i64 @nova_rt_str_concat(i64 %r191, i64 %r193)
  %t66 = inttoptr i64 %t65 to ptr
  call i32 @puts(ptr %t66)
  %t67 = call ptr @malloc(i64 8)
  %t68 = ptrtoint ptr @double_tramp to i64
  store i64 %t68, ptr %t67
  %r197 = ptrtoint ptr %t67 to i64
  %r198 = call i64 @double(i64 5)
  %t69 = call ptr @malloc(i64 8)
  %t70 = ptrtoint ptr @add_one_tramp to i64
  store i64 %t70, ptr %t69
  %r199 = ptrtoint ptr %t69 to i64
  %r200 = call i64 @add_one(i64 %r198)
  store i64 %r200, ptr %slot.result
  %t71 = getelementptr inbounds [26 x i8], ptr @.str.26, i64 0, i64 0
  %r205 = ptrtoint ptr %t71 to i64
  %r207 = call i64 @nova_rt_int_to_str(i64 %r200)
  %t72 = call i64 @nova_rt_str_concat(i64 %r205, i64 %r207)
  %t73 = inttoptr i64 %t72 to ptr
  call i32 @puts(ptr %t73)
  %t74 = getelementptr inbounds [8 x i8], ptr @.str.27, i64 0, i64 0
  %r211 = ptrtoint ptr %t74 to i64
  %r214 = call i64 @power(i64 2, i64 10)
  %r215 = call i64 @nova_rt_int_to_str(i64 %r214)
  %t75 = call i64 @nova_rt_str_concat(i64 %r211, i64 %r215)
  %t76 = inttoptr i64 %t75 to ptr
  call i32 @puts(ptr %t76)
  %t77 = getelementptr inbounds [17 x i8], ptr @.str.28, i64 0, i64 0
  %r218 = ptrtoint ptr %t77 to i64
  store i64 %r218, ptr %slot.greeting
  %t78 = getelementptr inbounds [11 x i8], ptr @.str.29, i64 0, i64 0
  %r223 = ptrtoint ptr %t78 to i64
  %r225 = call i64 @nova_rt_trim(i64 %r218)
  %t79 = call i64 @nova_rt_str_concat(i64 %r223, i64 %r225)
  %t80 = getelementptr inbounds [2 x i8], ptr @.str.30, i64 0, i64 0
  %r227 = ptrtoint ptr %t80 to i64
  %t81 = call i64 @nova_rt_str_concat(i64 %t79, i64 %r227)
  %t82 = inttoptr i64 %t81 to ptr
  call i32 @puts(ptr %t82)
  %t83 = getelementptr inbounds [8 x i8], ptr @.str.31, i64 0, i64 0
  %r231 = ptrtoint ptr %t83 to i64
  %t84 = getelementptr inbounds [6 x i8], ptr @.str.32, i64 0, i64 0
  %r232 = ptrtoint ptr %t84 to i64
  %r233 = call i64 @nova_rt_upper(i64 %r232)
  %t85 = call i64 @nova_rt_str_concat(i64 %r231, i64 %r233)
  %t86 = inttoptr i64 %t85 to ptr
  call i32 @puts(ptr %t86)
  %t87 = getelementptr inbounds [16 x i8], ptr @.str.33, i64 0, i64 0
  %r237 = ptrtoint ptr %t87 to i64
  %t88 = getelementptr inbounds [11 x i8], ptr @.str.34, i64 0, i64 0
  %r238 = ptrtoint ptr %t88 to i64
  %t89 = getelementptr inbounds [5 x i8], ptr @.str.6, i64 0, i64 0
  %r239 = ptrtoint ptr %t89 to i64
  %r240 = call i64 @nova_rt_contains(i64 %r238, i64 %r239)
  %r241 = call i64 @nova_rt_bool_to_str(i64 %r240)
  %t90 = call i64 @nova_rt_str_concat(i64 %r237, i64 %r241)
  %t91 = inttoptr i64 %t90 to ptr
  call i32 @puts(ptr %t91)
  %t92 = getelementptr inbounds [9 x i8], ptr @.str.35, i64 0, i64 0
  %r245 = ptrtoint ptr %t92 to i64
  %t93 = getelementptr inbounds [5 x i8], ptr @.str.6, i64 0, i64 0
  %r247 = ptrtoint ptr %t93 to i64
  %r248 = call i64 @nova_rt_len(i64 %r247)
  %r249 = call i64 @nova_rt_int_to_str(i64 %r248)
  %t94 = call i64 @nova_rt_str_concat(i64 %r245, i64 %r249)
  %t95 = inttoptr i64 %t94 to ptr
  call i32 @puts(ptr %t95)
  store i64 1, ptr %slot.i
  br label %while_header7

while_header7:
  %r255 = load i64, ptr %slot.i
  %t96 = icmp sle i64 %r255, 20
  %r257 = zext i1 %t96 to i64
  %t97 = trunc i64 %r257 to i1
  br i1 %t97, label %while_body8, label %while_exit9

while_body8:
  %r260 = load i64, ptr %slot.i
  %r261 = call i64 @fizzbuzz(i64 %r260)
  %t98 = inttoptr i64 %r261 to ptr
  call i32 @puts(ptr %t98)
  %r263 = load i64, ptr %slot.i
  %r265 = add i64 %r263, 1
  store i64 %r265, ptr %slot.i
  br label %while_header7

while_exit9:
  %t99 = getelementptr inbounds [1 x i8], ptr @.str.36, i64 0, i64 0
  %r270 = ptrtoint ptr %t99 to i64
  %t100 = inttoptr i64 %r270 to ptr
  call i32 @puts(ptr %t100)
  %t101 = getelementptr inbounds [21 x i8], ptr @.str.37, i64 0, i64 0
  %r273 = ptrtoint ptr %t101 to i64
  %t102 = inttoptr i64 %r273 to ptr
  call i32 @puts(ptr %t102)
  ret i64 0
}

define i64 @nova_main_lambda1(i64 %p0) {
entry0:
  %slot.x = alloca i64
  store i64 %p0, ptr %slot.x
  %r118 = mul i64 %p0, 2
  ret i64 %r118
}

define i64 @nova_main_lambda2(i64 %p0) {
entry0:
  %slot.x = alloca i64
  store i64 %p0, ptr %slot.x
  %r127 = srem i64 %p0, 2
  %t0 = icmp eq i64 %r127, 0
  %r129 = zext i1 %t0 to i64
  ret i64 %r129
}

define i64 @make_adder_lambda0_tramp(i64 %p0, i64 %p1) {
entry_tramp:
  %env_ptr = inttoptr i64 %p0 to ptr
  %cap0_gep = getelementptr i64, ptr %env_ptr, i64 1
  %cap0 = load i64, ptr %cap0_gep
  %tramp_result = call i64 @make_adder_lambda0(i64 %p1, i64 %cap0)
  ret i64 %tramp_result
}

define i64 @nova_main_lambda1_tramp(i64 %p0, i64 %p1) {
entry_tramp:
  %env_ptr = inttoptr i64 %p0 to ptr
  %tramp_result = call i64 @nova_main_lambda1(i64 %p1)
  ret i64 %tramp_result
}

define i64 @nova_main_lambda2_tramp(i64 %p0, i64 %p1) {
entry_tramp:
  %env_ptr = inttoptr i64 %p0 to ptr
  %tramp_result = call i64 @nova_main_lambda2(i64 %p1)
  ret i64 %tramp_result
}

define i64 @double_tramp(i64 %p0, i64 %p1) {
entry_tramp:
  %env_ptr = inttoptr i64 %p0 to ptr
  %tramp_result = call i64 @double(i64 %p1)
  ret i64 %tramp_result
}

define i64 @add_one_tramp(i64 %p0, i64 %p1) {
entry_tramp:
  %env_ptr = inttoptr i64 %p0 to ptr
  %tramp_result = call i64 @add_one(i64 %p1)
  ret i64 %tramp_result
}

define i32 @main() {
entry:
  call i64 @nova_main()
  call void @nova_rt_wait_all()
  ret i32 0
}
