; Generated by NOVA compiler
target triple = "x86_64-pc-windows-msvc"

declare i32 @printf(ptr, ...)
declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare ptr @realloc(ptr, i64)
declare void @free(ptr)
; nova runtime — list ops
declare i64 @nova_rt_list_create()
declare i64 @nova_rt_list_append(i64, i64)
declare i64 @nova_rt_list_get(i64, i64)
declare i64 @nova_rt_list_set(i64, i64, i64)
declare i64 @nova_rt_list_len(i64)
declare i64 @nova_rt_list_print(i64)
declare i64 @nova_rt_iter_has_next(i64, i64)
; nova runtime — string ops
declare i64 @nova_rt_str_concat(i64, i64)
declare i64 @nova_rt_int_to_str(i64)
declare i64 @nova_rt_float_to_str(i64)
declare i64 @nova_rt_bool_to_str(i64)
declare i64 @nova_rt_str_len(i64)
declare i64 @nova_rt_len(i64)
declare i64 @nova_rt_contains(i64, i64)
declare i64 @nova_rt_slice(i64, i64, i64)
declare i64 @nova_rt_upper(i64)
declare i64 @nova_rt_lower(i64)
declare i64 @nova_rt_trim(i64)
declare i64 @nova_rt_split(i64, i64)
declare i64 @nova_rt_replace(i64, i64, i64)
declare i64 @nova_rt_starts_with(i64, i64)
declare i64 @nova_rt_ends_with(i64, i64)
declare i64 @nova_rt_find(i64, i64)
declare i64 @nova_rt_join(i64, i64)
declare i64 @nova_rt_chars(i64)
; nova runtime — list stdlib
declare i64 @nova_rt_list_reverse(i64)
declare i64 @nova_rt_list_sort(i64)
declare i64 @nova_rt_list_map(i64, i64)
declare i64 @nova_rt_list_filter(i64, i64)
declare i64 @nova_rt_list_concat(i64, i64)
declare i64 @nova_rt_list_to_str(i64)
declare i64 @nova_rt_len_any(i64)
; nova runtime — type conversions
declare i64 @nova_rt_parse_int(i64)
declare i64 @nova_rt_parse_float(i64)
declare i32 @strcmp(ptr, ptr)
; nova runtime — dict ops (Phase 1: ordered array, O(n) lookup)
declare i64 @nova_rt_dict_create()
declare i64 @nova_rt_dict_set(i64, i64, i64)
declare i64 @nova_rt_dict_get(i64, i64)
declare i64 @nova_rt_dict_has(i64, i64)
declare i64 @nova_rt_dict_del(i64, i64)
declare i64 @nova_rt_dict_len(i64)
declare i64 @nova_rt_dict_keys(i64)
; nova runtime — IO ops
declare i64 @nova_rt_read_line()
declare i64 @nova_rt_read_file(i64)
declare i64 @nova_rt_write_file(i64, i64)
; nova runtime — channel/spawn ops
declare i64 @nova_rt_channel_create()
declare i64 @nova_rt_channel_send(i64, i64)
declare i64 @nova_rt_channel_recv(i64)
declare i64 @nova_rt_channel_close(i64)
declare i64 @nova_rt_channel_select(i64, i64)
declare i64 @nova_rt_channel_recv_timeout(i64, i64)
declare i64 @nova_rt_spawn(i64, i64)
declare i64 @nova_rt_monitor(i64)
declare void @nova_rt_wait_all()
; nova runtime — math (trig/log via C runtime for non-intrinsic functions)
declare i64 @nova_rt_tan(i64)
declare i64 @nova_rt_asin(i64)
declare i64 @nova_rt_acos(i64)
declare i64 @nova_rt_atan(i64)
declare i64 @nova_rt_atan2(i64, i64)
declare i64 @nova_rt_fmod(i64, i64)
declare i64 @nova_rt_int_pow(i64, i64)
; nova error state — global flag (errno-style)
@__nova_error_flag = global i64 0
@__nova_error_msg = global i64 0

@.str.0 = private unnamed_addr constant [6 x i8] c"%lld\0A\00"
@.str.1 = private unnamed_addr constant [4 x i8] c"%f\0A\00"
@.str.2 = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.str.3 = private unnamed_addr constant [5 x i8] c"true\00"
@.str.4 = private unnamed_addr constant [6 x i8] c"false\00"

define i64 @sumList(i64 %p0, i64 %p1) {
entry0:
  %slot.nums = alloca i64
  store i64 %p0, ptr %slot.nums
  %slot.n = alloca i64
  store i64 %p1, ptr %slot.n
  %slot.total = alloca i64
  store i64 0, ptr %slot.total
  %slot.i = alloca i64
  store i64 0, ptr %slot.i
  br label %while_header1

while_header1:
  %r13 = load i64, ptr %slot.i
  %r14 = load i64, ptr %slot.n
  %t0 = icmp slt i64 %r13, %r14
  %r15 = zext i1 %t0 to i64
  %t1 = trunc i64 %r15 to i1
  br i1 %t1, label %while_body2, label %while_exit3

while_body2:
  %r17 = load i64, ptr %slot.total
  %r18 = load i64, ptr %slot.nums
  %r19 = load i64, ptr %slot.i
  %r20 = call i64 @nova_rt_list_get(i64 %r18, i64 %r19)
  %r21 = add i64 %r17, %r20
  store i64 %r21, ptr %slot.total
  %r24 = load i64, ptr %slot.i
  %r26 = add i64 %r24, 1
  store i64 %r26, ptr %slot.i
  br label %while_header1

while_exit3:
  %r30 = load i64, ptr %slot.total
  ret i64 %r30
}

define i64 @maxInList(i64 %p0, i64 %p1) {
entry0:
  %slot.nums = alloca i64
  store i64 %p0, ptr %slot.nums
  %slot.n = alloca i64
  store i64 %p1, ptr %slot.n
  %r7 = call i64 @nova_rt_list_get(i64 %p0, i64 0)
  %slot.best = alloca i64
  store i64 %r7, ptr %slot.best
  %slot.i = alloca i64
  store i64 1, ptr %slot.i
  br label %while_header1

while_header1:
  %r15 = load i64, ptr %slot.i
  %r16 = load i64, ptr %slot.n
  %t0 = icmp slt i64 %r15, %r16
  %r17 = zext i1 %t0 to i64
  %t1 = trunc i64 %r17 to i1
  br i1 %t1, label %while_body2, label %while_exit3

while_body2:
  %r19 = load i64, ptr %slot.nums
  %r20 = load i64, ptr %slot.i
  %r21 = call i64 @nova_rt_list_get(i64 %r19, i64 %r20)
  %r22 = load i64, ptr %slot.best
  %t2 = icmp sgt i64 %r21, %r22
  %r23 = zext i1 %t2 to i64
  %slot.__ifb_0 = alloca i64
  %t3 = trunc i64 %r23 to i1
  br i1 %t3, label %ifb_then4, label %ifb_else5

while_exit3:
  %r41 = load i64, ptr %slot.best
  ret i64 %r41

ifb_then4:
  %r26 = load i64, ptr %slot.nums
  %r27 = load i64, ptr %slot.i
  %r28 = call i64 @nova_rt_list_get(i64 %r26, i64 %r27)
  store i64 %r28, ptr %slot.best
  store i64 0, ptr %slot.__ifb_0
  br label %ifb_merge6

ifb_else5:
  store i64 0, ptr %slot.__ifb_0
  br label %ifb_merge6

ifb_merge6:
  %r35 = load i64, ptr %slot.i
  %r37 = add i64 %r35, 1
  store i64 %r37, ptr %slot.i
  br label %while_header1
}

define i64 @nova_main() {
entry0:
  %r5 = call i64 @nova_rt_list_create()
  %t0 = call i64 @nova_rt_list_append(i64 %r5, i64 10)
  %t1 = call i64 @nova_rt_list_append(i64 %r5, i64 20)
  %t2 = call i64 @nova_rt_list_append(i64 %r5, i64 30)
  %t3 = call i64 @nova_rt_list_append(i64 %r5, i64 40)
  %t4 = call i64 @nova_rt_list_append(i64 %r5, i64 50)
  %slot.nums = alloca i64
  store i64 %r5, ptr %slot.nums
  %r12 = call i64 @nova_rt_list_get(i64 %r5, i64 0)
  %t5 = getelementptr inbounds [5 x i8], ptr @.str.0, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t5, i64 %r12)
  %r17 = call i64 @nova_rt_list_get(i64 %r5, i64 2)
  %t6 = getelementptr inbounds [5 x i8], ptr @.str.0, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t6, i64 %r17)
  %r22 = call i64 @nova_rt_list_get(i64 %r5, i64 4)
  %t7 = getelementptr inbounds [5 x i8], ptr @.str.0, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t7, i64 %r22)
  %r27 = call i64 @nova_rt_list_len(i64 %r5)
  %t8 = getelementptr inbounds [5 x i8], ptr @.str.0, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t8, i64 %r27)
  %r32 = call i64 @sumList(i64 %r5, i64 5)
  %t9 = getelementptr inbounds [5 x i8], ptr @.str.0, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t9, i64 %r32)
  %r37 = call i64 @maxInList(i64 %r5, i64 5)
  %t10 = getelementptr inbounds [5 x i8], ptr @.str.0, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t10, i64 %r37)
  %r45 = call i64 @nova_rt_list_create()
  %t11 = call i64 @nova_rt_list_append(i64 %r45, i64 2)
  %t12 = call i64 @nova_rt_list_append(i64 %r45, i64 3)
  %t13 = call i64 @nova_rt_list_append(i64 %r45, i64 5)
  %t14 = call i64 @nova_rt_list_append(i64 %r45, i64 7)
  %t15 = call i64 @nova_rt_list_append(i64 %r45, i64 11)
  %t16 = call i64 @nova_rt_list_append(i64 %r45, i64 13)
  %slot.primes = alloca i64
  store i64 %r45, ptr %slot.primes
  %r52 = call i64 @nova_rt_list_get(i64 %r45, i64 0)
  %t17 = getelementptr inbounds [5 x i8], ptr @.str.0, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t17, i64 %r52)
  %r57 = call i64 @nova_rt_list_get(i64 %r45, i64 5)
  %t18 = getelementptr inbounds [5 x i8], ptr @.str.0, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t18, i64 %r57)
  %r62 = call i64 @nova_rt_list_len(i64 %r45)
  %t19 = getelementptr inbounds [5 x i8], ptr @.str.0, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t19, i64 %r62)
  %r67 = call i64 @sumList(i64 %r45, i64 6)
  %t20 = getelementptr inbounds [5 x i8], ptr @.str.0, i64 0, i64 0
  call i32 (ptr, ...) @printf(ptr %t20, i64 %r67)
  ret i64 0
}

define i32 @main() {
entry:
  call i64 @nova_main()
  call void @nova_rt_wait_all()
  ret i32 0
}
