; Generated by NOVA compiler
target triple = "x86_64-pc-windows-msvc"

declare i32 @printf(ptr, ...)
declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare ptr @realloc(ptr, i64)
declare void @free(ptr)
; nova runtime — list ops
declare i64 @nova_rt_list_create()
declare i64 @nova_rt_list_append(i64, i64)
declare i64 @nova_rt_list_get(i64, i64)
declare i64 @nova_rt_list_set(i64, i64, i64)
declare i64 @nova_rt_list_len(i64)
declare i64 @nova_rt_list_print(i64)
declare i64 @nova_rt_iter_has_next(i64, i64)
; nova runtime — string ops
declare i64 @nova_rt_str_concat(i64, i64)
declare i64 @nova_rt_int_to_str(i64)
declare i64 @nova_rt_float_to_str(i64)
declare i64 @nova_rt_bool_to_str(i64)
declare i64 @nova_rt_str_len(i64)
declare i64 @nova_rt_len(i64)
declare i64 @nova_rt_contains(i64, i64)
declare i64 @nova_rt_slice(i64, i64, i64)
declare i64 @nova_rt_upper(i64)
declare i64 @nova_rt_lower(i64)
declare i64 @nova_rt_trim(i64)
declare i64 @nova_rt_split(i64, i64)
declare i64 @nova_rt_replace(i64, i64, i64)
declare i64 @nova_rt_starts_with(i64, i64)
declare i64 @nova_rt_ends_with(i64, i64)
declare i64 @nova_rt_find(i64, i64)
declare i64 @nova_rt_join(i64, i64)
declare i64 @nova_rt_chars(i64)
; nova runtime — list stdlib
declare i64 @nova_rt_list_reverse(i64)
declare i64 @nova_rt_list_sort(i64)
declare i64 @nova_rt_list_map(i64, i64)
declare i64 @nova_rt_list_filter(i64, i64)
declare i64 @nova_rt_list_concat(i64, i64)
declare i64 @nova_rt_list_to_str(i64)
declare i64 @nova_rt_len_any(i64)
; nova runtime — type conversions
declare i64 @nova_rt_parse_int(i64)
declare i64 @nova_rt_parse_float(i64)
declare i32 @strcmp(ptr, ptr)
; nova runtime — dict ops (Phase 1: ordered array, O(n) lookup)
declare i64 @nova_rt_dict_create()
declare i64 @nova_rt_dict_set(i64, i64, i64)
declare i64 @nova_rt_dict_get(i64, i64)
declare i64 @nova_rt_dict_has(i64, i64)
declare i64 @nova_rt_dict_del(i64, i64)
declare i64 @nova_rt_dict_len(i64)
declare i64 @nova_rt_dict_keys(i64)
; nova runtime — IO ops
declare i64 @nova_rt_read_line()
declare i64 @nova_rt_read_file(i64)
declare i64 @nova_rt_write_file(i64, i64)
; nova runtime — channel/spawn ops
declare i64 @nova_rt_channel_create()
declare i64 @nova_rt_channel_send(i64, i64)
declare i64 @nova_rt_channel_recv(i64)
declare i64 @nova_rt_channel_close(i64)
declare i64 @nova_rt_channel_select(i64, i64)
declare i64 @nova_rt_channel_recv_timeout(i64, i64)
declare i64 @nova_rt_spawn(i64, i64)
declare i64 @nova_rt_monitor(i64)
declare void @nova_rt_wait_all()
; nova runtime — math (trig/log via C runtime for non-intrinsic functions)
declare i64 @nova_rt_tan(i64)
declare i64 @nova_rt_asin(i64)
declare i64 @nova_rt_acos(i64)
declare i64 @nova_rt_atan(i64)
declare i64 @nova_rt_atan2(i64, i64)
declare i64 @nova_rt_fmod(i64, i64)
declare i64 @nova_rt_int_pow(i64, i64)
; nova error state — global flag (errno-style)
@__nova_error_flag = global i64 0
@__nova_error_msg = global i64 0

@.str.0 = private unnamed_addr constant [5 x i8] c"name\00"
@.str.1 = private unnamed_addr constant [4 x i8] c"age\00"
@.str.2 = private unnamed_addr constant [6 x i8] c"score\00"
@.str.3 = private unnamed_addr constant [29 x i8] c"| Name     | Score | Grade |\00"
@.str.4 = private unnamed_addr constant [29 x i8] c"+----------+-------+-------+\00"
@.str.5 = private unnamed_addr constant [87 x i8] c"+----------+-------+-------+\0A| Name     | Score | Grade |\0A+----------+-------+-------+\00"
@.str.6 = private unnamed_addr constant [2 x i8] c"F\00"
@.str.7 = private unnamed_addr constant [2 x i8] c"\0A\00"
@.str.8 = private unnamed_addr constant [2 x i8] c"A\00"
@.str.9 = private unnamed_addr constant [4 x i8] c"\0A| \00"
@.str.10 = private unnamed_addr constant [4 x i8] c" | \00"
@.str.11 = private unnamed_addr constant [7 x i8] c"    | \00"
@.str.12 = private unnamed_addr constant [7 x i8] c"     |\00"
@.str.13 = private unnamed_addr constant [2 x i8] c"B\00"
@.str.14 = private unnamed_addr constant [2 x i8] c"C\00"
@.str.15 = private unnamed_addr constant [2 x i8] c"D\00"
@.str.16 = private unnamed_addr constant [9 x i8] c"negative\00"
@.str.17 = private unnamed_addr constant [5 x i8] c"zero\00"
@.str.18 = private unnamed_addr constant [15 x i8] c"perfect square\00"
@.str.19 = private unnamed_addr constant [6 x i8] c"prime\00"
@.str.20 = private unnamed_addr constant [10 x i8] c"composite\00"
@.str.21 = private unnamed_addr constant [3 x i8] c"OK\00"
@.str.22 = private unnamed_addr constant [8 x i8] c"Created\00"
@.str.23 = private unnamed_addr constant [18 x i8] c"Moved Permanently\00"
@.str.24 = private unnamed_addr constant [12 x i8] c"Bad Request\00"
@.str.25 = private unnamed_addr constant [13 x i8] c"Unauthorized\00"
@.str.26 = private unnamed_addr constant [10 x i8] c"Forbidden\00"
@.str.27 = private unnamed_addr constant [10 x i8] c"Not Found\00"
@.str.28 = private unnamed_addr constant [22 x i8] c"Internal Server Error\00"
@.str.29 = private unnamed_addr constant [8 x i8] c"Unknown\00"
@.str.30 = private unnamed_addr constant [6 x i8] c"Alice\00"
@.str.31 = private unnamed_addr constant [4 x i8] c"Bob\00"
@.str.32 = private unnamed_addr constant [8 x i8] c"Charlie\00"
@.str.33 = private unnamed_addr constant [6 x i8] c"Diana\00"
@.str.34 = private unnamed_addr constant [4 x i8] c"Eve\00"
@.str.35 = private unnamed_addr constant [6 x i8] c"Frank\00"
@.str.36 = private unnamed_addr constant [6 x i8] c"Grace\00"
@.str.37 = private unnamed_addr constant [5 x i8] c"Hank\00"
@.str.38 = private unnamed_addr constant [11 x i8] c"Students: \00"
@.str.39 = private unnamed_addr constant [10 x i8] c"Passing: \00"
@.str.40 = private unnamed_addr constant [16 x i8] c"Average score: \00"
@.str.41 = private unnamed_addr constant [16 x i8] c"Sorted scores: \00"
@.str.42 = private unnamed_addr constant [15 x i8] c"Even squares: \00"
@.str.43 = private unnamed_addr constant [15 x i8] c"Tripled > 15: \00"
@.str.44 = private unnamed_addr constant [5 x i8] c" -> \00"
@.str.45 = private unnamed_addr constant [4 x i8] c"the\00"
@.str.46 = private unnamed_addr constant [4 x i8] c"cat\00"
@.str.47 = private unnamed_addr constant [4 x i8] c"sat\00"
@.str.48 = private unnamed_addr constant [3 x i8] c"on\00"
@.str.49 = private unnamed_addr constant [4 x i8] c"mat\00"
@.str.50 = private unnamed_addr constant [13 x i8] c"Word 'the': \00"
@.str.51 = private unnamed_addr constant [13 x i8] c"Word 'cat': \00"
@.str.52 = private unnamed_addr constant [12 x i8] c"Word 'on': \00"
@.str.53 = private unnamed_addr constant [13 x i8] c"Word 'sat': \00"
@.str.54 = private unnamed_addr constant [13 x i8] c"Word 'mat': \00"
@.str.55 = private unnamed_addr constant [2 x i8] c"$\00"
@.str.56 = private unnamed_addr constant [4 x i8] c".00\00"
@.str.57 = private unnamed_addr constant [2 x i8] c"(\00"
@.str.58 = private unnamed_addr constant [2 x i8] c")\00"
@.str.59 = private unnamed_addr constant [15 x i8] c"Age 25 valid: \00"
@.str.60 = private unnamed_addr constant [16 x i8] c"Age 200 valid: \00"
@.str.61 = private unnamed_addr constant [17 x i8] c"Score 85 valid: \00"
@.str.62 = private unnamed_addr constant [18 x i8] c"Score 150 valid: \00"
@.str.63 = private unnamed_addr constant [9 x i8] c"Dollar: \00"
@.str.64 = private unnamed_addr constant [8 x i8] c"Paren: \00"
@.str.65 = private unnamed_addr constant [14 x i8] c"Twin primes: \00"
@.str.66 = private unnamed_addr constant [3 x i8] c", \00"
@.str.67 = private unnamed_addr constant [39 x i8] c"Sum excluding multiples of 3 (1..30): \00"
@.str.68 = private unnamed_addr constant [3 x i8] c": \00"
@.str.69 = private unnamed_addr constant [18 x i8] c"Large list size: \00"
@.str.70 = private unnamed_addr constant [15 x i8] c"big_list[0] = \00"
@.str.71 = private unnamed_addr constant [17 x i8] c"big_list[999] = \00"
@.str.72 = private unnamed_addr constant [22 x i8] c"Sum of 1000 squares: \00"
@.str.73 = private unnamed_addr constant [1 x i8] c"\00"
@.str.74 = private unnamed_addr constant [36 x i8] c"=== ALL PRODUCTION TESTS PASSED ===\00"
@.str.75 = private unnamed_addr constant [6 x i8] c"%lld\0A\00"
@.str.76 = private unnamed_addr constant [4 x i8] c"%f\0A\00"
@.str.77 = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.str.78 = private unnamed_addr constant [5 x i8] c"true\00"
@.str.79 = private unnamed_addr constant [6 x i8] c"false\00"

define i64 @make_record(i64 %p0, i64 %p1, i64 %p2) {
entry0:
  %slot.name = alloca i64
  store i64 %p0, ptr %slot.name
  %slot.age = alloca i64
  store i64 %p1, ptr %slot.age
  %slot.score = alloca i64
  store i64 %p2, ptr %slot.score
  %t0 = getelementptr inbounds [5 x i8], ptr @.str.0, i64 0, i64 0
  %r7 = ptrtoint ptr %t0 to i64
  %t1 = getelementptr inbounds [4 x i8], ptr @.str.1, i64 0, i64 0
  %r9 = ptrtoint ptr %t1 to i64
  %t2 = getelementptr inbounds [6 x i8], ptr @.str.2, i64 0, i64 0
  %r11 = ptrtoint ptr %t2 to i64
  %r13 = call i64 @nova_rt_dict_create()
  %t3 = call i64 @nova_rt_dict_set(i64 %r13, i64 %r7, i64 %p0)
  %t4 = call i64 @nova_rt_dict_set(i64 %r13, i64 %r9, i64 %p1)
  %t5 = call i64 @nova_rt_dict_set(i64 %r13, i64 %r11, i64 %p2)
  ret i64 %r13
}

define i64 @is_passing(i64 %p0) {
entry0:
  %slot.student = alloca i64
  store i64 %p0, ptr %slot.student
  %t0 = getelementptr inbounds [6 x i8], ptr @.str.2, i64 0, i64 0
  %t1 = ptrtoint ptr %t0 to i64
  %r4 = call i64 @nova_rt_dict_get(i64 %p0, i64 %t1)
  %t2 = icmp sge i64 %r4, 70
  %r6 = zext i1 %t2 to i64
  ret i64 %r6
}

define i64 @build_table(i64 %p0) {
entry0:
  %slot.rows = alloca i64
  store i64 %p0, ptr %slot.rows
  %t0 = getelementptr inbounds [29 x i8], ptr @.str.3, i64 0, i64 0
  %r3 = ptrtoint ptr %t0 to i64
  %slot.header = alloca i64
  store i64 %r3, ptr %slot.header
  %t1 = getelementptr inbounds [29 x i8], ptr @.str.4, i64 0, i64 0
  %r7 = ptrtoint ptr %t1 to i64
  %slot.sep = alloca i64
  store i64 %r7, ptr %slot.sep
  %t2 = getelementptr inbounds [87 x i8], ptr @.str.5, i64 0, i64 0
  %r19 = ptrtoint ptr %t2 to i64
  %slot.result = alloca i64
  store i64 %r19, ptr %slot.result
  %slot.i = alloca i64
  store i64 0, ptr %slot.i
  %slot.row = alloca i64
  %slot.name = alloca i64
  %slot.score = alloca i64
  %slot.grade = alloca i64
  br label %while_header1

while_header1:
  %r27 = load i64, ptr %slot.i
  %r29 = load i64, ptr %slot.rows
  %r30 = call i64 @nova_rt_len_any(i64 %r29)
  %t3 = icmp slt i64 %r27, %r30
  %r31 = zext i1 %t3 to i64
  %t4 = trunc i64 %r31 to i1
  br i1 %t4, label %while_body2, label %while_exit3

while_body2:
  %r33 = load i64, ptr %slot.rows
  %r34 = load i64, ptr %slot.i
  %r35 = call i64 @nova_rt_list_get(i64 %r33, i64 %r34)
  store i64 %r35, ptr %slot.row
  %t5 = getelementptr inbounds [5 x i8], ptr @.str.0, i64 0, i64 0
  %t6 = ptrtoint ptr %t5 to i64
  %r40 = call i64 @nova_rt_dict_get(i64 %r35, i64 %t6)
  store i64 %r40, ptr %slot.name
  %t7 = getelementptr inbounds [6 x i8], ptr @.str.2, i64 0, i64 0
  %t8 = ptrtoint ptr %t7 to i64
  %r45 = call i64 @nova_rt_dict_get(i64 %r35, i64 %t8)
  store i64 %r45, ptr %slot.score
  %t9 = getelementptr inbounds [2 x i8], ptr @.str.6, i64 0, i64 0
  %r49 = ptrtoint ptr %t9 to i64
  store i64 %r49, ptr %slot.grade
  %t10 = icmp sge i64 %r45, 90
  %r55 = zext i1 %t10 to i64
  %slot.__ifb_0 = alloca i64
  %t11 = trunc i64 %r55 to i1
  br i1 %t11, label %ifb_then4, label %ifb_else5

while_exit3:
  %r122 = load i64, ptr %slot.result
  %t12 = getelementptr inbounds [2 x i8], ptr @.str.7, i64 0, i64 0
  %r123 = ptrtoint ptr %t12 to i64
  %t13 = call i64 @nova_rt_str_concat(i64 %r122, i64 %r123)
  %r125 = load i64, ptr %slot.sep
  %t14 = call i64 @nova_rt_str_concat(i64 %t13, i64 %r125)
  store i64 %t14, ptr %slot.result
  ret i64 %t14

ifb_then4:
  %t15 = getelementptr inbounds [2 x i8], ptr @.str.8, i64 0, i64 0
  %r58 = ptrtoint ptr %t15 to i64
  store i64 %r58, ptr %slot.grade
  store i64 0, ptr %slot.__ifb_0
  br label %ifb_merge6

ifb_else5:
  %r62 = load i64, ptr %slot.score
  %t16 = icmp sge i64 %r62, 80
  %r64 = zext i1 %t16 to i64
  %slot.__ifb_1 = alloca i64
  %t17 = trunc i64 %r64 to i1
  br i1 %t17, label %ifb_then7, label %ifb_else8

ifb_merge6:
  %r98 = load i64, ptr %slot.result
  %t18 = getelementptr inbounds [4 x i8], ptr @.str.9, i64 0, i64 0
  %r99 = ptrtoint ptr %t18 to i64
  %t19 = call i64 @nova_rt_str_concat(i64 %r98, i64 %r99)
  %r101 = load i64, ptr %slot.name
  %t20 = call i64 @nova_rt_str_concat(i64 %t19, i64 %r101)
  %t21 = getelementptr inbounds [4 x i8], ptr @.str.10, i64 0, i64 0
  %r103 = ptrtoint ptr %t21 to i64
  %t22 = call i64 @nova_rt_str_concat(i64 %t20, i64 %r103)
  %r105 = load i64, ptr %slot.score
  %r106 = call i64 @nova_rt_int_to_str(i64 %r105)
  %t23 = call i64 @nova_rt_str_concat(i64 %t22, i64 %r106)
  %t24 = getelementptr inbounds [7 x i8], ptr @.str.11, i64 0, i64 0
  %r108 = ptrtoint ptr %t24 to i64
  %t25 = call i64 @nova_rt_str_concat(i64 %t23, i64 %r108)
  %r110 = load i64, ptr %slot.grade
  %t26 = call i64 @nova_rt_str_concat(i64 %t25, i64 %r110)
  %t27 = getelementptr inbounds [7 x i8], ptr @.str.12, i64 0, i64 0
  %r112 = ptrtoint ptr %t27 to i64
  %t28 = call i64 @nova_rt_str_concat(i64 %t26, i64 %r112)
  store i64 %t28, ptr %slot.result
  %r116 = load i64, ptr %slot.i
  %r118 = add i64 %r116, 1
  store i64 %r118, ptr %slot.i
  br label %while_header1

ifb_then7:
  %t29 = getelementptr inbounds [2 x i8], ptr @.str.13, i64 0, i64 0
  %r67 = ptrtoint ptr %t29 to i64
  store i64 %r67, ptr %slot.grade
  store i64 0, ptr %slot.__ifb_1
  br label %ifb_merge9

ifb_else8:
  %r71 = load i64, ptr %slot.score
  %t30 = icmp sge i64 %r71, 70
  %r73 = zext i1 %t30 to i64
  %slot.__ifb_2 = alloca i64
  %t31 = trunc i64 %r73 to i1
  br i1 %t31, label %ifb_then10, label %ifb_else11

ifb_merge9:
  %r95 = load i64, ptr %slot.__ifb_1
  store i64 %r95, ptr %slot.__ifb_0
  br label %ifb_merge6

ifb_then10:
  %t32 = getelementptr inbounds [2 x i8], ptr @.str.14, i64 0, i64 0
  %r76 = ptrtoint ptr %t32 to i64
  store i64 %r76, ptr %slot.grade
  store i64 0, ptr %slot.__ifb_2
  br label %ifb_merge12

ifb_else11:
  %r80 = load i64, ptr %slot.score
  %t33 = icmp sge i64 %r80, 60
  %r82 = zext i1 %t33 to i64
  %slot.__ifb_3 = alloca i64
  %t34 = trunc i64 %r82 to i1
  br i1 %t34, label %ifb_then13, label %ifb_else14

ifb_merge12:
  %r93 = load i64, ptr %slot.__ifb_2
  store i64 %r93, ptr %slot.__ifb_1
  br label %ifb_merge9

ifb_then13:
  %t35 = getelementptr inbounds [2 x i8], ptr @.str.15, i64 0, i64 0
  %r85 = ptrtoint ptr %t35 to i64
  store i64 %r85, ptr %slot.grade
  store i64 0, ptr %slot.__ifb_3
  br label %ifb_merge15

ifb_else14:
  store i64 0, ptr %slot.__ifb_3
  br label %ifb_merge15

ifb_merge15:
  %r91 = load i64, ptr %slot.__ifb_3
  store i64 %r91, ptr %slot.__ifb_2
  br label %ifb_merge12
}

define i64 @quicksort_scores(i64 %p0) {
entry0:
  %slot.scores = alloca i64
  store i64 %p0, ptr %slot.scores
  %r5 = call i64 @nova_rt_list_len(i64 %p0)
  %t0 = icmp sle i64 %r5, 1
  %r7 = zext i1 %t0 to i64
  %slot.__ifb_0 = alloca i64
  %slot.pivot = alloca i64
  %slot.less = alloca i64
  %slot.equal = alloca i64
  %slot.greater = alloca i64
  %slot.i = alloca i64
  %slot.v = alloca i64
  %t1 = trunc i64 %r7 to i1
  br i1 %t1, label %ifb_then1, label %ifb_else2

ifb_then1:
  %r10 = load i64, ptr %slot.scores
  ret i64 %r10

ifb_else2:
  store i64 0, ptr %slot.__ifb_0
  br label %ifb_merge3

ifb_merge3:
  %r15 = load i64, ptr %slot.scores
  %r17 = call i64 @nova_rt_list_get(i64 %r15, i64 0)
  store i64 %r17, ptr %slot.pivot
  %r21 = call i64 @nova_rt_list_create()
  store i64 %r21, ptr %slot.less
  %r25 = call i64 @nova_rt_list_create()
  store i64 %r25, ptr %slot.equal
  %r29 = call i64 @nova_rt_list_create()
  store i64 %r29, ptr %slot.greater
  store i64 0, ptr %slot.i
  br label %while_header5

while_header5:
  %r37 = load i64, ptr %slot.i
  %r39 = load i64, ptr %slot.scores
  %r40 = call i64 @nova_rt_list_len(i64 %r39)
  %t2 = icmp slt i64 %r37, %r40
  %r41 = zext i1 %t2 to i64
  %t3 = trunc i64 %r41 to i1
  br i1 %t3, label %while_body6, label %while_exit7

while_body6:
  %r43 = load i64, ptr %slot.scores
  %r44 = load i64, ptr %slot.i
  %r45 = call i64 @nova_rt_list_get(i64 %r43, i64 %r44)
  store i64 %r45, ptr %slot.v
  %r50 = load i64, ptr %slot.pivot
  %t4 = icmp slt i64 %r45, %r50
  %r51 = zext i1 %t4 to i64
  %slot.__ifb_1 = alloca i64
  %t5 = trunc i64 %r51 to i1
  br i1 %t5, label %ifb_then8, label %ifb_else9

while_exit7:
  %r81 = load i64, ptr %slot.less
  %r82 = call i64 @quicksort_scores(i64 %r81)
  %r83 = load i64, ptr %slot.equal
  %r84 = call i64 @nova_rt_list_concat(i64 %r82, i64 %r83)
  %r85 = load i64, ptr %slot.greater
  %r86 = call i64 @quicksort_scores(i64 %r85)
  %r87 = call i64 @nova_rt_list_concat(i64 %r84, i64 %r86)
  ret i64 %r87

ifb_then8:
  %r54 = load i64, ptr %slot.less
  %r55 = load i64, ptr %slot.v
  %r56 = call i64 @nova_rt_list_append(i64 %r54, i64 %r55)
  store i64 %r56, ptr %slot.__ifb_1
  br label %ifb_merge10

ifb_else9:
  %r58 = load i64, ptr %slot.v
  %r59 = load i64, ptr %slot.pivot
  %t6 = icmp eq i64 %r58, %r59
  %r60 = zext i1 %t6 to i64
  %slot.__ifb_2 = alloca i64
  %t7 = trunc i64 %r60 to i1
  br i1 %t7, label %ifb_then11, label %ifb_else12

ifb_merge10:
  %r75 = load i64, ptr %slot.i
  %r77 = add i64 %r75, 1
  store i64 %r77, ptr %slot.i
  br label %while_header5

ifb_then11:
  %r63 = load i64, ptr %slot.equal
  %r64 = load i64, ptr %slot.v
  %r65 = call i64 @nova_rt_list_append(i64 %r63, i64 %r64)
  store i64 %r65, ptr %slot.__ifb_2
  br label %ifb_merge13

ifb_else12:
  %r68 = load i64, ptr %slot.greater
  %r69 = load i64, ptr %slot.v
  %r70 = call i64 @nova_rt_list_append(i64 %r68, i64 %r69)
  store i64 %r70, ptr %slot.__ifb_2
  br label %ifb_merge13

ifb_merge13:
  %r72 = load i64, ptr %slot.__ifb_2
  store i64 %r72, ptr %slot.__ifb_1
  br label %ifb_merge10
}

define i64 @is_prime(i64 %p0) {
entry0:
  %slot.n = alloca i64
  store i64 %p0, ptr %slot.n
  %t0 = icmp slt i64 %p0, 2
  %r5 = zext i1 %t0 to i64
  %slot.__ifb_0 = alloca i64
  %slot.d = alloca i64
  %t1 = trunc i64 %r5 to i1
  br i1 %t1, label %ifb_then1, label %ifb_else2

ifb_then1:
  ret i64 0

ifb_else2:
  store i64 0, ptr %slot.__ifb_0
  br label %ifb_merge3

ifb_merge3:
  %r13 = load i64, ptr %slot.n
  %t2 = icmp eq i64 %r13, 2
  %r15 = zext i1 %t2 to i64
  %slot.__ifb_1 = alloca i64
  %t3 = trunc i64 %r15 to i1
  br i1 %t3, label %ifb_then5, label %ifb_else6

ifb_then5:
  ret i64 1

ifb_else6:
  store i64 0, ptr %slot.__ifb_1
  br label %ifb_merge7

ifb_merge7:
  %r23 = load i64, ptr %slot.n
  %r25 = srem i64 %r23, 2
  %t4 = icmp eq i64 %r25, 0
  %r27 = zext i1 %t4 to i64
  %slot.__ifb_2 = alloca i64
  %t5 = trunc i64 %r27 to i1
  br i1 %t5, label %ifb_then9, label %ifb_else10

ifb_then9:
  ret i64 0

ifb_else10:
  store i64 0, ptr %slot.__ifb_2
  br label %ifb_merge11

ifb_merge11:
  store i64 3, ptr %slot.d
  br label %while_header13

while_header13:
  %r39 = load i64, ptr %slot.d
  %r40 = load i64, ptr %slot.d
  %r41 = mul i64 %r39, %r40
  %r42 = load i64, ptr %slot.n
  %t6 = icmp sle i64 %r41, %r42
  %r43 = zext i1 %t6 to i64
  %t7 = trunc i64 %r43 to i1
  br i1 %t7, label %while_body14, label %while_exit15

while_body14:
  %r45 = load i64, ptr %slot.n
  %r46 = load i64, ptr %slot.d
  %r47 = srem i64 %r45, %r46
  %t8 = icmp eq i64 %r47, 0
  %r49 = zext i1 %t8 to i64
  %slot.__ifb_3 = alloca i64
  %t9 = trunc i64 %r49 to i1
  br i1 %t9, label %ifb_then16, label %ifb_else17

while_exit15:
  ret i64 1

ifb_then16:
  ret i64 0

ifb_else17:
  store i64 0, ptr %slot.__ifb_3
  br label %ifb_merge18

ifb_merge18:
  %r57 = load i64, ptr %slot.d
  %r59 = add i64 %r57, 2
  store i64 %r59, ptr %slot.d
  br label %while_header13
}

define i64 @classify(i64 %p0) {
entry0:
  %slot.n = alloca i64
  store i64 %p0, ptr %slot.n
  %t0 = icmp slt i64 %p0, 0
  %r5 = zext i1 %t0 to i64
  %slot.__ifb_0 = alloca i64
  %slot.root = alloca i64
  %t1 = trunc i64 %r5 to i1
  br i1 %t1, label %ifb_then1, label %ifb_else2

ifb_then1:
  %t2 = getelementptr inbounds [9 x i8], ptr @.str.16, i64 0, i64 0
  %r8 = ptrtoint ptr %t2 to i64
  ret i64 %r8

ifb_else2:
  store i64 0, ptr %slot.__ifb_0
  br label %ifb_merge3

ifb_merge3:
  %r13 = load i64, ptr %slot.n
  %t3 = icmp eq i64 %r13, 0
  %r15 = zext i1 %t3 to i64
  %slot.__ifb_1 = alloca i64
  %t4 = trunc i64 %r15 to i1
  br i1 %t4, label %ifb_then5, label %ifb_else6

ifb_then5:
  %t5 = getelementptr inbounds [5 x i8], ptr @.str.17, i64 0, i64 0
  %r18 = ptrtoint ptr %t5 to i64
  ret i64 %r18

ifb_else6:
  store i64 0, ptr %slot.__ifb_1
  br label %ifb_merge7

ifb_merge7:
  store i64 1, ptr %slot.root
  br label %while_header9

while_header9:
  %r27 = load i64, ptr %slot.root
  %r28 = load i64, ptr %slot.root
  %r29 = mul i64 %r27, %r28
  %r30 = load i64, ptr %slot.n
  %t6 = icmp slt i64 %r29, %r30
  %r31 = zext i1 %t6 to i64
  %t7 = trunc i64 %r31 to i1
  br i1 %t7, label %while_body10, label %while_exit11

while_body10:
  %r33 = load i64, ptr %slot.root
  %r35 = add i64 %r33, 1
  store i64 %r35, ptr %slot.root
  br label %while_header9

while_exit11:
  %r39 = load i64, ptr %slot.root
  %r40 = load i64, ptr %slot.root
  %r41 = mul i64 %r39, %r40
  %r42 = load i64, ptr %slot.n
  %t8 = icmp eq i64 %r41, %r42
  %r43 = zext i1 %t8 to i64
  %slot.__ifb_2 = alloca i64
  %t9 = trunc i64 %r43 to i1
  br i1 %t9, label %ifb_then12, label %ifb_else13

ifb_then12:
  %t10 = getelementptr inbounds [15 x i8], ptr @.str.18, i64 0, i64 0
  %r46 = ptrtoint ptr %t10 to i64
  ret i64 %r46

ifb_else13:
  store i64 0, ptr %slot.__ifb_2
  br label %ifb_merge14

ifb_merge14:
  %r51 = load i64, ptr %slot.n
  %r52 = call i64 @is_prime(i64 %r51)
  %slot.__ifb_3 = alloca i64
  %t11 = trunc i64 %r52 to i1
  br i1 %t11, label %ifb_then16, label %ifb_else17

ifb_then16:
  %t12 = getelementptr inbounds [6 x i8], ptr @.str.19, i64 0, i64 0
  %r55 = ptrtoint ptr %t12 to i64
  ret i64 %r55

ifb_else17:
  store i64 0, ptr %slot.__ifb_3
  br label %ifb_merge18

ifb_merge18:
  %t13 = getelementptr inbounds [10 x i8], ptr @.str.20, i64 0, i64 0
  %r60 = ptrtoint ptr %t13 to i64
  ret i64 %r60
}

define i64 @count_word(i64 %p0, i64 %p1) {
entry0:
  %slot.counts = alloca i64
  store i64 %p0, ptr %slot.counts
  %slot.word = alloca i64
  store i64 %p1, ptr %slot.word
  %r7 = call i64 @nova_rt_dict_has(i64 %p0, i64 %p1)
  %slot.__ifb_0 = alloca i64
  %slot.old = alloca i64
  %t0 = trunc i64 %r7 to i1
  br i1 %t0, label %ifb_then1, label %ifb_else2

ifb_then1:
  %r10 = load i64, ptr %slot.counts
  %r11 = load i64, ptr %slot.word
  %r12 = call i64 @nova_rt_dict_get(i64 %r10, i64 %r11)
  store i64 %r12, ptr %slot.old
  %r18 = add i64 %r12, 1
  %r19 = load i64, ptr %slot.counts
  %r20 = load i64, ptr %slot.word
  %t1 = call i64 @nova_rt_dict_set(i64 %r19, i64 %r20, i64 %r18)
  store i64 0, ptr %slot.__ifb_0
  br label %ifb_merge3

ifb_else2:
  %r26 = load i64, ptr %slot.counts
  %r27 = load i64, ptr %slot.word
  %t2 = call i64 @nova_rt_dict_set(i64 %r26, i64 %r27, i64 1)
  store i64 0, ptr %slot.__ifb_0
  br label %ifb_merge3

ifb_merge3:
  %r32 = load i64, ptr %slot.counts
  ret i64 %r32
}

define i64 @make_validator(i64 %p0, i64 %p1) {
entry0:
  %slot.min_val = alloca i64
  store i64 %p0, ptr %slot.min_val
  %slot.max_val = alloca i64
  store i64 %p1, ptr %slot.max_val
  %t0 = call ptr @malloc(i64 24)
  %t1 = ptrtoint ptr @make_validator_lambda0_tramp to i64
  store i64 %t1, ptr %t0
  %t2 = getelementptr i64, ptr %t0, i64 1
  store i64 %p0, ptr %t2
  %t3 = getelementptr i64, ptr %t0, i64 2
  store i64 %p1, ptr %t3
  %r7 = ptrtoint ptr %t0 to i64
  ret i64 %r7
}

define i64 @make_validator_lambda0(i64 %p0, i64 %p1, i64 %p2) {
entry0:
  %slot.x = alloca i64
  store i64 %p0, ptr %slot.x
  %slot.min_val = alloca i64
  store i64 %p1, ptr %slot.min_val
  %slot.max_val = alloca i64
  store i64 %p2, ptr %slot.max_val
  %t0 = icmp sge i64 %p0, %p1
  %r13 = zext i1 %t0 to i64
  %t1 = icmp sle i64 %p0, %p2
  %r16 = zext i1 %t1 to i64
  %t2 = icmp ne i64 %r13, 0
  %t3 = icmp ne i64 %r16, 0
  %t4 = and i1 %t2, %t3
  %r17 = zext i1 %t4 to i64
  ret i64 %r17
}

define i64 @make_formatter(i64 %p0, i64 %p1) {
entry0:
  %slot.prefix = alloca i64
  store i64 %p0, ptr %slot.prefix
  %slot.suffix = alloca i64
  store i64 %p1, ptr %slot.suffix
  %t0 = call ptr @malloc(i64 24)
  %t1 = ptrtoint ptr @make_formatter_lambda1_tramp to i64
  store i64 %t1, ptr %t0
  %t2 = getelementptr i64, ptr %t0, i64 1
  store i64 %p0, ptr %t2
  %t3 = getelementptr i64, ptr %t0, i64 2
  store i64 %p1, ptr %t3
  %r7 = ptrtoint ptr %t0 to i64
  ret i64 %r7
}

define i64 @make_formatter_lambda1(i64 %p0, i64 %p1, i64 %p2) {
entry0:
  %slot.x = alloca i64
  store i64 %p0, ptr %slot.x
  %slot.prefix = alloca i64
  store i64 %p1, ptr %slot.prefix
  %slot.suffix = alloca i64
  store i64 %p2, ptr %slot.suffix
  %r13 = call i64 @nova_rt_int_to_str(i64 %p0)
  %t0 = call i64 @nova_rt_str_concat(i64 %p1, i64 %r13)
  %t1 = call i64 @nova_rt_str_concat(i64 %t0, i64 %p2)
  ret i64 %t1
}

define i64 @http_status(i64 %p0) {
entry0:
  %slot.code = alloca i64
  store i64 %p0, ptr %slot.code
  %r3 = load i64, ptr %slot.code
  %slot.__match_0 = alloca i64
  %t0 = icmp eq i64 %r3, 200
  %r6 = zext i1 %t0 to i64
  %t1 = trunc i64 %r6 to i1
  br i1 %t1, label %arm0_body2, label %arm0_next3

arm0_body2:
  %t2 = getelementptr inbounds [3 x i8], ptr @.str.21, i64 0, i64 0
  %r7 = ptrtoint ptr %t2 to i64
  store i64 %r7, ptr %slot.__match_0
  br label %match_merge1

arm0_next3:
  %t3 = icmp eq i64 %r3, 201
  %r10 = zext i1 %t3 to i64
  %t4 = trunc i64 %r10 to i1
  br i1 %t4, label %arm1_body4, label %arm1_next5

arm1_body4:
  %t5 = getelementptr inbounds [8 x i8], ptr @.str.22, i64 0, i64 0
  %r11 = ptrtoint ptr %t5 to i64
  store i64 %r11, ptr %slot.__match_0
  br label %match_merge1

arm1_next5:
  %t6 = icmp eq i64 %r3, 301
  %r14 = zext i1 %t6 to i64
  %t7 = trunc i64 %r14 to i1
  br i1 %t7, label %arm2_body6, label %arm2_next7

arm2_body6:
  %t8 = getelementptr inbounds [18 x i8], ptr @.str.23, i64 0, i64 0
  %r15 = ptrtoint ptr %t8 to i64
  store i64 %r15, ptr %slot.__match_0
  br label %match_merge1

arm2_next7:
  %t9 = icmp eq i64 %r3, 400
  %r18 = zext i1 %t9 to i64
  %t10 = trunc i64 %r18 to i1
  br i1 %t10, label %arm3_body8, label %arm3_next9

arm3_body8:
  %t11 = getelementptr inbounds [12 x i8], ptr @.str.24, i64 0, i64 0
  %r19 = ptrtoint ptr %t11 to i64
  store i64 %r19, ptr %slot.__match_0
  br label %match_merge1

arm3_next9:
  %t12 = icmp eq i64 %r3, 401
  %r22 = zext i1 %t12 to i64
  %t13 = trunc i64 %r22 to i1
  br i1 %t13, label %arm4_body10, label %arm4_next11

arm4_body10:
  %t14 = getelementptr inbounds [13 x i8], ptr @.str.25, i64 0, i64 0
  %r23 = ptrtoint ptr %t14 to i64
  store i64 %r23, ptr %slot.__match_0
  br label %match_merge1

arm4_next11:
  %t15 = icmp eq i64 %r3, 403
  %r26 = zext i1 %t15 to i64
  %t16 = trunc i64 %r26 to i1
  br i1 %t16, label %arm5_body12, label %arm5_next13

arm5_body12:
  %t17 = getelementptr inbounds [10 x i8], ptr @.str.26, i64 0, i64 0
  %r27 = ptrtoint ptr %t17 to i64
  store i64 %r27, ptr %slot.__match_0
  br label %match_merge1

arm5_next13:
  %t18 = icmp eq i64 %r3, 404
  %r30 = zext i1 %t18 to i64
  %t19 = trunc i64 %r30 to i1
  br i1 %t19, label %arm6_body14, label %arm6_next15

arm6_body14:
  %t20 = getelementptr inbounds [10 x i8], ptr @.str.27, i64 0, i64 0
  %r31 = ptrtoint ptr %t20 to i64
  store i64 %r31, ptr %slot.__match_0
  br label %match_merge1

arm6_next15:
  %t21 = icmp eq i64 %r3, 500
  %r34 = zext i1 %t21 to i64
  %t22 = trunc i64 %r34 to i1
  br i1 %t22, label %arm7_body16, label %arm7_next17

arm7_body16:
  %t23 = getelementptr inbounds [22 x i8], ptr @.str.28, i64 0, i64 0
  %r35 = ptrtoint ptr %t23 to i64
  store i64 %r35, ptr %slot.__match_0
  br label %match_merge1

arm7_next17:
  br label %arm8_body18

arm8_body18:
  %t24 = getelementptr inbounds [8 x i8], ptr @.str.29, i64 0, i64 0
  %r37 = ptrtoint ptr %t24 to i64
  store i64 %r37, ptr %slot.__match_0
  br label %match_merge1

match_merge1:
  %r39 = load i64, ptr %slot.__match_0
  ret i64 %r39
}

define i64 @build_large_list(i64 %p0) {
entry0:
  %slot.n = alloca i64
  store i64 %p0, ptr %slot.n
  %r3 = call i64 @nova_rt_list_create()
  %slot.result = alloca i64
  store i64 %r3, ptr %slot.result
  %slot.i = alloca i64
  store i64 0, ptr %slot.i
  br label %while_header1

while_header1:
  %r11 = load i64, ptr %slot.i
  %r12 = load i64, ptr %slot.n
  %t0 = icmp slt i64 %r11, %r12
  %r13 = zext i1 %t0 to i64
  %t1 = trunc i64 %r13 to i1
  br i1 %t1, label %while_body2, label %while_exit3

while_body2:
  %r15 = load i64, ptr %slot.result
  %r16 = load i64, ptr %slot.i
  %r17 = load i64, ptr %slot.i
  %r18 = mul i64 %r16, %r17
  %r19 = call i64 @nova_rt_list_append(i64 %r15, i64 %r18)
  %r20 = load i64, ptr %slot.i
  %r22 = add i64 %r20, 1
  store i64 %r22, ptr %slot.i
  br label %while_header1

while_exit3:
  %r26 = load i64, ptr %slot.result
  ret i64 %r26
}

define i64 @nova_main() {
entry0:
  %r0 = call i64 @nova_rt_list_create()
  %slot.students = alloca i64
  store i64 %r0, ptr %slot.students
  %t0 = getelementptr inbounds [6 x i8], ptr @.str.30, i64 0, i64 0
  %r5 = ptrtoint ptr %t0 to i64
  %r8 = call i64 @make_record(i64 %r5, i64 22, i64 95)
  %r9 = call i64 @nova_rt_list_append(i64 %r0, i64 %r8)
  %t1 = getelementptr inbounds [4 x i8], ptr @.str.31, i64 0, i64 0
  %r11 = ptrtoint ptr %t1 to i64
  %r14 = call i64 @make_record(i64 %r11, i64 19, i64 72)
  %r15 = call i64 @nova_rt_list_append(i64 %r0, i64 %r14)
  %t2 = getelementptr inbounds [8 x i8], ptr @.str.32, i64 0, i64 0
  %r17 = ptrtoint ptr %t2 to i64
  %r20 = call i64 @make_record(i64 %r17, i64 25, i64 88)
  %r21 = call i64 @nova_rt_list_append(i64 %r0, i64 %r20)
  %t3 = getelementptr inbounds [6 x i8], ptr @.str.33, i64 0, i64 0
  %r23 = ptrtoint ptr %t3 to i64
  %r26 = call i64 @make_record(i64 %r23, i64 20, i64 91)
  %r27 = call i64 @nova_rt_list_append(i64 %r0, i64 %r26)
  %t4 = getelementptr inbounds [4 x i8], ptr @.str.34, i64 0, i64 0
  %r29 = ptrtoint ptr %t4 to i64
  %r32 = call i64 @make_record(i64 %r29, i64 23, i64 65)
  %r33 = call i64 @nova_rt_list_append(i64 %r0, i64 %r32)
  %t5 = getelementptr inbounds [6 x i8], ptr @.str.35, i64 0, i64 0
  %r35 = ptrtoint ptr %t5 to i64
  %r38 = call i64 @make_record(i64 %r35, i64 21, i64 78)
  %r39 = call i64 @nova_rt_list_append(i64 %r0, i64 %r38)
  %t6 = getelementptr inbounds [6 x i8], ptr @.str.36, i64 0, i64 0
  %r41 = ptrtoint ptr %t6 to i64
  %r44 = call i64 @make_record(i64 %r41, i64 24, i64 99)
  %r45 = call i64 @nova_rt_list_append(i64 %r0, i64 %r44)
  %t7 = getelementptr inbounds [5 x i8], ptr @.str.37, i64 0, i64 0
  %r47 = ptrtoint ptr %t7 to i64
  %r50 = call i64 @make_record(i64 %r47, i64 18, i64 55)
  %r51 = call i64 @nova_rt_list_append(i64 %r0, i64 %r50)
  %slot.passing_count = alloca i64
  store i64 0, ptr %slot.passing_count
  %slot.total_score = alloca i64
  store i64 0, ptr %slot.total_score
  %slot.i = alloca i64
  store i64 0, ptr %slot.i
  %slot.s = alloca i64
  %slot.all_scores = alloca i64
  %slot.sorted = alloca i64
  %slot.numbers = alloca i64
  %slot.squared = alloca i64
  %slot.even_squares = alloca i64
  %slot.tripled = alloca i64
  %slot.big = alloca i64
  %slot.test_nums = alloca i64
  %slot.j = alloca i64
  %slot.n = alloca i64
  %slot.words = alloca i64
  %slot.freq = alloca i64
  %slot.k = alloca i64
  %slot.age_valid = alloca i64
  %slot.score_valid = alloca i64
  %slot.dollar_fmt = alloca i64
  %slot.paren_fmt = alloca i64
  %slot.count = alloca i64
  %slot.skip_sum = alloca i64
  %slot.m = alloca i64
  %slot.codes = alloca i64
  %slot.ci = alloca i64
  %slot.c = alloca i64
  %slot.big_list = alloca i64
  %slot.big_sum = alloca i64
  %slot.bi = alloca i64
  br label %while_header1

while_header1:
  %r64 = load i64, ptr %slot.i
  %r66 = load i64, ptr %slot.students
  %r67 = call i64 @nova_rt_list_len(i64 %r66)
  %t8 = icmp slt i64 %r64, %r67
  %r68 = zext i1 %t8 to i64
  %t9 = trunc i64 %r68 to i1
  br i1 %t9, label %while_body2, label %while_exit3

while_body2:
  %r70 = load i64, ptr %slot.students
  %r71 = load i64, ptr %slot.i
  %r72 = call i64 @nova_rt_list_get(i64 %r70, i64 %r71)
  store i64 %r72, ptr %slot.s
  %r77 = call i64 @is_passing(i64 %r72)
  %slot.__ifb_0 = alloca i64
  %t10 = trunc i64 %r77 to i1
  br i1 %t10, label %ifb_then4, label %ifb_else5

while_exit3:
  %t11 = getelementptr inbounds [11 x i8], ptr @.str.38, i64 0, i64 0
  %r102 = ptrtoint ptr %t11 to i64
  %r104 = load i64, ptr %slot.students
  %r105 = call i64 @nova_rt_list_len(i64 %r104)
  %r106 = call i64 @nova_rt_int_to_str(i64 %r105)
  %t12 = call i64 @nova_rt_str_concat(i64 %r102, i64 %r106)
  %t13 = inttoptr i64 %t12 to ptr
  call i32 @puts(ptr %t13)
  %t14 = getelementptr inbounds [10 x i8], ptr @.str.39, i64 0, i64 0
  %r110 = ptrtoint ptr %t14 to i64
  %r111 = load i64, ptr %slot.passing_count
  %r112 = call i64 @nova_rt_int_to_str(i64 %r111)
  %t15 = call i64 @nova_rt_str_concat(i64 %r110, i64 %r112)
  %t16 = inttoptr i64 %t15 to ptr
  call i32 @puts(ptr %t16)
  %t17 = getelementptr inbounds [16 x i8], ptr @.str.40, i64 0, i64 0
  %r116 = ptrtoint ptr %t17 to i64
  %r117 = load i64, ptr %slot.total_score
  %r119 = load i64, ptr %slot.students
  %r120 = call i64 @nova_rt_list_len(i64 %r119)
  %r121 = sdiv i64 %r117, %r120
  %r122 = call i64 @nova_rt_int_to_str(i64 %r121)
  %t18 = call i64 @nova_rt_str_concat(i64 %r116, i64 %r122)
  %t19 = inttoptr i64 %t18 to ptr
  call i32 @puts(ptr %t19)
  %r126 = load i64, ptr %slot.students
  %r127 = call i64 @build_table(i64 %r126)
  %t20 = inttoptr i64 %r127 to ptr
  call i32 @puts(ptr %t20)
  %r137 = call i64 @nova_rt_list_create()
  %t21 = call i64 @nova_rt_list_append(i64 %r137, i64 95)
  %t22 = call i64 @nova_rt_list_append(i64 %r137, i64 72)
  %t23 = call i64 @nova_rt_list_append(i64 %r137, i64 88)
  %t24 = call i64 @nova_rt_list_append(i64 %r137, i64 91)
  %t25 = call i64 @nova_rt_list_append(i64 %r137, i64 65)
  %t26 = call i64 @nova_rt_list_append(i64 %r137, i64 78)
  %t27 = call i64 @nova_rt_list_append(i64 %r137, i64 99)
  %t28 = call i64 @nova_rt_list_append(i64 %r137, i64 55)
  store i64 %r137, ptr %slot.all_scores
  %r142 = call i64 @quicksort_scores(i64 %r137)
  store i64 %r142, ptr %slot.sorted
  %t29 = getelementptr inbounds [16 x i8], ptr @.str.41, i64 0, i64 0
  %r147 = ptrtoint ptr %t29 to i64
  %r149 = call i64 @nova_rt_list_to_str(i64 %r142)
  %t30 = call i64 @nova_rt_str_concat(i64 %r147, i64 %r149)
  %t31 = inttoptr i64 %t30 to ptr
  call i32 @puts(ptr %t31)
  %r162 = call i64 @nova_rt_list_create()
  %t32 = call i64 @nova_rt_list_append(i64 %r162, i64 1)
  %t33 = call i64 @nova_rt_list_append(i64 %r162, i64 2)
  %t34 = call i64 @nova_rt_list_append(i64 %r162, i64 3)
  %t35 = call i64 @nova_rt_list_append(i64 %r162, i64 4)
  %t36 = call i64 @nova_rt_list_append(i64 %r162, i64 5)
  %t37 = call i64 @nova_rt_list_append(i64 %r162, i64 6)
  %t38 = call i64 @nova_rt_list_append(i64 %r162, i64 7)
  %t39 = call i64 @nova_rt_list_append(i64 %r162, i64 8)
  %t40 = call i64 @nova_rt_list_append(i64 %r162, i64 9)
  %t41 = call i64 @nova_rt_list_append(i64 %r162, i64 10)
  store i64 %r162, ptr %slot.numbers
  %t42 = call ptr @malloc(i64 8)
  %t43 = ptrtoint ptr @nova_main_lambda2_tramp to i64
  store i64 %t43, ptr %t42
  %r167 = ptrtoint ptr %t42 to i64
  %r168 = call i64 @nova_rt_list_map(i64 %r162, i64 %r167)
  store i64 %r168, ptr %slot.squared
  %t44 = call ptr @malloc(i64 8)
  %t45 = ptrtoint ptr @nova_main_lambda3_tramp to i64
  store i64 %t45, ptr %t44
  %r173 = ptrtoint ptr %t44 to i64
  %r174 = call i64 @nova_rt_list_filter(i64 %r168, i64 %r173)
  store i64 %r174, ptr %slot.even_squares
  %t46 = getelementptr inbounds [15 x i8], ptr @.str.42, i64 0, i64 0
  %r179 = ptrtoint ptr %t46 to i64
  %r181 = call i64 @nova_rt_list_to_str(i64 %r174)
  %t47 = call i64 @nova_rt_str_concat(i64 %r179, i64 %r181)
  %t48 = inttoptr i64 %t47 to ptr
  call i32 @puts(ptr %t48)
  %t49 = call ptr @malloc(i64 8)
  %t50 = ptrtoint ptr @nova_main_lambda4_tramp to i64
  store i64 %t50, ptr %t49
  %r185 = ptrtoint ptr %t49 to i64
  %r186 = call i64 @nova_rt_list_map(i64 %r162, i64 %r185)
  store i64 %r186, ptr %slot.tripled
  %t51 = call ptr @malloc(i64 8)
  %t52 = ptrtoint ptr @nova_main_lambda5_tramp to i64
  store i64 %t52, ptr %t51
  %r191 = ptrtoint ptr %t51 to i64
  %r192 = call i64 @nova_rt_list_filter(i64 %r186, i64 %r191)
  store i64 %r192, ptr %slot.big
  %t53 = getelementptr inbounds [15 x i8], ptr @.str.43, i64 0, i64 0
  %r197 = ptrtoint ptr %t53 to i64
  %r199 = call i64 @nova_rt_list_to_str(i64 %r192)
  %t54 = call i64 @nova_rt_str_concat(i64 %r197, i64 %r199)
  %t55 = inttoptr i64 %t54 to ptr
  call i32 @puts(ptr %t55)
  %r214 = call i64 @nova_rt_list_create()
  %t56 = call i64 @nova_rt_list_append(i64 %r214, i64 0)
  %t57 = call i64 @nova_rt_list_append(i64 %r214, i64 1)
  %t58 = call i64 @nova_rt_list_append(i64 %r214, i64 2)
  %t59 = call i64 @nova_rt_list_append(i64 %r214, i64 3)
  %t60 = call i64 @nova_rt_list_append(i64 %r214, i64 4)
  %t61 = call i64 @nova_rt_list_append(i64 %r214, i64 5)
  %t62 = call i64 @nova_rt_list_append(i64 %r214, i64 9)
  %t63 = call i64 @nova_rt_list_append(i64 %r214, i64 10)
  %t64 = call i64 @nova_rt_list_append(i64 %r214, i64 16)
  %t65 = call i64 @nova_rt_list_append(i64 %r214, i64 25)
  %t66 = call i64 @nova_rt_list_append(i64 %r214, i64 37)
  %t67 = call i64 @nova_rt_list_append(i64 %r214, i64 100)
  store i64 %r214, ptr %slot.test_nums
  store i64 0, ptr %slot.j
  br label %while_header7

ifb_then4:
  %r80 = load i64, ptr %slot.passing_count
  %r82 = add i64 %r80, 1
  store i64 %r82, ptr %slot.passing_count
  store i64 0, ptr %slot.__ifb_0
  br label %ifb_merge6

ifb_else5:
  store i64 0, ptr %slot.__ifb_0
  br label %ifb_merge6

ifb_merge6:
  %r89 = load i64, ptr %slot.total_score
  %r90 = load i64, ptr %slot.s
  %t68 = getelementptr inbounds [6 x i8], ptr @.str.2, i64 0, i64 0
  %t69 = ptrtoint ptr %t68 to i64
  %r91 = call i64 @nova_rt_dict_get(i64 %r90, i64 %t69)
  %r92 = add i64 %r89, %r91
  store i64 %r92, ptr %slot.total_score
  %r95 = load i64, ptr %slot.i
  %r97 = add i64 %r95, 1
  store i64 %r97, ptr %slot.i
  br label %while_header1

while_header7:
  %r222 = load i64, ptr %slot.j
  %r224 = load i64, ptr %slot.test_nums
  %r225 = call i64 @nova_rt_list_len(i64 %r224)
  %t70 = icmp slt i64 %r222, %r225
  %r226 = zext i1 %t70 to i64
  %t71 = trunc i64 %r226 to i1
  br i1 %t71, label %while_body8, label %while_exit9

while_body8:
  %r228 = load i64, ptr %slot.test_nums
  %r229 = load i64, ptr %slot.j
  %r230 = call i64 @nova_rt_list_get(i64 %r228, i64 %r229)
  store i64 %r230, ptr %slot.n
  %r236 = call i64 @nova_rt_int_to_str(i64 %r230)
  %t72 = getelementptr inbounds [5 x i8], ptr @.str.44, i64 0, i64 0
  %r237 = ptrtoint ptr %t72 to i64
  %t73 = call i64 @nova_rt_str_concat(i64 %r236, i64 %r237)
  %r240 = call i64 @classify(i64 %r230)
  %t74 = call i64 @nova_rt_str_concat(i64 %t73, i64 %r240)
  %t75 = inttoptr i64 %t74 to ptr
  call i32 @puts(ptr %t75)
  %r243 = load i64, ptr %slot.j
  %r245 = add i64 %r243, 1
  store i64 %r245, ptr %slot.j
  br label %while_header7

while_exit9:
  %t76 = getelementptr inbounds [4 x i8], ptr @.str.45, i64 0, i64 0
  %r249 = ptrtoint ptr %t76 to i64
  %t77 = getelementptr inbounds [4 x i8], ptr @.str.46, i64 0, i64 0
  %r250 = ptrtoint ptr %t77 to i64
  %t78 = getelementptr inbounds [4 x i8], ptr @.str.47, i64 0, i64 0
  %r251 = ptrtoint ptr %t78 to i64
  %t79 = getelementptr inbounds [3 x i8], ptr @.str.48, i64 0, i64 0
  %r252 = ptrtoint ptr %t79 to i64
  %t80 = getelementptr inbounds [4 x i8], ptr @.str.45, i64 0, i64 0
  %r253 = ptrtoint ptr %t80 to i64
  %t81 = getelementptr inbounds [4 x i8], ptr @.str.49, i64 0, i64 0
  %r254 = ptrtoint ptr %t81 to i64
  %t82 = getelementptr inbounds [4 x i8], ptr @.str.45, i64 0, i64 0
  %r255 = ptrtoint ptr %t82 to i64
  %t83 = getelementptr inbounds [4 x i8], ptr @.str.46, i64 0, i64 0
  %r256 = ptrtoint ptr %t83 to i64
  %t84 = getelementptr inbounds [3 x i8], ptr @.str.48, i64 0, i64 0
  %r257 = ptrtoint ptr %t84 to i64
  %t85 = getelementptr inbounds [4 x i8], ptr @.str.45, i64 0, i64 0
  %r258 = ptrtoint ptr %t85 to i64
  %r259 = call i64 @nova_rt_list_create()
  %t86 = call i64 @nova_rt_list_append(i64 %r259, i64 %r249)
  %t87 = call i64 @nova_rt_list_append(i64 %r259, i64 %r250)
  %t88 = call i64 @nova_rt_list_append(i64 %r259, i64 %r251)
  %t89 = call i64 @nova_rt_list_append(i64 %r259, i64 %r252)
  %t90 = call i64 @nova_rt_list_append(i64 %r259, i64 %r253)
  %t91 = call i64 @nova_rt_list_append(i64 %r259, i64 %r254)
  %t92 = call i64 @nova_rt_list_append(i64 %r259, i64 %r255)
  %t93 = call i64 @nova_rt_list_append(i64 %r259, i64 %r256)
  %t94 = call i64 @nova_rt_list_append(i64 %r259, i64 %r257)
  %t95 = call i64 @nova_rt_list_append(i64 %r259, i64 %r258)
  store i64 %r259, ptr %slot.words
  %r263 = call i64 @nova_rt_dict_create()
  store i64 %r263, ptr %slot.freq
  store i64 0, ptr %slot.k
  br label %while_header10

while_header10:
  %r271 = load i64, ptr %slot.k
  %r273 = load i64, ptr %slot.words
  %r274 = call i64 @nova_rt_list_len(i64 %r273)
  %t96 = icmp slt i64 %r271, %r274
  %r275 = zext i1 %t96 to i64
  %t97 = trunc i64 %r275 to i1
  br i1 %t97, label %while_body11, label %while_exit12

while_body11:
  %r277 = load i64, ptr %slot.freq
  %r278 = load i64, ptr %slot.words
  %r279 = load i64, ptr %slot.k
  %r280 = call i64 @nova_rt_list_get(i64 %r278, i64 %r279)
  %r281 = call i64 @count_word(i64 %r277, i64 %r280)
  store i64 %r281, ptr %slot.freq
  %r284 = load i64, ptr %slot.k
  %r286 = add i64 %r284, 1
  store i64 %r286, ptr %slot.k
  br label %while_header10

while_exit12:
  %t98 = getelementptr inbounds [13 x i8], ptr @.str.50, i64 0, i64 0
  %r291 = ptrtoint ptr %t98 to i64
  %r292 = load i64, ptr %slot.freq
  %t99 = getelementptr inbounds [4 x i8], ptr @.str.45, i64 0, i64 0
  %r293 = ptrtoint ptr %t99 to i64
  %r294 = call i64 @nova_rt_dict_get(i64 %r292, i64 %r293)
  %r295 = call i64 @nova_rt_int_to_str(i64 %r294)
  %t100 = call i64 @nova_rt_str_concat(i64 %r291, i64 %r295)
  %t101 = inttoptr i64 %t100 to ptr
  call i32 @puts(ptr %t101)
  %t102 = getelementptr inbounds [13 x i8], ptr @.str.51, i64 0, i64 0
  %r299 = ptrtoint ptr %t102 to i64
  %r300 = load i64, ptr %slot.freq
  %t103 = getelementptr inbounds [4 x i8], ptr @.str.46, i64 0, i64 0
  %r301 = ptrtoint ptr %t103 to i64
  %r302 = call i64 @nova_rt_dict_get(i64 %r300, i64 %r301)
  %r303 = call i64 @nova_rt_int_to_str(i64 %r302)
  %t104 = call i64 @nova_rt_str_concat(i64 %r299, i64 %r303)
  %t105 = inttoptr i64 %t104 to ptr
  call i32 @puts(ptr %t105)
  %t106 = getelementptr inbounds [12 x i8], ptr @.str.52, i64 0, i64 0
  %r307 = ptrtoint ptr %t106 to i64
  %r308 = load i64, ptr %slot.freq
  %t107 = getelementptr inbounds [3 x i8], ptr @.str.48, i64 0, i64 0
  %r309 = ptrtoint ptr %t107 to i64
  %r310 = call i64 @nova_rt_dict_get(i64 %r308, i64 %r309)
  %r311 = call i64 @nova_rt_int_to_str(i64 %r310)
  %t108 = call i64 @nova_rt_str_concat(i64 %r307, i64 %r311)
  %t109 = inttoptr i64 %t108 to ptr
  call i32 @puts(ptr %t109)
  %t110 = getelementptr inbounds [13 x i8], ptr @.str.53, i64 0, i64 0
  %r315 = ptrtoint ptr %t110 to i64
  %r316 = load i64, ptr %slot.freq
  %t111 = getelementptr inbounds [4 x i8], ptr @.str.47, i64 0, i64 0
  %r317 = ptrtoint ptr %t111 to i64
  %r318 = call i64 @nova_rt_dict_get(i64 %r316, i64 %r317)
  %r319 = call i64 @nova_rt_int_to_str(i64 %r318)
  %t112 = call i64 @nova_rt_str_concat(i64 %r315, i64 %r319)
  %t113 = inttoptr i64 %t112 to ptr
  call i32 @puts(ptr %t113)
  %t114 = getelementptr inbounds [13 x i8], ptr @.str.54, i64 0, i64 0
  %r323 = ptrtoint ptr %t114 to i64
  %r324 = load i64, ptr %slot.freq
  %t115 = getelementptr inbounds [4 x i8], ptr @.str.49, i64 0, i64 0
  %r325 = ptrtoint ptr %t115 to i64
  %r326 = call i64 @nova_rt_dict_get(i64 %r324, i64 %r325)
  %r327 = call i64 @nova_rt_int_to_str(i64 %r326)
  %t116 = call i64 @nova_rt_str_concat(i64 %r323, i64 %r327)
  %t117 = inttoptr i64 %t116 to ptr
  call i32 @puts(ptr %t117)
  %r332 = call i64 @make_validator(i64 0, i64 150)
  store i64 %r332, ptr %slot.age_valid
  %r338 = call i64 @make_validator(i64 0, i64 100)
  store i64 %r338, ptr %slot.score_valid
  %t118 = getelementptr inbounds [2 x i8], ptr @.str.55, i64 0, i64 0
  %r342 = ptrtoint ptr %t118 to i64
  %t119 = getelementptr inbounds [4 x i8], ptr @.str.56, i64 0, i64 0
  %r343 = ptrtoint ptr %t119 to i64
  %r344 = call i64 @make_formatter(i64 %r342, i64 %r343)
  store i64 %r344, ptr %slot.dollar_fmt
  %t120 = getelementptr inbounds [2 x i8], ptr @.str.57, i64 0, i64 0
  %r348 = ptrtoint ptr %t120 to i64
  %t121 = getelementptr inbounds [2 x i8], ptr @.str.58, i64 0, i64 0
  %r349 = ptrtoint ptr %t121 to i64
  %r350 = call i64 @make_formatter(i64 %r348, i64 %r349)
  store i64 %r350, ptr %slot.paren_fmt
  %t122 = getelementptr inbounds [15 x i8], ptr @.str.59, i64 0, i64 0
  %r355 = ptrtoint ptr %t122 to i64
  %t123 = inttoptr i64 %r332 to ptr
  %t124 = load i64, ptr %t123
  %t125 = inttoptr i64 %t124 to ptr
  %r358 = call i64 %t125(i64 %r332, i64 25)
  %r359 = call i64 @nova_rt_int_to_str(i64 %r358)
  %t126 = call i64 @nova_rt_str_concat(i64 %r355, i64 %r359)
  %t127 = inttoptr i64 %t126 to ptr
  call i32 @puts(ptr %t127)
  %t128 = getelementptr inbounds [16 x i8], ptr @.str.60, i64 0, i64 0
  %r363 = ptrtoint ptr %t128 to i64
  %t129 = inttoptr i64 %r332 to ptr
  %t130 = load i64, ptr %t129
  %t131 = inttoptr i64 %t130 to ptr
  %r366 = call i64 %t131(i64 %r332, i64 200)
  %r367 = call i64 @nova_rt_int_to_str(i64 %r366)
  %t132 = call i64 @nova_rt_str_concat(i64 %r363, i64 %r367)
  %t133 = inttoptr i64 %t132 to ptr
  call i32 @puts(ptr %t133)
  %t134 = getelementptr inbounds [17 x i8], ptr @.str.61, i64 0, i64 0
  %r371 = ptrtoint ptr %t134 to i64
  %t135 = inttoptr i64 %r338 to ptr
  %t136 = load i64, ptr %t135
  %t137 = inttoptr i64 %t136 to ptr
  %r374 = call i64 %t137(i64 %r338, i64 85)
  %r375 = call i64 @nova_rt_int_to_str(i64 %r374)
  %t138 = call i64 @nova_rt_str_concat(i64 %r371, i64 %r375)
  %t139 = inttoptr i64 %t138 to ptr
  call i32 @puts(ptr %t139)
  %t140 = getelementptr inbounds [18 x i8], ptr @.str.62, i64 0, i64 0
  %r379 = ptrtoint ptr %t140 to i64
  %t141 = inttoptr i64 %r338 to ptr
  %t142 = load i64, ptr %t141
  %t143 = inttoptr i64 %t142 to ptr
  %r382 = call i64 %t143(i64 %r338, i64 150)
  %r383 = call i64 @nova_rt_int_to_str(i64 %r382)
  %t144 = call i64 @nova_rt_str_concat(i64 %r379, i64 %r383)
  %t145 = inttoptr i64 %t144 to ptr
  call i32 @puts(ptr %t145)
  %t146 = getelementptr inbounds [9 x i8], ptr @.str.63, i64 0, i64 0
  %r387 = ptrtoint ptr %t146 to i64
  %t147 = inttoptr i64 %r344 to ptr
  %t148 = load i64, ptr %t147
  %t149 = inttoptr i64 %t148 to ptr
  %r390 = call i64 %t149(i64 %r344, i64 42)
  %t150 = call i64 @nova_rt_str_concat(i64 %r387, i64 %r390)
  %t151 = inttoptr i64 %t150 to ptr
  call i32 @puts(ptr %t151)
  %t152 = getelementptr inbounds [8 x i8], ptr @.str.64, i64 0, i64 0
  %r394 = ptrtoint ptr %t152 to i64
  %t153 = inttoptr i64 %r350 to ptr
  %t154 = load i64, ptr %t153
  %t155 = inttoptr i64 %t154 to ptr
  %r397 = call i64 %t155(i64 %r350, i64 99)
  %t156 = call i64 @nova_rt_str_concat(i64 %r394, i64 %r397)
  %t157 = inttoptr i64 %t156 to ptr
  call i32 @puts(ptr %t157)
  store i64 0, ptr %slot.count
  store i64 2, ptr %slot.n
  br label %while_header13

while_header13:
  %r407 = load i64, ptr %slot.n
  %t158 = icmp slt i64 %r407, 200
  %r409 = zext i1 %t158 to i64
  %t159 = trunc i64 %r409 to i1
  br i1 %t159, label %while_body14, label %while_exit15

while_body14:
  %r411 = load i64, ptr %slot.n
  %r412 = call i64 @is_prime(i64 %r411)
  %r413 = load i64, ptr %slot.n
  %r415 = add i64 %r413, 2
  %r416 = call i64 @is_prime(i64 %r415)
  %t160 = icmp ne i64 %r412, 0
  %t161 = icmp ne i64 %r416, 0
  %t162 = and i1 %t160, %t161
  %r417 = zext i1 %t162 to i64
  %slot.__ifb_1 = alloca i64
  %t163 = trunc i64 %r417 to i1
  br i1 %t163, label %ifb_then16, label %ifb_else17

while_exit15:
  store i64 0, ptr %slot.skip_sum
  store i64 1, ptr %slot.m
  br label %while_header23

ifb_then16:
  %t164 = getelementptr inbounds [14 x i8], ptr @.str.65, i64 0, i64 0
  %r421 = ptrtoint ptr %t164 to i64
  %r422 = load i64, ptr %slot.n
  %r423 = call i64 @nova_rt_int_to_str(i64 %r422)
  %t165 = call i64 @nova_rt_str_concat(i64 %r421, i64 %r423)
  %t166 = getelementptr inbounds [3 x i8], ptr @.str.66, i64 0, i64 0
  %r425 = ptrtoint ptr %t166 to i64
  %t167 = call i64 @nova_rt_str_concat(i64 %t165, i64 %r425)
  %r427 = load i64, ptr %slot.n
  %r429 = add i64 %r427, 2
  %r430 = call i64 @nova_rt_int_to_str(i64 %r429)
  %t168 = call i64 @nova_rt_str_concat(i64 %t167, i64 %r430)
  %t169 = inttoptr i64 %t168 to ptr
  call i32 @puts(ptr %t169)
  %r433 = load i64, ptr %slot.count
  %r435 = add i64 %r433, 1
  store i64 %r435, ptr %slot.count
  %t170 = icmp sge i64 %r435, 5
  %r440 = zext i1 %t170 to i64
  %slot.__ifb_2 = alloca i64
  %t171 = trunc i64 %r440 to i1
  br i1 %t171, label %ifb_then19, label %ifb_else20

ifb_else17:
  store i64 0, ptr %slot.__ifb_1
  br label %ifb_merge18

ifb_merge18:
  %r452 = load i64, ptr %slot.n
  %r454 = add i64 %r452, 1
  store i64 %r454, ptr %slot.n
  br label %while_header13

ifb_then19:
  br label %while_exit15

ifb_else20:
  store i64 0, ptr %slot.__ifb_2
  br label %ifb_merge21

ifb_merge21:
  %r447 = load i64, ptr %slot.__ifb_2
  store i64 %r447, ptr %slot.__ifb_1
  br label %ifb_merge18

while_header23:
  %r466 = load i64, ptr %slot.m
  %t172 = icmp sle i64 %r466, 30
  %r468 = zext i1 %t172 to i64
  %t173 = trunc i64 %r468 to i1
  br i1 %t173, label %while_body24, label %while_exit25

while_body24:
  %r470 = load i64, ptr %slot.m
  %r472 = srem i64 %r470, 3
  %t174 = icmp eq i64 %r472, 0
  %r474 = zext i1 %t174 to i64
  %slot.__ifb_3 = alloca i64
  %t175 = trunc i64 %r474 to i1
  br i1 %t175, label %ifb_then26, label %ifb_else27

while_exit25:
  %t176 = getelementptr inbounds [39 x i8], ptr @.str.67, i64 0, i64 0
  %r499 = ptrtoint ptr %t176 to i64
  %r500 = load i64, ptr %slot.skip_sum
  %r501 = call i64 @nova_rt_int_to_str(i64 %r500)
  %t177 = call i64 @nova_rt_str_concat(i64 %r499, i64 %r501)
  %t178 = inttoptr i64 %t177 to ptr
  call i32 @puts(ptr %t178)
  %r511 = call i64 @nova_rt_list_create()
  %t179 = call i64 @nova_rt_list_append(i64 %r511, i64 200)
  %t180 = call i64 @nova_rt_list_append(i64 %r511, i64 201)
  %t181 = call i64 @nova_rt_list_append(i64 %r511, i64 301)
  %t182 = call i64 @nova_rt_list_append(i64 %r511, i64 400)
  %t183 = call i64 @nova_rt_list_append(i64 %r511, i64 404)
  %t184 = call i64 @nova_rt_list_append(i64 %r511, i64 500)
  %t185 = call i64 @nova_rt_list_append(i64 %r511, i64 418)
  store i64 %r511, ptr %slot.codes
  store i64 0, ptr %slot.ci
  br label %while_header30

ifb_then26:
  %r477 = load i64, ptr %slot.m
  %r479 = add i64 %r477, 1
  store i64 %r479, ptr %slot.m
  br label %while_header23

ifb_else27:
  store i64 0, ptr %slot.__ifb_3
  br label %ifb_merge28

ifb_merge28:
  %r487 = load i64, ptr %slot.skip_sum
  %r488 = load i64, ptr %slot.m
  %r489 = add i64 %r487, %r488
  store i64 %r489, ptr %slot.skip_sum
  %r492 = load i64, ptr %slot.m
  %r494 = add i64 %r492, 1
  store i64 %r494, ptr %slot.m
  br label %while_header23

while_header30:
  %r519 = load i64, ptr %slot.ci
  %r521 = load i64, ptr %slot.codes
  %r522 = call i64 @nova_rt_list_len(i64 %r521)
  %t186 = icmp slt i64 %r519, %r522
  %r523 = zext i1 %t186 to i64
  %t187 = trunc i64 %r523 to i1
  br i1 %t187, label %while_body31, label %while_exit32

while_body31:
  %r525 = load i64, ptr %slot.codes
  %r526 = load i64, ptr %slot.ci
  %r527 = call i64 @nova_rt_list_get(i64 %r525, i64 %r526)
  store i64 %r527, ptr %slot.c
  %r533 = call i64 @nova_rt_int_to_str(i64 %r527)
  %t188 = getelementptr inbounds [3 x i8], ptr @.str.68, i64 0, i64 0
  %r534 = ptrtoint ptr %t188 to i64
  %t189 = call i64 @nova_rt_str_concat(i64 %r533, i64 %r534)
  %r537 = call i64 @http_status(i64 %r527)
  %t190 = call i64 @nova_rt_str_concat(i64 %t189, i64 %r537)
  %t191 = inttoptr i64 %t190 to ptr
  call i32 @puts(ptr %t191)
  %r540 = load i64, ptr %slot.ci
  %r542 = add i64 %r540, 1
  store i64 %r542, ptr %slot.ci
  br label %while_header30

while_exit32:
  %r547 = call i64 @build_large_list(i64 1000)
  store i64 %r547, ptr %slot.big_list
  %t192 = getelementptr inbounds [18 x i8], ptr @.str.69, i64 0, i64 0
  %r552 = ptrtoint ptr %t192 to i64
  %r555 = call i64 @nova_rt_list_len(i64 %r547)
  %r556 = call i64 @nova_rt_int_to_str(i64 %r555)
  %t193 = call i64 @nova_rt_str_concat(i64 %r552, i64 %r556)
  %t194 = inttoptr i64 %t193 to ptr
  call i32 @puts(ptr %t194)
  %t195 = getelementptr inbounds [15 x i8], ptr @.str.70, i64 0, i64 0
  %r560 = ptrtoint ptr %t195 to i64
  %r563 = call i64 @nova_rt_list_get(i64 %r547, i64 0)
  %r564 = call i64 @nova_rt_int_to_str(i64 %r563)
  %t196 = call i64 @nova_rt_str_concat(i64 %r560, i64 %r564)
  %t197 = inttoptr i64 %t196 to ptr
  call i32 @puts(ptr %t197)
  %t198 = getelementptr inbounds [17 x i8], ptr @.str.71, i64 0, i64 0
  %r568 = ptrtoint ptr %t198 to i64
  %r571 = call i64 @nova_rt_list_get(i64 %r547, i64 999)
  %r572 = call i64 @nova_rt_int_to_str(i64 %r571)
  %t199 = call i64 @nova_rt_str_concat(i64 %r568, i64 %r572)
  %t200 = inttoptr i64 %t199 to ptr
  call i32 @puts(ptr %t200)
  store i64 0, ptr %slot.big_sum
  store i64 0, ptr %slot.bi
  br label %while_header33

while_header33:
  %r583 = load i64, ptr %slot.bi
  %r585 = load i64, ptr %slot.big_list
  %r586 = call i64 @nova_rt_list_len(i64 %r585)
  %t201 = icmp slt i64 %r583, %r586
  %r587 = zext i1 %t201 to i64
  %t202 = trunc i64 %r587 to i1
  br i1 %t202, label %while_body34, label %while_exit35

while_body34:
  %r589 = load i64, ptr %slot.big_sum
  %r590 = load i64, ptr %slot.big_list
  %r591 = load i64, ptr %slot.bi
  %r592 = call i64 @nova_rt_list_get(i64 %r590, i64 %r591)
  %r593 = add i64 %r589, %r592
  store i64 %r593, ptr %slot.big_sum
  %r596 = load i64, ptr %slot.bi
  %r598 = add i64 %r596, 1
  store i64 %r598, ptr %slot.bi
  br label %while_header33

while_exit35:
  %t203 = getelementptr inbounds [22 x i8], ptr @.str.72, i64 0, i64 0
  %r603 = ptrtoint ptr %t203 to i64
  %r604 = load i64, ptr %slot.big_sum
  %r605 = call i64 @nova_rt_int_to_str(i64 %r604)
  %t204 = call i64 @nova_rt_str_concat(i64 %r603, i64 %r605)
  %t205 = inttoptr i64 %t204 to ptr
  call i32 @puts(ptr %t205)
  %t206 = getelementptr inbounds [1 x i8], ptr @.str.73, i64 0, i64 0
  %r609 = ptrtoint ptr %t206 to i64
  %t207 = inttoptr i64 %r609 to ptr
  call i32 @puts(ptr %t207)
  %t208 = getelementptr inbounds [36 x i8], ptr @.str.74, i64 0, i64 0
  %r612 = ptrtoint ptr %t208 to i64
  %t209 = inttoptr i64 %r612 to ptr
  call i32 @puts(ptr %t209)
  ret i64 0
}

define i64 @nova_main_lambda2(i64 %p0) {
entry0:
  %slot.x = alloca i64
  store i64 %p0, ptr %slot.x
  %r171 = mul i64 %p0, %p0
  ret i64 %r171
}

define i64 @nova_main_lambda3(i64 %p0) {
entry0:
  %slot.x = alloca i64
  store i64 %p0, ptr %slot.x
  %r177 = srem i64 %p0, 2
  %t0 = icmp eq i64 %r177, 0
  %r179 = zext i1 %t0 to i64
  ret i64 %r179
}

define i64 @nova_main_lambda4(i64 %p0) {
entry0:
  %slot.x = alloca i64
  store i64 %p0, ptr %slot.x
  %r189 = mul i64 %p0, 3
  ret i64 %r189
}

define i64 @nova_main_lambda5(i64 %p0) {
entry0:
  %slot.x = alloca i64
  store i64 %p0, ptr %slot.x
  %t0 = icmp sgt i64 %p0, 15
  %r195 = zext i1 %t0 to i64
  ret i64 %r195
}

define i64 @make_validator_lambda0_tramp(i64 %p0, i64 %p1) {
entry_tramp:
  %env_ptr = inttoptr i64 %p0 to ptr
  %cap0_gep = getelementptr i64, ptr %env_ptr, i64 1
  %cap0 = load i64, ptr %cap0_gep
  %cap1_gep = getelementptr i64, ptr %env_ptr, i64 2
  %cap1 = load i64, ptr %cap1_gep
  %tramp_result = call i64 @make_validator_lambda0(i64 %p1, i64 %cap0, i64 %cap1)
  ret i64 %tramp_result
}

define i64 @make_formatter_lambda1_tramp(i64 %p0, i64 %p1) {
entry_tramp:
  %env_ptr = inttoptr i64 %p0 to ptr
  %cap0_gep = getelementptr i64, ptr %env_ptr, i64 1
  %cap0 = load i64, ptr %cap0_gep
  %cap1_gep = getelementptr i64, ptr %env_ptr, i64 2
  %cap1 = load i64, ptr %cap1_gep
  %tramp_result = call i64 @make_formatter_lambda1(i64 %p1, i64 %cap0, i64 %cap1)
  ret i64 %tramp_result
}

define i64 @nova_main_lambda2_tramp(i64 %p0, i64 %p1) {
entry_tramp:
  %env_ptr = inttoptr i64 %p0 to ptr
  %tramp_result = call i64 @nova_main_lambda2(i64 %p1)
  ret i64 %tramp_result
}

define i64 @nova_main_lambda3_tramp(i64 %p0, i64 %p1) {
entry_tramp:
  %env_ptr = inttoptr i64 %p0 to ptr
  %tramp_result = call i64 @nova_main_lambda3(i64 %p1)
  ret i64 %tramp_result
}

define i64 @nova_main_lambda4_tramp(i64 %p0, i64 %p1) {
entry_tramp:
  %env_ptr = inttoptr i64 %p0 to ptr
  %tramp_result = call i64 @nova_main_lambda4(i64 %p1)
  ret i64 %tramp_result
}

define i64 @nova_main_lambda5_tramp(i64 %p0, i64 %p1) {
entry_tramp:
  %env_ptr = inttoptr i64 %p0 to ptr
  %tramp_result = call i64 @nova_main_lambda5(i64 %p1)
  ret i64 %tramp_result
}

define i32 @main() {
entry:
  call i64 @nova_main()
  call void @nova_rt_wait_all()
  ret i32 0
}
