; Generated by NOVA compiler
target triple = "x86_64-pc-windows-msvc"

declare i32 @printf(ptr, ...)
declare i32 @puts(ptr)
declare noalias ptr @malloc(i64) nounwind allocsize(0)
declare ptr @realloc(ptr, i64) nounwind allocsize(1)
declare void @free(ptr)
; nova runtime — list ops
declare i64 @nova_rt_list_create()
declare i64 @nova_rt_list_create_filled(i64, i64)
declare i64 @nova_rt_list_append(i64, i64)
declare i64 @nova_rt_list_get(i64, i64)
declare i64 @nova_rt_list_set(i64, i64, i64)
declare i64 @nova_rt_list_len(i64)
declare i64 @nova_rt_list_print(i64)
declare i64 @nova_rt_iter_has_next(i64, i64)
declare i64 @nova_rt_iter_get(i64, i64)
; nova runtime — string ops
declare i64 @nova_rt_str_concat(i64, i64)
declare i64 @nova_rt_int_to_str(i64)
declare i64 @nova_rt_float_to_str(i64)
declare i64 @nova_rt_bool_to_str(i64)
declare i64 @nova_rt_str_len(i64)
declare i64 @nova_rt_len(i64)
declare i64 @nova_rt_contains(i64, i64)
declare i64 @nova_rt_slice(i64, i64, i64)
declare i64 @nova_rt_upper(i64)
declare i64 @nova_rt_lower(i64)
declare i64 @nova_rt_trim(i64)
declare i64 @nova_rt_split(i64, i64)
declare i64 @nova_rt_replace(i64, i64, i64)
declare i64 @nova_rt_starts_with(i64, i64)
declare i64 @nova_rt_ends_with(i64, i64)
declare i64 @nova_rt_find(i64, i64)
declare i64 @nova_rt_join(i64, i64)
declare i64 @nova_rt_chars(i64)
; nova runtime — list stdlib
declare i64 @nova_rt_list_reverse(i64)
declare i64 @nova_rt_list_sort(i64)
declare i64 @nova_rt_list_map(i64, i64)
declare i64 @nova_rt_list_filter(i64, i64)
declare i64 @nova_rt_list_concat(i64, i64)
declare i64 @nova_rt_list_slice(i64, i64, i64)
declare i64 @nova_rt_list_to_str(i64)
declare i64 @nova_rt_len_any(i64)
; nova runtime — type conversions
declare i64 @nova_rt_parse_int(i64)
declare i64 @nova_rt_parse_float(i64)
; nova runtime — character ops
declare i64 @nova_rt_ord(i64)
declare i64 @nova_rt_chr(i64)
; nova runtime — process control
declare void @nova_rt_exit(i64)
declare i32 @strcmp(ptr, ptr)
; nova runtime — dict ops (Phase 1: ordered array, O(n) lookup)
declare i64 @nova_rt_dict_create()
declare i64 @nova_rt_dict_set(i64, i64, i64)
declare i64 @nova_rt_dict_get(i64, i64)
declare i64 @nova_rt_dict_has(i64, i64)
declare i64 @nova_rt_dict_del(i64, i64)
declare i64 @nova_rt_dict_len(i64)
declare i64 @nova_rt_dict_keys(i64)
declare i64 @nova_rt_dict_values(i64)
declare i64 @nova_rt_dict_items(i64)
; nova runtime — IO ops
declare i64 @nova_rt_read_line()
declare i64 @nova_rt_read_file(i64)
declare i64 @nova_rt_write_file(i64, i64)
declare i64 @nova_rt_append_file(i64, i64)
declare i64 @nova_rt_file_exists(i64)
; nova runtime — JSON ops
declare i64 @nova_rt_json_parse(i64)
declare i64 @nova_rt_json_stringify(i64)
; nova runtime — HTTP ops
declare i64 @nova_rt_http_get(i64)
declare i64 @nova_rt_http_post(i64, i64, i64)
; nova runtime — type dispatch
declare i64 @nova_rt_any_to_str(i64)
declare i64 @nova_rt_str_concat_safe(i64, i64)
declare void @nova_rt_init()
; nova runtime — channel/spawn ops
declare i64 @nova_rt_channel_create()
declare i64 @nova_rt_channel_send(i64, i64)
declare i64 @nova_rt_channel_recv(i64)
declare i64 @nova_rt_channel_close(i64)
declare i64 @nova_rt_channel_select(i64, i64)
declare i64 @nova_rt_channel_recv_timeout(i64, i64)
declare i64 @nova_rt_spawn(i64, i64)
declare i64 @nova_rt_monitor(i64)
declare void @nova_rt_wait_all()
; nova runtime — math (trig/log via C runtime for non-intrinsic functions)
declare i64 @nova_rt_tan(i64)
declare i64 @nova_rt_asin(i64)
declare i64 @nova_rt_acos(i64)
declare i64 @nova_rt_atan(i64)
declare i64 @nova_rt_atan2(i64, i64)
declare i64 @nova_rt_fmod(i64, i64)
declare i64 @nova_rt_int_pow(i64, i64)
; nova runtime — memory management
declare void @nova_rt_cleanup()
declare void @nova_rt_track_raw(ptr)
declare i64 @nova_rt_alloc_count()
declare i64 @nova_rt_live_count()
; nova runtime — reference counting
declare void @nova_rc_inc(i64)
declare void @nova_rc_dec(i64)
; nova error state — thread-local flag (safe for spawn/concurrent programs)
@__nova_error_flag = thread_local global i64 0
@__nova_error_msg = thread_local global i64 0

@.str.0 = private unnamed_addr constant [11 x i8] c"2 ** 10 = \00"
@.str.1 = private unnamed_addr constant [11 x i8] c"3 ** 5  = \00"
@.str.2 = private unnamed_addr constant [11 x i8] c"10 ** 0 = \00"
@.str.3 = private unnamed_addr constant [11 x i8] c"7 ** 1  = \00"
@.str.4 = private unnamed_addr constant [11 x i8] c"2 ** 20 = \00"
@.str.5 = private unnamed_addr constant [18 x i8] c"fast_pow(5, 3) = \00"
@.str.6 = private unnamed_addr constant [19 x i8] c"fast_pow(2, 16) = \00"
@.str.7 = private unnamed_addr constant [19 x i8] c"2^8 = 256: correct\00"
@.str.8 = private unnamed_addr constant [6 x i8] c"%lld\0A\00"
@.str.9 = private unnamed_addr constant [4 x i8] c"%f\0A\00"
@.str.10 = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.str.11 = private unnamed_addr constant [5 x i8] c"true\00"
@.str.12 = private unnamed_addr constant [6 x i8] c"false\00"

define i64 @fast_pow(i64 %p0, i64 %p1) {
entry0:
  %slot.b = alloca i64, align 8
  %slot.e = alloca i64, align 8
  store i64 %p0, ptr %slot.b, align 8
  store i64 %p1, ptr %slot.e, align 8
  %r7 = call i64 @nova_rt_int_pow(i64 %p0, i64 %p1)
  ret i64 %r7
}

define i64 @nova_main() {
entry0:
  %slot.base = alloca i64, align 8
  %slot.exp = alloca i64, align 8
  %slot.result = alloca i64, align 8
  %slot.__ifb_0 = alloca i64, align 8
  store i64 0, ptr %slot.__ifb_0, align 8
  %t0 = getelementptr inbounds [11 x i8], ptr @.str.0, i64 0, i64 0
  %r0 = ptrtoint ptr %t0 to i64
  %r4 = call i64 @nova_rt_int_to_str(i64 1024)
  %t1 = call i64 @nova_rt_str_concat(i64 %r0, i64 %r4)
  call void @nova_rc_dec(i64 %r4)
  %t2 = inttoptr i64 %t1 to ptr
  call i32 @puts(ptr %t2)
  call void @nova_rc_dec(i64 %t1)
  %t3 = getelementptr inbounds [11 x i8], ptr @.str.1, i64 0, i64 0
  %r7 = ptrtoint ptr %t3 to i64
  %r11 = call i64 @nova_rt_int_to_str(i64 243)
  %t4 = call i64 @nova_rt_str_concat(i64 %r7, i64 %r11)
  call void @nova_rc_dec(i64 %r11)
  %t5 = inttoptr i64 %t4 to ptr
  call i32 @puts(ptr %t5)
  call void @nova_rc_dec(i64 %t4)
  %t6 = getelementptr inbounds [11 x i8], ptr @.str.2, i64 0, i64 0
  %r14 = ptrtoint ptr %t6 to i64
  %r18 = call i64 @nova_rt_int_to_str(i64 1)
  %t7 = call i64 @nova_rt_str_concat(i64 %r14, i64 %r18)
  call void @nova_rc_dec(i64 %r18)
  %t8 = inttoptr i64 %t7 to ptr
  call i32 @puts(ptr %t8)
  call void @nova_rc_dec(i64 %t7)
  %t9 = getelementptr inbounds [11 x i8], ptr @.str.3, i64 0, i64 0
  %r21 = ptrtoint ptr %t9 to i64
  %r25 = call i64 @nova_rt_int_to_str(i64 7)
  %t10 = call i64 @nova_rt_str_concat(i64 %r21, i64 %r25)
  call void @nova_rc_dec(i64 %r25)
  %t11 = inttoptr i64 %t10 to ptr
  call i32 @puts(ptr %t11)
  call void @nova_rc_dec(i64 %t10)
  store i64 2, ptr %slot.base, align 8
  store i64 20, ptr %slot.exp, align 8
  store i64 1048576, ptr %slot.result, align 8
  %t12 = getelementptr inbounds [11 x i8], ptr @.str.4, i64 0, i64 0
  %r42 = ptrtoint ptr %t12 to i64
  %r44 = call i64 @nova_rt_int_to_str(i64 1048576)
  %t13 = call i64 @nova_rt_str_concat(i64 %r42, i64 %r44)
  call void @nova_rc_dec(i64 %r44)
  %t14 = inttoptr i64 %t13 to ptr
  call i32 @puts(ptr %t14)
  call void @nova_rc_dec(i64 %t13)
  %t15 = getelementptr inbounds [18 x i8], ptr @.str.5, i64 0, i64 0
  %r47 = ptrtoint ptr %t15 to i64
  %r50 = call i64 @fast_pow(i64 5, i64 3)
  %r51 = call i64 @nova_rt_int_to_str(i64 %r50)
  %t16 = call i64 @nova_rt_str_concat(i64 %r47, i64 %r51)
  call void @nova_rc_dec(i64 %r51)
  %t17 = inttoptr i64 %t16 to ptr
  call i32 @puts(ptr %t17)
  call void @nova_rc_dec(i64 %t16)
  %t18 = getelementptr inbounds [19 x i8], ptr @.str.6, i64 0, i64 0
  %r54 = ptrtoint ptr %t18 to i64
  %r57 = call i64 @fast_pow(i64 2, i64 16)
  %r58 = call i64 @nova_rt_int_to_str(i64 %r57)
  %t19 = call i64 @nova_rt_str_concat(i64 %r54, i64 %r58)
  call void @nova_rc_dec(i64 %r58)
  %t20 = inttoptr i64 %t19 to ptr
  call i32 @puts(ptr %t20)
  call void @nova_rc_dec(i64 %t19)
  %t21 = trunc i64 1 to i1
  br i1 %t21, label %ifb_then1, label %ifb_else2

ifb_then1:
  %t22 = getelementptr inbounds [19 x i8], ptr @.str.7, i64 0, i64 0
  %r68 = ptrtoint ptr %t22 to i64
  %t23 = inttoptr i64 %r68 to ptr
  call i32 @puts(ptr %t23)
  %t24 = load i64, ptr %slot.__ifb_0, align 8
  call void @nova_rc_dec(i64 %t24)
  store i64 0, ptr %slot.__ifb_0, align 8
  br label %ifb_merge3

ifb_else2:
  %t25 = load i64, ptr %slot.__ifb_0, align 8
  call void @nova_rc_dec(i64 %t25)
  store i64 0, ptr %slot.__ifb_0, align 8
  br label %ifb_merge3

ifb_merge3:
  call void @nova_rc_inc(i64 0)
  %t26 = load i64, ptr %slot.__ifb_0, align 8
  call void @nova_rc_dec(i64 %t26)
  ret i64 0
}

define i32 @main() {
entry:
  call void @nova_rt_init()
  call i64 @nova_main()
  call void @nova_rt_wait_all()
  call void @nova_rt_cleanup()
  ret i32 0
}

!0 = !{!"NOVA TBAA"}
!1 = !{!"list_data_ptr", !0}
!2 = !{!1, !1, i64 0}
!3 = !{!"list_elem", !0}
!4 = !{!3, !3, i64 0}
!5 = !{!"list_size", !0}
!6 = !{!5, !5, i64 0}
!7 = !{!"list_cap", !0}
!8 = !{!7, !7, i64 0}
