; Generated by NOVA compiler
target triple = "x86_64-pc-windows-msvc"

declare i32 @printf(ptr, ...)
declare i32 @puts(ptr)
declare noalias ptr @malloc(i64) nounwind allocsize(0)
declare noalias ptr @calloc(i64, i64) nounwind
declare ptr @realloc(ptr, i64) nounwind allocsize(1)
declare void @free(ptr)
declare i64 @llvm.smax.i64(i64, i64) nounwind readnone
; nova runtime — list ops
declare i64 @nova_rt_list_create()
declare i64 @nova_rt_list_create_filled(i64, i64)
declare i64 @nova_rt_list_append(i64, i64)
declare i64 @nova_rt_list_get(i64, i64)
declare i64 @nova_rt_list_set(i64, i64, i64)
declare i64 @nova_rt_list_len(i64)
declare i64 @nova_rt_list_print(i64)
declare i64 @nova_rt_iter_has_next(i64, i64)
declare i64 @nova_rt_iter_get(i64, i64)
; nova runtime — string ops
declare i64 @nova_rt_str_concat(i64, i64)
declare i64 @nova_rt_int_to_str(i64)
declare i64 @nova_rt_float_to_str(i64)
declare i64 @nova_rt_bool_to_str(i64)
declare i64 @nova_rt_str_len(i64)
declare i64 @nova_rt_len(i64)
declare i64 @nova_rt_contains(i64, i64)
declare i64 @nova_rt_slice(i64, i64, i64)
declare i64 @nova_rt_upper(i64)
declare i64 @nova_rt_lower(i64)
declare i64 @nova_rt_trim(i64)
declare i64 @nova_rt_split(i64, i64)
declare i64 @nova_rt_replace(i64, i64, i64)
declare i64 @nova_rt_starts_with(i64, i64)
declare i64 @nova_rt_ends_with(i64, i64)
declare i64 @nova_rt_find(i64, i64)
declare i64 @nova_rt_join(i64, i64)
declare i64 @nova_rt_chars(i64)
; nova runtime — list stdlib
declare i64 @nova_rt_list_reverse(i64)
declare i64 @nova_rt_list_sort(i64)
declare i64 @nova_rt_list_map(i64, i64)
declare i64 @nova_rt_list_filter(i64, i64)
declare i64 @nova_rt_list_concat(i64, i64)
declare i64 @nova_rt_list_slice(i64, i64, i64)
declare i64 @nova_rt_list_to_str(i64)
declare i64 @nova_rt_len_any(i64)
; nova runtime — type conversions
declare i64 @nova_rt_parse_int(i64)
declare i64 @nova_rt_parse_float(i64)
; nova runtime — character ops
declare i64 @nova_rt_ord(i64)
declare i64 @nova_rt_chr(i64)
; nova runtime — process control
declare void @nova_rt_exit(i64)
declare i32 @strcmp(ptr, ptr)
; nova runtime — dict ops (Phase 1: ordered array, O(n) lookup)
declare i64 @nova_rt_dict_create()
declare i64 @nova_rt_dict_set(i64, i64, i64)
declare i64 @nova_rt_dict_get(i64, i64)
declare i64 @nova_rt_dict_has(i64, i64)
declare i64 @nova_rt_dict_del(i64, i64)
declare i64 @nova_rt_dict_len(i64)
declare i64 @nova_rt_dict_keys(i64)
declare i64 @nova_rt_dict_values(i64)
declare i64 @nova_rt_dict_items(i64)
; nova runtime — IO ops
declare i64 @nova_rt_read_line()
declare i64 @nova_rt_read_file(i64)
declare i64 @nova_rt_write_file(i64, i64)
declare i64 @nova_rt_append_file(i64, i64)
declare i64 @nova_rt_file_exists(i64)
; nova runtime — JSON ops
declare i64 @nova_rt_json_parse(i64)
declare i64 @nova_rt_json_stringify(i64)
; nova runtime — HTTP ops
declare i64 @nova_rt_http_get(i64)
declare i64 @nova_rt_http_post(i64, i64, i64)
; nova runtime — type dispatch
declare i64 @nova_rt_any_to_str(i64)
declare i64 @nova_rt_str_concat_safe(i64, i64)
declare void @nova_rt_init()
; nova runtime — channel/spawn ops
declare i64 @nova_rt_channel_create()
declare i64 @nova_rt_channel_send(i64, i64)
declare i64 @nova_rt_channel_recv(i64)
declare i64 @nova_rt_channel_close(i64)
declare i64 @nova_rt_channel_select(i64, i64)
declare i64 @nova_rt_channel_recv_timeout(i64, i64)
declare i64 @nova_rt_spawn(i64, i64)
declare i64 @nova_rt_monitor(i64)
declare void @nova_rt_wait_all()
; nova runtime — math (trig/log via C runtime for non-intrinsic functions)
declare i64 @nova_rt_tan(i64)
declare i64 @nova_rt_asin(i64)
declare i64 @nova_rt_acos(i64)
declare i64 @nova_rt_atan(i64)
declare i64 @nova_rt_atan2(i64, i64)
declare i64 @nova_rt_fmod(i64, i64)
declare i64 @nova_rt_int_pow(i64, i64)
; nova runtime — memory management
declare void @nova_rt_cleanup()
declare void @nova_rt_track_raw(ptr)
declare i64 @nova_rt_alloc_count()
declare i64 @nova_rt_live_count()
; nova runtime — reference counting
declare void @nova_rc_inc(i64)
declare void @nova_rc_dec(i64)
; nova error state — thread-local flag (safe for spawn/concurrent programs)
@__nova_error_flag = thread_local global i64 0
@__nova_error_msg = thread_local global i64 0

@.str.0 = private unnamed_addr constant [4 x i8] c"one\00"
@.str.1 = private unnamed_addr constant [4 x i8] c"two\00"
@.str.2 = private unnamed_addr constant [6 x i8] c"three\00"
@.str.3 = private unnamed_addr constant [6 x i8] c"other\00"
@.str.4 = private unnamed_addr constant [5 x i8] c"zero\00"
@.str.5 = private unnamed_addr constant [5 x i8] c"many\00"
@.str.6 = private unnamed_addr constant [6 x i8] c"%lld\0A\00"
@.str.7 = private unnamed_addr constant [4 x i8] c"%f\0A\00"
@.str.8 = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.str.9 = private unnamed_addr constant [5 x i8] c"true\00"
@.str.10 = private unnamed_addr constant [6 x i8] c"false\00"

define i64 @nova_main() {
entry0:
  %slot.x = alloca i64, align 8
  %slot.__match_1 = alloca i64, align 8
  %slot.__mb0_ret = alloca i64, align 8
  %slot.__mb0_n = alloca i64, align 8
  %slot.__mb0___match_0 = alloca i64, align 8
  %slot.__mb1_ret = alloca i64, align 8
  %slot.__mb1_n = alloca i64, align 8
  %slot.__mb1___match_0 = alloca i64, align 8
  %slot.__mb2_ret = alloca i64, align 8
  %slot.__mb2_n = alloca i64, align 8
  %slot.__mb2___match_0 = alloca i64, align 8
  store i64 0, ptr %slot.__match_1, align 8
  store i64 0, ptr %slot.__mb0___match_0, align 8
  store i64 0, ptr %slot.__mb0_ret, align 8
  store i64 0, ptr %slot.__mb1___match_0, align 8
  store i64 0, ptr %slot.__mb1_ret, align 8
  store i64 0, ptr %slot.__mb2___match_0, align 8
  store i64 0, ptr %slot.__mb2_ret, align 8
  store i64 3, ptr %slot.x, align 8
  %r4 = load i64, ptr %slot.x, align 8
  %t0 = icmp eq i64 %r4, 1
  br i1 %t0, label %arm0_body2, label %arm0_next3

arm0_body2:
  %t1 = getelementptr inbounds [4 x i8], ptr @.str.0, i64 0, i64 0
  %r8 = ptrtoint ptr %t1 to i64
  %t2 = load i64, ptr %slot.__match_1, align 8
  call void @nova_rc_dec(i64 %t2)
  store i64 %r8, ptr %slot.__match_1, align 8
  br label %match_merge1

arm0_next3:
  %t3 = icmp eq i64 %r4, 2
  br i1 %t3, label %arm1_body4, label %arm1_next5

arm1_body4:
  %t4 = getelementptr inbounds [4 x i8], ptr @.str.1, i64 0, i64 0
  %r12 = ptrtoint ptr %t4 to i64
  %t5 = load i64, ptr %slot.__match_1, align 8
  call void @nova_rc_dec(i64 %t5)
  store i64 %r12, ptr %slot.__match_1, align 8
  br label %match_merge1

arm1_next5:
  %t6 = icmp eq i64 %r4, 3
  br i1 %t6, label %arm2_body6, label %arm2_next7

arm2_body6:
  %t7 = getelementptr inbounds [6 x i8], ptr @.str.2, i64 0, i64 0
  %r16 = ptrtoint ptr %t7 to i64
  %t8 = load i64, ptr %slot.__match_1, align 8
  call void @nova_rc_dec(i64 %t8)
  store i64 %r16, ptr %slot.__match_1, align 8
  br label %match_merge1

arm2_next7:
  br label %arm3_body8

arm3_body8:
  %t9 = getelementptr inbounds [6 x i8], ptr @.str.3, i64 0, i64 0
  %r18 = ptrtoint ptr %t9 to i64
  %t10 = load i64, ptr %slot.__match_1, align 8
  call void @nova_rc_dec(i64 %t10)
  store i64 %r18, ptr %slot.__match_1, align 8
  br label %match_merge1

match_merge1:
  %r20 = load i64, ptr %slot.__match_1, align 8
  %t11 = inttoptr i64 %r20 to ptr
  call i32 @puts(ptr %t11)
  br label %__mb0_entry0

__mb0_entry0:
  store i64 0, ptr %slot.__mb0_n, align 8
  %r39 = load i64, ptr %slot.__mb0_n, align 8
  %t12 = icmp eq i64 %r39, 0
  br i1 %t12, label %__mb0_arm0_body2, label %__mb0_arm0_next3

__mb0_arm0_body2:
  %t13 = getelementptr inbounds [5 x i8], ptr @.str.4, i64 0, i64 0
  %r43 = ptrtoint ptr %t13 to i64
  %t14 = load i64, ptr %slot.__mb0___match_0, align 8
  call void @nova_rc_dec(i64 %t14)
  store i64 %r43, ptr %slot.__mb0___match_0, align 8
  br label %__mb0_match_merge1

__mb0_arm0_next3:
  %t15 = icmp eq i64 %r39, 1
  br i1 %t15, label %__mb0_arm1_body4, label %__mb0_arm1_next5

__mb0_arm1_body4:
  %t16 = getelementptr inbounds [4 x i8], ptr @.str.0, i64 0, i64 0
  %r47 = ptrtoint ptr %t16 to i64
  %t17 = load i64, ptr %slot.__mb0___match_0, align 8
  call void @nova_rc_dec(i64 %t17)
  store i64 %r47, ptr %slot.__mb0___match_0, align 8
  br label %__mb0_match_merge1

__mb0_arm1_next5:
  br label %__mb0_arm2_body6

__mb0_arm2_body6:
  %t18 = getelementptr inbounds [5 x i8], ptr @.str.5, i64 0, i64 0
  %r49 = ptrtoint ptr %t18 to i64
  %t19 = load i64, ptr %slot.__mb0___match_0, align 8
  call void @nova_rc_dec(i64 %t19)
  store i64 %r49, ptr %slot.__mb0___match_0, align 8
  br label %__mb0_match_merge1

__mb0_match_merge1:
  %r51 = load i64, ptr %slot.__mb0___match_0, align 8
  %t20 = load i64, ptr %slot.__mb0_ret, align 8
  call void @nova_rc_dec(i64 %t20)
  call void @nova_rc_inc(i64 %r51)
  store i64 %r51, ptr %slot.__mb0_ret, align 8
  br label %__mb0_merge

__mb0_merge:
  %r52 = load i64, ptr %slot.__mb0_ret, align 8
  %t21 = inttoptr i64 %r52 to ptr
  call i32 @puts(ptr %t21)
  br label %__mb1_entry0

__mb1_entry0:
  store i64 1, ptr %slot.__mb1_n, align 8
  %r58 = load i64, ptr %slot.__mb1_n, align 8
  %t22 = icmp eq i64 %r58, 0
  br i1 %t22, label %__mb1_arm0_body2, label %__mb1_arm0_next3

__mb1_arm0_body2:
  %t23 = getelementptr inbounds [5 x i8], ptr @.str.4, i64 0, i64 0
  %r62 = ptrtoint ptr %t23 to i64
  %t24 = load i64, ptr %slot.__mb1___match_0, align 8
  call void @nova_rc_dec(i64 %t24)
  store i64 %r62, ptr %slot.__mb1___match_0, align 8
  br label %__mb1_match_merge1

__mb1_arm0_next3:
  %t25 = icmp eq i64 %r58, 1
  br i1 %t25, label %__mb1_arm1_body4, label %__mb1_arm1_next5

__mb1_arm1_body4:
  %t26 = getelementptr inbounds [4 x i8], ptr @.str.0, i64 0, i64 0
  %r66 = ptrtoint ptr %t26 to i64
  %t27 = load i64, ptr %slot.__mb1___match_0, align 8
  call void @nova_rc_dec(i64 %t27)
  store i64 %r66, ptr %slot.__mb1___match_0, align 8
  br label %__mb1_match_merge1

__mb1_arm1_next5:
  br label %__mb1_arm2_body6

__mb1_arm2_body6:
  %t28 = getelementptr inbounds [5 x i8], ptr @.str.5, i64 0, i64 0
  %r68 = ptrtoint ptr %t28 to i64
  %t29 = load i64, ptr %slot.__mb1___match_0, align 8
  call void @nova_rc_dec(i64 %t29)
  store i64 %r68, ptr %slot.__mb1___match_0, align 8
  br label %__mb1_match_merge1

__mb1_match_merge1:
  %r70 = load i64, ptr %slot.__mb1___match_0, align 8
  %t30 = load i64, ptr %slot.__mb1_ret, align 8
  call void @nova_rc_dec(i64 %t30)
  call void @nova_rc_inc(i64 %r70)
  store i64 %r70, ptr %slot.__mb1_ret, align 8
  br label %__mb1_merge

__mb1_merge:
  %r71 = load i64, ptr %slot.__mb1_ret, align 8
  %t31 = inttoptr i64 %r71 to ptr
  call i32 @puts(ptr %t31)
  br label %__mb2_entry0

__mb2_entry0:
  store i64 99, ptr %slot.__mb2_n, align 8
  %r77 = load i64, ptr %slot.__mb2_n, align 8
  %t32 = icmp eq i64 %r77, 0
  br i1 %t32, label %__mb2_arm0_body2, label %__mb2_arm0_next3

__mb2_arm0_body2:
  %t33 = getelementptr inbounds [5 x i8], ptr @.str.4, i64 0, i64 0
  %r81 = ptrtoint ptr %t33 to i64
  %t34 = load i64, ptr %slot.__mb2___match_0, align 8
  call void @nova_rc_dec(i64 %t34)
  store i64 %r81, ptr %slot.__mb2___match_0, align 8
  br label %__mb2_match_merge1

__mb2_arm0_next3:
  %t35 = icmp eq i64 %r77, 1
  br i1 %t35, label %__mb2_arm1_body4, label %__mb2_arm1_next5

__mb2_arm1_body4:
  %t36 = getelementptr inbounds [4 x i8], ptr @.str.0, i64 0, i64 0
  %r85 = ptrtoint ptr %t36 to i64
  %t37 = load i64, ptr %slot.__mb2___match_0, align 8
  call void @nova_rc_dec(i64 %t37)
  store i64 %r85, ptr %slot.__mb2___match_0, align 8
  br label %__mb2_match_merge1

__mb2_arm1_next5:
  br label %__mb2_arm2_body6

__mb2_arm2_body6:
  %t38 = getelementptr inbounds [5 x i8], ptr @.str.5, i64 0, i64 0
  %r87 = ptrtoint ptr %t38 to i64
  %t39 = load i64, ptr %slot.__mb2___match_0, align 8
  call void @nova_rc_dec(i64 %t39)
  store i64 %r87, ptr %slot.__mb2___match_0, align 8
  br label %__mb2_match_merge1

__mb2_match_merge1:
  %r89 = load i64, ptr %slot.__mb2___match_0, align 8
  %t40 = load i64, ptr %slot.__mb2_ret, align 8
  call void @nova_rc_dec(i64 %t40)
  call void @nova_rc_inc(i64 %r89)
  store i64 %r89, ptr %slot.__mb2_ret, align 8
  br label %__mb2_merge

__mb2_merge:
  %r90 = load i64, ptr %slot.__mb2_ret, align 8
  %t41 = inttoptr i64 %r90 to ptr
  call i32 @puts(ptr %t41)
  %t42 = load i64, ptr %slot.__match_1, align 8
  call void @nova_rc_dec(i64 %t42)
  %t43 = load i64, ptr %slot.__mb0___match_0, align 8
  call void @nova_rc_dec(i64 %t43)
  %t44 = load i64, ptr %slot.__mb0_ret, align 8
  call void @nova_rc_dec(i64 %t44)
  %t45 = load i64, ptr %slot.__mb1___match_0, align 8
  call void @nova_rc_dec(i64 %t45)
  %t46 = load i64, ptr %slot.__mb1_ret, align 8
  call void @nova_rc_dec(i64 %t46)
  %t47 = load i64, ptr %slot.__mb2___match_0, align 8
  call void @nova_rc_dec(i64 %t47)
  %t48 = load i64, ptr %slot.__mb2_ret, align 8
  call void @nova_rc_dec(i64 %t48)
  ret i64 0
}

define i32 @main() {
entry:
  call void @nova_rt_init()
  call i64 @nova_main()
  call void @nova_rt_wait_all()
  call void @nova_rt_cleanup()
  ret i32 0
}

!0 = !{!"NOVA TBAA"}
!1 = !{!"list_data_ptr", !0}
!2 = !{!1, !1, i64 0}
!3 = !{!"list_elem", !0}
!4 = !{!3, !3, i64 0}
!5 = !{!"list_size", !0}
!6 = !{!5, !5, i64 0}
!7 = !{!"list_cap", !0}
!8 = !{!7, !7, i64 0}
