; Generated by NOVA compiler
target triple = "x86_64-pc-windows-msvc"

declare i32 @printf(ptr, ...)
declare i32 @puts(ptr)
declare noalias ptr @malloc(i64) nounwind allocsize(0)
declare ptr @realloc(ptr, i64) nounwind allocsize(1)
declare void @free(ptr)
; nova runtime — list ops
declare i64 @nova_rt_list_create()
declare i64 @nova_rt_list_create_filled(i64, i64)
declare i64 @nova_rt_list_append(i64, i64)
declare i64 @nova_rt_list_get(i64, i64)
declare i64 @nova_rt_list_set(i64, i64, i64)
declare i64 @nova_rt_list_len(i64)
declare i64 @nova_rt_list_print(i64)
declare i64 @nova_rt_iter_has_next(i64, i64)
; nova runtime — string ops
declare i64 @nova_rt_str_concat(i64, i64)
declare i64 @nova_rt_int_to_str(i64)
declare i64 @nova_rt_float_to_str(i64)
declare i64 @nova_rt_bool_to_str(i64)
declare i64 @nova_rt_str_len(i64)
declare i64 @nova_rt_len(i64)
declare i64 @nova_rt_contains(i64, i64)
declare i64 @nova_rt_slice(i64, i64, i64)
declare i64 @nova_rt_upper(i64)
declare i64 @nova_rt_lower(i64)
declare i64 @nova_rt_trim(i64)
declare i64 @nova_rt_split(i64, i64)
declare i64 @nova_rt_replace(i64, i64, i64)
declare i64 @nova_rt_starts_with(i64, i64)
declare i64 @nova_rt_ends_with(i64, i64)
declare i64 @nova_rt_find(i64, i64)
declare i64 @nova_rt_join(i64, i64)
declare i64 @nova_rt_chars(i64)
; nova runtime — list stdlib
declare i64 @nova_rt_list_reverse(i64)
declare i64 @nova_rt_list_sort(i64)
declare i64 @nova_rt_list_map(i64, i64)
declare i64 @nova_rt_list_filter(i64, i64)
declare i64 @nova_rt_list_concat(i64, i64)
declare i64 @nova_rt_list_to_str(i64)
declare i64 @nova_rt_len_any(i64)
; nova runtime — type conversions
declare i64 @nova_rt_parse_int(i64)
declare i64 @nova_rt_parse_float(i64)
; nova runtime — character ops
declare i64 @nova_rt_ord(i64)
declare i64 @nova_rt_chr(i64)
; nova runtime — process control
declare void @nova_rt_exit(i64)
declare i32 @strcmp(ptr, ptr)
; nova runtime — dict ops (Phase 1: ordered array, O(n) lookup)
declare i64 @nova_rt_dict_create()
declare i64 @nova_rt_dict_set(i64, i64, i64)
declare i64 @nova_rt_dict_get(i64, i64)
declare i64 @nova_rt_dict_has(i64, i64)
declare i64 @nova_rt_dict_del(i64, i64)
declare i64 @nova_rt_dict_len(i64)
declare i64 @nova_rt_dict_keys(i64)
; nova runtime — IO ops
declare i64 @nova_rt_read_line()
declare i64 @nova_rt_read_file(i64)
declare i64 @nova_rt_write_file(i64, i64)
declare i64 @nova_rt_append_file(i64, i64)
declare i64 @nova_rt_file_exists(i64)
; nova runtime — JSON ops
declare i64 @nova_rt_json_parse(i64)
declare i64 @nova_rt_json_stringify(i64)
; nova runtime — HTTP ops
declare i64 @nova_rt_http_get(i64)
declare i64 @nova_rt_http_post(i64, i64, i64)
; nova runtime — type dispatch
declare i64 @nova_rt_any_to_str(i64)
declare i64 @nova_rt_str_concat_safe(i64, i64)
declare void @nova_rt_init()
; nova runtime — channel/spawn ops
declare i64 @nova_rt_channel_create()
declare i64 @nova_rt_channel_send(i64, i64)
declare i64 @nova_rt_channel_recv(i64)
declare i64 @nova_rt_channel_close(i64)
declare i64 @nova_rt_channel_select(i64, i64)
declare i64 @nova_rt_channel_recv_timeout(i64, i64)
declare i64 @nova_rt_spawn(i64, i64)
declare i64 @nova_rt_monitor(i64)
declare void @nova_rt_wait_all()
; nova runtime — math (trig/log via C runtime for non-intrinsic functions)
declare i64 @nova_rt_tan(i64)
declare i64 @nova_rt_asin(i64)
declare i64 @nova_rt_acos(i64)
declare i64 @nova_rt_atan(i64)
declare i64 @nova_rt_atan2(i64, i64)
declare i64 @nova_rt_fmod(i64, i64)
declare i64 @nova_rt_int_pow(i64, i64)
; nova runtime — memory management
declare void @nova_rt_cleanup()
declare void @nova_rt_track_raw(ptr)
declare i64 @nova_rt_alloc_count()
declare i64 @nova_rt_live_count()
; nova runtime — reference counting
declare void @nova_rc_inc(i64)
declare void @nova_rc_dec(i64)
; nova error state — thread-local flag (safe for spawn/concurrent programs)
@__nova_error_flag = thread_local global i64 0
@__nova_error_msg = thread_local global i64 0

@.str.0 = private unnamed_addr constant [6 x i8] c"hello\00"
@.str.1 = private unnamed_addr constant [7 x i8] c" world\00"
@.str.2 = private unnamed_addr constant [22 x i8] c"Live objects before: \00"
@.str.3 = private unnamed_addr constant [29 x i8] c"Live after 1000 string ops: \00"
@.str.4 = private unnamed_addr constant [29 x i8] c"Live after 2000 string ops: \00"
@.str.5 = private unnamed_addr constant [22 x i8] c"Live after list ops: \00"
@.str.6 = private unnamed_addr constant [27 x i8] c"Live after more list ops: \00"
@.str.7 = private unnamed_addr constant [31 x i8] c"Total historical allocations: \00"
@.str.8 = private unnamed_addr constant [22 x i8] c"Live objects at end: \00"
@.str.9 = private unnamed_addr constant [26 x i8] c"Objects reclaimed by RC: \00"
@.str.10 = private unnamed_addr constant [18 x i8] c"RC TEST PASSED - \00"
@.str.11 = private unnamed_addr constant [27 x i8] c" objects freed mid-program\00"
@.str.12 = private unnamed_addr constant [38 x i8] c"RC TEST FAILED - no objects reclaimed\00"
@.str.13 = private unnamed_addr constant [6 x i8] c"%lld\0A\00"
@.str.14 = private unnamed_addr constant [4 x i8] c"%f\0A\00"
@.str.15 = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.str.16 = private unnamed_addr constant [5 x i8] c"true\00"
@.str.17 = private unnamed_addr constant [6 x i8] c"false\00"

define i64 @make_temp_strings(i64 %p0) {
entry0:
  %slot.n = alloca i64, align 8
  %slot.i = alloca i64, align 8
  %slot.s = alloca i64, align 8
  store i64 0, ptr %slot.s, align 8
  store i64 %p0, ptr %slot.n, align 8
  store i64 0, ptr %slot.i, align 8
  br label %while_header1

while_header1:
  %r7 = load i64, ptr %slot.i, align 8
  %r8 = load i64, ptr %slot.n, align 8
  %t0 = icmp slt i64 %r7, %r8
  br i1 %t0, label %while_body2, label %while_exit3

while_body2:
  %t1 = getelementptr inbounds [6 x i8], ptr @.str.0, i64 0, i64 0
  %r11 = ptrtoint ptr %t1 to i64
  %r12 = load i64, ptr %slot.i, align 8
  %r13 = call i64 @nova_rt_int_to_str(i64 %r12)
  %t2 = call i64 @nova_rt_str_concat(i64 %r11, i64 %r13)
  %t3 = getelementptr inbounds [7 x i8], ptr @.str.1, i64 0, i64 0
  %r15 = ptrtoint ptr %t3 to i64
  %t4 = call i64 @nova_rt_str_concat(i64 %t2, i64 %r15)
  %r17 = load i64, ptr %slot.i, align 8
  %r19 = mul i64 %r17, 2
  %r20 = call i64 @nova_rt_int_to_str(i64 %r19)
  %t5 = call i64 @nova_rt_str_concat(i64 %t4, i64 %r20)
  store i64 %t5, ptr %slot.s, align 8
  %r25 = load i64, ptr %slot.i, align 8
  %r27 = add i64 %r25, 1
  store i64 %r27, ptr %slot.i, align 8
  br label %while_header1

while_exit3:
  %r31 = load i64, ptr %slot.n, align 8
  call void @nova_rc_inc(i64 %r31)
  %t6 = load i64, ptr %slot.s, align 8
  call void @nova_rc_dec(i64 %t6)
  ret i64 %r31
}

define i64 @make_temp_lists(i64 %p0) {
entry0:
  %slot.n = alloca i64, align 8
  %slot.i = alloca i64, align 8
  %slot.lst = alloca i64, align 8
  store i64 0, ptr %slot.lst, align 8
  store i64 %p0, ptr %slot.n, align 8
  store i64 0, ptr %slot.i, align 8
  br label %while_header1

while_header1:
  %r7 = load i64, ptr %slot.i, align 8
  %r8 = load i64, ptr %slot.n, align 8
  %t0 = icmp slt i64 %r7, %r8
  br i1 %t0, label %while_body2, label %while_exit3

while_body2:
  %r11 = load i64, ptr %slot.i, align 8
  %r12 = load i64, ptr %slot.i, align 8
  %r14 = add i64 %r12, 1
  %r15 = load i64, ptr %slot.i, align 8
  %r17 = add i64 %r15, 2
  %r18 = load i64, ptr %slot.i, align 8
  %r20 = add i64 %r18, 3
  %r21 = load i64, ptr %slot.i, align 8
  %r23 = add i64 %r21, 4
  %r24 = call i64 @nova_rt_list_create()
  %t1 = call i64 @nova_rt_list_append(i64 %r24, i64 %r11)
  %t2 = call i64 @nova_rt_list_append(i64 %r24, i64 %r14)
  %t3 = call i64 @nova_rt_list_append(i64 %r24, i64 %r17)
  %t4 = call i64 @nova_rt_list_append(i64 %r24, i64 %r20)
  %t5 = call i64 @nova_rt_list_append(i64 %r24, i64 %r23)
  store i64 %r24, ptr %slot.lst, align 8
  %r28 = load i64, ptr %slot.i, align 8
  %r30 = add i64 %r28, 1
  store i64 %r30, ptr %slot.i, align 8
  br label %while_header1

while_exit3:
  %r34 = load i64, ptr %slot.n, align 8
  call void @nova_rc_inc(i64 %r34)
  %t6 = load i64, ptr %slot.lst, align 8
  call void @nova_rc_dec(i64 %t6)
  ret i64 %r34
}

define i64 @nova_main() {
entry0:
  %slot.before = alloca i64, align 8
  %slot.after1 = alloca i64, align 8
  %slot.after2 = alloca i64, align 8
  %slot.after3 = alloca i64, align 8
  %slot.after4 = alloca i64, align 8
  %slot.total_allocs = alloca i64, align 8
  %slot.reclaim_rate = alloca i64, align 8
  %slot.__ifb_0 = alloca i64, align 8
  store i64 0, ptr %slot.before, align 8
  store i64 0, ptr %slot.after1, align 8
  store i64 0, ptr %slot.after2, align 8
  store i64 0, ptr %slot.after3, align 8
  store i64 0, ptr %slot.after4, align 8
  store i64 0, ptr %slot.total_allocs, align 8
  store i64 0, ptr %slot.__ifb_0, align 8
  %r1 = call i64 @nova_rt_live_count()
  store i64 %r1, ptr %slot.before, align 8
  %t0 = getelementptr inbounds [22 x i8], ptr @.str.2, i64 0, i64 0
  %r6 = ptrtoint ptr %t0 to i64
  %r8 = call i64 @nova_rt_any_to_str(i64 %r1)
  %t1 = call i64 @nova_rt_str_concat(i64 %r6, i64 %r8)
  %t2 = inttoptr i64 %t1 to ptr
  call i32 @puts(ptr %t2)
  %r12 = call i64 @make_temp_strings(i64 1000)
  %r14 = call i64 @nova_rt_live_count()
  store i64 %r14, ptr %slot.after1, align 8
  %t3 = getelementptr inbounds [29 x i8], ptr @.str.3, i64 0, i64 0
  %r19 = ptrtoint ptr %t3 to i64
  %r21 = call i64 @nova_rt_any_to_str(i64 %r14)
  %t4 = call i64 @nova_rt_str_concat(i64 %r19, i64 %r21)
  %t5 = inttoptr i64 %t4 to ptr
  call i32 @puts(ptr %t5)
  %r25 = call i64 @make_temp_strings(i64 1000)
  %r27 = call i64 @nova_rt_live_count()
  store i64 %r27, ptr %slot.after2, align 8
  %t6 = getelementptr inbounds [29 x i8], ptr @.str.4, i64 0, i64 0
  %r32 = ptrtoint ptr %t6 to i64
  %r34 = call i64 @nova_rt_any_to_str(i64 %r27)
  %t7 = call i64 @nova_rt_str_concat(i64 %r32, i64 %r34)
  %t8 = inttoptr i64 %t7 to ptr
  call i32 @puts(ptr %t8)
  %r38 = call i64 @make_temp_lists(i64 500)
  %r40 = call i64 @nova_rt_live_count()
  store i64 %r40, ptr %slot.after3, align 8
  %t9 = getelementptr inbounds [22 x i8], ptr @.str.5, i64 0, i64 0
  %r45 = ptrtoint ptr %t9 to i64
  %r47 = call i64 @nova_rt_any_to_str(i64 %r40)
  %t10 = call i64 @nova_rt_str_concat(i64 %r45, i64 %r47)
  %t11 = inttoptr i64 %t10 to ptr
  call i32 @puts(ptr %t11)
  %r51 = call i64 @make_temp_lists(i64 500)
  %r53 = call i64 @nova_rt_live_count()
  store i64 %r53, ptr %slot.after4, align 8
  %t12 = getelementptr inbounds [27 x i8], ptr @.str.6, i64 0, i64 0
  %r58 = ptrtoint ptr %t12 to i64
  %r60 = call i64 @nova_rt_any_to_str(i64 %r53)
  %t13 = call i64 @nova_rt_str_concat(i64 %r58, i64 %r60)
  %t14 = inttoptr i64 %t13 to ptr
  call i32 @puts(ptr %t14)
  %r64 = call i64 @nova_rt_alloc_count()
  store i64 %r64, ptr %slot.total_allocs, align 8
  %t15 = getelementptr inbounds [31 x i8], ptr @.str.7, i64 0, i64 0
  %r69 = ptrtoint ptr %t15 to i64
  %r71 = call i64 @nova_rt_any_to_str(i64 %r64)
  %t16 = call i64 @nova_rt_str_concat(i64 %r69, i64 %r71)
  %t17 = inttoptr i64 %t16 to ptr
  call i32 @puts(ptr %t17)
  %t18 = getelementptr inbounds [22 x i8], ptr @.str.8, i64 0, i64 0
  %r75 = ptrtoint ptr %t18 to i64
  %r77 = call i64 @nova_rt_any_to_str(i64 %r53)
  %t19 = call i64 @nova_rt_str_concat(i64 %r75, i64 %r77)
  %t20 = inttoptr i64 %t19 to ptr
  call i32 @puts(ptr %t20)
  %r82 = sub i64 %r64, %r53
  store i64 %r82, ptr %slot.reclaim_rate, align 8
  %t21 = getelementptr inbounds [26 x i8], ptr @.str.9, i64 0, i64 0
  %r87 = ptrtoint ptr %t21 to i64
  %r89 = call i64 @nova_rt_int_to_str(i64 %r82)
  %t22 = call i64 @nova_rt_str_concat(i64 %r87, i64 %r89)
  %t23 = inttoptr i64 %t22 to ptr
  call i32 @puts(ptr %t23)
  %t24 = icmp sgt i64 %r82, 0
  br i1 %t24, label %ifb_then1, label %ifb_else2

ifb_then1:
  %t25 = getelementptr inbounds [18 x i8], ptr @.str.10, i64 0, i64 0
  %r98 = ptrtoint ptr %t25 to i64
  %r99 = load i64, ptr %slot.reclaim_rate, align 8
  %r100 = call i64 @nova_rt_int_to_str(i64 %r99)
  %t26 = call i64 @nova_rt_str_concat(i64 %r98, i64 %r100)
  %t27 = getelementptr inbounds [27 x i8], ptr @.str.11, i64 0, i64 0
  %r102 = ptrtoint ptr %t27 to i64
  %t28 = call i64 @nova_rt_str_concat(i64 %t26, i64 %r102)
  %t29 = inttoptr i64 %t28 to ptr
  call i32 @puts(ptr %t29)
  store i64 0, ptr %slot.__ifb_0, align 8
  br label %ifb_merge3

ifb_else2:
  %t30 = getelementptr inbounds [38 x i8], ptr @.str.12, i64 0, i64 0
  %r108 = ptrtoint ptr %t30 to i64
  %t31 = inttoptr i64 %r108 to ptr
  call i32 @puts(ptr %t31)
  store i64 0, ptr %slot.__ifb_0, align 8
  br label %ifb_merge3

ifb_merge3:
  call void @nova_rc_inc(i64 0)
  %t32 = load i64, ptr %slot.before, align 8
  call void @nova_rc_dec(i64 %t32)
  %t33 = load i64, ptr %slot.after1, align 8
  call void @nova_rc_dec(i64 %t33)
  %t34 = load i64, ptr %slot.after2, align 8
  call void @nova_rc_dec(i64 %t34)
  %t35 = load i64, ptr %slot.after3, align 8
  call void @nova_rc_dec(i64 %t35)
  %t36 = load i64, ptr %slot.after4, align 8
  call void @nova_rc_dec(i64 %t36)
  %t37 = load i64, ptr %slot.total_allocs, align 8
  call void @nova_rc_dec(i64 %t37)
  %t38 = load i64, ptr %slot.__ifb_0, align 8
  call void @nova_rc_dec(i64 %t38)
  ret i64 0
}

define i32 @main() {
entry:
  call void @nova_rt_init()
  call i64 @nova_main()
  call void @nova_rt_wait_all()
  call void @nova_rt_cleanup()
  ret i32 0
}

!0 = !{!"NOVA TBAA"}
!1 = !{!"list_data_ptr", !0}
!2 = !{!1, !1, i64 0}
!3 = !{!"list_elem", !0}
!4 = !{!3, !3, i64 0}
!5 = !{!"list_size", !0}
!6 = !{!5, !5, i64 0}
!7 = !{!"list_cap", !0}
!8 = !{!7, !7, i64 0}
