; Generated by NOVA compiler
target triple = "x86_64-pc-windows-msvc"

declare i32 @printf(ptr, ...)
declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare ptr @realloc(ptr, i64)
declare void @free(ptr)
; nova runtime — list ops
declare i64 @nova_rt_list_create()
declare i64 @nova_rt_list_append(i64, i64)
declare i64 @nova_rt_list_get(i64, i64)
declare i64 @nova_rt_list_set(i64, i64, i64)
declare i64 @nova_rt_list_len(i64)
declare i64 @nova_rt_list_print(i64)
declare i64 @nova_rt_iter_has_next(i64, i64)
; nova runtime — string ops
declare i64 @nova_rt_str_concat(i64, i64)
declare i64 @nova_rt_int_to_str(i64)
declare i64 @nova_rt_float_to_str(i64)
declare i64 @nova_rt_bool_to_str(i64)
declare i64 @nova_rt_str_len(i64)
declare i64 @nova_rt_len(i64)
declare i64 @nova_rt_contains(i64, i64)
declare i64 @nova_rt_slice(i64, i64, i64)
declare i64 @nova_rt_upper(i64)
declare i64 @nova_rt_lower(i64)
declare i64 @nova_rt_trim(i64)
declare i64 @nova_rt_split(i64, i64)
declare i64 @nova_rt_replace(i64, i64, i64)
declare i64 @nova_rt_starts_with(i64, i64)
declare i64 @nova_rt_ends_with(i64, i64)
declare i64 @nova_rt_find(i64, i64)
declare i64 @nova_rt_join(i64, i64)
declare i64 @nova_rt_chars(i64)
; nova runtime — list stdlib
declare i64 @nova_rt_list_reverse(i64)
declare i64 @nova_rt_list_sort(i64)
declare i64 @nova_rt_list_map(i64, i64)
declare i64 @nova_rt_list_filter(i64, i64)
declare i64 @nova_rt_list_concat(i64, i64)
declare i64 @nova_rt_list_to_str(i64)
declare i64 @nova_rt_len_any(i64)
; nova runtime — type conversions
declare i64 @nova_rt_parse_int(i64)
declare i64 @nova_rt_parse_float(i64)
; nova runtime — character ops
declare i64 @nova_rt_ord(i64)
declare i64 @nova_rt_chr(i64)
; nova runtime — process control
declare void @nova_rt_exit(i64)
declare i32 @strcmp(ptr, ptr)
; nova runtime — dict ops (Phase 1: ordered array, O(n) lookup)
declare i64 @nova_rt_dict_create()
declare i64 @nova_rt_dict_set(i64, i64, i64)
declare i64 @nova_rt_dict_get(i64, i64)
declare i64 @nova_rt_dict_has(i64, i64)
declare i64 @nova_rt_dict_del(i64, i64)
declare i64 @nova_rt_dict_len(i64)
declare i64 @nova_rt_dict_keys(i64)
; nova runtime — IO ops
declare i64 @nova_rt_read_line()
declare i64 @nova_rt_read_file(i64)
declare i64 @nova_rt_write_file(i64, i64)
; nova runtime — channel/spawn ops
declare i64 @nova_rt_channel_create()
declare i64 @nova_rt_channel_send(i64, i64)
declare i64 @nova_rt_channel_recv(i64)
declare i64 @nova_rt_channel_close(i64)
declare i64 @nova_rt_channel_select(i64, i64)
declare i64 @nova_rt_channel_recv_timeout(i64, i64)
declare i64 @nova_rt_spawn(i64, i64)
declare i64 @nova_rt_monitor(i64)
declare void @nova_rt_wait_all()
; nova runtime — math (trig/log via C runtime for non-intrinsic functions)
declare i64 @nova_rt_tan(i64)
declare i64 @nova_rt_asin(i64)
declare i64 @nova_rt_acos(i64)
declare i64 @nova_rt_atan(i64)
declare i64 @nova_rt_atan2(i64, i64)
declare i64 @nova_rt_fmod(i64, i64)
declare i64 @nova_rt_int_pow(i64, i64)
; nova runtime — memory management
declare void @nova_rt_cleanup()
declare void @nova_rt_track_raw(ptr)
declare i64 @nova_rt_alloc_count()
; nova error state — global flag (errno-style)
@__nova_error_flag = global i64 0
@__nova_error_msg = global i64 0

@.str.0 = private unnamed_addr constant [9 x i8] c"ord A = \00"
@.str.1 = private unnamed_addr constant [2 x i8] c"A\00"
@.str.2 = private unnamed_addr constant [9 x i8] c"ord 0 = \00"
@.str.3 = private unnamed_addr constant [2 x i8] c"0\00"
@.str.4 = private unnamed_addr constant [10 x i8] c"chr 65 = \00"
@.str.5 = private unnamed_addr constant [10 x i8] c"chr 48 = \00"
@.str.6 = private unnamed_addr constant [5 x i8] c"Done\00"
@.str.7 = private unnamed_addr constant [6 x i8] c"%lld\0A\00"
@.str.8 = private unnamed_addr constant [4 x i8] c"%f\0A\00"
@.str.9 = private unnamed_addr constant [4 x i8] c"%s\0A\00"
@.str.10 = private unnamed_addr constant [5 x i8] c"true\00"
@.str.11 = private unnamed_addr constant [6 x i8] c"false\00"

define i64 @nova_main() {
entry0:
  %t0 = getelementptr inbounds [9 x i8], ptr @.str.0, i64 0, i64 0
  %r1 = ptrtoint ptr %t0 to i64
  %t1 = getelementptr inbounds [2 x i8], ptr @.str.1, i64 0, i64 0
  %r2 = ptrtoint ptr %t1 to i64
  %r3 = call i64 @nova_rt_ord(i64 %r2)
  %r4 = call i64 @nova_rt_int_to_str(i64 %r3)
  %t2 = call i64 @nova_rt_str_concat(i64 %r1, i64 %r4)
  %t3 = inttoptr i64 %t2 to ptr
  call i32 @puts(ptr %t3)
  %t4 = getelementptr inbounds [9 x i8], ptr @.str.2, i64 0, i64 0
  %r8 = ptrtoint ptr %t4 to i64
  %t5 = getelementptr inbounds [2 x i8], ptr @.str.3, i64 0, i64 0
  %r9 = ptrtoint ptr %t5 to i64
  %r10 = call i64 @nova_rt_ord(i64 %r9)
  %r11 = call i64 @nova_rt_int_to_str(i64 %r10)
  %t6 = call i64 @nova_rt_str_concat(i64 %r8, i64 %r11)
  %t7 = inttoptr i64 %t6 to ptr
  call i32 @puts(ptr %t7)
  %t8 = getelementptr inbounds [10 x i8], ptr @.str.4, i64 0, i64 0
  %r15 = ptrtoint ptr %t8 to i64
  %r17 = call i64 @nova_rt_chr(i64 65)
  %t9 = call i64 @nova_rt_str_concat(i64 %r15, i64 %r17)
  %t10 = inttoptr i64 %t9 to ptr
  call i32 @puts(ptr %t10)
  %t11 = getelementptr inbounds [10 x i8], ptr @.str.5, i64 0, i64 0
  %r21 = ptrtoint ptr %t11 to i64
  %r23 = call i64 @nova_rt_chr(i64 48)
  %t12 = call i64 @nova_rt_str_concat(i64 %r21, i64 %r23)
  %t13 = inttoptr i64 %t12 to ptr
  call i32 @puts(ptr %t13)
  %t14 = getelementptr inbounds [5 x i8], ptr @.str.6, i64 0, i64 0
  %r27 = ptrtoint ptr %t14 to i64
  %t15 = inttoptr i64 %r27 to ptr
  call i32 @puts(ptr %t15)
  ret i64 0
}

define i32 @main() {
entry:
  call i64 @nova_main()
  call void @nova_rt_wait_all()
  call void @nova_rt_cleanup()
  ret i32 0
}
